U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/myMemory.h File Reference
#include <avr/io.h>
*
#include `myUart.h`
*
#include `myUtil.h`
*
Functions
void testMemory ()
void readRTLMemory ()
void XMEM_init (void)
Function Documentation
void readRTLMemory ()
Definition at line 57 of file myMemory.c.
References print_hexAddress(), print_hexWord(), and RS232_putstring().
void testMemory ()
Definition at line 4 of file myMemory.c.
References print_hexAddress(), print_hexWord(), and RS232_putstring().
void XMEM_init (void)
Definition at line 113 of file myMemory.c.