U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/myRTL.h File Reference
#include `myUart.h`
*
#include <util/delay.h>
*
Typedefs
typedef unsigned char u_char
typedef unsigned short u_short
Functions
void TestRealtek (void)
u_short TestExternalRam (u_short first, u_short last)
Typedef Documentation
typedef unsigned char u_char
Definition at line 10 of file myRTL.h.
typedef unsigned short u_short
Definition at line 11 of file myRTL.h.
Function Documentation
u_short TestExternalRam (u_short first, u_short last)
Definition at line 78 of file myRTL.c.
References print_hexByte(), and RS232_putstring().
void TestRealtek (void)
Definition at line 5 of file myRTL.c.
References print_hexWord(), and RS232_putstring().