U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/myRTL.c File Reference
#include `myRTL.h`
*
Functions
void TestRealtek (void)
u_short TestExternalRam (u_short first, u_short last)
Function Documentation
u_short TestExternalRam (u_short first, u_short last)
Definition at line 78 of file myRTL.c.
References print_hexByte(), and RS232_putstring().
void TestRealtek (void)
Definition at line 5 of file myRTL.c.
References print_hexWord(), and RS232_putstring().