U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/myUart.h File Reference
#include `myUtil.h`
*
Macros
#define F_CPU 14745600UL
#define BAUDRATE 115200
#define BAUD_PRESCALLER (((F_CPU / (BAUDRATE * 16UL))) - 1)
Functions
void RS232_init (uint32_t baudrate)
void RS485_init (uint32_t baudrate)
unsigned char RS232_ReadChar (void)
unsigned char RS485_ReadChar (void)
uint8_t * RS485_QueryTelegram (uint8_t *myTelegram)
void RS232_WriteChar (unsigned char data)
void RS485_WriteChar (unsigned char data)
void RS232_putstring (char *StringPtr)
void RS485_putstring (char *StringPtr)
Macro Definition Documentation
#define BAUD_PRESCALLER (((F_CPU / (BAUDRATE * 16UL))) - 1)
Definition at line 8 of file myUart.h.
#define BAUDRATE 115200
Definition at line 7 of file myUart.h.
#define F_CPU 14745600UL
Definition at line 6 of file myUart.h.
Referenced by RS232_init(), and RS485_init().
Function Documentation
void RS232_init (uint32_t baudrate)
Definition at line 92 of file myUart.c.
References F_CPU.
Referenced by main().
void RS232_putstring (char * StringPtr)
Definition at line 77 of file myUart.c.
References RS232_WriteChar().
Referenced by deb_print(), displayTelegram(), main(), print_binByte(), print_hexAddress(), print_hexByte(), print_hexWord(), readRTLMemory(), TestExternalRam(), testMemory(), and TestRealtek().
unsigned char RS232_ReadChar (void)
Definition at line 6 of file myUart.c.
void RS232_WriteChar (unsigned char data)
Definition at line 24 of file myUart.c.
Referenced by print_binByte(), and RS232_putstring().
void RS485_init (uint32_t baudrate)
Definition at line 103 of file myUart.c.
References F_CPU.
Referenced by main().
void RS485_putstring (char * StringPtr)
Definition at line 84 of file myUart.c.
References RS485_WriteChar().
uint8_t* RS485_QueryTelegram (uint8_t * myTelegram)
Definition at line 52 of file myUart.c.
References myTelegram, RS485_ReadChar(), and RS485_WriteChar().
Referenced by getValue().
unsigned char RS485_ReadChar (void)
Definition at line 14 of file myUart.c.
Referenced by RS485_QueryTelegram().
void RS485_WriteChar (unsigned char data)
Definition at line 32 of file myUart.c.
Referenced by RS485_putstring(), and RS485_QueryTelegram().