U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/myUtil.h File Reference
#include <avr/io.h>
*
#include <stdlib.h>
*
Functions
void print_binByte (uint8_t myByte)
void print_hexByte (uint8_t myByte)
void print_hexWord (uint16_t word)
void print_hexAddress (uint16_t address)
void printStrInHex (char *aString)
void deb_print (char *aString, uint8_t byte)
void wait (uint8_t ileNopuf)
Function Documentation
void deb_print (char * aString, uint8_t byte)
Definition at line 179 of file myUtil.c.
References RS232_putstring().
void print_binByte (uint8_t myByte)
Definition at line 16 of file myUtil.c.
References RS232_putstring(), and RS232_WriteChar().
void print_hexAddress (uint16_t address)
Definition at line 109 of file myUtil.c.
References RS232_putstring().
Referenced by readRTLMemory(), and testMemory().
void print_hexByte (uint8_t myByte)
Definition at line 35 of file myUtil.c.
References RS232_putstring().
Referenced by displayTelegram(), printStrInHex(), and TestExternalRam().
void print_hexWord (uint16_t word)
Definition at line 49 of file myUtil.c.
References RS232_putstring().
Referenced by main(), readRTLMemory(), testMemory(), and TestRealtek().
void printStrInHex (char * aString)
Definition at line 169 of file myUtil.c.
References print_hexByte().
void wait (uint8_t ileNopuf)