U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/usscalc.h File Reference
#include `myUart.h`
*
Functions
uint16_t getValue (uint16_t myParam)
void getAllValues (uint16_t *myParamArr, uint8_t length)
Variables
uint8_t myTelegram [14]
Function Documentation
void getAllValues (uint16_t * myParamArr, uint8_t length)
Definition at line 106 of file usscalc.c.
References getValue().
Referenced by main().
uint16_t getValue (uint16_t myParam)
Definition at line 100 of file usscalc.c.
References myTelegram, prepTelegram(), and RS485_QueryTelegram().
Referenced by getAllValues().
Variable Documentation
uint8_t myTelegram[14]
Definition at line 6 of file usscalc.h.
Referenced by calcBCC(), getValue(), prepTelegram(), and RS485_QueryTelegram().