U:/ICT/7th_semester/bpri2/code/myEthernut/rs485/src/usscalc.c File Reference
#include `usscalc.h`
*
Macros
#define ppo 1
#define mirror 0
#define pkw 0
#define AK 0x00
#define SP 0
#define PNU 0x12bc
#define PNUex 0x00
#define IDX 0x00
Functions
uint8_t calcBCC ()
void prepTelegram (uint16_t myParam)
uint16_t getValue (uint16_t myParam)
void getAllValues (uint16_t *mmParametersArr, uint8_t length)
Macro Definition Documentation
#define AK 0x00
Definition at line 29 of file usscalc.c.
Referenced by prepTelegram().
#define IDX 0x00
Definition at line 41 of file usscalc.c.
Referenced by prepTelegram().
#define mirror 0
Definition at line 20 of file usscalc.c.
Referenced by prepTelegram().
#define pkw 0
Definition at line 22 of file usscalc.c.
#define PNU 0x12bc
Definition at line 35 of file usscalc.c.
#define PNUex 0x00
Definition at line 38 of file usscalc.c.
#define ppo 1
Definition at line 18 of file usscalc.c.
#define SP 0
Definition at line 32 of file usscalc.c.
Referenced by prepTelegram().
Function Documentation
uint8_t calcBCC ()
Definition at line 43 of file usscalc.c.
References myTelegram.
Referenced by prepTelegram().
void getAllValues (uint16_t * mmParametersArr, uint8_t length)
Definition at line 106 of file usscalc.c.
References getValue().
Referenced by main().
uint16_t getValue (uint16_t myParam)
Definition at line 100 of file usscalc.c.
References myTelegram, prepTelegram(), and RS485_QueryTelegram().
Referenced by getAllValues().
void prepTelegram (uint16_t myParam)
Definition at line 55 of file usscalc.c.
References AK, calcBCC(), IDX, mirror, myTelegram, and SP.
Referenced by getValue().