Dave/Generated/DAVE.h File Reference
#include `xmc_common.h`
#include `CLOCK_XMC1/clock_xmc1.h`
#include `CPU_CTRL_XMC1/cpu_ctrl_xmc1.h`
#include `FREERTOS/freertos.h`
#include `DIGITAL_IO/digital_io.h`
#include `SPI_SLAVE/spi_slave.h`
#include `UART/uart.h`
Typedefs
typedef enum DAVE_STATUS DAVE_STATUS_t
Enumerations
enum DAVE_STATUS { DAVE_STATUS_SUCCESS = 0,
DAVE_STATUS_FAILURE
 }
Functions
DAVE_STATUS_t DAVE_Init (void)
Typedef Documentation
DAVE_STATUS_t
typedef enum DAVE_STATUS DAVE_STATUS_t
#include DAVE APP Header files.
Enumeration Type Documentation
DAVE_STATUS
enum DAVE_STATUS
#include DAVE APP Header files.
Enumerator
DAVE_STATUS_SUCCESS
DAVE_STATUS_FAILURE
Definition at line 74 of file DAVE.h.
Function Documentation
DAVE_Init()
DAVE_STATUS_t DAVE_Init (void)
@Initialization of APPs Init Functions
Initialization of DIGITAL_IO APP instance LED0
Initialization of DIGITAL_IO APP instance LED1
Initialization of SPI_SLAVE APP instance SPI_SLAVE_0
Initialization of UART APP instance UART_0
Initialization of DIGITAL_IO APP instance VDIOP0_0
Initialization of DIGITAL_IO APP instance VDIOP0_5
Definition at line 61 of file DAVE.c.
References CLOCK_XMC1_0, CLOCK_XMC1_Init(), DAVE_STATUS_SUCCESS, DIGITAL_IO_Init(), LED0, LED1, SPI_SLAVE_0, SPI_SLAVE_Init(), UART_0, UART_Init(), VDIOP0_0, and VDIOP0_5.
Referenced by main().