Dave/Generated/DAVE.c File Reference
#include `DAVE.h`
Functions
DAVE_STATUS_t DAVE_Init (void)
Function Documentation
DAVE_Init()
DAVE_STATUS_t DAVE_Init (void)
@Initialization of APPs Init Functions
Initialization of DIGITAL_IO APP instance LED0
Initialization of DIGITAL_IO APP instance LED1
Initialization of SPI_SLAVE APP instance SPI_SLAVE_0
Initialization of UART APP instance UART_0
Initialization of DIGITAL_IO APP instance VDIOP0_0
Initialization of DIGITAL_IO APP instance VDIOP0_5
Definition at line 61 of file DAVE.c.
References CLOCK_XMC1_0, CLOCK_XMC1_Init(), DAVE_STATUS_SUCCESS, DIGITAL_IO_Init(), LED0, LED1, SPI_SLAVE_0, SPI_SLAVE_Init(), UART_0, UART_Init(), VDIOP0_0, and VDIOP0_5.
Referenced by main().