Dave/Generated/FREERTOS/event_groups.c File Reference
#include <stdlib.h>
#include `FreeRTOS.h`
#include `task.h`
#include `timers.h`
#include `event_groups.h`
Data Structures
struct xEventGroupDefinition
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define eventCLEAR_EVENTS_ON_EXIT_BIT 0x01000000UL
#define eventUNBLOCKED_DUE_TO_BIT_SET 0x02000000UL
#define eventWAIT_FOR_ALL_BITS 0x04000000UL
#define eventEVENT_BITS_CONTROL_BYTES 0xff000000UL
Typedefs
typedef struct xEventGroupDefinition EventGroup_t
Functions
static BaseType_t prvTestWaitCondition (const EventBits_t uxCurrentEventBits, const EventBits_t uxBitsToWaitFor, const BaseType_t xWaitForAllBits) PRIVILEGED_FUNCTION
EventGroupHandle_t xEventGroupCreate (void)
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
BaseType_t xEventGroupClearBitsFromISR (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
void vEventGroupSetBitsCallback (void *pvEventGroup, const uint32_t ulBitsToSet)
void vEventGroupClearBitsCallback (void *pvEventGroup, const uint32_t ulBitsToClear)
BaseType_t xEventGroupSetBitsFromISR (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, BaseType_t *pxHigherPriorityTaskWoken)
UBaseType_t uxEventGroupGetNumber (void *xEventGroup)
void vEventGroupSetNumber (void *xEventGroup, UBaseType_t uxEventGroupNumber)
Macro Definition Documentation
eventCLEAR_EVENTS_ON_EXIT_BIT
#define eventCLEAR_EVENTS_ON_EXIT_BIT 0x01000000UL
Definition at line 58 of file event_groups.c.
eventEVENT_BITS_CONTROL_BYTES
#define eventEVENT_BITS_CONTROL_BYTES 0xff000000UL
Definition at line 61 of file event_groups.c.
eventUNBLOCKED_DUE_TO_BIT_SET
#define eventUNBLOCKED_DUE_TO_BIT_SET 0x02000000UL
Definition at line 59 of file event_groups.c.
eventWAIT_FOR_ALL_BITS
#define eventWAIT_FOR_ALL_BITS 0x04000000UL
Definition at line 60 of file event_groups.c.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 35 of file event_groups.c.
Typedef Documentation
EventGroup_t
typedef struct xEventGroupDefinition EventGroup_t
Function Documentation
prvTestWaitCondition()
static BaseType_t prvTestWaitCondition (const EventBits_t uxCurrentEventBits, const EventBits_t uxBitsToWaitFor, const BaseType_t xWaitForAllBits) [static]
Definition at line 656 of file event_groups.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, and pdTRUE.
Referenced by xEventGroupWaitBits().
uxEventGroupGetNumber()
UBaseType_t uxEventGroupGetNumber (void * xEventGroup)
Definition at line 708 of file event_groups.c.
References xEventGroupDefinition::uxEventGroupNumber.
vEventGroupClearBitsCallback()
void vEventGroupClearBitsCallback (void * pvEventGroup, const uint32_t ulBitsToClear)
Definition at line 650 of file event_groups.c.
Referenced by xEventGroupClearBitsFromISR().
vEventGroupDelete()
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
event_groups.h
   void xEventGroupDelete(EventGroupHandle_t xEventGroup);
Delete an event group that was previously created by a call to xEventGroupCreate(). Tasks that are blocked on the event group will be unblocked and obtain 0 as the event group's value.
Parameters
xEventGroup The event group being deleted.
Definition at line 598 of file event_groups.c.
vEventGroupSetBitsCallback()
void vEventGroupSetBitsCallback (void * pvEventGroup, const uint32_t ulBitsToSet)
Definition at line 642 of file event_groups.c.
Referenced by xEventGroupSetBitsFromISR().
vEventGroupSetNumber()
void vEventGroupSetNumber (void * xEventGroup, UBaseType_t uxEventGroupNumber)
Definition at line 730 of file event_groups.c.
xEventGroupClearBits()
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
Definition at line 446 of file event_groups.c.
Referenced by vEventGroupClearBitsCallback().
xEventGroupClearBitsFromISR()
BaseType_t xEventGroupClearBitsFromISR (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
Definition at line 475 of file event_groups.c.
References traceEVENT_GROUP_CLEAR_BITS_FROM_ISR, vEventGroupClearBitsCallback(), and xTimerPendFunctionCallFromISR().
xEventGroupCreate()
EventGroupHandle_t xEventGroupCreate (void)
Definition at line 142 of file event_groups.c.
References pdFALSE, pvPortMalloc(), traceEVENT_GROUP_CREATE, traceEVENT_GROUP_CREATE_FAILED, xEventGroupDefinition::uxEventBits, vListInitialise(), and xEventGroupDefinition::xTasksWaitingForBits.
xEventGroupGetBitsFromISR()
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
Definition at line 488 of file event_groups.c.
xEventGroupSetBits()
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
Definition at line 504 of file event_groups.c.
Referenced by vEventGroupSetBitsCallback(), and xEventGroupSync().
xEventGroupSetBitsFromISR()
BaseType_t xEventGroupSetBitsFromISR (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 693 of file event_groups.c.
References traceEVENT_GROUP_SET_BITS_FROM_ISR, vEventGroupSetBitsCallback(), and xTimerPendFunctionCallFromISR().
xEventGroupSync()
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
Definition at line 176 of file event_groups.c.
xEventGroupWaitBits()
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
Definition at line 296 of file event_groups.c.