Dave/Generated/FREERTOS/stream_buffer.c File Reference
#include <stdint.h>
#include <string.h>
#include `FreeRTOS.h`
#include `task.h`
#include `stream_buffer.h`
Data Structures
struct xSTREAM_BUFFER
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define sbRECEIVE_COMPLETED(pxStreamBuffer)
#define sbRECEIVE_COMPLETED_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
#define sbSEND_COMPLETED(pxStreamBuffer)
#define sbSEND_COMPLETE_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
#define sbBYTES_TO_STORE_MESSAGE_LENGTH (sizeof(size_t))
#define sbFLAGS_IS_MESSAGE_BUFFER ((uint8_t) 1) /* Set if the stream buffer was created as a message buffer, in which case it holds discrete messages rather than a stream. */
#define sbFLAGS_IS_STATICALLY_ALLOCATED ((uint8_t) 2) /* Set if the stream buffer was created using statically allocated memory. */
Typedefs
typedef struct xSTREAM_BUFFER StreamBuffer_t
Functions
static size_t prvBytesInBuffer (const StreamBuffer_t *const pxStreamBuffer) PRIVILEGED_FUNCTION
static size_t prvWriteBytesToBuffer (StreamBuffer_t *const pxStreamBuffer, const uint8_t *pucData, size_t xCount) PRIVILEGED_FUNCTION
static size_t prvReadMessageFromBuffer (StreamBuffer_t *pxStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, size_t xBytesAvailable, size_t xBytesToStoreMessageLength) PRIVILEGED_FUNCTION
static size_t prvWriteMessageToBuffer (StreamBuffer_t *const pxStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, size_t xSpace, size_t xRequiredSpace) PRIVILEGED_FUNCTION
static size_t prvReadBytesFromBuffer (StreamBuffer_t *pxStreamBuffer, uint8_t *pucData, size_t xMaxCount, size_t xBytesAvailable)
static PRIVILEGED_FUNCTION void prvInitialiseNewStreamBuffer (StreamBuffer_t *const pxStreamBuffer, uint8_t *const pucBuffer, size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer) PRIVILEGED_FUNCTION
StreamBufferHandle_t xStreamBufferGenericCreate (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer)
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel)
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer)
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer)
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait)
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait)
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken)
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken)
UBaseType_t uxStreamBufferGetStreamBufferNumber (StreamBufferHandle_t xStreamBuffer)
void vStreamBufferSetStreamBufferNumber (StreamBufferHandle_t xStreamBuffer, UBaseType_t uxStreamBufferNumber)
uint8_t ucStreamBufferGetStreamBufferType (StreamBufferHandle_t xStreamBuffer)
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 36 of file stream_buffer.c.
sbBYTES_TO_STORE_MESSAGE_LENGTH
#define sbBYTES_TO_STORE_MESSAGE_LENGTH (sizeof(size_t))
Definition at line 133 of file stream_buffer.c.
sbFLAGS_IS_MESSAGE_BUFFER
#define sbFLAGS_IS_MESSAGE_BUFFER ((uint8_t) 1) /* Set if the stream buffer was created as a message buffer, in which case it holds discrete messages rather than a stream. */
Definition at line 136 of file stream_buffer.c.
sbFLAGS_IS_STATICALLY_ALLOCATED
#define sbFLAGS_IS_STATICALLY_ALLOCATED ((uint8_t) 2) /* Set if the stream buffer was created using statically allocated memory. */
Definition at line 137 of file stream_buffer.c.
sbRECEIVE_COMPLETED
#define sbRECEIVE_COMPLETED(pxStreamBuffer)
Value:
        vTaskSuspendAll(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToSend != NULL) \
            { \
                (void) xTaskNotify((pxStreamBuffer)->xTaskWaitingToSend, \
                                      (uint32_t) 0, \
                                      eNoAction); \
                (pxStreamBuffer)->xTaskWaitingToSend = NULL; \
            } \
        } \
        (void) xTaskResumeAll();
Definition at line 58 of file stream_buffer.c.
sbRECEIVE_COMPLETED_FROM_ISR
#define sbRECEIVE_COMPLETED_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
Value:
    { \
    UBaseType_t uxSavedInterruptStatus; \
                                                                                        \
        uxSavedInterruptStatus = (UBaseType_t) portSET_INTERRUPT_MASK_FROM_ISR(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToSend != NULL) \
            { \
                (void) xTaskNotifyFromISR((pxStreamBuffer)->xTaskWaitingToSend, \
                                             (uint32_t) 0, \
                                             eNoAction, \
                                             pxHigherPriorityTaskWoken); \
                (pxStreamBuffer)->xTaskWaitingToSend = NULL; \
            } \
        } \
        portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedInterruptStatus); \
    }
Definition at line 73 of file stream_buffer.c.
sbSEND_COMPLETE_FROM_ISR
#define sbSEND_COMPLETE_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
Value:
    { \
    UBaseType_t uxSavedInterruptStatus; \
                                                                                        \
        uxSavedInterruptStatus = (UBaseType_t) portSET_INTERRUPT_MASK_FROM_ISR(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToReceive != NULL) \
            { \
                (void) xTaskNotifyFromISR((pxStreamBuffer)->xTaskWaitingToReceive, \
                                             (uint32_t) 0, \
                                             eNoAction, \
                                             pxHigherPriorityTaskWoken); \
                (pxStreamBuffer)->xTaskWaitingToReceive = NULL; \
            } \
        } \
        portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedInterruptStatus); \
    }
Definition at line 112 of file stream_buffer.c.
sbSEND_COMPLETED
#define sbSEND_COMPLETED(pxStreamBuffer)
Value:
        vTaskSuspendAll(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToReceive != NULL) \
            { \
                (void) xTaskNotify((pxStreamBuffer)->xTaskWaitingToReceive, \
                                      (uint32_t) 0, \
                                      eNoAction); \
                (pxStreamBuffer)->xTaskWaitingToReceive = NULL; \
            } \
        } \
        (void) xTaskResumeAll();
Definition at line 97 of file stream_buffer.c.
Typedef Documentation
StreamBuffer_t
typedef struct xSTREAM_BUFFER StreamBuffer_t
Function Documentation
prvBytesInBuffer()
static size_t prvBytesInBuffer (const StreamBuffer_t *const pxStreamBuffer) [static]
Definition at line 1121 of file stream_buffer.c.
References mtCOVERAGE_TEST_MARKER, xSTREAM_BUFFER::xHead, xSTREAM_BUFFER::xLength, and xSTREAM_BUFFER::xTail.
Referenced by xStreamBufferBytesAvailable(), xStreamBufferReceive(), xStreamBufferReceiveFromISR(), xStreamBufferSend(), and xStreamBufferSendFromISR().
prvInitialiseNewStreamBuffer()
static void prvInitialiseNewStreamBuffer (StreamBuffer_t *const pxStreamBuffer, uint8_t *const pucBuffer, size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer) [static]
Definition at line 1141 of file stream_buffer.c.
References configASSERT, pdFALSE, and sbFLAGS_IS_MESSAGE_BUFFER.
Referenced by xStreamBufferGenericCreate(), and xStreamBufferReset().
prvReadBytesFromBuffer()
static size_t prvReadBytesFromBuffer (StreamBuffer_t * pxStreamBuffer, uint8_t * pucData, size_t xMaxCount, size_t xBytesAvailable) [static]
Definition at line 1066 of file stream_buffer.c.
References configASSERT, configMIN, mtCOVERAGE_TEST_MARKER, xSTREAM_BUFFER::pucBuffer, xSTREAM_BUFFER::xLength, and xSTREAM_BUFFER::xTail.
Referenced by prvReadMessageFromBuffer().
prvReadMessageFromBuffer()
static size_t prvReadMessageFromBuffer (StreamBuffer_t * pxStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, size_t xBytesAvailable, size_t xBytesToStoreMessageLength) [static]
Definition at line 852 of file stream_buffer.c.
References mtCOVERAGE_TEST_MARKER, prvReadBytesFromBuffer(), and xSTREAM_BUFFER::xTail.
Referenced by xStreamBufferReceive(), and xStreamBufferReceiveFromISR().
prvWriteBytesToBuffer()
static size_t prvWriteBytesToBuffer (StreamBuffer_t *const pxStreamBuffer, const uint8_t * pucData, size_t xCount) [static]
Definition at line 1020 of file stream_buffer.c.
References configASSERT, configMIN, mtCOVERAGE_TEST_MARKER, xSTREAM_BUFFER::pucBuffer, xSTREAM_BUFFER::xHead, and xSTREAM_BUFFER::xLength.
Referenced by prvWriteMessageToBuffer().
prvWriteMessageToBuffer()
static size_t prvWriteMessageToBuffer (StreamBuffer_t *const pxStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, size_t xSpace, size_t xRequiredSpace) [static]
Definition at line 639 of file stream_buffer.c.
References configMIN, pdFALSE, pdTRUE, prvWriteBytesToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, and xSTREAM_BUFFER::ucFlags.
Referenced by xStreamBufferSend(), and xStreamBufferSendFromISR().
ucStreamBufferGetStreamBufferType()
uint8_t ucStreamBufferGetStreamBufferType (StreamBufferHandle_t xStreamBuffer)
Definition at line 1193 of file stream_buffer.c.
References sbFLAGS_IS_MESSAGE_BUFFER.
uxStreamBufferGetStreamBufferNumber()
UBaseType_t uxStreamBufferGetStreamBufferNumber (StreamBufferHandle_t xStreamBuffer)
Definition at line 1173 of file stream_buffer.c.
vStreamBufferDelete()
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer)
Definition at line 335 of file stream_buffer.c.
vStreamBufferSetStreamBufferNumber()
void vStreamBufferSetStreamBufferNumber (StreamBufferHandle_t xStreamBuffer, UBaseType_t uxStreamBufferNumber)
Definition at line 1183 of file stream_buffer.c.
xStreamBufferBytesAvailable()
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 475 of file stream_buffer.c.
xStreamBufferGenericCreate()
StreamBufferHandle_t xStreamBufferGenericCreate (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer)
Definition at line 219 of file stream_buffer.c.
xStreamBufferIsEmpty()
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer)
Definition at line 902 of file stream_buffer.c.
xStreamBufferIsFull()
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer)
Definition at line 925 of file stream_buffer.c.
xStreamBufferReceive()
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait)
Definition at line 691 of file stream_buffer.c.
xStreamBufferReceiveCompletedFromISR()
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 990 of file stream_buffer.c.
xStreamBufferReceiveFromISR()
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 795 of file stream_buffer.c.
xStreamBufferReset()
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer)
Definition at line 368 of file stream_buffer.c.
xStreamBufferSend()
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait)
Definition at line 487 of file stream_buffer.c.
xStreamBufferSendCompletedFromISR()
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 960 of file stream_buffer.c.
xStreamBufferSendFromISR()
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 588 of file stream_buffer.c.
xStreamBufferSetTriggerLevel()
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel)
Definition at line 422 of file stream_buffer.c.
xStreamBufferSpacesAvailable()
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 451 of file stream_buffer.c.
Referenced by xStreamBufferIsFull(), xStreamBufferSend(), and xStreamBufferSendFromISR().