Dave/Generated/FREERTOS/portable.h File Reference
#include `deprecated_definitions.h`
#include `mpu_wrappers.h`
Data Structures
struct HeapRegion
Macros
#define portNUM_CONFIGURABLE_REGIONS 1
Typedefs
typedef struct HeapRegion HeapRegion_t
Functions
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters) PRIVILEGED_FUNCTION
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions) PRIVILEGED_FUNCTION
void * pvPortMalloc (size_t xSize) PRIVILEGED_FUNCTION
void vPortFree (void *pv) PRIVILEGED_FUNCTION
void vPortInitialiseBlocks (void) PRIVILEGED_FUNCTION
size_t xPortGetFreeHeapSize (void) PRIVILEGED_FUNCTION
size_t xPortGetMinimumEverFreeHeapSize (void) PRIVILEGED_FUNCTION
BaseType_t xPortStartScheduler (void) PRIVILEGED_FUNCTION
void vPortEndScheduler (void) PRIVILEGED_FUNCTION
Macro Definition Documentation
portNUM_CONFIGURABLE_REGIONS
#define portNUM_CONFIGURABLE_REGIONS 1
Definition at line 93 of file portable.h.
Typedef Documentation
HeapRegion_t
typedef struct HeapRegion HeapRegion_t
Function Documentation
pvPortMalloc()
void* pvPortMalloc (size_t xSize)
Definition at line 70 of file heap_1.h.
pxPortInitialiseStack()
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Referenced by prvInitialiseNewTask().
vPortDefineHeapRegions()
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
Definition at line 393 of file heap_5.h.
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 421 of file port_mpu.h.
Referenced by vTaskEndScheduler().
vPortFree()
void vPortFree (void * pv)
Definition at line 122 of file heap_1.h.
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 134 of file heap_1.h.
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 141 of file heap_1.h.
xPortGetMinimumEverFreeHeapSize()
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 317 of file heap_4.h.
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 307 of file port_mpu.h.
Referenced by vTaskStartScheduler().