Dave/Generated/FREERTOS/heap_1.h File Reference
#include <stdlib.h>
#include `FreeRTOS.h`
#include `task.h`
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define configADJUSTED_HEAP_SIZE (configTOTAL_HEAP_SIZE - portBYTE_ALIGNMENT)
Functions
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
void vPortInitialiseBlocks (void)
size_t xPortGetFreeHeapSize (void)
Variables
static uint8_t ucHeap [configTOTAL_HEAP_SIZE]
static size_t xNextFreeByte = (size_t) 0
Macro Definition Documentation
configADJUSTED_HEAP_SIZE
#define configADJUSTED_HEAP_SIZE (configTOTAL_HEAP_SIZE - portBYTE_ALIGNMENT)
Definition at line 54 of file heap_1.h.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 42 of file heap_1.h.
Function Documentation
pvPortMalloc()
void* pvPortMalloc (size_t xWantedSize)
Definition at line 70 of file heap_1.h.
Referenced by main(), vTaskList(), xEventGroupCreate(), xQueueGenericCreate(), xStreamBufferGenericCreate(), and xTimerCreate().
vPortFree()
void vPortFree (void * pv)
Definition at line 122 of file heap_1.h.
Referenced by prvDeleteTCB(), prvProcessReceivedCommands(), vEventGroupDelete(), vQueueDelete(), vStreamBufferDelete(), and vTaskList().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 134 of file heap_1.h.
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 141 of file heap_1.h.
Variable Documentation
ucHeap
uint8_t ucHeap[configTOTAL_HEAP_SIZE] [static]
Definition at line 62 of file heap_1.h.
Referenced by pvPortMalloc().
xNextFreeByte
size_t xNextFreeByte = (size_t) 0 [static]
Definition at line 66 of file heap_1.h.
Referenced by pvPortMalloc(), vPortInitialiseBlocks(), and xPortGetFreeHeapSize().