Dave/Generated/SPI_SLAVE/spi_slave.h File Reference
#include <xmc_scu.h>
#include <xmc_gpio.h>
#include <xmc_spi.h>
#include <DAVE_common.h>
#include `spi_slave_conf.h`
#include `spi_slave_extern.h`
Data Structures
struct SPI_SLAVE_PIN_CONFIG
Structure for transmit pin configuration.
struct SPI_SLAVE_CONFIG
Structure for holding the configuration parameters of SPI_SLAVE channel.
struct SPI_SLAVE_RUNTIME
Structure to hold the dynamic variables for the SPI_SLAVE communication.
struct SPI_SLAVE
Handler structure with pointers to dynamic and static parameters.
Macros
#define SPI_SLAVE_DMA_MAXCOUNT (4095U)
Typedefs
typedef void(* SPI_SLAVE_cbhandler) (void)
Function pointer used for callback function.
typedef SPI_SLAVE_STATUS_t(* SPI_SLAVE_init_handler) (void)
Function pointer used for USIC channel initialization function.
typedef struct SPI_SLAVE_PIN_CONFIG SPI_SLAVE_PIN_CONFIG_t
Structure for transmit pin configuration.
typedef struct SPI_SLAVE_CONFIG SPI_SLAVE_CONFIG_t
Structure for holding the configuration parameters of SPI_SLAVE channel.
typedef struct SPI_SLAVE_RUNTIME SPI_SLAVE_RUNTIME_t
Structure to hold the dynamic variables for the SPI_SLAVE communication.
typedef struct SPI_SLAVE SPI_SLAVE_t
Handler structure with pointers to dynamic and static parameters.
Functions
DAVE_APP_VERSION_t SPI_SLAVE_GetAppVersion (void)
Get the SPI_SLAVE APP version.
SPI_SLAVE_STATUS_t SPI_SLAVE_Init (const SPI_SLAVE_t *const handle)
Initializes the USIC channel as SPI slave.
SPI_SLAVE_STATUS_t SPI_SLAVE_Transmit (const SPI_SLAVE_t *const handle, uint8_t *data_ptr, uint32_t count)
Registers a request for transmitting data over SPI channel as a slave device.
SPI_SLAVE_STATUS_t SPI_SLAVE_Receive (const SPI_SLAVE_t *const handle, uint8_t *data_ptr, uint32_t count)
Registers a request for receiving data over SPI_SLAVE channel.
SPI_SLAVE_STATUS_t SPI_SLAVE_StartTransmitIRQ (const SPI_SLAVE_t *const handle, uint8_t *data_ptr, uint32_t count)
Registers a request for transmitting data over SPI channel as a slave device.
SPI_SLAVE_STATUS_t SPI_SLAVE_StartReceiveIRQ (const SPI_SLAVE_t *const handle, uint8_t *data_ptr, uint32_t count)
Registers a request for receiving data over SPI channel as a slave device.
SPI_SLAVE_STATUS_t SPI_SLAVE_AbortTransmit (const SPI_SLAVE_t *const handle)
Aborts the ongoing data transmission.
SPI_SLAVE_STATUS_t SPI_SLAVE_AbortReceive (const SPI_SLAVE_t *const handle)
Stops the active data reception sequence.
SPI_SLAVE_STATUS_t SPI_SLAVE_Transfer (const SPI_SLAVE_t *const handle, uint8_t *tx_dataptr, uint8_t *rx_dataptr, uint32_t count)
Registers a request for transmitting and receiving data simultaneously over SPI channel as a slave device.
SPI_SLAVE_STATUS_t SPI_SLAVE_SetMode (const SPI_SLAVE_t *const handle, XMC_SPI_CH_MODE_t mode)
Changes the operation mode of the SPI slave channel.
__STATIC_INLINE uint32_t SPI_SLAVE_GetFlagStatus (SPI_SLAVE_t *handle, const uint32_t flag)
Provides the status of protocol events.
__STATIC_INLINE void SPI_SLAVE_ClearFlag (const SPI_SLAVE_t *handle, const uint32_t flag_mask)
Clears the event status in the register(PSR_SSCMode).
__STATIC_INLINE uint16_t SPI_SLAVE_GetReceivedWord (const SPI_SLAVE_t *const handle)
Provides data received in the receive buffer.
__STATIC_INLINE void SPI_SLAVE_TransmitWord (const SPI_SLAVE_t *const handle, uint16_t data)
Transmits a word of data.
__STATIC_INLINE void SPI_SLAVE_EnableEvent (const SPI_SLAVE_t *const handle, uint32_t events)
Enables the selected protocol events for interrupt generation.
__STATIC_INLINE void SPI_SLAVE_DisableEvent (const SPI_SLAVE_t *const handle, uint32_t events)
Disables selected events from generating interrupt.
__STATIC_INLINE bool SPI_SLAVE_IsTXFIFOFull (const SPI_SLAVE_t *const handle)
Checks if the transmit FIFO is full.
__STATIC_INLINE bool SPI_SLAVE_IsRXFIFOEmpty (const SPI_SLAVE_t *const handle)
Checks if the receive FIFO is empty.
__STATIC_INLINE void SPI_SLAVE_SetTXFIFOTriggerLimit (const SPI_SLAVE_t *const handle, uint32_t limit)
Configures trigger limit for the transmit FIFO.
__STATIC_INLINE void SPI_SLAVE_SetRXFIFOTriggerLimit (const SPI_SLAVE_t *const handle, uint32_t limit)
Configures trigger limit for the receive FIFO.
__STATIC_INLINE uint32_t SPI_SLAVE_GetRXFIFOStatus (const SPI_SLAVE_t *const handle)
Gets the status of event flags related to receive FIFO.
__STATIC_INLINE uint32_t SPI_SLAVE_GetTXFIFOStatus (const SPI_SLAVE_t *const handle)
Gets the status of transmit FIFO event flags.
__STATIC_INLINE void SPI_SLAVE_ClearTXFIFOStatus (const SPI_SLAVE_t *const handle, const uint32_t flag)
Function clears the specified FIFO event flag related to transmit FIFO.
__STATIC_INLINE void SPI_SLAVE_ClearRXFIFOStatus (const SPI_SLAVE_t *const handle, const uint32_t flag)
Function clears the specified FIFO event flag related to receive FIFO. It should be used to clear the status of standard receive buffer interrupt, alternative receive buffer interupt and receive buffer error interrupt flags.
__STATIC_INLINE bool SPI_SLAVE_IsTxBusy (const SPI_SLAVE_t *const handle)
Function provides the status of data transmission.
__STATIC_INLINE bool SPI_SLAVE_IsRxBusy (const SPI_SLAVE_t *const handle)
Function provides the status of data reception.
enum SPI_SLAVE_STATUS {
SPI_SLAVE_STATUS_SUCCESS,
SPI_SLAVE_STATUS_FAILURE,
SPI_SLAVE_STATUS_BUSY,
SPI_SLAVE_STATUS_BUFFER_INVALID,
SPI_SLAVE_STATUS_MODE_MISMATCH,
SPI_SLAVE_STATUS_SUCCESS,
SPI_SLAVE_STATUS_FAILURE,
SPI_SLAVE_STATUS_BUSY,
SPI_SLAVE_STATUS_BUFFER_INVALID,
SPI_SLAVE_STATUS_MODE_MISMATCH
 }
Enum to describe the possible status values, returned by SPI_SLAVE APIs.
enum SPI_SLAVE_TRANSFER_MODE {
SPI_SLAVE_TRANSFER_MODE_INTERRUPT,
SPI_SLAVE_TRANSFER_MODE_DMA,
SPI_SLAVE_TRANSFER_MODE_DIRECT,
SPI_SLAVE_TRANSFER_MODE_INTERRUPT,
SPI_SLAVE_TRANSFER_MODE_DMA,
SPI_SLAVE_TRANSFER_MODE_DIRECT
 }
Enum used to identify the transfer type used for either transmit or receive function.
enum SPI_SLAVE_DATA_SIZE { SPI_SLAVE_DATA_SIZE_8BITS = 1U,
SPI_SLAVE_DATA_SIZE_16BITS = 2U,
SPI_SLAVE_DATA_SIZE_8BITS = 1U,
SPI_SLAVE_DATA_SIZE_16BITS = 2U
 }
Enum used to identify the size of each word. This only identifies the adressing size but not the actual word length of the channel. Useful for processing user buffer.
enum SPI_SLAVE_INPUT {
SPI_SLAVE_INPUT_A = 0U,
SPI_SLAVE_INPUT_B,
SPI_SLAVE_INPUT_C,
SPI_SLAVE_INPUT_D,
SPI_SLAVE_INPUT_E,
SPI_SLAVE_INPUT_F,
SPI_SLAVE_INPUT_G,
SPI_SLAVE_INPUT_INVALID,
SPI_SLAVE_INPUT_A = 0U,
SPI_SLAVE_INPUT_B,
SPI_SLAVE_INPUT_C,
SPI_SLAVE_INPUT_D,
SPI_SLAVE_INPUT_E,
SPI_SLAVE_INPUT_F,
SPI_SLAVE_INPUT_G,
SPI_SLAVE_INPUT_INVALID
 }
Enum to represent USIC input stage(DXn) multiplexer(DXnCR_DSEL) value.
typedef enum SPI_SLAVE_STATUS SPI_SLAVE_STATUS_t
Enum to describe the possible status values, returned by SPI_SLAVE APIs.
typedef enum SPI_SLAVE_TRANSFER_MODE SPI_SLAVE_TRANSFER_MODE_t
Enum used to identify the transfer type used for either transmit or receive function.
typedef enum SPI_SLAVE_DATA_SIZE SPI_SLAVE_DATA_SIZE_t
Enum used to identify the size of each word. This only identifies the adressing size but not the actual word length of the channel. Useful for processing user buffer.
typedef enum SPI_SLAVE_INPUT SPI_SLAVE_INPUT_t
Enum to represent USIC input stage(DXn) multiplexer(DXnCR_DSEL) value.
Detailed Description
Date
2015-12-17
NOTE: This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
Macro Definition Documentation
SPI_SLAVE_DMA_MAXCOUNT
#define SPI_SLAVE_DMA_MAXCOUNT (4095U)
Definition at line 77 of file spi_slave.h.
Typedef Documentation
SPI_SLAVE_cbhandler
typedef void(* SPI_SLAVE_cbhandler) (void)
Function pointer used for callback function.
Definition at line 150 of file spi_slave.h.
SPI_SLAVE_CONFIG_t
typedef struct SPI_SLAVE_CONFIG SPI_SLAVE_CONFIG_t
Structure for holding the configuration parameters of SPI_SLAVE channel.
SPI_SLAVE_DATA_SIZE_t
typedef enum SPI_SLAVE_DATA_SIZE SPI_SLAVE_DATA_SIZE_t
Enum used to identify the size of each word. This only identifies the adressing size but not the actual word length of the channel. Useful for processing user buffer.
SPI_SLAVE_init_handler
typedef SPI_SLAVE_STATUS_t(* SPI_SLAVE_init_handler) (void)
Function pointer used for USIC channel initialization function.
Definition at line 154 of file spi_slave.h.
SPI_SLAVE_INPUT_t
typedef enum SPI_SLAVE_INPUT SPI_SLAVE_INPUT_t
Enum to represent USIC input stage(DXn) multiplexer(DXnCR_DSEL) value.
SPI_SLAVE_PIN_CONFIG_t
typedef struct SPI_SLAVE_PIN_CONFIG SPI_SLAVE_PIN_CONFIG_t
Structure for transmit pin configuration.
SPI_SLAVE_RUNTIME_t
typedef struct SPI_SLAVE_RUNTIME SPI_SLAVE_RUNTIME_t
Structure to hold the dynamic variables for the SPI_SLAVE communication.
SPI_SLAVE_STATUS_t
typedef enum SPI_SLAVE_STATUS SPI_SLAVE_STATUS_t
Enum to describe the possible status values, returned by SPI_SLAVE APIs.
SPI_SLAVE_t
typedef struct SPI_SLAVE SPI_SLAVE_t
Handler structure with pointers to dynamic and static parameters.
SPI_SLAVE_TRANSFER_MODE_t
typedef enum SPI_SLAVE_TRANSFER_MODE SPI_SLAVE_TRANSFER_MODE_t
Enum used to identify the transfer type used for either transmit or receive function.
Enumeration Type Documentation
SPI_SLAVE_DATA_SIZE
enum SPI_SLAVE_DATA_SIZE
Enum used to identify the size of each word. This only identifies the adressing size but not the actual word length of the channel. Useful for processing user buffer.
Enumerator
SPI_SLAVE_DATA_SIZE_8BITS User buffer will be accessed one byte as one word
SPI_SLAVE_DATA_SIZE_16BITS One word will be considered as 16bits, hence 2bytes(16bits) will be considered from user buffer for each transaction(transmit/receive).
SPI_SLAVE_DATA_SIZE_8BITS User buffer will be accessed one byte as one word
SPI_SLAVE_DATA_SIZE_16BITS One word will be considered as 16bits, hence 2bytes(16bits) will be considered from user buffer for each transaction(transmit/receive).
Definition at line 122 of file spi_slave.h.
SPI_SLAVE_INPUT
enum SPI_SLAVE_INPUT
Enum to represent USIC input stage(DXn) multiplexer(DXnCR_DSEL) value.
Enumerator
SPI_SLAVE_INPUT_A Input-A (DXnA)
SPI_SLAVE_INPUT_B Input-B (DXnB)
SPI_SLAVE_INPUT_C Input-C (DXnC)
SPI_SLAVE_INPUT_D Input-D (DXnD)
SPI_SLAVE_INPUT_E Input-E (DXnE)
SPI_SLAVE_INPUT_F Input-F (DXnF)
SPI_SLAVE_INPUT_G Input-G (DXnG)
SPI_SLAVE_INPUT_INVALID Indicates that the input multiplexer value is invalid. Used while switching operation mode.
SPI_SLAVE_INPUT_A Input-A (DXnA)
SPI_SLAVE_INPUT_B Input-B (DXnB)
SPI_SLAVE_INPUT_C Input-C (DXnC)
SPI_SLAVE_INPUT_D Input-D (DXnD)
SPI_SLAVE_INPUT_E Input-E (DXnE)
SPI_SLAVE_INPUT_F Input-F (DXnF)
SPI_SLAVE_INPUT_G Input-G (DXnG)
SPI_SLAVE_INPUT_INVALID Indicates that the input multiplexer value is invalid. Used while switching operation mode.
Definition at line 131 of file spi_slave.h.
SPI_SLAVE_STATUS
enum SPI_SLAVE_STATUS
Enum to describe the possible status values, returned by SPI_SLAVE APIs.
Enumerator
SPI_SLAVE_STATUS_SUCCESS Indicates APP initialization state successful
SPI_SLAVE_STATUS_FAILURE Unknown error
SPI_SLAVE_STATUS_BUSY SPI_SLAVE Busy
SPI_SLAVE_STATUS_BUFFER_INVALID Buffer provided or the buffer size is invalid
SPI_SLAVE_STATUS_MODE_MISMATCH API invoked by a handle configured with different mode. e.g, If SPI_SLAVE_StartTransmitDMA is invoked for an instance which has transmit mode configured as `Interrupt`, will return this status.
SPI_SLAVE_STATUS_SUCCESS Indicates APP initialization state successful
SPI_SLAVE_STATUS_FAILURE Unknown error
SPI_SLAVE_STATUS_BUSY SPI_SLAVE Busy
SPI_SLAVE_STATUS_BUFFER_INVALID Buffer provided or the buffer size is invalid
SPI_SLAVE_STATUS_MODE_MISMATCH API invoked by a handle configured with different mode. e.g, If SPI_SLAVE_StartTransmitDMA is invoked for an instance which has transmit mode configured as `Interrupt`, will return this status.
Definition at line 90 of file spi_slave.h.
SPI_SLAVE_TRANSFER_MODE
enum SPI_SLAVE_TRANSFER_MODE
Enum used to identify the transfer type used for either transmit or receive function.
Enumerator
SPI_SLAVE_TRANSFER_MODE_INTERRUPT Implement data transmit or receive using interrupts
SPI_SLAVE_TRANSFER_MODE_DMA Implement data transmit or receive using DMA
SPI_SLAVE_TRANSFER_MODE_DIRECT This configuration exposes signals for external APP connection
SPI_SLAVE_TRANSFER_MODE_INTERRUPT Implement data transmit or receive using interrupts
SPI_SLAVE_TRANSFER_MODE_DMA Implement data transmit or receive using DMA
SPI_SLAVE_TRANSFER_MODE_DIRECT This configuration exposes signals for external APP connection
Definition at line 111 of file spi_slave.h.
Function Documentation
SPI_SLAVE_AbortReceive()
SPI_SLAVE_STATUS_t SPI_SLAVE_AbortReceive (const SPI_SLAVE_t *const handle)
Stops the active data reception sequence.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
SPI_SLAVE_STATUS_t: Result of reception abort request.
 SPI_SLAVE_STATUS_SUCCESS if the SPI_SLAVE channel reception has been stopped.
 SPI_SLAVE_STATUS_MODE_MISMATCH if receive mode is Direct.
Description:
If a reception is in progress, it will be stopped. When a reception request is active, user will not be able to place a new receive request till the active reception is complete. This API can stop the progressing reception to make a new receive request. Abort request for receive mode direct cannot be serviced since the direct mode receive API is a blocking call.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Transmit mode and receive mode should be configured as "Interrupt".
 //Description:
 //Transmits the string "Infineon DAVE application" to the master.
 //Starts to receive data from master, checks if the first byte is 0x55.
 //If so, aborts the reception and retransmits 0x55 to master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = "Infineon DAVE application.";
   uint8_t Rec_Data[64];
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     SPI_SLAVE_Transmit(&SPI_SLAVE_0, Send_Data, sizeof(Send_Data));
     while(SPI_SLAVE_0.runtime->tx_busy);
     SPI_SLAVE_Receive(&SPI_SLAVE_0, Rec_Data, 15);
     while(SPI_SLAVE_0.runtime->rx_data_index == 0);
     if(SPI_SLAVE_0.runtime->rx_data[0] == 0x55)
     {
       if(SPI_SLAVE_AbortReceive(&SPI_SLAVE_0) == SPI_SLAVE_STATUS_SUCCESS)
       {
         SPI_SLAVE_Transmit(&SPI_SLAVE_0, Rec_Data, 1);
       }
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 324 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE_CONFIG::receive_mode, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_RUNTIME::rx_data, SPI_SLAVE_CONFIG::rx_fifo_size, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_TRANSFER_MODE_DMA, SPI_SLAVE_TRANSFER_MODE_INTERRUPT, XMC_ASSERT, XMC_SPI_CH_DisableEvent(), XMC_SPI_CH_EVENT_ALTERNATIVE_RECEIVE, XMC_SPI_CH_EVENT_STANDARD_RECEIVE, XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_RXFIFO_DisableEvent(), XMC_USIC_CH_RXFIFO_EVENT_CONF_ALTERNATE, and XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD.
SPI_SLAVE_AbortTransmit()
SPI_SLAVE_STATUS_t SPI_SLAVE_AbortTransmit (const SPI_SLAVE_t *const handle)
Aborts the ongoing data transmission.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
SPI_SLAVE_STATUS_t: Result of transmit abort request.
 SPI_SLAVE_STATUS_SUCCESS if the SPI_SLAVE channel transmission is stopped successfully.
 SPI_SLAVE_STATUS_MODE_MISMATCH if transmit mode is Direct.
Description:
If there is a transmission in progress, it will be stopped. If transmit FIFO is used, the existing data will be flushed. After the transmission is stopped, user can start a new transmission without delay. Abort request for transmit mode direct cannot be serviced since the direct mode transmit API is a blocking call.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Transmit mode should be configured as "Interrupt".
 //Description:
 //Transmits test data from buffer Send_Data and aborts it immediately.
 //Retransmits data from NewData.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {0x55, 0xaa, 0x5a, 0xa5, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99};
   uint8_t NewData[] = {0,1,2,3,4,5,6,7,8,9};
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     SPI_SLAVE_Transmit(&SPI_SLAVE_0, Send_Data, sizeof(Send_Data));
     if(SPI_SLAVE_0.runtime->tx_busy)
     {
       if(SPI_SLAVE_AbortTransmit(&SPI_SLAVE_0) == SPI_SLAVE_STATUS_SUCCESS)
       {
         SPI_SLAVE_Transmit(&SPI_SLAVE_0, NewData, sizeof(NewData));
       }
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 254 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE::runtime, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_TRANSFER_MODE_DMA, SPI_SLAVE_TRANSFER_MODE_INTERRUPT, SPI_SLAVE_CONFIG::transmit_mode, SPI_SLAVE_RUNTIME::tx_busy, SPI_SLAVE_RUNTIME::tx_data, SPI_SLAVE_CONFIG::tx_fifo_size, XMC_ASSERT, XMC_SPI_CH_DisableEvent(), XMC_SPI_CH_EVENT_RECEIVE_START, XMC_SPI_CH_EVENT_TRANSMIT_BUFFER, XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_SetTransmitBufferStatus(), XMC_USIC_CH_TBUF_STATUS_SET_IDLE, XMC_USIC_CH_TXFIFO_DisableEvent(), XMC_USIC_CH_TXFIFO_EVENT_CONF_STANDARD, and XMC_USIC_CH_TXFIFO_Flush().
SPI_SLAVE_ClearFlag()
__STATIC_INLINE void SPI_SLAVE_ClearFlag (const SPI_SLAVE_t * handle, const uint32_t flag_mask)
Clears the event status in the register(PSR_SSCMode).
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
protocol_status Event whose status is to be cleared.
 Range: Use type XMC_SPI_CH_STATUS_FLAG_t for input. Multiple events can be combined using OR operation.
Returns
None
Description:
Clears a given protocol event flag bit using the PSCR register. This function is an inline wrapper for the API provided by xmc_spi.h file. The user should mask the input value based on the events to be cleared.
Example Usage:
#include <DAVE.h>
//Description:
//Receives a data word and retransmits it to the master as the next word.
int main(void)
{
  DAVE_STATUS_t init_status;
  uint16_t ReceiveData = 0;
  init_status = DAVE_Init();
  if(init_status == DAVE_STATUS_SUCCESS)
  {
    while(1U)
    {
       //Check if any data received
       if(SPI_SLAVE_GetFlagStatus(&SPI_SLAVE_0, (XMC_SPI_CH_STATUS_FLAG_RECEIVE_INDICATION |
        XMC_SPI_CH_STATUS_FLAG_ALTERNATIVE_RECEIVE_INDICATION)))
       {
          //Read the received data
          ReceiveData = XMC_SPI_CH_GetReceivedData(SPI_SLAVE_0.channel);
          //Transmit the received data
          SPI_SLAVE_TransmitWord(&SPI_SLAVE_0,ReceiveData);
          //Clear the receive flags
          SPI_SLAVE_ClearFlag(&SPI_SLAVE_0,(XMC_SPI_CH_STATUS_FLAG_RECEIVE_INDICATION |
                   XMC_SPI_CH_STATUS_FLAG_ALTERNATIVE_RECEIVE_INDICATION));
       }
    }
  }
  else
  {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
  }
  return 1U;
}
Definition at line 1224 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_SPI_CH_ClearStatusFlag().
SPI_SLAVE_ClearRXFIFOStatus()
__STATIC_INLINE void SPI_SLAVE_ClearRXFIFOStatus (const SPI_SLAVE_t *const handle, const uint32_t flag)
Function clears the specified FIFO event flag related to receive FIFO. It should be used to clear the status of standard receive buffer interrupt, alternative receive buffer interupt and receive buffer error interrupt flags.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
flag Value with event bits at the bit positions in TRBSR register to be cleared.
 Range: Use type XMC_USIC_CH_RXFIFO_EVENT_t for providing events. Multiple events can be input by using OR operation.
Returns
None
Description:
Function clears a status bit in TRBSR using the TRBSCR register. The function does not mask the input value to clear only receive buffer events. So user should appropriately mask the input value before calling the function.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure transmit mode and receive mode as "Direct".
// Description:
 //The example below receives 10 words from the master. Transmits the received 10 words in the
 //subsequent clock cycles.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint16_t Rec_Data[10];
   uint32_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      //Configure the receive FIFO to generate event when the FIFO is filled with 10 words.
      SPI_SLAVE_SetRXFIFOTriggerLimit(&SPI_SLAVE_0, 9);
      //Receive 10 words input
      data_index = 0;
      //Wait for receive FIFO to be filled
      while(!(SPI_SLAVE_GetRXFIFOStatus(&SPI_SLAVE_0) &
           (XMC_USIC_CH_RXFIFO_EVENT_STANDARD | XMC_USIC_CH_RXFIFO_EVENT_ALTERNATE)))
      {
      }
      SPI_SLAVE_ClearRXFIFOStatus(&SPI_SLAVE_0, (XMC_USIC_CH_RXFIFO_EVENT_STANDARD | XMC_USIC_CH_RXFIFO_EVENT_ALTERNATE));
        while(1)
        {
          Rec_Data[data_index] = SPI_SLAVE_GetReceivedWord(&SPI_SLAVE_0);
          data_index++;
          //Break out of while(1) if 10 words are received.
          if(data_index == 10)
          {
            break;
          }
          else
          {
            //Wait if FIFO is empty
            while(SPI_SLAVE_IsRXFIFOEmpty(&SPI_SLAVE_0));
          }
        }
      //Transmit the received data
      SPI_SLAVE_Transmit(&SPI_SLAVE_0,Rec_Data, 10);
      while(SPI_SLAVE_0.runtime->tx_busy);
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 2068 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_USIC_CH_RXFIFO_ClearEvent().
SPI_SLAVE_ClearTXFIFOStatus()
__STATIC_INLINE void SPI_SLAVE_ClearTXFIFOStatus (const SPI_SLAVE_t *const handle, const uint32_t flag)
Function clears the specified FIFO event flag related to transmit FIFO.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
flag Value with event bits at their bit positions in TRBSR register to be cleared.
 Range: Use type XMC_USIC_CH_TXFIFO_EVENT_t. Multiple events can be combined using OR operation.
Returns
None
Description:
Function clears a status bit in TRBSR register using the TRBSCR register. But the function does not mask the input value with the bit positions restricted to transmit FIFO status bits. User should ensure that the input value is appropriately masked.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition: Configure transmit mode as 'Direct', set transmit FIFO size as 8.
// Description:
 //Example below transmits 10 bytes of data to the master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
   uint8_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      //Configure the transmit FIFO to generate event when FIFO level drops from 5 to 4.
      SPI_SLAVE_SetTXFIFOTriggerLimit(&SPI_SLAVE_0, 5);
      while(data_index < sizeof(Send_Data))
      {
         //Put data into the FIFO till it gets full
         if(SPI_SLAVE_IsTXFIFOFull(&SPI_SLAVE_0) == false)
         {
           SPI_SLAVE_TransmitWord(&SPI_SLAVE_0,(uint16_t)Send_Data[data_index]);
           data_index++;
         }
         else
         {
           //Wait for FIFO transmit standard buffer interrupt to fill it again with remaining data
           while((SPI_SLAVE_GetTXFIFOStatus(&SPI_SLAVE_0) & XMC_USIC_CH_TXFIFO_EVENT_STANDARD) == 0);
           SPI_SLAVE_ClearTXFIFOStatus(&SPI_SLAVE_0, XMC_USIC_CH_TXFIFO_EVENT_STANDARD);
         }
      }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 1977 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_USIC_CH_TXFIFO_ClearEvent().
SPI_SLAVE_DisableEvent()
__STATIC_INLINE void SPI_SLAVE_DisableEvent (const SPI_SLAVE_t *const handle, uint32_t events)
Disables selected events from generating interrupt.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
events Events to be disabled from generating interrupt.
 Range: Use type XMC_SPI_CH_EVENT_t to select the event. Multiple events can be combined using the bitwise OR operation.
Returns
None
Description:
Events are disabled by clearing their respective bits in either CCR or PCR register.
Example Usage:
#include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 // Precondition:
 // Add INTERRUPT APP and connect the SPI_SLAVE APP protocol interrupt signal to the INTERRUPT APP
 // irq signal. Provide the callback function name in INTERRUPT APP as "ProtocolInterrupt".
 //
 // Description: The example configures protocol interrupt for data loss detection.
 // When the data loss interrupt occurs, the receive FIFO is cleared. After the receive FIFO
 // is cleared, the channel can receive few bytes till the FIFO gets filled.
 int main(void)
 {
   DAVE_STATUS_t status;
   status = DAVE_Init();
   if(status == DAVE_STATUS_FAILURE)
   {
     XMC_DEBUG("DAVE APPs initialization failed\n");
     while(1U)
     {
     }
   }
   SPI_SLAVE_EnableEvent(&SPI_SLAVE_0, XMC_SPI_CH_EVENT_DATA_LOST);
   while(1U)
   {
   }
 }
 void ProtocolInterrupt()
 {
   SPI_SLAVE_DisableEvent(&SPI_SLAVE_0, XMC_SPI_CH_EVENT_DATA_LOST);
   //Clear receive FIFO so that data will be received.
   XMC_USIC_CH_RXFIFO_Flush(SPI_SLAVE_0.channel);
   SPI_SLAVE_EnableEvent(&SPI_SLAVE_0, XMC_SPI_CH_EVENT_DATA_LOST);
 }
Definition at line 1495 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_SPI_CH_DisableEvent().
SPI_SLAVE_EnableEvent()
__STATIC_INLINE void SPI_SLAVE_EnableEvent (const SPI_SLAVE_t *const handle, uint32_t events)
Enables the selected protocol events for interrupt generation.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
events Protocol events to be enabled for interrupt generation.
 Range: Use type XMC_SPI_CH_EVENT_t to select the event. Multiple events can be combined using the bitwise OR operation.
Returns
None
Description:
Enables the events by configuring CCR or PCR register based on the event. When the event is enabled, an interrupt can be generated on occurrence of the event. The API can be used for protocol events(PCR_SSC events) only when the callback functions are not registered under 'Error and Protocol Handling' group.
Example Usage:
#include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 // Precondition:
 // Add INTERRUPT APP and connect the SPI_SLAVE APP protocol interrupt signal to the INTERRUPT APP
 // irq signal. Provide the callback function name in INTERRUPT APP as "ProtocolInterrupt".
 //
 // Description: The example configures protocol interrupt for data loss detection.
 // When the data loss interrupt occurs, the receive FIFO is cleared. After the receive FIFO
 // is cleared, the channel can receive few bytes till the FIFO gets filled.
 int main(void)
 {
   DAVE_STATUS_t status;
   //Initializes USIC for SPI slave functionality
   status = DAVE_Init();
   if(status == DAVE_STATUS_FAILURE)
   {
     XMC_DEBUG("DAVE APPs initialization failed\n");
     while(1U)
     {
     }
   }
   //Enable the data lost event to generate interrupt
   SPI_SLAVE_EnableEvent(&SPI_SLAVE_0, XMC_SPI_CH_EVENT_DATA_LOST);
   while(1U)
   {
   }
 }
 //Protocol interrupt handler
 void ProtocolInterrupt()
 {
   SPI_SLAVE_DisableEvent(&SPI_SLAVE_0, XMC_SPI_CH_EVENT_DATA_LOST);
   //Clear receive FIFO so that data will be received.
   XMC_USIC_CH_RXFIFO_Flush(SPI_SLAVE_0.channel);
   //Enable the event to generate interrupt again.
   SPI_SLAVE_EnableEvent(&SPI_SLAVE_0, XMC_SPI_CH_EVENT_DATA_LOST);
 }
Definition at line 1434 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_SPI_CH_EnableEvent().
SPI_SLAVE_GetAppVersion()
DAVE_APP_VERSION_t SPI_SLAVE_GetAppVersion (void)
Get the SPI_SLAVE APP version.
Returns
DAVE_APP_VERSION_t APP version information (major, minor and patch number)
Example Usage:
#include <DAVE.h>
//Example below, transmits data to master only if the version of the SPI_SLAVE APP is v4.0.x
//Value of x can be anything.
int main(void)
{
  SPI_SLAVE_STATUS_t init_status;
  DAVE_APP_VERSION_t spi_slave_version;
  uint8_t valid_data[] = {0x55, 0xaa, 0x5a, 0xa5};
  init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
  if(init_status == SPI_SLAVE_STATUS_SUCCESS)
  {
    spi_slave_version = SPI_SLAVE_GetAppVersion();
    //Check the APP version
    if((spi_slave_version.major == 4) &&
      (spi_slave_version.minor == 0))
    {
      //Transmit data
      SPI_SLAVE_Transmit(&SPI_SLAVE_0, valid_data, sizeof(valid_data));
    }
  }
  else
  {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
  }
  return 1U;
}
Definition at line 111 of file spi_slave.c.
SPI_SLAVE_GetFlagStatus()
__STATIC_INLINE uint32_t SPI_SLAVE_GetFlagStatus (SPI_SLAVE_t * handle, const uint32_t flag)
Provides the status of protocol events.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
protocol_status Event whose status is to be read.
 Range: Use type XMC_SPI_CH_STATUS_FLAG_t for input. Multiple events can be combined using OR operation.
Returns
uint32_t: Status of selected protocol events read from PSR_SSCMode register.
Range: Use type XMC_SPI_CH_STATUS_FLAG_t for comparing the return value with event bitmasks. Status of multiple events can be checked by combining enum values using OR operation while comparing.
Description:
Reads the protocol status bits from the register PSR_SSCMode and compares the values with the input value of selected events. Returns the masked value of selected events with the status register value.
Example Usage:
#include <DAVE.h>
//Configure SPI_SLAVE word length = 16, frame length = 64.
//Description:
//The example below, waits for slave select signal to be asserted.
//It receives 10 words from the SPI master.
//Transmits the received data in the subsequent clock cycles.
//For the communication to start, master should transmit 10 words and
//receive 10 words.
int main(void)
{
  DAVE_STATUS_t init_status;
  uint16_t ReceiveData[10];
  init_status = DAVE_Init();
  if(init_status == DAVE_STATUS_SUCCESS)
  {
    while(1U)
    {
      //Wait for slave select signal to be asserted
      if(SPI_SLAVE_GetFlagStatus(&SPI_SLAVE_0, XMC_SPI_CH_STATUS_FLAG_DX2S))
      {
        if(SPI_SLAVE_Receive(&SPI_SLAVE_0, ReceiveData, 10) == SPI_SLAVE_STATUS_SUCCESS)
        {
          //Wait for reception of 10 words
          while(SPI_SLAVE_IsRxBusy(&SPI_SLAVE_0))
          {
          }
          SPI_SLAVE_Transmit(&SPI_SLAVE_0, ReceiveData, 10);
          //Wait for transmission of 10 words
          while(SPI_SLAVE_IsTxBusy(&SPI_SLAVE_0))
          {
          }
        }
      }
    }
  }
  else
  {
   XMC_DEBUG("main: Application initialization failed");
   while(1U)
   {
   }
  }
  return 1U;
}
Definition at line 1159 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_SPI_CH_GetStatusFlag().
SPI_SLAVE_GetReceivedWord()
__STATIC_INLINE uint16_t SPI_SLAVE_GetReceivedWord (const SPI_SLAVE_t *const handle)
Provides data received in the receive buffer.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
uint16_t: Data read from RBUF or FIFO.
Description:
This can be used in receive mode `Direct` to read the received data. If receive FIFO is not configured, function reads the value of RBUF register. Otherwise the data is read from OUTR register. User can poll for receive event or configure an interrupt by connecting external INTERRUPT APP with receive event signals. This API can be used inside the ISR to read the received data.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure transmit mode and receive mode as "Direct".
 //Description:
 //The example below receives 10 words from the master. Transmits the received 10 words in the
 //subsequent clock cycles.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint16_t Rec_Data[10];
   uint32_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      //Configure the receive FIFO to generate event when the FIFO is filled with 10 words.
      SPI_SLAVE_SetRXFIFOTriggerLimit(&SPI_SLAVE_0, 9);
      //Receive 10 words input
      data_index = 0;
      //Wait for receive FIFO to be filled
      while(!(SPI_SLAVE_GetRXFIFOStatus(&SPI_SLAVE_0) &
           (XMC_USIC_CH_RXFIFO_EVENT_STANDARD | XMC_USIC_CH_RXFIFO_EVENT_ALTERNATE)))
      {
      }
        while(1)
        {
          Rec_Data[data_index] = SPI_SLAVE_GetReceivedWord(&SPI_SLAVE_0);
          data_index++;
          //Break out of while(1) if 10 words are received.
          if(data_index == 10)
          {
            break;
          }
          else
          {
            //Wait if FIFO is empty
            while(SPI_SLAVE_IsRXFIFOEmpty(&SPI_SLAVE_0));
          }
        }
      //Transmit the received data
      SPI_SLAVE_Transmit(&SPI_SLAVE_0,Rec_Data, 10);
      while(SPI_SLAVE_0.runtime->tx_busy);
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 1306 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_SPI_CH_GetReceivedData().
SPI_SLAVE_GetRXFIFOStatus()
__STATIC_INLINE uint32_t SPI_SLAVE_GetRXFIFOStatus (const SPI_SLAVE_t *const handle)
Gets the status of event flags related to receive FIFO.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
uint32_t: Status of standard receive buffer event, alternative receive buffer event and receive buffer error event in their bit positions in TRBSR register.
Range: Use type XMC_USIC_CH_RXFIFO_EVENT_t for event bitmasks. Multiple events' status can be combined for comparison using OR operation.
Description:
It provides the status of standard receive buffer event, alternative receive buffer event and receive buffer error event. Function masks the TRBSR register with the bitmask of SRBI, ARBI and RBERI flags. User has to mask the bits of interest before checking the status.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure transmit mode and receive mode as "Direct".
// Description:
 //The example below receives 10 words from the master. Transmits the received 10 words in the
 //subsequent clock cycles.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint16_t Rec_Data[10];
   uint32_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      //Configure the receive FIFO to generate event when the FIFO is filled with 10 words.
      SPI_SLAVE_SetRXFIFOTriggerLimit(&SPI_SLAVE_0, 9);
      //Receive 10 words input
      data_index = 0;
      //Wait for receive FIFO to be filled
      while(!(SPI_SLAVE_GetRXFIFOStatus(&SPI_SLAVE_0) &
           (XMC_USIC_CH_RXFIFO_EVENT_STANDARD | XMC_USIC_CH_RXFIFO_EVENT_ALTERNATE)))
      {
      }
      SPI_SLAVE_ClearRXFIFOStatus(&SPI_SLAVE_0, (XMC_USIC_CH_RXFIFO_EVENT_STANDARD | XMC_USIC_CH_RXFIFO_EVENT_ALTERNATE));
        while(1)
        {
          Rec_Data[data_index] = SPI_SLAVE_GetReceivedWord(&SPI_SLAVE_0);
          data_index++;
          //Break out of while(1) if 10 words are received.
          if(data_index == 10)
          {
            break;
          }
          else
          {
            //Wait if FIFO is empty
            while(SPI_SLAVE_IsRXFIFOEmpty(&SPI_SLAVE_0));
          }
        }
      //Transmit the received data
      SPI_SLAVE_Transmit(&SPI_SLAVE_0,Rec_Data, 10);
      while(SPI_SLAVE_0.runtime->tx_busy);
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 1838 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_USIC_CH_RXFIFO_GetEvent().
SPI_SLAVE_GetTXFIFOStatus()
__STATIC_INLINE uint32_t SPI_SLAVE_GetTXFIFOStatus (const SPI_SLAVE_t *const handle)
Gets the status of transmit FIFO event flags.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
uint32_t: Status of the STBI and TBERI bits in TRBSR register in their bit positions.
 Range: Use type XMC_USIC_CH_TXFIFO_EVENT_t for the bitmask of events.
Description:
Function reads the value of TRBSR register. It masks the standard transmit buffer interrupt flag and transmit buffer error flag before providing the value. User has to mask the bits of interest before checking the status.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition: Configure transmit mode as 'Direct', set transmit FIFO size as 8.
// Description:
 //Example below transmits 10 bytes of data to the master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
   uint8_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      //Configure the transmit FIFO to generate event when FIFO level drops from 5 to 4.
      SPI_SLAVE_SetTXFIFOTriggerLimit(&SPI_SLAVE_0, 5);
      while(data_index < sizeof(Send_Data))
      {
         //Put data into the FIFO till it gets full
         if(SPI_SLAVE_IsTXFIFOFull(&SPI_SLAVE_0) == false)
         {
           SPI_SLAVE_TransmitWord(&SPI_SLAVE_0,(uint16_t)Send_Data[data_index]);
           data_index++;
         }
         else
         {
           //Wait for FIFO transmit standard buffer interrupt to fill it again with remaining data
           while((SPI_SLAVE_GetTXFIFOStatus(&SPI_SLAVE_0) & XMC_USIC_CH_TXFIFO_EVENT_STANDARD) == 0);
           SPI_SLAVE_ClearTXFIFOStatus(&SPI_SLAVE_0, XMC_USIC_CH_TXFIFO_EVENT_STANDARD);
         }
      }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 1905 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_USIC_CH_TXFIFO_GetEvent().
SPI_SLAVE_Init()
SPI_SLAVE_STATUS_t SPI_SLAVE_Init (const SPI_SLAVE_t *const handle)
Initializes the USIC channel as SPI slave.
Parameters
handle Pointer to static and dynamic attributes of APP configuration.
Returns
SPI_SLAVE_STATUS_t: Status of SPI_SLAVE driver initialization.
 SPI_SLAVE_STATUS_SUCCESS - on successful initialization.
 SPI_SLAVE_STATUS_FAILURE - if initialization fails.
 SPI_SLAVE_STATUS_BUSY - if SPI_SLAVE channel is busy.
Description:
Initializes IO pins used for the SPI_SLAVE communication, configures USIC registers based on the GUI modifications. It also configures selected interrupts, DMA channels and peripheral register bitfields.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
       while(1U)
       {
       }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 132 of file spi_slave.c.
SPI_SLAVE_IsRxBusy()
__STATIC_INLINE bool SPI_SLAVE_IsRxBusy (const SPI_SLAVE_t *const handle)
Function provides the status of data reception.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
bool Status of data reception.
 Range: true - Data reception is in progress.
 false - No reception in progress.
Description:
Function provides the status of APP handle member SPI_SLAVE.runtime->rx_busy. This flag will be true if a reception is in progress and it will change to false when the reception of given count is finished.
 The API can be used after executing SPI_SLAVE_Receive(), SPI_SLAVE_Transfer() APIs to check if the reception or transfer is finished.
Example Usage:
#include <DAVE.h>
//Description:
//The example below, waits for slave select signal to be asserted.
//Receive 10 bytes from the SPI master.
//For the communication to start, master should transmit 10 bytes.
int main(void)
{
  DAVE_STATUS_t init_status;
  uint8_t ReceiveData[10];
  init_status = DAVE_Init();
  if(init_status == DAVE_STATUS_SUCCESS)
  {
    //Wait for slave select signal to be asserted
    while(!(SPI_SLAVE_GetFlagStatus(&SPI_SLAVE_0, XMC_SPI_CH_STATUS_FLAG_DX2S)))
    {
      SPI_SLAVE_Receive(&SPI_SLAVE_0, ReceiveData, 10);
      //Wait for transmission of 10 words
      while(SPI_SLAVE_IsRxBusy(&SPI_SLAVE_0))
      {
      }
    }
    while(1)
    {
    }
  }
  else
  {
   XMC_DEBUG("main: Application initialization failed");
   while(1U)
   {
   }
  }
  return 1U;
}
Definition at line 2204 of file spi_slave.h.
References SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, and XMC_ASSERT.
SPI_SLAVE_IsRXFIFOEmpty()
__STATIC_INLINE bool SPI_SLAVE_IsRXFIFOEmpty (const SPI_SLAVE_t *const handle)
Checks if the receive FIFO is empty.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
bool Status of receive FIFO filling level.
 Range: true - if receive FIFO is empty.
 false - if receive FIFO still has data.
Description:
Checks the status using the register TRBSR. Can be used while reading data from the receive FIFO.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 // Precondition:
 // Receive mode should be "Direct", word length = 16
 //
 // Description:
 // Receives 10 words and transmits the received 10 words.
uint16_t rec_data[10U];
int main(void)
{
  DAVE_STATUS_t status;
  uint32_t loc_index;
  status = DAVE_Init(); // Initialization of DAVE APPs
  if(status == DAVE_STATUS_FAILURE)
  {
    XMC_DEBUG("DAVE APPs initialization failed\n");
    while(1U)
    {
    }
  }
  //sizeof() returns the number of bytes
  for(loc_index = 0; loc_index < (sizeof(rec_data)/2U); loc_index++)
  {
    //Wait when Rx FIFO is empty
    while(SPI_SLAVE_IsRXFIFOEmpty(&SPI_SLAVE_0))
    {
    }
    rec_data[loc_index] = SPI_SLAVE_GetReceivedWord(&SPI_SLAVE_0);
  }
  //Transmit the received data
  SPI_SLAVE_Transmit(&SPI_SLAVE_0, rec_data, sizeof(rec_data)/2U);
  while(1U)
  {
  }
}
Definition at line 1615 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_USIC_CH_RXFIFO_IsEmpty().
SPI_SLAVE_IsTxBusy()
__STATIC_INLINE bool SPI_SLAVE_IsTxBusy (const SPI_SLAVE_t *const handle)
Function provides the status of data transmission.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
bool Status of data transmission.
 Range: true - Data transmission is in progress.
 false - No transmission in progress.
Description:
Function provides the status of APP handle member SPI_SLAVE.runtime->tx_busy. This flag will be true if a transmission is in progress and it will change to false when the transmission has finished.
 Note: Even after the state changes from true to false, one word might still be present in the shift register.
 It is recommended to provide some wait time before stopping the channel after transmission.
Example Usage:
#include <DAVE.h>
//Description:
//The example below, waits for slave select signal to be asserted.
//Transmits 10 bytes to the SPI master.
//For the communication to start, master should receive 10 bytes.
int main(void)
{
  DAVE_STATUS_t init_status;
  uint8_t SendData[10] = {0,1,2,3,4,5,6,7,8,9};
  init_status = DAVE_Init();
  if(init_status == DAVE_STATUS_SUCCESS)
  {
    //Wait for slave select signal to be asserted
    while(!(SPI_SLAVE_GetFlagStatus(&SPI_SLAVE_0, XMC_SPI_CH_STATUS_FLAG_DX2S)))
    {
      SPI_SLAVE_Transmit(&SPI_SLAVE_0, SendData, 10);
      //Wait for transmission of 10 words
      while(SPI_SLAVE_IsTxBusy(&SPI_SLAVE_0))
      {
      }
    }
    while(1)
    {
    }
  }
  else
  {
   XMC_DEBUG("main: Application initialization failed");
   while(1U)
   {
   }
  }
  return 1U;
}
Definition at line 2136 of file spi_slave.h.
References SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::tx_busy, and XMC_ASSERT.
SPI_SLAVE_IsTXFIFOFull()
__STATIC_INLINE bool SPI_SLAVE_IsTXFIFOFull (const SPI_SLAVE_t *const handle)
Checks if the transmit FIFO is full.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
Returns
bool Status of transmit FIFO filling level.
 Range: true - if transmit FIFO is full.
 false - if transmit FIFO is not full.
Description:
Checks the status using the register TRBSR. Can be used while filling data to the transmit FIFO.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 // Precondition:
 // Transmit mode should be "Direct"
 // Description:
 // Transmits 10 words using FIFO.
uint16_t send_data[] = {0,1,2,3,4,5,6,7,8,9};
int main(void)
{
  DAVE_STATUS_t status;
  uint32_t loc_index;
  status = DAVE_Init(); // Initialization of DAVE APPs
  if(status == DAVE_STATUS_FAILURE)
  {
    XMC_DEBUG("DAVE APPs initialization failed\n");
    while(1U)
    {
    }
  }
  for(loc_index = 0; loc_index < sizeof(send_data)/2U; loc_index++)
  {
    //Wait when Tx FIFO is full
    while(SPI_SLAVE_IsTXFIFOFull(&SPI_SLAVE_0))
    {
    }
    SPI_SLAVE_TransmitWord(&SPI_SLAVE_0, send_data[loc_index]);
  }
  while(1U)
  {
  }
}
Definition at line 1553 of file spi_slave.h.
References SPI_SLAVE::channel, XMC_ASSERT, and XMC_USIC_CH_TXFIFO_IsFull().
SPI_SLAVE_Receive()
SPI_SLAVE_STATUS_t SPI_SLAVE_Receive (const SPI_SLAVE_t *const handle, uint8_t * data_ptr, uint32_t count)
Registers a request for receiving data over SPI_SLAVE channel.
Parameters
handle Pointer to SPI_SLAVE_t handle structure
data_ptr Pointer to data of type uint8_t.
count Total no of bytes to be received.
 Range: minimum= 1, maximum= maximum value supported by type uint32_t.
 In DMA mode, a maximum of 4095 words can be received in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status for receive request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a reception is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
Description:
Data will be received from the SPI master synchronously. After the requested number of data bytes are received, optionally, the user configured callback function will be executed. Data reception is accomplished using the receive mode selected in the UI. Interrupt:
 Based on the UI configuration, either standard receive buffer(RBUF) or receive FIFO(OUT) is used for data reception. An interrupt is configured for reading received data from the bus. This function only registers a request to receive a number of data bytes from a USIC channel. If FIFO is configured for reception, the FIFO limit is dynamically configured to optimally utilize the CPU load. Before starting data reception, the receive buffers are flushed. So only those data, received after calling the API, will be placed in the user buffer. When all the requested number of data bytes are received, the configured callback function will be executed. If a callback function is not configured, the user has to poll for the value of the variable, handle->runtime->rx_busy to be false. The value is updated to false when all the requested number of data bytes are received.
 DMA:
 DMA mode is available only in XMC4x family of microcontrollers. In this mode, a DMA channel is configured for receiving data from standard receive buffer(RBUF) to the user buffer. By calling this API, the DMA channel destination address is configured to the user buffer and the channel is enabled. Receive FIFO will not be used when the receive mode is DMA. Before starting data reception, the receive buffers are flushed. So only those data, received after calling the API, will be placed in the user buffer. When all the requested number of data bytes are received, the configured callback function will be executed. If a callback function is not configured, the user has to poll for the value of the variable, handle->runtime->rx_busy to be false. The value is updated to false when all the requested number of data bytes are received.
 Direct
 In Direct receive mode, neither interrupt nor DMA is used. The API polls the receive flag to read the received data and waits for all the requested number of bytes to be received. Based on FIFO configuration, either RBUF or OUT register is used for reading received data. Before starting data reception, the receive buffers are flushed. So only those data, received after calling the API, will be placed in the user buffer. Note: In Direct mode, the API blocks the CPU until the count of bytes requested is received. If this behaviour is not desired, use other APIs like SPI_SLAVE_GetReceivedWord, SPI_SLAVE_GetProtocolStatus etc.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Receive mode should be configured as "Direct".
 //Description:
 //Receives 10 bytes from master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t ReadData[10];
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     if(SPI_SLAVE_Receive(&SPI_SLAVE_0, ReadData, 10) == SPI_SLAVE_STATUS_SUCCESS)
     {
       SPI_SLAVE_Transmit(&SPI_SLAVE_0, ReadData, 10);
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 207 of file spi_slave.c.
SPI_SLAVE_SetMode()
SPI_SLAVE_STATUS_t SPI_SLAVE_SetMode (const SPI_SLAVE_t *const handle, XMC_SPI_CH_MODE_t mode)
Changes the operation mode of the SPI slave channel.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
mode Operation mode to be configured.
Range: XMC_SPI_CH_MODE_STANDARD - Full duplex
 XMC_SPI_CH_MODE_STANDARD_HALFDUPLEX - Half duplex
 XMC_SPI_CH_MODE_DUAL - Dual SPI
 XMC_SPI_CH_MODE_QUAD - Quad SPI
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission or reception is in progress.
 SPI_SLAVE_STATUS_FAILURE if the mode change is not possible.
 Imp Note: Return value should be validated by user to ensure that the operation mode is changed.
Description:
Tries to change the operation mode of the SPI channel. Mode change is possible when the operation mode configured in the GUI uses higher number of pins than the new mode requested. Mode change is not possible when the GUI configured operation mode is 'Full Duplex' or 'Half Duplex'. This is due to the connection between MOSI and MISO pins. In 'Full Duplex' mode, MOSI pin of the SPI slave device will be configured as input. But in 'Half Duplex' mode, the same pin has to be configured as output pin with the alternate function of USIC channel DOUT0. Information about the output alternate function will not be available with the APP at runtime. So change of operation mode from 'Full Duplex' to 'Half Duplex' is not possible. Mode change is possible from 'Quad SPI' to 'Dual SPI' or to 'Half Duplex' or to 'Full Duplex'. Mode change is also possible from 'Dual SPI' to 'Half Duplex' or 'Full Duplex'. But mode change from 'Dual SPI' to 'Quad SPI' is not possible. When the mode change is not possible, the API will return the status SPI_SLAVE_STATUS_FAILURE.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure the SPI_SLAVE APP operation mode as 'Quad SPI'.
 //Description:
 //The following code expects a command from SPI master device (0x08, 0x01) to change the operation mode to 'Half Duplex'
 //After receiving the code, slave device changes opeation mode and starts waiting for 4 words of data.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[10];
   uint8_t Rec_Data[10];
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     SPI_SLAVE_Receive(&SPI_SLAVE_0, Rec_Data, 2);
     while(SPI_SLAVE_0.runtime->rx_busy)
     {
     }
     if((Rec_Data[0] == 0x08) && (Rec_Data[1] == 0x01))
     {
       if(SPI_SLAVE_SetMode(&SPI_SLAVE_0, XMC_SPI_CH_MODE_STANDARD_HALFDUPLEX) == SPI_SLAVE_STATUS_FAILURE)
       {
         while(1);
       }
       else
       {
         SPI_SLAVE_Receive(&SPI_SLAVE_0, Rec_Data, 4);
         while(SPI_SLAVE_0.runtime->rx_busy)
         {
         }
       }
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 379 of file spi_slave.c.
SPI_SLAVE_SetRXFIFOTriggerLimit()
__STATIC_INLINE void SPI_SLAVE_SetRXFIFOTriggerLimit (const SPI_SLAVE_t *const handle, uint32_t limit)
Configures trigger limit for the receive FIFO.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
limit Value of receive FIFO filling level, transition above which the interrupt should be generated.
 \bRange: 0 to receive FIFO size.
 e.g, If receive FIFO size is 16, and limit is configured as 8, FIFO receive buffer interrupt will be generated when the FIFO filling level rises from 8 to 9.
Returns
None
Description:
Receive FIFO trigger limit is configured by setting its value in the RBCTR register. Receive FIFO is configured to generate interrupt when the FIFO filling level rises above the trigger limit.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure receive mode as "Direct"
 //Add an instance of the INTERRUPT APP and connect the SPI_SLAVE event_fifo_receive_buffer_interrupt
 //signal to the INTERRUPT sr_irq signal.
 //Provide the callback function name in INTERRUPT APP as "rx_cb"
// Description:
// Receives 10 words from the master. Callback function will be executed when 10 words are received.
 uint16_t Rec_Data[10];
 uint32_t data_index = 0;
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     //Configure receive interrupt generation when 10 bytes are received
     SPI_SLAVE_SetRXFIFOTriggerLimit(&SPI_SLAVE_0, 9);
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
//INTERRUPT APP callback function
void rx_cb()
{
  while((data_index < 10) && (!XMC_USIC_CH_RXFIFO_IsEmpty(SPI_SLAVE_0.channel)))
  {
    Rec_Data[data_index] = SPI_SLAVE_GetReceivedWord(&SPI_SLAVE_0);
    data_index++;
  }
}
Definition at line 1750 of file spi_slave.h.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE_CONFIG::rx_fifo_size, XMC_ASSERT, and XMC_USIC_CH_RXFIFO_SetSizeTriggerLimit().
SPI_SLAVE_SetTXFIFOTriggerLimit()
__STATIC_INLINE void SPI_SLAVE_SetTXFIFOTriggerLimit (const SPI_SLAVE_t *const handle, uint32_t limit)
Configures trigger limit for the transmit FIFO.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
limit Value of transmit FIFO filling level, transition below which the interrupt should be generated.
 \bRange: 0 to transmit FIFO size.
 e.g, If transmit FIFO size is 16, and limit is configured as 8, FIFO standard transmit buffer interrupt will be generated when the FIFO filling level drops from 8 to 7.
Returns
None
Description:
Transmit FIFO trigger limit is configured by setting its value in the TBCTR register. Transmit FIFO is configured to generate interrupt when the FIFO filling level drops below the trigger limit.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition: Configure transmit mode as 'Direct', set transmit FIFO size as 8.
// Description:
 //Example below transmits 10 bytes of data to the master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
   uint8_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      //Configure the transmit FIFO to generate event when FIFO level drops from 5 to 4.
      SPI_SLAVE_SetTXFIFOTriggerLimit(&SPI_SLAVE_0, 5);
      while(data_index < sizeof(Send_Data))
      {
         //Put data into the FIFO till it gets full
         if(SPI_SLAVE_IsTXFIFOFull(&SPI_SLAVE_0) == false)
         {
           SPI_SLAVE_TransmitWord(&SPI_SLAVE_0,(uint16_t)Send_Data[data_index]);
           data_index++;
         }
         else
         {
           //Wait for FIFO transmit standard buffer interrupt to fill it again with remaining data
           while((SPI_SLAVE_GetTXFIFOStatus(&SPI_SLAVE_0) & XMC_USIC_CH_TXFIFO_EVENT_STANDARD) == 0);
           SPI_SLAVE_ClearTXFIFOStatus(&SPI_SLAVE_0, XMC_USIC_CH_TXFIFO_EVENT_STANDARD);
         }
      }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 1683 of file spi_slave.h.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE_CONFIG::tx_fifo_size, XMC_ASSERT, and XMC_USIC_CH_TXFIFO_SetSizeTriggerLimit().
SPI_SLAVE_StartReceiveIRQ()
SPI_SLAVE_STATUS_t SPI_SLAVE_StartReceiveIRQ (const SPI_SLAVE_t *const handle, uint8_t * data_ptr, uint32_t count)
Registers a request for receiving data over SPI channel as a slave device.
Parameters
handle Pointer to SPI_SLAVE_t handle structure
data_ptr Pointer to data of type uint8_t.
count Total no of words to be received.
 Range: minimum= 1, maximum= maximum value supported by type uint32_t.
 In DMA mode, a maximum of 4095 words can be received in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status for receive request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a reception is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
Description:
Data will be received from a master device synchronously. When the requested number of data words are received, optionally, the user configured callback function will be executed. Based on the GUI configuration, either standard receive buffer or receive FIFO is used for data reception. An interrupt will be configured for reading received data from the register. This function only registers a request to receive a number of data words from a USIC channel. If FIFO is configured for data reception, the FIFO limit is dynamically configured to optimally utilize the CPU load. When all the requested count of data words are received, the configured callback function will be executed. If a callback function is not configured, the user has to poll for the value of the variable, handle->runtime->rx_busy to be false. The value is updated to false when all the requested number of data bytes are received.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Transmit mode and receive mode should be configured as "Interrupt".
 //Description:
 //Receives 10 bytes from master and retransmits the same.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t ReadData[10];
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     if(SPI_SLAVE_Receive(&SPI_SLAVE_0, ReadData, 10) == SPI_SLAVE_STATUS_SUCCESS)
     {
       while(SPI_SLAVE_0.runtime->rx_busy)
       {
       }
       SPI_SLAVE_Transmit(&SPI_SLAVE_0, ReadData, 10);
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 632 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE_CONFIG::receive_mode, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_RUNTIME::rx_data, SPI_SLAVE_RUNTIME::rx_data_count, SPI_SLAVE_RUNTIME::rx_data_index, SPI_SLAVE_CONFIG::rx_fifo_size, SPI_SLAVE_RUNTIME::spi_current_mode, SPI_SLAVE_lReconfigureRxFIFO(), SPI_SLAVE_STATUS_BUFFER_INVALID, SPI_SLAVE_STATUS_BUSY, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_TRANSFER_MODE_INTERRUPT, XMC_ASSERT, XMC_SPI_CH_GetReceivedData(), XMC_SPI_CH_Receive(), XMC_USIC_CH_EnableEvent(), XMC_USIC_CH_EVENT_ALTERNATIVE_RECEIVE, XMC_USIC_CH_EVENT_STANDARD_RECEIVE, XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_RXFIFO_EnableEvent(), XMC_USIC_CH_RXFIFO_EVENT_CONF_ALTERNATE, XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD, and XMC_USIC_CH_RXFIFO_Flush().
Referenced by SPI_SLAVE_Receive().
SPI_SLAVE_StartTransmitIRQ()
SPI_SLAVE_STATUS_t SPI_SLAVE_StartTransmitIRQ (const SPI_SLAVE_t *const handle, uint8_t * data_ptr, uint32_t count)
Registers a request for transmitting data over SPI channel as a slave device.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
data_ptr Pointer to data of type uint8_t.
count Total no of words to be transmitted.
Range: minimum= 1, maximum= maximum supported by uint32_t.
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
 Imp Note: Return value should be validated by user to ensure that the request is registered.
Description:
The data transmission is accomplished using transmit interrupt. User can configure a callback function in the APP UI. When the data is fully transmitted, the callback function will be executed. If transmit FIFO is enabled, the trigger limit is set to 1. So the transmit interrupt will be generated when all the data in FIFO is moved from FIFO. The function uses APP handle's runtime structure to store the data pointer, count, data index and status of transmission. This function only registers a data transmission request if there is no active transmission in progress. Actual data transmission happens in the transmit interrupt service routine. A trigger is generated for the transmit interrupt to start loading the data. If transmit FIFO is configured, the data is filled into the FIFO. Transmit interrupt will be generated next time when the transmit FIFO is empty. At this point of time, if there is some more data to be transmitted, it will be loaded to the FIFO again. When FIFO is not enabled, data will be transmitted one byte at a time. On transmission of each byte an interrupt will be generated and the next byte is transmitted in the interrupt service routine. Callback function will be executed when all the data words are transmitted. If a callback function is not configured, user has to poll for the value of tx_busy flag of the APP handle structure(handle->runtime->tx_busy) to check for the completion of data transmission.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Transmit mode should be configured as "Interrupt".
 //Description:
 //Transmits test data to master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {0x55, 0xaa, 0x5a, 0xa5};
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     if(SPI_SLAVE_StartTransmitIRQ(&SPI_SLAVE_0, Send_Data, sizeof(Send_Data)) == SPI_SLAVE_STATUS_SUCCESS)
     {
       while(SPI_SLAVE_0.runtime->tx_busy)
       {
       }
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 481 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE::runtime, SPI_SLAVE_STATUS_BUFFER_INVALID, SPI_SLAVE_STATUS_BUSY, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_TRANSFER_MODE_INTERRUPT, SPI_SLAVE_CONFIG::transmit_mode, SPI_SLAVE_RUNTIME::tx_busy, SPI_SLAVE_RUNTIME::tx_data, SPI_SLAVE_RUNTIME::tx_data_count, SPI_SLAVE_RUNTIME::tx_data_index, SPI_SLAVE_CONFIG::tx_fifo_size, SPI_SLAVE_CONFIG::tx_sr, XMC_ASSERT, XMC_SPI_CH_EnableEvent(), XMC_SPI_CH_EVENT_TRANSMIT_BUFFER, XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_SetTransmitBufferStatus(), XMC_USIC_CH_TBUF_STATUS_SET_IDLE, XMC_USIC_CH_TriggerServiceRequest(), XMC_USIC_CH_TXFIFO_EnableEvent(), XMC_USIC_CH_TXFIFO_EVENT_CONF_STANDARD, and XMC_USIC_CH_TXFIFO_Flush().
Referenced by SPI_SLAVE_Transmit().
SPI_SLAVE_Transfer()
SPI_SLAVE_STATUS_t SPI_SLAVE_Transfer (const SPI_SLAVE_t *const handle, uint8_t * tx_dataptr, uint8_t * rx_dataptr, uint32_t count)
Registers a request for transmitting and receiving data simultaneously over SPI channel as a slave device.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
tx_dataptr Pointer to data of type uint8_t.
rx_dataptr Pointer to data of type uint8_t.
count Total no of words to be transmitted and received.
Range: minimum= 1, maximum= maximum supported by uint32_t.
 In DMA mode, a maximum of 4095 words can be transferred in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
 Imp Note: Return value should be validated by user to ensure that the request is registered.
Description:
Transmits and receives data simultaneously using the SPI channel as a slave device. API is applicable only in Full duplex</> operation mode. Data transfer happens based on the individual modes configured for transmission and reception.
 Two data pins MOSI and MISO will be used for receiving and transmitting data respectively. A callback function can be configured to execute after completing the transfer when 'Interrupt' or 'DMA' mode is used. The callback function should be configured for End of receive/transfer callback in the 'Interrupt Settings' tab. The callback function will be executed when the last word of data is received.
Example Usage:
  #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
//Precondition: Operation mode should be 'Full Duplex"
//Description: Transmit and receive 9 bytes of data from master in parallel.
  int main(void)
  {
    SPI_SLAVE_STATUS_t init_status;
    uint8_t Send_Data[] = {1,2,3,4,5,6,7,8,9};
    uint8_t Rec_Data[10];
    init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
    if(init_status == SPI_SLAVE_STATUS_SUCCESS)
    {
      SPI_SLAVE_Transfer(&SPI_SLAVE_0, Send_Data, Rec_Data, sizeof(Send_Data));
      while(SPI_SLAVE_0.runtime->rx_busy)
      {
      }
    }
    else
    {
     XMC_DEBUG("main: Application initialization failed");
     while(1U)
     {
     }
    }
     return 1U;
 }
Definition at line 801 of file spi_slave.c.
SPI_SLAVE_Transmit()
SPI_SLAVE_STATUS_t SPI_SLAVE_Transmit (const SPI_SLAVE_t *const handle, uint8_t * data_ptr, uint32_t count)
Registers a request for transmitting data over SPI channel as a slave device.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
data_ptr Pointer to data of type uint8_t.
count Total no of words to be transmitted.
Range: minimum= 1, maximum= maximum supported by uint32_t.
 In DMA mode, a maximum of 4095 words can be transmitted in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
 Imp Note: Return value should be validated by user to ensure that the request is registered.
Description:
Transmits data using the SPI channel as a slave device. Transmission is accomplished using the transmit mode as configured in the UI.
 Interrupt:
 The data transmission is accomplished using transmit interrupt. User can configure a callback function in the APP UI. When the data is fully transmitted, the callback function will be executed. If transmit FIFO is enabled, the trigger limit is set to 1. So the transmit interrupt will be generated when all the data in FIFO is moved out of FIFO. The APP handle's runtime structure is used to store the data pointer, count, data index and status of transmission. This function only registers a data transmission request if there is no active transmission in progress. Actual data transmission happens in the transmit interrupt service routine. A trigger is generated for the transmit interrupt to start loading the data to the transmit buffer. If transmit FIFO is configured, the data is filled into the FIFO. Transmit interrupt will be generated subsequently when the transmit FIFO is empty. At this point of time, if there is some more data to be transmitted, it is loaded to the FIFO again. When FIFO is not enabled, data is transmitted one byte at a time. On transmission of each byte an interrupt is generated and the next byte is transmitted in the interrupt service routine. Callback function is executed when all the data bytes are transmitted. If a callback function is not configured, user has to poll for the value of tx_busy flag of the APP handle structure(handle->runtime->tx_busy) to check for the completion of data transmission.
 DMA:
 A DMA channel is configured to provide data to the SPI channel transmit buffer. This removes the load off the CPU. This API will only configure and enable the DMA channel by specifying the data buffer and count of bytes to transmit. Rest is taken care without the CPU's intervention. User can configure a callback function in the APP UI. When the transmission is complete, the callback function will be executed. FIFO will not be used in DMA mode. Receive start interrupt is configured for triggering the DMA channel. So each byte is transmitted in the background through the DMA channel. If the callback function is not configured, handle->runtime->tx_busy flag can be checked to verify if the transmission is complete. Direct:
 Data will be transmitted using polling method. Status flags are used to check if data can be transmitted. Note: In Direct mode, the API blocks the CPU until the count of bytes requested is transmitted. If this behavior is not desired, use other APIs like SPI_SLAVE_TransmitWord, SPI_SLAVE_GetProtocolStatus etc.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Transmit mode should be configured as "Direct".
 //Description:
 //Transmits 9 bytes to the master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {1,2,3,4,5,6,7,8,9};
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     SPI_SLAVE_Transmit(&SPI_SLAVE_0, Send_Data, sizeof(Send_Data));
     while(SPI_SLAVE_0.runtime->tx_busy)
     {
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 158 of file spi_slave.c.
SPI_SLAVE_TransmitWord()
__STATIC_INLINE void SPI_SLAVE_TransmitWord (const SPI_SLAVE_t *const handle, uint16_t data)
Transmits a word of data.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
data Data to be transmitted.
Returns
None
Description:
Transmits a word of data through the SPI channel as a slave device. If transmit FIFO is configured, the data is placed in the IN[0] register of the USIC channel. If transmit FIFO is not configured, API waits for the TBUF to be free and then places the data in the TBUF register. User can poll for receive event or configure interrupt by connecting an external INTERRUPT APP. This API can be used inside the ISR to read the received data.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure transmit mode and receive mode as "Direct", word length = 16
 //Description:
 //Transmits 10 words to the master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint16_t Send_Data[] = {0,1,2,3,4,5,6,7,8,9};
   uint16_t Rec_Data[10];
   uint32_t data_index = 0;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
      while(data_index < sizeof(Send_Data))
      {
         SPI_SLAVE_TransmitWord(&SPI_SLAVE_0,Send_Data[data_index]);
         data_index++;
         //Wait for transmit buffer interrupt to fill it again with remaining data
         while((SPI_SLAVE_GetTXFIFOStatus(&SPI_SLAVE_0) & XMC_USIC_CH_TXFIFO_EVENT_STANDARD) == 0);
         SPI_SLAVE_ClearTXFIFOStatus(&SPI_SLAVE_0, XMC_USIC_CH_TXFIFO_EVENT_STANDARD);
      }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 1367 of file spi_slave.h.
References SPI_SLAVE::channel, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::spi_current_mode, XMC_ASSERT, and XMC_SPI_CH_Transmit().