Dave/Generated/DIGITAL_IO/digital_io.h File Reference
#include <xmc_gpio.h>
#include <DAVE_Common.h>
#include `digital_io_conf.h`
#include `digital_io_extern.h`
Data Structures
struct DIGITAL_IO
Initialization data structure of DIGITAL_IO APP.
Typedefs
typedef struct DIGITAL_IO DIGITAL_IO_t
Initialization data structure of DIGITAL_IO APP.
Functions
DAVE_APP_VERSION_t DIGITAL_IO_GetAppVersion (void)
Get DIGITAL_IO APP version.
DIGITAL_IO_STATUS_t DIGITAL_IO_Init (const DIGITAL_IO_t *const handler)
Function to initialize the port pin as per UI settings.
__STATIC_INLINE void DIGITAL_IO_SetOutputHigh (const DIGITAL_IO_t *const handler)
Function to set port pin high.
__STATIC_INLINE void DIGITAL_IO_SetOutputLow (const DIGITAL_IO_t *const handler)
Function to reset port pin.
__STATIC_INLINE void DIGITAL_IO_ToggleOutput (const DIGITAL_IO_t *const handler)
Function to Toggle port pin.
__STATIC_INLINE uint32_t DIGITAL_IO_GetInput (const DIGITAL_IO_t *const handler)
Function to read input level of port pin.
enum DIGITAL_IO_STATUS { DIGITAL_IO_STATUS_OK = 0U,
DIGITAL_IO_STATUS_FAILURE = 1U,
DIGITAL_IO_STATUS_OK = 0U,
DIGITAL_IO_STATUS_FAILURE = 1U
 }
Initialization status of DIGITAL_IO APP.
typedef enum DIGITAL_IO_STATUS DIGITAL_IO_STATUS_t
Initialization status of DIGITAL_IO APP.
Typedef Documentation
DIGITAL_IO_STATUS_t
typedef enum DIGITAL_IO_STATUS DIGITAL_IO_STATUS_t
Initialization status of DIGITAL_IO APP.
DIGITAL_IO_t
typedef struct DIGITAL_IO DIGITAL_IO_t
Initialization data structure of DIGITAL_IO APP.
Enumeration Type Documentation
DIGITAL_IO_STATUS
enum DIGITAL_IO_STATUS
Initialization status of DIGITAL_IO APP.
Enumerator
DIGITAL_IO_STATUS_OK 0=Status OK
DIGITAL_IO_STATUS_FAILURE 1=Status Failed
DIGITAL_IO_STATUS_OK 0=Status OK
DIGITAL_IO_STATUS_FAILURE 1=Status Failed
Definition at line 93 of file digital_io.h.
Function Documentation
DIGITAL_IO_GetAppVersion()
DAVE_APP_VERSION_t DIGITAL_IO_GetAppVersion (void)
Get DIGITAL_IO APP version.
Returns
DAVE_APP_VERSION_t APP version information (major, minor and patch number)
Description:
The function can be used to check application software compatibility with a specific version of the APP.
Example Usage:
#include <DAVE.h>
int main(void)
{
  DAVE_STATUS_t init_status;
  DAVE_APP_VERSION_t version;
  // Initialize DIGITAL_IO APP:
  // DIGITAL_IO_Init() is called from within DAVE_Init().
  init_status = DAVE_Init();
  if(init_status == DAVE_STATUS_SUCCESS)
  {
    version = DIGITAL_IO_GetAppVersion();
    if (version.major != 4U) {
    // Probably, not the right version.
    }
  }
    // More code here
    while(1) {
    }
    return (1);
 }
Returns
DAVE_APP_VERSION_t APP version information (major, minor and patch number)
Definition at line 79 of file digital_io.c.
DIGITAL_IO_GetInput()
__STATIC_INLINE uint32_t DIGITAL_IO_GetInput (const DIGITAL_IO_t *const handler)
Function to read input level of port pin.
Parameters
handler Pointer pointing to APP data structure. Refer DIGITAL_IO_t for details.
Returns
uint32_t input logic level. Range:0-1
Description:
This function reads the Pn_IN register and returns the current logical value at the GPIO pin.
Related APIs:
None
Example Usage:
#include <DAVE.h>//Declarations from DAVE Code Generation (includes SFR declaration)
int main(void)
{
  DAVE_STATUS_t status;
  uint32_t pin_status;
  status = DAVE_Init(); // (DAVE_STATUS_t)DIGITAL_IO_Init(&DIGITAL_IO_0) is called within DAVE_Init()
  if(status == DAVE_STATUS_SUCCESS)
  {
    XMC_DEBUG("DAVE Apps initialization success\n");
  }
  else
  {
    XMC_DEBUG(("DAVE Apps initialization failed with status %d\n", status));
    while(1U)
    {
    }
  }
  //Placeholder for user application code. The while loop below can be replaced with user application code.
  while(1U)
  {
    pin_status = DIGITAL_IO_GetInput(&DIGITAL_IO_0);
    if(pin_status == 1)
    {
      // Add application code here
    }
    else
    {
      // Add application code here
    }
  }
  return (1);
}
Definition at line 421 of file digital_io.h.
References DIGITAL_IO::gpio_pin, DIGITAL_IO::gpio_port, XMC_ASSERT, and XMC_GPIO_GetInput().
DIGITAL_IO_Init()
DIGITAL_IO_STATUS_t DIGITAL_IO_Init (const DIGITAL_IO_t *const handler)
Function to initialize the port pin as per UI settings.
Parameters
handler Pointer pointing to APP data structure. Refer DIGITAL_IO_t for details.
Returns
DIGITAL_IO_STATUS_t DIGITAL_IO APP status. Refer DIGITAL_IO_STATUS_t structure for details.
Description:
This function initializes GPIO port registers IOCR,PDISC,OMR,PDR/PHCR to configure pin direction,initial output level, and pad driver strength/hysteresis.
Related APIs:
None
Example Usage:
#include <DAVE.h>//Declarations from DAVE Code Generation (includes SFR declaration)
int main(void)
{
  DAVE_STATUS_t status;
  status = DAVE_Init(); //(DAVE_STATUS_t)DIGITAL_IO_Init(&DIGITAL_IO_0) is called within DAVE_Init()
  if(status == DAVE_STATUS_SUCCESS)
  {
    XMC_DEBUG("DAVE Apps initialization success\n");
  }
  else
  {
    XMC_DEBUG(("DAVE Apps initialization failed with status %d\n", status));
    while(1U)
    {
    }
  }
  //Placeholder for user application code. The while loop below can be replaced with user application code.
  while(1U)
  {
  }
  return 1U;
 }
Parameters
handler Pointer pointing to APP data structure.
Returns
DIGITAL_IO_STATUS_t DIGITAL_IO APP status.
Definition at line 97 of file digital_io.c.
DIGITAL_IO_SetOutputHigh()
__STATIC_INLINE void DIGITAL_IO_SetOutputHigh (const DIGITAL_IO_t *const handler)
Function to set port pin high.
Parameters
handler Pointer pointing to APP data structure. Refer DIGITAL_IO_t for details.
Returns
None
Description:
This function configures port output modification register Pn_OMR, to make port pin to high level.
Related APIs:
DIGITAL_IO_SetOutputLow()
Example Usage:
#include <DAVE.h>//Declarations from DAVE Code Generation (includes SFR declaration)
int main(void)
{
  DAVE_STATUS_t status;
  status = DAVE_Init(); //(DAVE_STATUS_t)DIGITAL_IO_Init(&DIGITAL_IO_0) is called within DAVE_Init()
  if(status == DAVE_STATUS_SUCCESS)
  {
    XMC_DEBUG("DAVE Apps initialization success\n");
  }
  else
  {
    XMC_DEBUG(("DAVE Apps initialization failed with status %d\n", status));
    while(1U)
    {
    }
  }
  //Placeholder for user application code. The while loop below can be replaced with user application code.
  DIGITAL_IO_SetOutputHigh(&DIGITAL_IO_0);
  while(1U)
  {
    // Add application code here
  }
  return (1);
}
Definition at line 268 of file digital_io.h.
References DIGITAL_IO::gpio_pin, DIGITAL_IO::gpio_port, XMC_ASSERT, and XMC_GPIO_SetOutputHigh().
Referenced by MySPILEDsToggling(), MyUARTLEDsToggling(), and UART_Task().
DIGITAL_IO_SetOutputLow()
__STATIC_INLINE void DIGITAL_IO_SetOutputLow (const DIGITAL_IO_t *const handler)
Function to reset port pin.
Parameters
handler Pointer pointing to APP data structure. Refer DIGITAL_IO_t for details.
Returns
None
Description:
This function configures port output modification register Pn_OMR, to make port pin to low level.
Related APIs:
DIGITAL_IO_SetOutputHigh()
Example Usage:
 #include <DAVE.h>//Declarations from DAVE Code Generation (includes SFR declaration)
 int main(void)
 {
   DAVE_STATUS_t status;
   status = DAVE_Init(); //(DAVE_STATUS_t)DIGITAL_IO_Init(&DIGITAL_IO_0) is called within DAVE_Init()
   if(status == DAVE_STATUS_SUCCESS)
   {
     XMC_DEBUG("DAVE Apps initialization success\n");
   }
   else
   {
     XMC_DEBUG(("DAVE Apps initialization failed with status %d\n", status));
     while(1U)
     {
     }
   }
   //Placeholder for user application code. The while loop below can be replaced with user application code.
   DIGITAL_IO_SetOutputLow(&DIGITAL_IO_0);
   while(1U)
   {
     // Add application code here
   }
  return (1);
}
Definition at line 315 of file digital_io.h.
References DIGITAL_IO::gpio_pin, DIGITAL_IO::gpio_port, XMC_ASSERT, and XMC_GPIO_SetOutputLow().
Referenced by MySPILEDsToggling(), MyUARTLEDsToggling(), and UART_Task().
DIGITAL_IO_ToggleOutput()
__STATIC_INLINE void DIGITAL_IO_ToggleOutput (const DIGITAL_IO_t *const handler)
Function to Toggle port pin.
Parameters
handler Pointer pointing to APP data structure. Refer DIGITAL_IO_t for details.
Returns
None
Description:
This function configures port output modification register Pn_OMR, to toggle port pin.
Related APIs:
DIGITAL_IO_SetOutputLow(), DIGITAL_IO_SetOutputHigh()
Example Usage:
#include <DAVE.h>//Declarations from DAVE Code Generation (includes SFR declaration)
int main(void)
{
  DAVE_STATUS_t status;
  uint32_t delay_count;;
  status = DAVE_Init(); //(DAVE_STATUS_t)DIGITAL_IO_Init(&DIGITAL_IO_0) is called within DAVE_Init()
  if(status == DAVE_STATUS_SUCCESS)
  {
    XMC_DEBUG("DAVE Apps initialization success\n");
  }
  else
  {
     XMC_DEBUG(("DAVE Apps initialization failed with status %d\n", status));
     while(1U)
     {
     }
  }
  //Placeholder for user application code. The while loop below can be replaced with user application code.
  while(1U)
  {
     DIGITAL_IO_ToggleOutput(&DIGITAL_IO_0); //toggles : 1 -> 0 (if initial output level is logic 1)
     //Add application code here
     for(delay_count = 0;delay_count<0xfffff;delay_count++);
     DIGITAL_IO_ToggleOutput(&DIGITAL_IO_0); //toggles : 0 -> 1
     //Add application code here
     for(delay_count = 0;delay_count<0xfffff;delay_count++);
  }
  return (1);
}
Definition at line 367 of file digital_io.h.
References DIGITAL_IO::gpio_pin, DIGITAL_IO::gpio_port, XMC_ASSERT, and XMC_GPIO_ToggleOutput().
Referenced by MyLEDsToggling(), worker1_task(), and worker2_task().