Dave/Generated/FREERTOS/list.c File Reference
#include <stdlib.h>
#include `FreeRTOS.h`
#include `list.h`
Functions
void vListInitialise (List_t *const pxList)
void vListInitialiseItem (ListItem_t *const pxItem)
void vListInsertEnd (List_t *const pxList, ListItem_t *const pxNewListItem)
void vListInsert (List_t *const pxList, ListItem_t *const pxNewListItem)
UBaseType_t uxListRemove (ListItem_t *const pxItemToRemove)
Function Documentation
uxListRemove()
UBaseType_t uxListRemove (ListItem_t *const pxItemToRemove)
Definition at line 170 of file list.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvCheckTasksWaitingTermination(), prvProcessExpiredTimer(), prvProcessReceivedCommands(), prvSwitchTimerLists(), vTaskDelete(), vTaskNotifyGiveFromISR(), vTaskPriorityDisinheritAfterTimeout(), vTaskPrioritySet(), vTaskRemoveFromUnorderedEventList(), vTaskResume(), vTaskSuspend(), xTaskAbortDelay(), xTaskGenericNotify(), xTaskGenericNotifyFromISR(), xTaskIncrementTick(), xTaskPriorityDisinherit(), xTaskPriorityInherit(), xTaskRemoveFromEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
vListInitialise()
void vListInitialise (List_t *const pxList)
Definition at line 37 of file list.c.
Referenced by prvCheckForValidListAndQueue(), prvInitialiseTaskLists(), xEventGroupCreate(), and xQueueGenericReset().
vListInitialiseItem()
void vListInitialiseItem (ListItem_t *const pxItem)
Definition at line 62 of file list.c.
Referenced by prvInitialiseNewTask(), and prvInitialiseNewTimer().
vListInsert()
void vListInsert (List_t *const pxList, ListItem_t *const pxNewListItem)
Definition at line 103 of file list.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvInsertTimerInActiveList(), prvSwitchTimerLists(), and vTaskPlaceOnEventList().
vListInsertEnd()
void vListInsertEnd (List_t *const pxList, ListItem_t *const pxNewListItem)
Definition at line 74 of file list.c.
Referenced by prvAddCurrentTaskToDelayedList(), vTaskDelete(), vTaskNotifyGiveFromISR(), vTaskPlaceOnEventListRestricted(), vTaskPlaceOnUnorderedEventList(), vTaskSuspend(), xTaskGenericNotifyFromISR(), xTaskRemoveFromEventList(), and xTaskResumeFromISR().