Dave/Generated/FREERTOS/tasks.c File Reference
#include <stdlib.h>
#include <string.h>
#include `FreeRTOS.h`
#include `task.h`
#include `timers.h`
#include `stack_macros.h`
#include <stdio.h>
Data Structures
struct tskTaskControlBlock
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define taskYIELD_IF_USING_PREEMPTION() portYIELD_WITHIN_API()
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
#define tskSTACK_FILL_BYTE (0xa5U)
#define tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE ((configSUPPORT_STATIC_ALLOCATION == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1))
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
#define tskSET_NEW_STACKS_TO_KNOWN_VALUE 1
#define tskRUNNING_CHAR ('X')
#define tskBLOCKED_CHAR ('B')
#define tskREADY_CHAR ('R')
#define tskDELETED_CHAR ('D')
#define tskSUSPENDED_CHAR ('S')
#define configIDLE_TASK_NAME `IDLE`
#define taskRECORD_READY_PRIORITY(uxPriority)
#define taskSELECT_HIGHEST_PRIORITY_TASK()
#define taskRESET_READY_PRIORITY(uxPriority)
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
#define taskSWITCH_DELAYED_LISTS()
#define prvAddTaskToReadyList(pxTCB)
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? (TCB_t *) pxCurrentTCB : (TCB_t *) (pxHandle))
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Typedefs
typedef struct tskTaskControlBlock tskTCB
typedef tskTCB TCB_t
Functions
static BaseType_t prvTaskIsTaskSuspended (const TaskHandle_t xTask) PRIVILEGED_FUNCTION
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void)
static void prvInitialiseNewTask (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t ulStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, TCB_t *pxNewTCB, const MemoryRegion_t *const xRegions)
static void prvAddNewTaskToReadyList (TCB_t *pxNewTCB)
void vTaskDelete (TaskHandle_t xTaskToDelete)
void vTaskDelayUntil (TickType_t *const pxPreviousWakeTime, const TickType_t xTimeIncrement)
void vTaskDelay (const TickType_t xTicksToDelay)
eTaskState eTaskGetState (TaskHandle_t xTask)
UBaseType_t uxTaskPriorityGet (TaskHandle_t xTask)
UBaseType_t uxTaskPriorityGetFromISR (TaskHandle_t xTask)
void vTaskPrioritySet (TaskHandle_t xTask, UBaseType_t uxNewPriority)
void vTaskSuspend (TaskHandle_t xTaskToSuspend)
void vTaskResume (TaskHandle_t xTaskToResume)
BaseType_t xTaskResumeFromISR (TaskHandle_t xTaskToResume)
void vTaskStartScheduler (void)
void vTaskEndScheduler (void)
void vTaskSuspendAll (void)
BaseType_t xTaskResumeAll (void)
TickType_t xTaskGetTickCount (void)
TickType_t xTaskGetTickCountFromISR (void)
UBaseType_t uxTaskGetNumberOfTasks (void)
char * pcTaskGetName (TaskHandle_t xTaskToQuery)
static TCB_t * prvSearchForNameWithinSingleList (List_t *pxList, const char pcNameToQuery[])
TaskHandle_t xTaskGetHandle (const char *pcNameToQuery)
UBaseType_t uxTaskGetSystemState (TaskStatus_t *const pxTaskStatusArray, const UBaseType_t uxArraySize, uint32_t *const pulTotalRunTime)
TaskHandle_t xTaskGetIdleTaskHandle (void)
BaseType_t xTaskAbortDelay (TaskHandle_t xTask)
BaseType_t xTaskIncrementTick (void)
void vTaskSwitchContext (void)
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
void vTaskPlaceOnUnorderedEventList (List_t *pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
void vTaskPlaceOnEventListRestricted (List_t *const pxEventList, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
void vTaskRemoveFromUnorderedEventList (ListItem_t *pxEventListItem, const TickType_t xItemValue)
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
void vTaskMissedYield (void)
UBaseType_t uxTaskGetTaskNumber (TaskHandle_t xTask)
void vTaskSetTaskNumber (TaskHandle_t xTask, const UBaseType_t uxHandle)
static portTASK_FUNCTION (prvIdleTask, pvParameters)
void vTaskSetThreadLocalStoragePointer (TaskHandle_t xTaskToSet, BaseType_t xIndex, void *pvValue)
void * pvTaskGetThreadLocalStoragePointer (TaskHandle_t xTaskToQuery, BaseType_t xIndex)
static void prvInitialiseTaskLists (void)
static void prvCheckTasksWaitingTermination (void)
void vTaskGetInfo (TaskHandle_t xTask, TaskStatus_t *pxTaskStatus, BaseType_t xGetFreeStackSpace, eTaskState eState)
static UBaseType_t prvListTasksWithinSingleList (TaskStatus_t *pxTaskStatusArray, List_t *pxList, eTaskState eState)
static uint16_t prvTaskCheckFreeStackSpace (const uint8_t *pucStackByte)
UBaseType_t uxTaskGetStackHighWaterMark (TaskHandle_t xTask)
static void prvDeleteTCB (TCB_t *pxTCB)
static void prvResetNextTaskUnblockTime (void)
TaskHandle_t xTaskGetCurrentTaskHandle (void)
BaseType_t xTaskGetSchedulerState (void)
BaseType_t xTaskPriorityInherit (TaskHandle_t const pxMutexHolder)
BaseType_t xTaskPriorityDisinherit (TaskHandle_t const pxMutexHolder)
void vTaskPriorityDisinheritAfterTimeout (TaskHandle_t const pxMutexHolder, UBaseType_t uxHighestPriorityWaitingTask)
static char * prvWriteNameToBuffer (char *pcBuffer, const char *pcTaskName)
void vTaskList (char *pcWriteBuffer)
TickType_t uxTaskResetEventItemValue (void)
void * pvTaskIncrementMutexHeldCount (void)
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t *pulNotificationValue, TickType_t xTicksToWait)
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue)
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue, BaseType_t *pxHigherPriorityTaskWoken)
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t *pxHigherPriorityTaskWoken)
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely)
Variables
PRIVILEGED_DATA TCB_t *volatile pxCurrentTCB = NULL
static PRIVILEGED_DATA List_t pxReadyTasksLists [configMAX_PRIORITIES]
static PRIVILEGED_DATA List_t xDelayedTaskList1
static PRIVILEGED_DATA List_t xDelayedTaskList2
static PRIVILEGED_DATA List_t *volatile pxDelayedTaskList
static PRIVILEGED_DATA List_t *volatile pxOverflowDelayedTaskList
static PRIVILEGED_DATA List_t xPendingReadyList
static PRIVILEGED_DATA List_t xTasksWaitingTermination
static PRIVILEGED_DATA volatile UBaseType_t uxDeletedTasksWaitingCleanUp = (UBaseType_t) 0U
static PRIVILEGED_DATA List_t xSuspendedTaskList
static PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) configINITIAL_TICK_COUNT
static PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY
static PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE
static PRIVILEGED_DATA volatile UBaseType_t uxPendedTicks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE
static PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0
static PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U
static PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL
static PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE
Macro Definition Documentation
configIDLE_TASK_NAME
#define configIDLE_TASK_NAME `IDLE`
Definition at line 130 of file tasks.c.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 36 of file tasks.c.
portRESET_READY_PRIORITY
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
Definition at line 173 of file tasks.c.
prvAddTaskToReadyList
#define prvAddTaskToReadyList(pxTCB)
Value:
    traceMOVED_TASK_TO_READY_STATE(pxTCB); \
    taskRECORD_READY_PRIORITY((pxTCB)->uxPriority); \
    vListInsertEnd(&(pxReadyTasksLists[ (pxTCB)->uxPriority ]), &((pxTCB)->xStateListItem)); \
    tracePOST_MOVED_TASK_TO_READY_STATE(pxTCB)
Definition at line 235 of file tasks.c.
prvGetTCBFromHandle
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? (TCB_t *) pxCurrentTCB : (TCB_t *) (pxHandle))
Definition at line 248 of file tasks.c.
taskEVENT_LIST_ITEM_VALUE_IN_USE
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Definition at line 261 of file tasks.c.
taskNOT_WAITING_NOTIFICATION
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
Definition at line 69 of file tasks.c.
taskNOTIFICATION_RECEIVED
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
Definition at line 71 of file tasks.c.
taskRECORD_READY_PRIORITY
#define taskRECORD_READY_PRIORITY(uxPriority)
Value:
    { \
        if((uxPriority) > uxTopReadyPriority) \
        { \
            uxTopReadyPriority = (uxPriority); \
        } \
    } /* taskRECORD_READY_PRIORITY */
Definition at line 141 of file tasks.c.
taskRESET_READY_PRIORITY
#define taskRESET_READY_PRIORITY(uxPriority)
Definition at line 172 of file tasks.c.
taskSELECT_HIGHEST_PRIORITY_TASK
#define taskSELECT_HIGHEST_PRIORITY_TASK()
Value:
    { \
    UBaseType_t uxTopPriority = uxTopReadyPriority; \
                                                                                                        \
        /* Find the highest priority queue that contains ready tasks. */ \
        while(listLIST_IS_EMPTY(&(pxReadyTasksLists[ uxTopPriority ]))) \
        { \
            configASSERT(uxTopPriority); \
            --uxTopPriority; \
        } \
                                                                                                        \
        /* listGET_OWNER_OF_NEXT_ENTRY indexes through the list, so the tasks of \
        the same priority get an equal share of the processor time. */ \
        listGET_OWNER_OF_NEXT_ENTRY(pxCurrentTCB, &(pxReadyTasksLists[ uxTopPriority ])); \
        uxTopReadyPriority = uxTopPriority; \
    } /* taskSELECT_HIGHEST_PRIORITY_TASK */
Definition at line 151 of file tasks.c.
taskSWITCH_DELAYED_LISTS
#define taskSWITCH_DELAYED_LISTS()
Value:
{ \
    List_t *pxTemp; \
                                                                                                    \
    /* The delayed tasks list should be empty when the lists are switched. */ \
    configASSERT((listLIST_IS_EMPTY(pxDelayedTaskList))); \
                                                                                                    \
    pxTemp = pxDelayedTaskList; \
    pxDelayedTaskList = pxOverflowDelayedTaskList; \
    pxOverflowDelayedTaskList = pxTemp; \
    xNumOfOverflows++; \
    prvResetNextTaskUnblockTime(); \
}
Definition at line 215 of file tasks.c.
taskWAITING_NOTIFICATION
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
Definition at line 70 of file tasks.c.
taskYIELD_IF_USING_PREEMPTION
#define taskYIELD_IF_USING_PREEMPTION() portYIELD_WITHIN_API()
Definition at line 65 of file tasks.c.
tskBLOCKED_CHAR
#define tskBLOCKED_CHAR ('B')
Definition at line 114 of file tasks.c.
tskDELETED_CHAR
#define tskDELETED_CHAR ('D')
Definition at line 116 of file tasks.c.
tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
Definition at line 97 of file tasks.c.
tskREADY_CHAR
#define tskREADY_CHAR ('R')
Definition at line 115 of file tasks.c.
tskRUNNING_CHAR
#define tskRUNNING_CHAR ('X')
Definition at line 113 of file tasks.c.
tskSET_NEW_STACKS_TO_KNOWN_VALUE
#define tskSET_NEW_STACKS_TO_KNOWN_VALUE 1
Definition at line 105 of file tasks.c.
tskSTACK_FILL_BYTE
#define tskSTACK_FILL_BYTE (0xa5U)
Definition at line 77 of file tasks.c.
tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE
#define tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE ((configSUPPORT_STATIC_ALLOCATION == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1))
Definition at line 96 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_AND_TCB
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
Definition at line 99 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_ONLY
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
Definition at line 98 of file tasks.c.
tskSUSPENDED_CHAR
#define tskSUSPENDED_CHAR ('S')
Definition at line 117 of file tasks.c.
Typedef Documentation
TCB_t
typedef tskTCB TCB_t
Definition at line 342 of file tasks.c.
tskTCB
typedef struct tskTaskControlBlock tskTCB
Function Documentation
eTaskGetState()
eTaskState eTaskGetState (TaskHandle_t xTask)
task. h
eTaskState eTaskGetState(TaskHandle_t xTask);
INCLUDE_eTaskGetState must be defined as 1 for this function to be available. See the configuration section for more information.
Obtain the state of any task. States are encoded by the eTaskState enumerated type.
Parameters
xTask Handle of the task to be queried.
Returns
The state of xTask at the time the function was called. Note the state of the task might change between the function being called, and the functions return value being tested by the calling task.
Definition at line 1332 of file tasks.c.
References configASSERT, eBlocked, eDeleted, eReady, eRunning, eSuspended, listLIST_ITEM_CONTAINER, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, and xTasksWaitingTermination.
Referenced by vTaskGetInfo(), and xTaskAbortDelay().
pcTaskGetName()
char* pcTaskGetName (TaskHandle_t xTaskToQuery)
Definition at line 2268 of file tasks.c.
portTASK_FUNCTION()
static portTASK_FUNCTION (prvIdleTask , pvParameters) [static]
THIS IS THE RTOS IDLE TASK - WHICH IS CREATED AUTOMATICALLY WHEN THE SCHEDULER IS STARTED.
Definition at line 3223 of file tasks.c.
References configASSERT, configEXPECTED_IDLE_TIME_BEFORE_SLEEP, configPRE_SUPPRESS_TICKS_AND_SLEEP_PROCESSING, listCURRENT_LIST_LENGTH, mtCOVERAGE_TEST_MARKER, portSUPPRESS_TICKS_AND_SLEEP, portTASK_CALLS_SECURE_FUNCTIONS, prvCheckTasksWaitingTermination(), pxReadyTasksLists, taskYIELD, traceLOW_POWER_IDLE_BEGIN, traceLOW_POWER_IDLE_END, tskIDLE_PRIORITY, vTaskSuspendAll(), xNextTaskUnblockTime, xTaskResumeAll(), and xTickCount.
prvAddCurrentTaskToDelayedList()
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely) [static]
Definition at line 4911 of file tasks.c.
References listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, portMAX_DELAY, portRESET_READY_PRIORITY, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, tskTaskControlBlock::ucDelayAborted, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, vListInsert(), vListInsertEnd(), xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, and xTickCount.
Referenced by ulTaskNotifyTake(), vTaskDelay(), vTaskDelayUntil(), vTaskPlaceOnEventList(), vTaskPlaceOnEventListRestricted(), vTaskPlaceOnUnorderedEventList(), and xTaskNotifyWait().
prvAddNewTaskToReadyList()
static void prvAddNewTaskToReadyList (TCB_t * pxNewTCB) [static]
Definition at line 1026 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, portSETUP_TCB, prvAddTaskToReadyList, prvInitialiseTaskLists(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_CREATE, uxCurrentNumberOfTasks, tskTaskControlBlock::uxPriority, uxTaskNumber, tskTaskControlBlock::uxTCBNumber, and xSchedulerRunning.
prvCheckTasksWaitingTermination()
static void prvCheckTasksWaitingTermination (void) [static]
THIS FUNCTION IS CALLED FROM THE RTOS IDLE TASK
Definition at line 3467 of file tasks.c.
References listGET_OWNER_OF_HEAD_ENTRY, prvDeleteTCB(), taskENTER_CRITICAL, taskEXIT_CRITICAL, uxCurrentNumberOfTasks, uxDeletedTasksWaitingCleanUp, uxListRemove(), tskTaskControlBlock::xStateListItem, and xTasksWaitingTermination.
Referenced by portTASK_FUNCTION().
prvDeleteTCB()
static void prvDeleteTCB (TCB_t * pxTCB) [static]
Definition at line 3675 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, portCLEAN_UP_TCB, tskTaskControlBlock::pxStack, tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB, tskSTATICALLY_ALLOCATED_STACK_AND_TCB, tskSTATICALLY_ALLOCATED_STACK_ONLY, and vPortFree().
Referenced by prvCheckTasksWaitingTermination(), and vTaskDelete().
prvInitialiseNewTask()
static void prvInitialiseNewTask (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t ulStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, TCB_t * pxNewTCB, const MemoryRegion_t *const xRegions) [static]
Definition at line 822 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, configNUM_THREAD_LOCAL_STORAGE_POINTERS, listSET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, tskTaskControlBlock::pcTaskName, pdFALSE, pdTRUE, portPOINTER_SIZE_TYPE, portPRIVILEGE_BIT, tskTaskControlBlock::pvThreadLocalStoragePointers, pxPortInitialiseStack(), tskTaskControlBlock::pxStack, tskTaskControlBlock::pxTopOfStack, taskNOT_WAITING_NOTIFICATION, tskSTACK_FILL_BYTE, tskTaskControlBlock::ucDelayAborted, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, tskTaskControlBlock::uxBasePriority, tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, vListInitialiseItem(), vPortStoreTaskMPUSettings(), tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
prvInitialiseTaskLists() [1/2]
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void) [static]
Definition at line 439 of file tasks.c.
Referenced by prvAddNewTaskToReadyList().
prvInitialiseTaskLists() [2/2]
static void prvInitialiseTaskLists (void) [static]
Definition at line 3435 of file tasks.c.
References configMAX_PRIORITIES, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, vListInitialise(), xDelayedTaskList1, xDelayedTaskList2, xPendingReadyList, xSuspendedTaskList, and xTasksWaitingTermination.
prvListTasksWithinSingleList()
static UBaseType_t prvListTasksWithinSingleList (TaskStatus_t * pxTaskStatusArray, List_t * pxList, eTaskState eState) [static]
Definition at line 3594 of file tasks.c.
References configLIST_VOLATILE, listCURRENT_LIST_LENGTH, listGET_OWNER_OF_NEXT_ENTRY, mtCOVERAGE_TEST_MARKER, pdTRUE, and vTaskGetInfo().
Referenced by uxTaskGetSystemState().
prvResetNextTaskUnblockTime()
static void prvResetNextTaskUnblockTime (void) [static]
Definition at line 3729 of file tasks.c.
References listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, pdFALSE, portMAX_DELAY, pxDelayedTaskList, and xNextTaskUnblockTime.
Referenced by vTaskDelete(), vTaskSuspend(), xTaskGenericNotify(), xTaskRemoveFromEventList(), and xTaskResumeAll().
prvSearchForNameWithinSingleList()
static TCB_t* prvSearchForNameWithinSingleList (List_t * pxList, const char pcNameToQuery[]) [static]
Definition at line 2282 of file tasks.c.
References configMAX_TASK_NAME_LEN, listCURRENT_LIST_LENGTH, listGET_OWNER_OF_NEXT_ENTRY, mtCOVERAGE_TEST_MARKER, and tskTaskControlBlock::pcTaskName.
Referenced by xTaskGetHandle().
prvTaskCheckFreeStackSpace()
static uint16_t prvTaskCheckFreeStackSpace (const uint8_t * pucStackByte) [static]
Definition at line 3627 of file tasks.c.
References portSTACK_GROWTH, and tskSTACK_FILL_BYTE.
Referenced by uxTaskGetStackHighWaterMark(), and vTaskGetInfo().
prvTaskIsTaskSuspended()
static BaseType_t prvTaskIsTaskSuspended (const TaskHandle_t xTask) [static]
Utility task that simply returns pdTRUE if the task referenced by xTask is currently in the Suspended state, or pdFALSE if the task referenced by xTask is in any other state.
Definition at line 1730 of file tasks.c.
References configASSERT, listIS_CONTAINED_WITHIN, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xSuspendedTaskList.
Referenced by vTaskResume(), and xTaskResumeFromISR().
prvWriteNameToBuffer()
static char* prvWriteNameToBuffer (char * pcBuffer, const char * pcTaskName) [static]
Definition at line 4132 of file tasks.c.
References configMAX_TASK_NAME_LEN.
Referenced by vTaskList().
pvTaskGetThreadLocalStoragePointer()
void* pvTaskGetThreadLocalStoragePointer (TaskHandle_t xTaskToQuery, BaseType_t xIndex)
Definition at line 3398 of file tasks.c.
References configNUM_THREAD_LOCAL_STORAGE_POINTERS, prvGetTCBFromHandle, and tskTaskControlBlock::pvThreadLocalStoragePointers.
pvTaskIncrementMutexHeldCount()
void* pvTaskIncrementMutexHeldCount (void)
Definition at line 4397 of file tasks.c.
References pxCurrentTCB, and tskTaskControlBlock::uxMutexesHeld.
Referenced by xQueueSemaphoreTake().
ulTaskNotifyTake()
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
Definition at line 4414 of file tasks.c.
uxTaskGetNumberOfTasks()
UBaseType_t uxTaskGetNumberOfTasks (void)
Definition at line 2260 of file tasks.c.
uxTaskGetStackHighWaterMark()
UBaseType_t uxTaskGetStackHighWaterMark (TaskHandle_t xTask)
task.h
UBaseType_t uxTaskGetStackHighWaterMark(TaskHandle_t xTask);
INCLUDE_uxTaskGetStackHighWaterMark must be set to 1 in FreeRTOSConfig.h for this function to be available.
Returns the high water mark of the stack associated with xTask. That is, the minimum free stack space there has been (in words, so on a 32 bit machine a value of 1 means 4 bytes) since the task started. The smaller the returned number the closer the task has come to overflowing its stack.
Parameters
xTask Handle of the task associated with the stack to be checked. Set xTask to NULL to check the stack of the calling task.
Returns
The smallest amount of free stack space there has been (in words, so actual spaces on the stack rather than bytes) since the task referenced by xTask was created.
Definition at line 3647 of file tasks.c.
References prvGetTCBFromHandle, prvTaskCheckFreeStackSpace(), and tskTaskControlBlock::pxStack.
uxTaskGetSystemState()
UBaseType_t uxTaskGetSystemState (TaskStatus_t *const pxTaskStatusArray, const UBaseType_t uxArraySize, uint32_t *const pulTotalRunTime)
configUSE_TRACE_FACILITY must be defined as 1 in FreeRTOSConfig.h for uxTaskGetSystemState() to be available.
uxTaskGetSystemState() populates an TaskStatus_t structure for each task in the system. TaskStatus_t structures contain, among other things, members for the task handle, task name, task priority, task state, and total amount of run time consumed by the task. See the TaskStatus_t structure definition in this file for the full member list.
NOTE: This function is intended for debugging use only as its use results in the scheduler remaining suspended for an extended period.
Parameters
pxTaskStatusArray A pointer to an array of TaskStatus_t structures. The array must contain at least one TaskStatus_t structure for each task that is under the control of the RTOS. The number of tasks under the control of the RTOS can be determined using the uxTaskGetNumberOfTasks() API function.
uxArraySize The size of the array pointed to by the pxTaskStatusArray parameter. The size is specified as the number of indexes in the array, or the number of TaskStatus_t structures contained in the array, not by the number of bytes in the array.
pulTotalRunTime If configGENERATE_RUN_TIME_STATS is set to 1 in FreeRTOSConfig.h then *pulTotalRunTime is set by uxTaskGetSystemState() to the total run time (as defined by the run time stats clock, see http://www.freertos.org/rtos-run-time-stats.html) since the target booted. pulTotalRunTime can be set to NULL to omit the total run time information.
Returns
The number of TaskStatus_t structures that were populated by uxTaskGetSystemState(). This should equal the number returned by the uxTaskGetNumberOfTasks() API function, but will be zero if the value passed in the uxArraySize parameter was too small.
Example usage:
 // This example demonstrates how a human readable table of run time stats
 // information is generated from raw data provided by uxTaskGetSystemState().
 // The human readable table is written to pcWriteBuffer
 void vTaskGetRunTimeStats(char *pcWriteBuffer)
 {
 TaskStatus_t *pxTaskStatusArray;
 volatile UBaseType_t uxArraySize, x;
 uint32_t ulTotalRunTime, ulStatsAsPercentage;
    // Make sure the write buffer does not contain a string.
    *pcWriteBuffer = 0x00;
    // Take a snapshot of the number of tasks in case it changes while this
    // function is executing.
    uxArraySize = uxTaskGetNumberOfTasks();
    // Allocate a TaskStatus_t structure for each task. An array could be
    // allocated statically at compile time.
    pxTaskStatusArray = pvPortMalloc(uxArraySize * sizeof(TaskStatus_t));
    if(pxTaskStatusArray != NULL)
    {
        // Generate raw status information about each task.
        uxArraySize = uxTaskGetSystemState(pxTaskStatusArray, uxArraySize, &ulTotalRunTime);
        // For percentage calculations.
        ulTotalRunTime /= 100UL;
        // Avoid divide by zero errors.
        if(ulTotalRunTime > 0)
        {
            // For each populated position in the pxTaskStatusArray array,
            // format the raw data as human readable ASCII data
            for(x = 0; x < uxArraySize; x++)
            {
                // What percentage of the total run time has the task used?
                // This will always be rounded down to the nearest integer.
                // ulTotalRunTimeDiv100 has already been divided by 100.
                ulStatsAsPercentage = pxTaskStatusArray[ x ].ulRunTimeCounter / ulTotalRunTime;
                if(ulStatsAsPercentage > 0UL)
                {
                    sprintf(pcWriteBuffer, "%s\t\t%lu\t\t%lu%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter, ulStatsAsPercentage);
                }
                else
                {
                    // If the percentage is zero here then the task has
                    // consumed less than 1% of the total run time.
                    sprintf(pcWriteBuffer, "%s\t\t%lu\t\t<1%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter);
                }
                pcWriteBuffer += strlen((char *) pcWriteBuffer);
            }
        }
        // The array is no longer needed, free the memory it consumes.
        vPortFree(pxTaskStatusArray);
    }
 }
Definition at line 2408 of file tasks.c.
References configMAX_PRIORITIES, eBlocked, eDeleted, eReady, eSuspended, mtCOVERAGE_TEST_MARKER, prvListTasksWithinSingleList(), pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskIDLE_PRIORITY, uxCurrentNumberOfTasks, vTaskSuspendAll(), xSuspendedTaskList, xTaskResumeAll(), and xTasksWaitingTermination.
Referenced by vTaskList().
uxTaskGetTaskNumber()
UBaseType_t uxTaskGetTaskNumber (TaskHandle_t xTask)
Definition at line 3176 of file tasks.c.
References tskTaskControlBlock::uxTaskNumber.
uxTaskPriorityGet()
UBaseType_t uxTaskPriorityGet (TaskHandle_t xTask)
Definition at line 1403 of file tasks.c.
References prvGetTCBFromHandle, taskENTER_CRITICAL, taskEXIT_CRITICAL, and tskTaskControlBlock::uxPriority.
uxTaskPriorityGetFromISR()
UBaseType_t uxTaskPriorityGetFromISR (TaskHandle_t xTask)
task. h
UBaseType_t uxTaskPriorityGetFromISR(TaskHandle_t xTask);
A version of uxTaskPriorityGet() that can be used from an ISR.
Definition at line 1425 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvGetTCBFromHandle, and tskTaskControlBlock::uxPriority.
uxTaskResetEventItemValue()
TickType_t uxTaskResetEventItemValue (void)
Definition at line 4381 of file tasks.c.
vTaskDelay()
void vTaskDelay (const TickType_t xTicksToDelay)
Definition at line 1287 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), traceTASK_DELAY, uxSchedulerSuspended, vTaskSuspendAll(), and xTaskResumeAll().
Referenced by fMyPrintf(), MyErrorHandler(), MyLEDsToggling(), MySPIErrorHandler(), MySPILEDsToggling(), MyUARTErrorHandler(), MyUARTLEDsToggling(), SPI_Slave_Task(), UART_Task(), vApplicationMallocFailedHook(), and vApplicationStackOverflowHook().
vTaskDelayUntil()
void vTaskDelayUntil (TickType_t *const pxPreviousWakeTime, const TickType_t xTimeIncrement)
Definition at line 1203 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), traceTASK_DELAY_UNTIL, uxSchedulerSuspended, vTaskSuspendAll(), xTaskResumeAll(), and xTickCount.
vTaskDelete()
void vTaskDelete (TaskHandle_t xTaskToDelete)
Definition at line 1111 of file tasks.c.
References configASSERT, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, portPRE_TASK_DELETE_HOOK, portYIELD_WITHIN_API, prvDeleteTCB(), prvGetTCBFromHandle, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskRESET_READY_PRIORITY, traceTASK_DELETE, uxCurrentNumberOfTasks, uxDeletedTasksWaitingCleanUp, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, uxTaskNumber, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, tskTaskControlBlock::xStateListItem, xTasksWaitingTermination, and xYieldPending.
Referenced by MyErrorHandler(), worker1_task(), and worker2_task().
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 2020 of file tasks.c.
vTaskGetInfo()
void vTaskGetInfo (TaskHandle_t xTask, TaskStatus_t * pxTaskStatus, BaseType_t xGetFreeStackSpace, eTaskState eState)
Definition at line 3498 of file tasks.c.
References eBlocked, xTASK_STATUS::eCurrentState, eInvalid, eRunning, eSuspended, eTaskGetState(), listLIST_ITEM_CONTAINER, xTASK_STATUS::pcTaskName, tskTaskControlBlock::pcTaskName, pdFALSE, prvGetTCBFromHandle, prvTaskCheckFreeStackSpace(), pxCurrentTCB, tskTaskControlBlock::pxStack, xTASK_STATUS::pxStackBase, xTASK_STATUS::ulRunTimeCounter, xTASK_STATUS::usStackHighWaterMark, xTASK_STATUS::uxBasePriority, tskTaskControlBlock::uxBasePriority, xTASK_STATUS::uxCurrentPriority, tskTaskControlBlock::uxPriority, tskTaskControlBlock::uxTCBNumber, vTaskSuspendAll(), tskTaskControlBlock::xEventListItem, xTASK_STATUS::xHandle, xTASK_STATUS::xTaskNumber, and xTaskResumeAll().
Referenced by prvListTasksWithinSingleList().
vTaskInternalSetTimeOutState()
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3097 of file tasks.c.
Referenced by xTaskCheckForTimeOut().
vTaskList()
void vTaskList (char * pcWriteBuffer)
Definition at line 4158 of file tasks.c.
References eBlocked, eDeleted, eReady, eRunning, eSuspended, mtCOVERAGE_TEST_MARKER, prvWriteNameToBuffer(), pvPortMalloc(), tskBLOCKED_CHAR, tskDELETED_CHAR, tskREADY_CHAR, tskRUNNING_CHAR, tskSUSPENDED_CHAR, uxCurrentNumberOfTasks, uxTaskGetSystemState(), and vPortFree().
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 3168 of file tasks.c.
vTaskNotifyGiveFromISR()
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4792 of file tasks.c.
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
Definition at line 2909 of file tasks.c.
vTaskPlaceOnEventListRestricted()
void vTaskPlaceOnEventListRestricted (List_t *const pxEventList, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
Definition at line 2952 of file tasks.c.
References configASSERT, pdFALSE, portMAX_DELAY, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, traceTASK_DELAY_UNTIL, vListInsertEnd(), tskTaskControlBlock::xEventListItem, and xTickCount.
Referenced by vQueueWaitForMessageRestricted().
vTaskPlaceOnUnorderedEventList()
void vTaskPlaceOnUnorderedEventList (List_t * pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
Definition at line 2926 of file tasks.c.
vTaskPriorityDisinheritAfterTimeout()
void vTaskPriorityDisinheritAfterTimeout (TaskHandle_t const pxMutexHolder, UBaseType_t uxHighestPriorityWaitingTask)
Definition at line 3967 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, prvAddTaskToReadyList, pxCurrentTCB, pxMutexHolder, pxReadyTasksLists, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_DISINHERIT, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
Referenced by xQueueSemaphoreTake().
vTaskPrioritySet()
void vTaskPrioritySet (TaskHandle_t xTask, UBaseType_t uxNewPriority)
Definition at line 1465 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portRESET_READY_PRIORITY, prvAddTaskToReadyList, prvGetTCBFromHandle, pxCurrentTCB, pxReadyTasksLists, taskENTER_CRITICAL, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_PRIORITY_SET, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
vTaskRemoveFromUnorderedEventList()
void vTaskRemoveFromUnorderedEventList (ListItem_t * pxEventListItem, const TickType_t xItemValue)
Definition at line 3051 of file tasks.c.
vTaskResume()
void vTaskResume (TaskHandle_t xTaskToResume)
Definition at line 1776 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, prvAddTaskToReadyList, prvTaskIsTaskSuspended(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_RESUME, uxListRemove(), tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xStateListItem.
Referenced by Manager_Task().
vTaskSetTaskNumber()
void vTaskSetTaskNumber (TaskHandle_t xTask, const UBaseType_t uxHandle)
Definition at line 3199 of file tasks.c.
References tskTaskControlBlock::uxTaskNumber.
vTaskSetThreadLocalStoragePointer()
void vTaskSetThreadLocalStoragePointer (TaskHandle_t xTaskToSet, BaseType_t xIndex, void * pvValue)
Definition at line 3382 of file tasks.c.
References configNUM_THREAD_LOCAL_STORAGE_POINTERS, prvGetTCBFromHandle, and tskTaskControlBlock::pvThreadLocalStoragePointers.
vTaskSetTimeOutState()
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3085 of file tasks.c.
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1900 of file tasks.c.
vTaskSuspend()
void vTaskSuspend (TaskHandle_t xTaskToSuspend)
Definition at line 1629 of file tasks.c.
References configASSERT, listCURRENT_LIST_LENGTH, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvGetTCBFromHandle, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskRESET_READY_PRIORITY, taskWAITING_NOTIFICATION, traceTASK_SUSPEND, tskTaskControlBlock::ucNotifyState, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), vTaskSwitchContext(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, tskTaskControlBlock::xStateListItem, and xSuspendedTaskList.
Referenced by worker1_task(), and worker2_task().
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 2031 of file tasks.c.
Referenced by portTASK_FUNCTION(), uxTaskGetSystemState(), vTaskDelay(), vTaskDelayUntil(), vTaskGetInfo(), xTaskAbortDelay(), and xTaskGetHandle().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 2850 of file tasks.c.
Referenced by vTaskSuspend().
xTaskAbortDelay()
BaseType_t xTaskAbortDelay (TaskHandle_t xTask)
Definition at line 2514 of file tasks.c.
References configASSERT, eBlocked, eTaskGetState(), listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::ucDelayAborted, uxListRemove(), tskTaskControlBlock::uxPriority, vTaskSuspendAll(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xStateListItem, xTaskResumeAll(), and xYieldPending.
xTaskCheckForTimeOut()
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
Definition at line 3105 of file tasks.c.
xTaskGenericNotify()
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue)
Definition at line 4562 of file tasks.c.
xTaskGenericNotifyFromISR()
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4668 of file tasks.c.
xTaskGetCurrentTaskHandle()
TaskHandle_t xTaskGetCurrentTaskHandle (void)
Definition at line 3755 of file tasks.c.
References pxCurrentTCB.
Referenced by xQueueGiveMutexRecursive(), xQueueTakeMutexRecursive(), xStreamBufferReceive(), and xStreamBufferSend().
xTaskGetHandle()
TaskHandle_t xTaskGetHandle (const char * pcNameToQuery)
Definition at line 2343 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, prvSearchForNameWithinSingleList(), pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskIDLE_PRIORITY, vTaskSuspendAll(), xSuspendedTaskList, xTaskResumeAll(), and xTasksWaitingTermination.
xTaskGetIdleTaskHandle()
TaskHandle_t xTaskGetIdleTaskHandle (void)
xTaskGetIdleTaskHandle() is only available if INCLUDE_xTaskGetIdleTaskHandle is set to 1 in FreeRTOSConfig.h.
Simply returns the handle of the idle task. It is not valid to call xTaskGetIdleTaskHandle() before the scheduler has been started.
Definition at line 2482 of file tasks.c.
References configASSERT, and xIdleTaskHandle.
xTaskGetSchedulerState()
BaseType_t xTaskGetSchedulerState (void)
Definition at line 3772 of file tasks.c.
References pdFALSE, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, uxSchedulerSuspended, and xSchedulerRunning.
Referenced by xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), xQueueSemaphoreTake(), and xTimerGenericCommand().
xTaskGetTickCount()
TickType_t xTaskGetTickCount (void)
Definition at line 2214 of file tasks.c.
xTaskGetTickCountFromISR()
TickType_t xTaskGetTickCountFromISR (void)
Definition at line 2229 of file tasks.c.
xTaskIncrementTick()
BaseType_t xTaskIncrementTick (void)
Definition at line 2588 of file tasks.c.
Referenced by xTaskResumeAll().
xTaskNotifyStateClear()
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
Definition at line 4881 of file tasks.c.
xTaskNotifyWait()
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t * pulNotificationValue, TickType_t xTicksToWait)
Definition at line 4482 of file tasks.c.
xTaskPriorityDisinherit()
BaseType_t xTaskPriorityDisinherit (TaskHandle_t const pxMutexHolder)
Definition at line 3887 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, pxMutexHolder, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_DISINHERIT, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
Referenced by prvCopyDataToQueue().
xTaskPriorityInherit()
BaseType_t xTaskPriorityInherit (TaskHandle_t const pxMutexHolder)
Definition at line 3800 of file tasks.c.
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, pxMutexHolder, pxReadyTasksLists, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_INHERIT, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
Referenced by xQueueSemaphoreTake().
xTaskRemoveFromEventList()
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
Definition at line 2983 of file tasks.c.
xTaskResumeAll()
BaseType_t xTaskResumeAll (void)
Definition at line 2104 of file tasks.c.
Referenced by portTASK_FUNCTION(), uxTaskGetSystemState(), vTaskDelay(), vTaskDelayUntil(), vTaskGetInfo(), xTaskAbortDelay(), and xTaskGetHandle().
xTaskResumeFromISR()
BaseType_t xTaskResumeFromISR (TaskHandle_t xTaskToResume)
Definition at line 1830 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, prvTaskIsTaskSuspended(), pxCurrentTCB, traceTASK_RESUME_FROM_ISR, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, and tskTaskControlBlock::xStateListItem.
Variable Documentation
pxCurrentTCB
PRIVILEGED_DATA TCB_t* volatile pxCurrentTCB = NULL
Definition at line 347 of file tasks.c.
Referenced by eTaskGetState(), prvAddCurrentTaskToDelayedList(), prvAddNewTaskToReadyList(), prvRestoreContextOfFirstTask(), pvTaskIncrementMutexHeldCount(), ulTaskNotifyTake(), uxTaskResetEventItemValue(), vTaskDelete(), vTaskGetInfo(), vTaskNotifyGiveFromISR(), vTaskPlaceOnEventList(), vTaskPlaceOnEventListRestricted(), vTaskPlaceOnUnorderedEventList(), vTaskPriorityDisinheritAfterTimeout(), vTaskPrioritySet(), vTaskRemoveFromUnorderedEventList(), vTaskResume(), vTaskStartScheduler(), vTaskSuspend(), vTaskSwitchContext(), xPortPendSVHandler(), xTaskAbortDelay(), xTaskCheckForTimeOut(), xTaskGenericNotify(), xTaskGenericNotifyFromISR(), xTaskGetCurrentTaskHandle(), xTaskIncrementTick(), xTaskNotifyWait(), xTaskPriorityDisinherit(), xTaskPriorityInherit(), xTaskRemoveFromEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
pxDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxDelayedTaskList [static]
Definition at line 353 of file tasks.c.
Referenced by eTaskGetState(), prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), prvResetNextTaskUnblockTime(), uxTaskGetSystemState(), xTaskGetHandle(), and xTaskIncrementTick().
pxOverflowDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxOverflowDelayedTaskList [static]
Definition at line 354 of file tasks.c.
Referenced by eTaskGetState(), prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), uxTaskGetSystemState(), and xTaskGetHandle().
pxReadyTasksLists
PRIVILEGED_DATA List_t pxReadyTasksLists[configMAX_PRIORITIES] [static]
Definition at line 350 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvInitialiseTaskLists(), uxTaskGetSystemState(), vTaskPriorityDisinheritAfterTimeout(), vTaskPrioritySet(), xTaskGetHandle(), xTaskIncrementTick(), and xTaskPriorityInherit().
uxCurrentNumberOfTasks
PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U [static]
Definition at line 371 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), prvCheckTasksWaitingTermination(), uxTaskGetNumberOfTasks(), uxTaskGetSystemState(), vTaskDelete(), vTaskList(), vTaskSuspend(), and xTaskResumeAll().
uxDeletedTasksWaitingCleanUp
PRIVILEGED_DATA volatile UBaseType_t uxDeletedTasksWaitingCleanUp = (UBaseType_t) 0U [static]
Definition at line 360 of file tasks.c.
Referenced by prvCheckTasksWaitingTermination(), and vTaskDelete().
uxPendedTicks
PRIVILEGED_DATA volatile UBaseType_t uxPendedTicks = (UBaseType_t) 0U [static]
Definition at line 375 of file tasks.c.
Referenced by xTaskIncrementTick(), and xTaskResumeAll().
uxSchedulerSuspended
PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE [static]
Definition at line 390 of file tasks.c.
Referenced by vTaskDelay(), vTaskDelayUntil(), vTaskDelete(), vTaskNotifyGiveFromISR(), vTaskPlaceOnUnorderedEventList(), vTaskRemoveFromUnorderedEventList(), vTaskSuspend(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskGenericNotifyFromISR(), xTaskGetSchedulerState(), xTaskIncrementTick(), xTaskRemoveFromEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
uxTaskNumber
PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U [static]
Definition at line 378 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), and vTaskDelete().
uxTopReadyPriority
PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY [static]
Definition at line 373 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), and vTaskPrioritySet().
xDelayedTaskList1
PRIVILEGED_DATA List_t xDelayedTaskList1 [static]
Definition at line 351 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xDelayedTaskList2
PRIVILEGED_DATA List_t xDelayedTaskList2 [static]
Definition at line 352 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xIdleTaskHandle
PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL [static]
Definition at line 380 of file tasks.c.
Referenced by vTaskStartScheduler(), and xTaskGetIdleTaskHandle().
xNextTaskUnblockTime
PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U [static]
Definition at line 379 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), prvResetNextTaskUnblockTime(), vTaskStartScheduler(), and xTaskIncrementTick().
xNumOfOverflows
PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0 [static]
Definition at line 377 of file tasks.c.
Referenced by vTaskInternalSetTimeOutState(), vTaskSetTimeOutState(), and xTaskCheckForTimeOut().
xPendingReadyList
PRIVILEGED_DATA List_t xPendingReadyList [static]
Definition at line 355 of file tasks.c.
Referenced by prvInitialiseTaskLists(), prvTaskIsTaskSuspended(), vTaskNotifyGiveFromISR(), xTaskGenericNotifyFromISR(), xTaskRemoveFromEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
xSchedulerRunning
PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE [static]
Definition at line 374 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), vTaskDelete(), vTaskEndScheduler(), vTaskStartScheduler(), vTaskSuspend(), and xTaskGetSchedulerState().
xSuspendedTaskList
PRIVILEGED_DATA List_t xSuspendedTaskList [static]
Definition at line 366 of file tasks.c.
Referenced by eTaskGetState(), prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), prvTaskIsTaskSuspended(), uxTaskGetSystemState(), vTaskSuspend(), and xTaskGetHandle().
xTasksWaitingTermination
PRIVILEGED_DATA List_t xTasksWaitingTermination [static]
Definition at line 359 of file tasks.c.
Referenced by eTaskGetState(), prvCheckTasksWaitingTermination(), prvInitialiseTaskLists(), uxTaskGetSystemState(), vTaskDelete(), and xTaskGetHandle().
xTickCount
PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) configINITIAL_TICK_COUNT [static]
Definition at line 372 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), vTaskDelayUntil(), vTaskInternalSetTimeOutState(), vTaskPlaceOnEventListRestricted(), vTaskSetTimeOutState(), vTaskStartScheduler(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskGetTickCountFromISR(), and xTaskIncrementTick().
xYieldPending
PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE [static]
Definition at line 376 of file tasks.c.
Referenced by vTaskDelete(), vTaskMissedYield(), vTaskNotifyGiveFromISR(), vTaskRemoveFromUnorderedEventList(), vTaskSwitchContext(), xTaskAbortDelay(), xTaskGenericNotifyFromISR(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().