Dave/Generated/FREERTOS/queue.c File Reference
#include <stdlib.h>
#include <string.h>
#include `FreeRTOS.h`
#include `task.h`
#include `queue.h`
Data Structures
struct QueueDefinition
struct QUEUE_REGISTRY_ITEM
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define queueUNLOCKED ((int8_t) -1)
#define queueLOCKED_UNMODIFIED ((int8_t) 0)
#define pxMutexHolder pcTail
#define uxQueueType pcHead
#define queueQUEUE_IS_MUTEX NULL
#define queueSEMAPHORE_QUEUE_ITEM_LENGTH ((UBaseType_t) 0)
#define queueMUTEX_GIVE_BLOCK_TIME ((TickType_t) 0U)
#define queueYIELD_IF_USING_PREEMPTION() portYIELD_WITHIN_API()
#define prvLockQueue(pxQueue)
Typedefs
typedef struct QueueDefinition xQUEUE
typedef xQUEUE Queue_t
typedef struct QUEUE_REGISTRY_ITEM xQueueRegistryItem
typedef xQueueRegistryItem QueueRegistryItem_t
Functions
static void prvUnlockQueue (Queue_t *const pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvIsQueueEmpty (const Queue_t *pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvIsQueueFull (const Queue_t *pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvCopyDataToQueue (Queue_t *const pxQueue, const void *pvItemToQueue, const BaseType_t xPosition) PRIVILEGED_FUNCTION
static void prvCopyDataFromQueue (Queue_t *const pxQueue, void *const pvBuffer) PRIVILEGED_FUNCTION
static BaseType_t prvNotifyQueueSetContainer (const Queue_t *const pxQueue, const BaseType_t xCopyPosition) PRIVILEGED_FUNCTION
static void prvInitialiseNewQueue (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, uint8_t *pucQueueStorage, const uint8_t ucQueueType, Queue_t *pxNewQueue) PRIVILEGED_FUNCTION
static void prvInitialiseMutex (Queue_t *pxNewQueue) PRIVILEGED_FUNCTION
static UBaseType_t prvGetDisinheritPriorityAfterTimeout (const Queue_t *const pxQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
QueueHandle_t xQueueGenericCreate (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, const uint8_t ucQueueType)
QueueHandle_t xQueueCreateMutex (const uint8_t ucQueueType)
void * xQueueGetMutexHolder (QueueHandle_t xSemaphore)
void * xQueueGetMutexHolderFromISR (QueueHandle_t xSemaphore)
BaseType_t xQueueGiveMutexRecursive (QueueHandle_t xMutex)
BaseType_t xQueueTakeMutexRecursive (QueueHandle_t xMutex, TickType_t xTicksToWait)
QueueHandle_t xQueueCreateCountingSemaphore (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount)
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
void vQueueDelete (QueueHandle_t xQueue)
UBaseType_t uxQueueGetQueueNumber (QueueHandle_t xQueue)
void vQueueSetQueueNumber (QueueHandle_t xQueue, UBaseType_t uxQueueNumber)
uint8_t ucQueueGetQueueType (QueueHandle_t xQueue)
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
void vQueueAddToRegistry (QueueHandle_t xQueue, const char *pcQueueName)
const char * pcQueueGetName (QueueHandle_t xQueue)
void vQueueUnregisterQueue (QueueHandle_t xQueue)
void vQueueWaitForMessageRestricted (QueueHandle_t xQueue, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
QueueSetHandle_t xQueueCreateSet (const UBaseType_t uxEventQueueLength)
BaseType_t xQueueAddToSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
BaseType_t xQueueRemoveFromSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
QueueSetMemberHandle_t xQueueSelectFromSet (QueueSetHandle_t xQueueSet, TickType_t const xTicksToWait)
QueueSetMemberHandle_t xQueueSelectFromSetFromISR (QueueSetHandle_t xQueueSet)
Variables
PRIVILEGED_DATA QueueRegistryItem_t xQueueRegistry [configQUEUE_REGISTRY_SIZE]
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 35 of file queue.c.
prvLockQueue
#define prvLockQueue(pxQueue)
Value:
    taskENTER_CRITICAL(); \
    { \
        if((pxQueue)->cRxLock == queueUNLOCKED) \
        { \
            (pxQueue)->cRxLock = queueLOCKED_UNMODIFIED; \
        } \
        if((pxQueue)->cTxLock == queueUNLOCKED) \
        { \
            (pxQueue)->cTxLock = queueLOCKED_UNMODIFIED; \
        } \
    } \
    taskEXIT_CRITICAL()
Definition at line 233 of file queue.c.
pxMutexHolder
#define pxMutexHolder pcTail
Definition at line 67 of file queue.c.
queueLOCKED_UNMODIFIED
#define queueLOCKED_UNMODIFIED ((int8_t) 0)
Definition at line 54 of file queue.c.
queueMUTEX_GIVE_BLOCK_TIME
#define queueMUTEX_GIVE_BLOCK_TIME ((TickType_t) 0U)
Definition at line 74 of file queue.c.
queueQUEUE_IS_MUTEX
#define queueQUEUE_IS_MUTEX NULL
Definition at line 69 of file queue.c.
queueSEMAPHORE_QUEUE_ITEM_LENGTH
#define queueSEMAPHORE_QUEUE_ITEM_LENGTH ((UBaseType_t) 0)
Definition at line 73 of file queue.c.
queueUNLOCKED
#define queueUNLOCKED ((int8_t) -1)
Definition at line 53 of file queue.c.
queueYIELD_IF_USING_PREEMPTION
#define queueYIELD_IF_USING_PREEMPTION() portYIELD_WITHIN_API()
Definition at line 81 of file queue.c.
uxQueueType
#define uxQueueType pcHead
Definition at line 68 of file queue.c.
Typedef Documentation
Queue_t
typedef xQUEUE Queue_t
Definition at line 127 of file queue.c.
QueueRegistryItem_t
typedef xQueueRegistryItem QueueRegistryItem_t
Definition at line 149 of file queue.c.
xQUEUE
typedef struct QueueDefinition xQUEUE
xQueueRegistryItem
typedef struct QUEUE_REGISTRY_ITEM xQueueRegistryItem
Function Documentation
pcQueueGetName()
const char* pcQueueGetName (QueueHandle_t xQueue)
Definition at line 2641 of file queue.c.
References configQUEUE_REGISTRY_SIZE, mtCOVERAGE_TEST_MARKER, QUEUE_REGISTRY_ITEM::pcQueueName, xQueue, and xQueueRegistry.
prvCopyDataFromQueue()
static void prvCopyDataFromQueue (Queue_t *const pxQueue, void *const pvBuffer) [static]
Definition at line 2119 of file queue.c.
References mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::u, and QueueDefinition::uxItemSize.
Referenced by xQueuePeek(), xQueuePeekFromISR(), xQueueReceive(), and xQueueReceiveFromISR().
prvCopyDataToQueue()
static BaseType_t prvCopyDataToQueue (Queue_t *const pxQueue, const void * pvItemToQueue, const BaseType_t xPosition) [static]
Definition at line 2040 of file queue.c.
References mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::pcWriteTo, pdFALSE, queueOVERWRITE, queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, and xTaskPriorityDisinherit().
Referenced by prvNotifyQueueSetContainer(), xQueueGenericSend(), and xQueueGenericSendFromISR().
prvGetDisinheritPriorityAfterTimeout()
static UBaseType_t prvGetDisinheritPriorityAfterTimeout (const Queue_t *const pxQueue) [static]
Definition at line 2015 of file queue.c.
References configMAX_PRIORITIES, listCURRENT_LIST_LENGTH, listGET_ITEM_VALUE_OF_HEAD_ENTRY, tskIDLE_PRIORITY, and QueueDefinition::xTasksWaitingToReceive.
Referenced by xQueueSemaphoreTake().
prvInitialiseMutex()
static void prvInitialiseMutex (Queue_t * pxNewQueue) [static]
Definition at line 452 of file queue.c.
References queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, traceCREATE_MUTEX, traceCREATE_MUTEX_FAILED, QueueDefinition::u, QueueDefinition::uxRecursiveCallCount, and xQueueGenericSend().
Referenced by xQueueCreateMutex().
prvInitialiseNewQueue()
static void prvInitialiseNewQueue (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, uint8_t * pucQueueStorage, const uint8_t ucQueueType, Queue_t * pxNewQueue) [static]
Definition at line 408 of file queue.c.
References QueueDefinition::pcHead, pdTRUE, QueueDefinition::pxQueueSetContainer, traceQUEUE_CREATE, QueueDefinition::ucQueueType, QueueDefinition::uxItemSize, QueueDefinition::uxLength, and xQueueGenericReset().
Referenced by xQueueGenericCreate().
prvIsQueueEmpty()
static BaseType_t prvIsQueueEmpty (const Queue_t * pxQueue) [static]
Definition at line 2257 of file queue.c.
References pdFALSE, pdTRUE, taskENTER_CRITICAL, taskEXIT_CRITICAL, and QueueDefinition::uxMessagesWaiting.
Referenced by xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
prvIsQueueFull()
static BaseType_t prvIsQueueFull (const Queue_t * pxQueue) [static]
Definition at line 2296 of file queue.c.
References pdFALSE, pdTRUE, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
Referenced by xQueueGenericSend().
prvNotifyQueueSetContainer()
static BaseType_t prvNotifyQueueSetContainer (const Queue_t *const pxQueue, const BaseType_t xCopyPosition) [static]
Definition at line 2846 of file queue.c.
References configASSERT, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvCopyDataToQueue(), QueueDefinition::pxQueueSetContainer, queueUNLOCKED, traceQUEUE_SEND, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
Referenced by prvUnlockQueue(), xQueueGenericSend(), xQueueGenericSendFromISR(), and xQueueGiveFromISR().
prvUnlockQueue()
static void prvUnlockQueue (Queue_t *const pxQueue) [static]
Definition at line 2137 of file queue.c.
References QueueDefinition::cRxLock, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, prvNotifyQueueSetContainer(), QueueDefinition::pxQueueSetContainer, queueLOCKED_UNMODIFIED, queueSEND_TO_BACK, queueUNLOCKED, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskMissedYield(), xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by vQueueWaitForMessageRestricted(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
ucQueueGetQueueType()
uint8_t ucQueueGetQueueType (QueueHandle_t xQueue)
Definition at line 2005 of file queue.c.
References xQueue.
uxQueueGetQueueNumber()
UBaseType_t uxQueueGetQueueNumber (QueueHandle_t xQueue)
Definition at line 1985 of file queue.c.
References xQueue.
uxQueueMessagesWaiting()
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
Definition at line 1895 of file queue.c.
uxQueueMessagesWaitingFromISR()
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
Definition at line 1929 of file queue.c.
uxQueueSpacesAvailable()
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
Definition at line 1911 of file queue.c.
vQueueAddToRegistry()
void vQueueAddToRegistry (QueueHandle_t xQueue, const char * pcQueueName)
Definition at line 2612 of file queue.c.
References configQUEUE_REGISTRY_SIZE, mtCOVERAGE_TEST_MARKER, QUEUE_REGISTRY_ITEM::pcQueueName, traceQUEUE_REGISTRY_ADD, QUEUE_REGISTRY_ITEM::xHandle, xQueue, and xQueueRegistry.
Referenced by Manager_Task(), and prvCheckForValidListAndQueue().
vQueueDelete()
void vQueueDelete (QueueHandle_t xQueue)
Definition at line 1941 of file queue.c.
vQueueSetQueueNumber()
void vQueueSetQueueNumber (QueueHandle_t xQueue, UBaseType_t uxQueueNumber)
Definition at line 1995 of file queue.c.
References xQueue.
vQueueUnregisterQueue()
void vQueueUnregisterQueue (QueueHandle_t xQueue)
Definition at line 2669 of file queue.c.
References configQUEUE_REGISTRY_SIZE, mtCOVERAGE_TEST_MARKER, QUEUE_REGISTRY_ITEM::pcQueueName, QUEUE_REGISTRY_ITEM::xHandle, xQueue, and xQueueRegistry.
Referenced by vQueueDelete().
vQueueWaitForMessageRestricted()
void vQueueWaitForMessageRestricted (QueueHandle_t xQueue, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
Definition at line 2701 of file queue.c.
References mtCOVERAGE_TEST_MARKER, prvLockQueue, prvUnlockQueue(), QueueDefinition::uxMessagesWaiting, vTaskPlaceOnEventListRestricted(), xQueue, and QueueDefinition::xTasksWaitingToReceive.
Referenced by prvProcessTimerOrBlockTask().
xQueueAddToSet()
BaseType_t xQueueAddToSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
Definition at line 2751 of file queue.c.
References pdFAIL, pdPASS, taskENTER_CRITICAL, and taskEXIT_CRITICAL.
xQueueCreateCountingSemaphore()
QueueHandle_t xQueueCreateCountingSemaphore (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount)
Definition at line 699 of file queue.c.
References configASSERT, queueQUEUE_TYPE_COUNTING_SEMAPHORE, queueSEMAPHORE_QUEUE_ITEM_LENGTH, traceCREATE_COUNTING_SEMAPHORE, traceCREATE_COUNTING_SEMAPHORE_FAILED, and xQueueGenericCreate().
xQueueCreateMutex()
QueueHandle_t xQueueCreateMutex (const uint8_t ucQueueType)
Definition at line 482 of file queue.c.
References prvInitialiseMutex(), and xQueueGenericCreate().
xQueueCreateSet()
QueueSetHandle_t xQueueCreateSet (const UBaseType_t uxEventQueueLength)
Definition at line 2737 of file queue.c.
References queueQUEUE_TYPE_SET, and xQueueGenericCreate().
xQueueGenericCreate()
QueueHandle_t xQueueGenericCreate (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, const uint8_t ucQueueType)
Definition at line 358 of file queue.c.
References configASSERT, pdFALSE, prvInitialiseNewQueue(), pvPortMalloc(), and traceQUEUE_CREATE_FAILED.
Referenced by xQueueCreateCountingSemaphore(), xQueueCreateMutex(), and xQueueCreateSet().
xQueueGenericReset()
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
Definition at line 247 of file queue.c.
Referenced by prvInitialiseNewQueue().
xQueueGenericSend()
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
Definition at line 725 of file queue.c.
Referenced by prvInitialiseMutex(), and xQueueGiveMutexRecursive().
xQueueGenericSendFromISR()
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
Definition at line 923 of file queue.c.
xQueueGetMutexHolder()
void* xQueueGetMutexHolder (QueueHandle_t xSemaphore)
Definition at line 518 of file queue.c.
References pxMutexHolder, queueQUEUE_IS_MUTEX, taskENTER_CRITICAL, taskEXIT_CRITICAL, and uxQueueType.
xQueueGetMutexHolderFromISR()
void* xQueueGetMutexHolderFromISR (QueueHandle_t xSemaphore)
Definition at line 548 of file queue.c.
References configASSERT, pxMutexHolder, queueQUEUE_IS_MUTEX, and uxQueueType.
xQueueGiveFromISR()
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1074 of file queue.c.
xQueueGiveMutexRecursive()
BaseType_t xQueueGiveMutexRecursive (QueueHandle_t xMutex)
Definition at line 574 of file queue.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, queueMUTEX_GIVE_BLOCK_TIME, queueSEND_TO_BACK, traceGIVE_MUTEX_RECURSIVE, traceGIVE_MUTEX_RECURSIVE_FAILED, QueueDefinition::u, QueueDefinition::uxRecursiveCallCount, xQueueGenericSend(), and xTaskGetCurrentTaskHandle().
xQueueIsQueueEmptyFromISR()
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
Definition at line 2278 of file queue.c.
xQueueIsQueueFullFromISR()
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Definition at line 2317 of file queue.c.
xQueuePeek()
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1600 of file queue.c.
xQueuePeekFromISR()
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
Definition at line 1841 of file queue.c.
xQueueReceive()
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1239 of file queue.c.
Referenced by prvProcessReceivedCommands(), UART_Task(), worker1_task(), worker2_task(), and xQueueSelectFromSet().
xQueueReceiveFromISR()
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1750 of file queue.c.
Referenced by xQueueSelectFromSetFromISR().
xQueueRemoveFromSet()
BaseType_t xQueueRemoveFromSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
Definition at line 2784 of file queue.c.
References pdFAIL, pdPASS, QueueDefinition::pxQueueSetContainer, taskENTER_CRITICAL, taskEXIT_CRITICAL, and QueueDefinition::uxMessagesWaiting.
xQueueSelectFromSet()
QueueSetMemberHandle_t xQueueSelectFromSet (QueueSetHandle_t xQueueSet, TickType_t const xTicksToWait)
Definition at line 2820 of file queue.c.
References xQueueReceive().
xQueueSelectFromSetFromISR()
QueueSetMemberHandle_t xQueueSelectFromSetFromISR (QueueSetHandle_t xQueueSet)
Definition at line 2833 of file queue.c.
References xQueueReceiveFromISR().
xQueueSemaphoreTake()
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
Definition at line 1381 of file queue.c.
Referenced by xQueueTakeMutexRecursive().
xQueueTakeMutexRecursive()
BaseType_t xQueueTakeMutexRecursive (QueueHandle_t xMutex, TickType_t xTicksToWait)
Definition at line 629 of file queue.c.
References configASSERT, pdFAIL, pdPASS, traceTAKE_MUTEX_RECURSIVE, traceTAKE_MUTEX_RECURSIVE_FAILED, QueueDefinition::u, QueueDefinition::uxRecursiveCallCount, xQueueSemaphoreTake(), and xTaskGetCurrentTaskHandle().
Variable Documentation
xQueueRegistry
PRIVILEGED_DATA QueueRegistryItem_t xQueueRegistry[configQUEUE_REGISTRY_SIZE]
Definition at line 154 of file queue.c.
Referenced by pcQueueGetName(), vQueueAddToRegistry(), and vQueueUnregisterQueue().