Dave/Model/APPS/FREERTOS/v4_1_2/Templates/portable/IAR/ARM_CM4F/port_mpu.h File Reference
#include <intrinsics.h>
#include `FREERTOS/FreeRTOS.h`
#include `FREERTOS/task.h`
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define configSYSTICK_CLOCK_HZ configCPU_CLOCK_HZ
#define portNVIC_SYSTICK_CLK_BIT (1UL << 2UL)
#define portNVIC_SYSTICK_CTRL_REG (* ((volatile uint32_t *) 0xe000e010))
#define portNVIC_SYSTICK_LOAD_REG (* ((volatile uint32_t *) 0xe000e014))
#define portNVIC_SYSTICK_CURRENT_VALUE_REG (* ((volatile uint32_t *) 0xe000e018))
#define portNVIC_SYSPRI2_REG (* ((volatile uint32_t *) 0xe000ed20))
#define portNVIC_SYSPRI1_REG (* ((volatile uint32_t *) 0xe000ed1c))
#define portNVIC_SYS_CTRL_STATE_REG (* ((volatile uint32_t *) 0xe000ed24))
#define portNVIC_MEM_FAULT_ENABLE (1UL << 16UL)
#define portMPU_TYPE_REG (* ((volatile uint32_t *) 0xe000ed90))
#define portMPU_REGION_BASE_ADDRESS_REG (* ((volatile uint32_t *) 0xe000ed9C))
#define portMPU_REGION_ATTRIBUTE_REG (* ((volatile uint32_t *) 0xe000edA0))
#define portMPU_CTRL_REG (* ((volatile uint32_t *) 0xe000ed94))
#define portEXPECTED_MPU_TYPE_VALUE (8UL << 8UL) /* 8 regions, unified. */
#define portMPU_ENABLE (0x01UL)
#define portMPU_BACKGROUND_ENABLE (1UL << 2UL)
#define portPRIVILEGED_EXECUTION_START_ADDRESS (0UL)
#define portMPU_REGION_VALID (0x10UL)
#define portMPU_REGION_ENABLE (0x01UL)
#define portPERIPHERALS_START_ADDRESS 0x40000000UL
#define portPERIPHERALS_END_ADDRESS 0x5FFFFFFFUL
#define portNVIC_SYSTICK_INT_BIT (1UL << 1UL)
#define portNVIC_SYSTICK_ENABLE_BIT (1UL << 0UL)
#define portNVIC_SYSTICK_COUNT_FLAG_BIT (1UL << 16UL)
#define portNVIC_PENDSVCLEAR_BIT (1UL << 27UL)
#define portNVIC_PEND_SYSTICK_CLEAR_BIT (1UL << 25UL)
#define portCPUID (* ((volatile uint32_t *) 0xE000ed00))
#define portCORTEX_M7_r0p1_ID (0x410FC271UL)
#define portCORTEX_M7_r0p0_ID (0x410FC270UL)
#define portNVIC_PENDSV_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 16UL)
#define portNVIC_SYSTICK_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
#define portNVIC_SVC_PRI (((uint32_t) configMAX_SYSCALL_INTERRUPT_PRIORITY - 1UL) << 24UL)
#define portFIRST_USER_INTERRUPT_NUMBER (16)
#define portNVIC_IP_REGISTERS_OFFSET_16 (0xE000E3F0)
#define portAIRCR_REG (* ((volatile uint32_t *) 0xE000ED0C))
#define portMAX_8_BIT_VALUE ((uint8_t) 0xff)
#define portTOP_BIT_OF_BYTE ((uint8_t) 0x80)
#define portMAX_PRIGROUP_BITS ((uint8_t) 7)
#define portPRIORITY_GROUP_MASK (0x07UL << 8UL)
#define portPRIGROUP_SHIFT (8UL)
#define portVECTACTIVE_MASK (0xFFUL)
#define portFPCCR ((volatile uint32_t *) 0xe000ef34) /* Floating point context control register. */
#define portASPEN_AND_LSPEN_BITS (0x3UL << 30UL)
#define portINITIAL_XPSR (0x01000000)
#define portINITIAL_EXC_RETURN (0xfffffffd)
#define portINITIAL_CONTROL_IF_UNPRIVILEGED (0x03)
#define portINITIAL_CONTROL_IF_PRIVILEGED (0x02)
#define portOFFSET_TO_PC (6)
#define portMAX_24_BIT_NUMBER (0xffffffUL)
#define portMISSED_COUNTS_FACTOR (45UL)
#define portSTART_ADDRESS_MASK ((StackType_t) 0xfffffffeUL)
Functions
static void prvSetupMPU (void) PRIVILEGED_FUNCTION
static uint32_t prvGetMPURegionSizeSetting (uint32_t ulActualSizeInBytes) PRIVILEGED_FUNCTION
BaseType_t xPortRaisePrivilege (void)
void vPortSetupTimerInterrupt (void)
void xPortSysTickHandler (void) PRIVILEGED_FUNCTION
void vPortStartFirstTask (void) PRIVILEGED_FUNCTION
void vPortEnableVFP (void)
void vPortSVCHandler_C (uint32_t *pulParam)
void vPortRestoreContextOfFirstTask (void) PRIVILEGED_FUNCTION
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters, BaseType_t xRunPrivileged)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
void vPortResetPrivilege (BaseType_t xRunningPrivileged)
void vPortStoreTaskMPUSettings (xMPU_SETTINGS *xMPUSettings, const struct xMEMORY_REGION *const xRegions, StackType_t *pxBottomOfStack, uint32_t ulStackDepth)
Variables
static UBaseType_t uxCriticalNesting = 0xaaaaaaaa
Macro Definition Documentation
configSYSTICK_CLOCK_HZ
#define configSYSTICK_CLOCK_HZ configCPU_CLOCK_HZ
Definition at line 58 of file port_mpu.h.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 39 of file port_mpu.h.
portAIRCR_REG
#define portAIRCR_REG (* ((volatile uint32_t *) 0xE000ED0C))
Definition at line 110 of file port_mpu.h.
portASPEN_AND_LSPEN_BITS
#define portASPEN_AND_LSPEN_BITS (0x3UL << 30UL)
Definition at line 122 of file port_mpu.h.
portCORTEX_M7_r0p0_ID
#define portCORTEX_M7_r0p0_ID (0x410FC270UL)
Definition at line 101 of file port_mpu.h.
portCORTEX_M7_r0p1_ID
#define portCORTEX_M7_r0p1_ID (0x410FC271UL)
Definition at line 100 of file port_mpu.h.
portCPUID
#define portCPUID (* ((volatile uint32_t *) 0xE000ed00))
Definition at line 99 of file port_mpu.h.
portEXPECTED_MPU_TYPE_VALUE
#define portEXPECTED_MPU_TYPE_VALUE (8UL << 8UL) /* 8 regions, unified. */
Definition at line 81 of file port_mpu.h.
portFIRST_USER_INTERRUPT_NUMBER
#define portFIRST_USER_INTERRUPT_NUMBER (16)
Definition at line 108 of file port_mpu.h.
portFPCCR
#define portFPCCR ((volatile uint32_t *) 0xe000ef34) /* Floating point context control register. */
Definition at line 121 of file port_mpu.h.
portINITIAL_CONTROL_IF_PRIVILEGED
#define portINITIAL_CONTROL_IF_PRIVILEGED (0x02)
Definition at line 128 of file port_mpu.h.
portINITIAL_CONTROL_IF_UNPRIVILEGED
#define portINITIAL_CONTROL_IF_UNPRIVILEGED (0x03)
Definition at line 127 of file port_mpu.h.
portINITIAL_EXC_RETURN
#define portINITIAL_EXC_RETURN (0xfffffffd)
Definition at line 126 of file port_mpu.h.
portINITIAL_XPSR
#define portINITIAL_XPSR (0x01000000)
Definition at line 125 of file port_mpu.h.
portMAX_24_BIT_NUMBER
#define portMAX_24_BIT_NUMBER (0xffffffUL)
Definition at line 134 of file port_mpu.h.
portMAX_8_BIT_VALUE
#define portMAX_8_BIT_VALUE ((uint8_t) 0xff)
Definition at line 111 of file port_mpu.h.
portMAX_PRIGROUP_BITS
#define portMAX_PRIGROUP_BITS ((uint8_t) 7)
Definition at line 113 of file port_mpu.h.
portMISSED_COUNTS_FACTOR
#define portMISSED_COUNTS_FACTOR (45UL)
Definition at line 139 of file port_mpu.h.
portMPU_BACKGROUND_ENABLE
#define portMPU_BACKGROUND_ENABLE (1UL << 2UL)
Definition at line 83 of file port_mpu.h.
portMPU_CTRL_REG
#define portMPU_CTRL_REG (* ((volatile uint32_t *) 0xe000ed94))
Definition at line 80 of file port_mpu.h.
portMPU_ENABLE
#define portMPU_ENABLE (0x01UL)
Definition at line 82 of file port_mpu.h.
portMPU_REGION_ATTRIBUTE_REG
#define portMPU_REGION_ATTRIBUTE_REG (* ((volatile uint32_t *) 0xe000edA0))
Definition at line 79 of file port_mpu.h.
portMPU_REGION_BASE_ADDRESS_REG
#define portMPU_REGION_BASE_ADDRESS_REG (* ((volatile uint32_t *) 0xe000ed9C))
Definition at line 78 of file port_mpu.h.
portMPU_REGION_ENABLE
#define portMPU_REGION_ENABLE (0x01UL)
Definition at line 86 of file port_mpu.h.
portMPU_REGION_VALID
#define portMPU_REGION_VALID (0x10UL)
Definition at line 85 of file port_mpu.h.
portMPU_TYPE_REG
#define portMPU_TYPE_REG (* ((volatile uint32_t *) 0xe000ed90))
Definition at line 77 of file port_mpu.h.
portNVIC_IP_REGISTERS_OFFSET_16
#define portNVIC_IP_REGISTERS_OFFSET_16 (0xE000E3F0)
Definition at line 109 of file port_mpu.h.
portNVIC_MEM_FAULT_ENABLE
#define portNVIC_MEM_FAULT_ENABLE (1UL << 16UL)
Definition at line 74 of file port_mpu.h.
portNVIC_PEND_SYSTICK_CLEAR_BIT
#define portNVIC_PEND_SYSTICK_CLEAR_BIT (1UL << 25UL)
Definition at line 95 of file port_mpu.h.
portNVIC_PENDSV_PRI
#define portNVIC_PENDSV_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 16UL)
Definition at line 103 of file port_mpu.h.
portNVIC_PENDSVCLEAR_BIT
#define portNVIC_PENDSVCLEAR_BIT (1UL << 27UL)
Definition at line 94 of file port_mpu.h.
portNVIC_SVC_PRI
#define portNVIC_SVC_PRI (((uint32_t) configMAX_SYSCALL_INTERRUPT_PRIORITY - 1UL) << 24UL)
Definition at line 105 of file port_mpu.h.
portNVIC_SYS_CTRL_STATE_REG
#define portNVIC_SYS_CTRL_STATE_REG (* ((volatile uint32_t *) 0xe000ed24))
Definition at line 73 of file port_mpu.h.
portNVIC_SYSPRI1_REG
#define portNVIC_SYSPRI1_REG (* ((volatile uint32_t *) 0xe000ed1c))
Definition at line 72 of file port_mpu.h.
portNVIC_SYSPRI2_REG
#define portNVIC_SYSPRI2_REG (* ((volatile uint32_t *) 0xe000ed20))
Definition at line 71 of file port_mpu.h.
portNVIC_SYSTICK_CLK_BIT
#define portNVIC_SYSTICK_CLK_BIT (1UL << 2UL)
Definition at line 60 of file port_mpu.h.
portNVIC_SYSTICK_COUNT_FLAG_BIT
#define portNVIC_SYSTICK_COUNT_FLAG_BIT (1UL << 16UL)
Definition at line 93 of file port_mpu.h.
portNVIC_SYSTICK_CTRL_REG
#define portNVIC_SYSTICK_CTRL_REG (* ((volatile uint32_t *) 0xe000e010))
Definition at line 68 of file port_mpu.h.
portNVIC_SYSTICK_CURRENT_VALUE_REG
#define portNVIC_SYSTICK_CURRENT_VALUE_REG (* ((volatile uint32_t *) 0xe000e018))
Definition at line 70 of file port_mpu.h.
portNVIC_SYSTICK_ENABLE_BIT
#define portNVIC_SYSTICK_ENABLE_BIT (1UL << 0UL)
Definition at line 92 of file port_mpu.h.
portNVIC_SYSTICK_INT_BIT
#define portNVIC_SYSTICK_INT_BIT (1UL << 1UL)
Definition at line 91 of file port_mpu.h.
portNVIC_SYSTICK_LOAD_REG
#define portNVIC_SYSTICK_LOAD_REG (* ((volatile uint32_t *) 0xe000e014))
Definition at line 69 of file port_mpu.h.
portNVIC_SYSTICK_PRI
#define portNVIC_SYSTICK_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
Definition at line 104 of file port_mpu.h.
portOFFSET_TO_PC
#define portOFFSET_TO_PC (6)
Definition at line 131 of file port_mpu.h.
portPERIPHERALS_END_ADDRESS
#define portPERIPHERALS_END_ADDRESS 0x5FFFFFFFUL
Definition at line 88 of file port_mpu.h.
portPERIPHERALS_START_ADDRESS
#define portPERIPHERALS_START_ADDRESS 0x40000000UL
Definition at line 87 of file port_mpu.h.
portPRIGROUP_SHIFT
#define portPRIGROUP_SHIFT (8UL)
Definition at line 115 of file port_mpu.h.
portPRIORITY_GROUP_MASK
#define portPRIORITY_GROUP_MASK (0x07UL << 8UL)
Definition at line 114 of file port_mpu.h.
portPRIVILEGED_EXECUTION_START_ADDRESS
#define portPRIVILEGED_EXECUTION_START_ADDRESS (0UL)
Definition at line 84 of file port_mpu.h.
portSTART_ADDRESS_MASK
#define portSTART_ADDRESS_MASK ((StackType_t) 0xfffffffeUL)
Definition at line 143 of file port_mpu.h.
portTOP_BIT_OF_BYTE
#define portTOP_BIT_OF_BYTE ((uint8_t) 0x80)
Definition at line 112 of file port_mpu.h.
portVECTACTIVE_MASK
#define portVECTACTIVE_MASK (0xFFUL)
Definition at line 118 of file port_mpu.h.
Function Documentation
prvGetMPURegionSizeSetting()
static uint32_t prvGetMPURegionSizeSetting (uint32_t ulActualSizeInBytes) [static]
Definition at line 543 of file port_mpu.h.
Referenced by prvSetupMPU(), and vPortStoreTaskMPUSettings().
prvSetupMPU()
static void prvSetupMPU (void) [static]
Definition at line 480 of file port_mpu.h.
References portEXPECTED_MPU_TYPE_VALUE, portGENERAL_PERIPHERALS_REGION, portMPU_BACKGROUND_ENABLE, portMPU_CTRL_REG, portMPU_ENABLE, portMPU_REGION_ATTRIBUTE_REG, portMPU_REGION_BASE_ADDRESS_REG, portMPU_REGION_CACHEABLE_BUFFERABLE, portMPU_REGION_ENABLE, portMPU_REGION_EXECUTE_NEVER, portMPU_REGION_PRIVILEGED_READ_ONLY, portMPU_REGION_PRIVILEGED_READ_WRITE, portMPU_REGION_READ_ONLY, portMPU_REGION_READ_WRITE, portMPU_REGION_VALID, portMPU_TYPE_REG, portNVIC_MEM_FAULT_ENABLE, portNVIC_SYS_CTRL_STATE_REG, portPERIPHERALS_END_ADDRESS, portPERIPHERALS_START_ADDRESS, portPRIVILEGED_FLASH_REGION, portPRIVILEGED_RAM_REGION, portUNPRIVILEGED_FLASH_REGION, and prvGetMPURegionSizeSetting().
Referenced by xPortStartScheduler().
pxPortInitialiseStack()
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters, BaseType_t xRunPrivileged)
Definition at line 217 of file port_mpu.h.
References pdTRUE, portINITIAL_CONTROL_IF_PRIVILEGED, portINITIAL_CONTROL_IF_UNPRIVILEGED, portINITIAL_EXC_RETURN, portINITIAL_XPSR, and portSTART_ADDRESS_MASK.
vPortEnableVFP()
__asm void vPortEnableVFP (void)
Definition at line 552 of file port_mpu.h.
Referenced by xPortStartScheduler().
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 399 of file port_mpu.h.
References configASSERT, and uxCriticalNesting.
vPortEnterCritical()
void vPortEnterCritical (void)
Definition at line 407 of file port_mpu.h.
References configASSERT, portDISABLE_INTERRUPTS, portNVIC_INT_CTRL_REG, portVECTACTIVE_MASK, uxCriticalNesting, vPortResetPrivilege(), and xPortRaisePrivilege().
vPortExitCritical()
void vPortExitCritical (void)
Definition at line 428 of file port_mpu.h.
References configASSERT, portENABLE_INTERRUPTS, uxCriticalNesting, vPortResetPrivilege(), and xPortRaisePrivilege().
vPortResetPrivilege()
void vPortResetPrivilege (BaseType_t xRunningPrivileged)
Definition at line 567 of file port_mpu.h.
References pdTRUE.
Referenced by vPortEnterCritical(), and vPortExitCritical().
vPortRestoreContextOfFirstTask()
void vPortRestoreContextOfFirstTask (void)
Referenced by vPortSVCHandler_C().
vPortSetupTimerInterrupt()
void vPortSetupTimerInterrupt (void)
Definition at line 468 of file port_mpu.h.
References configSYSTICK_CLOCK_HZ, configTICK_RATE_HZ, portNVIC_SYSTICK_CLK_BIT, portNVIC_SYSTICK_CTRL_REG, portNVIC_SYSTICK_CURRENT_VALUE_REG, portNVIC_SYSTICK_ENABLE_BIT, portNVIC_SYSTICK_INT_BIT, and portNVIC_SYSTICK_LOAD_REG.
Referenced by xPortStartScheduler().
vPortStartFirstTask()
void vPortStartFirstTask (void)
Referenced by xPortStartScheduler().
vPortStoreTaskMPUSettings()
void vPortStoreTaskMPUSettings (xMPU_SETTINGS * xMPUSettings, const struct xMEMORY_REGION *const xRegions, StackType_t * pxBottomOfStack, uint32_t ulStackDepth)
Definition at line 579 of file port_mpu.h.
References portMPU_REGION_CACHEABLE_BUFFERABLE, portMPU_REGION_ENABLE, portMPU_REGION_PRIVILEGED_READ_WRITE, portMPU_REGION_READ_WRITE, portMPU_REGION_VALID, portNUM_CONFIGURABLE_REGIONS, portSTACK_REGION, prvGetMPURegionSizeSetting(), MPU_REGION_REGISTERS::ulRegionAttribute, MPU_REGION_REGISTERS::ulRegionBaseAddress, and MPU_SETTINGS::xRegion.
vPortSVCHandler_C()
void vPortSVCHandler_C (uint32_t * pulParam)
Definition at line 256 of file port_mpu.h.
References portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET_BIT, portNVIC_SVC_PRI, portNVIC_SYSPRI1_REG, portOFFSET_TO_PC, portSVC_RAISE_PRIVILEGE, portSVC_START_SCHEDULER, portSVC_YIELD, and vPortRestoreContextOfFirstTask().
xPortRaisePrivilege()
BaseType_t xPortRaisePrivilege (void)
Definition at line 642 of file port_mpu.h.
References control, portSVC_RAISE_PRIVILEGE, and r0.
Referenced by vPortEnterCritical(), and vPortExitCritical().
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 297 of file port_mpu.h.
References __NVIC_PRIO_BITS, configASSERT, configMAX_SYSCALL_INTERRUPT_PRIORITY, portASPEN_AND_LSPEN_BITS, portCORTEX_M7_r0p0_ID, portCORTEX_M7_r0p1_ID, portCPUID, portFIRST_USER_INTERRUPT_NUMBER, portFPCCR, portMAX_8_BIT_VALUE, portMAX_PRIGROUP_BITS, portNVIC_IP_REGISTERS_OFFSET_16, portNVIC_PENDSV_PRI, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, portPRIGROUP_SHIFT, portPRIORITY_GROUP_MASK, portTOP_BIT_OF_BYTE, prvSetupMPU(), uxCriticalNesting, vPortEnableVFP(), vPortSetupTimerInterrupt(), and vPortStartFirstTask().
xPortSysTickHandler()
void xPortSysTickHandler (void)
Definition at line 444 of file port_mpu.h.
References pdFALSE, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET_BIT, and xTaskIncrementTick().
Variable Documentation
uxCriticalNesting
UBaseType_t uxCriticalNesting = 0xaaaaaaaa [static]
Definition at line 199 of file port_mpu.h.
Referenced by vPortEndScheduler(), vPortEnterCritical(), vPortExitCritical(), and xPortStartScheduler().