Dave/Model/APPS/FREERTOS/v4_1_2/Templates/portable/Keil/ARM_CM4F/portmacro_mpu.h File Reference
Data Structures
struct MPU_REGION_REGISTERS
struct MPU_SETTINGS
Macros
#define portCHAR char
#define portFLOAT float
#define portDOUBLE double
#define portLONG long
#define portSHORT short
#define portSTACK_TYPE uint32_t
#define portBASE_TYPE long
#define portMAX_DELAY (TickType_t) 0xffffffffUL
#define portTICK_TYPE_IS_ATOMIC 1
#define portUSING_MPU_WRAPPERS 1
#define portPRIVILEGE_BIT (0x80000000UL)
#define portMPU_REGION_READ_WRITE (0x03UL << 24UL)
#define portMPU_REGION_PRIVILEGED_READ_ONLY (0x05UL << 24UL)
#define portMPU_REGION_READ_ONLY (0x06UL << 24UL)
#define portMPU_REGION_PRIVILEGED_READ_WRITE (0x01UL << 24UL)
#define portMPU_REGION_CACHEABLE_BUFFERABLE (0x07UL << 16UL)
#define portMPU_REGION_EXECUTE_NEVER (0x01UL << 28UL)
#define portUNPRIVILEGED_FLASH_REGION (0UL)
#define portPRIVILEGED_FLASH_REGION (1UL)
#define portPRIVILEGED_RAM_REGION (2UL)
#define portGENERAL_PERIPHERALS_REGION (3UL)
#define portSTACK_REGION (4UL)
#define portFIRST_CONFIGURABLE_REGION (5UL)
#define portLAST_CONFIGURABLE_REGION (7UL)
#define portNUM_CONFIGURABLE_REGIONS ((portLAST_CONFIGURABLE_REGION - portFIRST_CONFIGURABLE_REGION) + 1)
#define portTOTAL_NUM_REGIONS (portNUM_CONFIGURABLE_REGIONS + 1) /* Plus one to make space for the stack region. */
#define portSWITCH_TO_USER_MODE() vPortSwitchToUserMode()
#define portSTACK_GROWTH (-1)
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
#define portBYTE_ALIGNMENT 8
#define portSY_FULL_READ_WRITE (15)
#define portSVC_START_SCHEDULER 0
#define portSVC_YIELD 1
#define portSVC_RAISE_PRIVILEGE 2
#define portYIELD() __asm{ SVC portSVC_YIELD }
#define portYIELD_WITHIN_API()
#define portNVIC_INT_CTRL_REG (* ((volatile uint32_t *) 0xe000ed04))
#define portNVIC_PENDSVSET_BIT (1UL << 28UL)
#define portEND_SWITCHING_ISR(xSwitchRequired) if(xSwitchRequired) portNVIC_INT_CTRL_REG = portNVIC_PENDSVSET_BIT
#define portYIELD_FROM_ISR(x) portEND_SWITCHING_ISR(x)
#define portDISABLE_INTERRUPTS() vPortRaiseBASEPRI()
#define portENABLE_INTERRUPTS() vPortSetBASEPRI(0)
#define portENTER_CRITICAL() vPortEnterCritical()
#define portEXIT_CRITICAL() vPortExitCritical()
#define portSET_INTERRUPT_MASK_FROM_ISR() ulPortRaiseBASEPRI()
#define portCLEAR_INTERRUPT_MASK_FROM_ISR(x) vPortSetBASEPRI(x)
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
#define portRECORD_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) |= (1UL << (uxPriority))
#define portRESET_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) &= ~(1UL << (uxPriority))
#define portGET_HIGHEST_PRIORITY(uxTopPriority, uxReadyPriorities) uxTopPriority = (31UL - (uint32_t) __clz((uxReadyPriorities)))
#define portTASK_FUNCTION_PROTO(vFunction, pvParameters) void vFunction(void *pvParameters)
#define portTASK_FUNCTION(vFunction, pvParameters) void vFunction(void *pvParameters)
#define portNOP()
#define portINLINE __inline
#define portFORCE_INLINE __forceinline
Typedefs
typedef portSTACK_TYPE StackType_t
typedef long BaseType_t
typedef unsigned long UBaseType_t
typedef uint32_t TickType_t
typedef struct MPU_REGION_REGISTERS xMPU_REGION_REGISTERS
typedef struct MPU_SETTINGS xMPU_SETTINGS
Functions
void vPortSwitchToUserMode (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
static portFORCE_INLINE void vPortSetBASEPRI (uint32_t ulBASEPRI)
static portFORCE_INLINE void vPortRaiseBASEPRI (void)
static portFORCE_INLINE void vPortClearBASEPRIFromISR (void)
static portFORCE_INLINE uint32_t ulPortRaiseBASEPRI (void)
static portFORCE_INLINE BaseType_t xPortIsInsideInterrupt (void)
static portFORCE_INLINE void vPortResetPrivilege (BaseType_t xRunningPrivileged)
Macro Definition Documentation
configUSE_PORT_OPTIMISED_TASK_SELECTION
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
Definition at line 159 of file portmacro_mpu.h.
portBASE_TYPE
#define portBASE_TYPE long
Definition at line 54 of file portmacro_mpu.h.
portBYTE_ALIGNMENT
#define portBYTE_ALIGNMENT 8
Definition at line 112 of file portmacro_mpu.h.
portCHAR
#define portCHAR char
Definition at line 48 of file portmacro_mpu.h.
portCLEAR_INTERRUPT_MASK_FROM_ISR
#define portCLEAR_INTERRUPT_MASK_FROM_ISR(x) vPortSetBASEPRI(x)
Definition at line 153 of file portmacro_mpu.h.
portDISABLE_INTERRUPTS
#define portDISABLE_INTERRUPTS() vPortRaiseBASEPRI()
Definition at line 148 of file portmacro_mpu.h.
portDOUBLE
#define portDOUBLE double
Definition at line 50 of file portmacro_mpu.h.
portENABLE_INTERRUPTS
#define portENABLE_INTERRUPTS() vPortSetBASEPRI(0)
Definition at line 149 of file portmacro_mpu.h.
portEND_SWITCHING_ISR
#define portEND_SWITCHING_ISR(xSwitchRequired) if(xSwitchRequired) portNVIC_INT_CTRL_REG = portNVIC_PENDSVSET_BIT
Definition at line 140 of file portmacro_mpu.h.
portENTER_CRITICAL
#define portENTER_CRITICAL() vPortEnterCritical()
Definition at line 150 of file portmacro_mpu.h.
portEXIT_CRITICAL
#define portEXIT_CRITICAL() vPortExitCritical()
Definition at line 151 of file portmacro_mpu.h.
portFIRST_CONFIGURABLE_REGION
#define portFIRST_CONFIGURABLE_REGION (5UL)
Definition at line 89 of file portmacro_mpu.h.
portFLOAT
#define portFLOAT float
Definition at line 49 of file portmacro_mpu.h.
portFORCE_INLINE
#define portFORCE_INLINE __forceinline
Definition at line 198 of file portmacro_mpu.h.
portGENERAL_PERIPHERALS_REGION
#define portGENERAL_PERIPHERALS_REGION (3UL)
Definition at line 87 of file portmacro_mpu.h.
portGET_HIGHEST_PRIORITY
#define portGET_HIGHEST_PRIORITY(uxTopPriority, uxReadyPriorities) uxTopPriority = (31UL - (uint32_t) __clz((uxReadyPriorities)))
Definition at line 175 of file portmacro_mpu.h.
portINLINE
#define portINLINE __inline
Definition at line 195 of file portmacro_mpu.h.
portLAST_CONFIGURABLE_REGION
#define portLAST_CONFIGURABLE_REGION (7UL)
Definition at line 90 of file portmacro_mpu.h.
portLONG
#define portLONG long
Definition at line 51 of file portmacro_mpu.h.
portMAX_DELAY
#define portMAX_DELAY (TickType_t) 0xffffffffUL
Definition at line 65 of file portmacro_mpu.h.
portMPU_REGION_CACHEABLE_BUFFERABLE
#define portMPU_REGION_CACHEABLE_BUFFERABLE (0x07UL << 16UL)
Definition at line 81 of file portmacro_mpu.h.
portMPU_REGION_EXECUTE_NEVER
#define portMPU_REGION_EXECUTE_NEVER (0x01UL << 28UL)
Definition at line 82 of file portmacro_mpu.h.
portMPU_REGION_PRIVILEGED_READ_ONLY
#define portMPU_REGION_PRIVILEGED_READ_ONLY (0x05UL << 24UL)
Definition at line 78 of file portmacro_mpu.h.
portMPU_REGION_PRIVILEGED_READ_WRITE
#define portMPU_REGION_PRIVILEGED_READ_WRITE (0x01UL << 24UL)
Definition at line 80 of file portmacro_mpu.h.
portMPU_REGION_READ_ONLY
#define portMPU_REGION_READ_ONLY (0x06UL << 24UL)
Definition at line 79 of file portmacro_mpu.h.
portMPU_REGION_READ_WRITE
#define portMPU_REGION_READ_WRITE (0x03UL << 24UL)
Definition at line 77 of file portmacro_mpu.h.
portNOP
#define portNOP()
Definition at line 193 of file portmacro_mpu.h.
portNUM_CONFIGURABLE_REGIONS
#define portNUM_CONFIGURABLE_REGIONS ((portLAST_CONFIGURABLE_REGION - portFIRST_CONFIGURABLE_REGION) + 1)
Definition at line 91 of file portmacro_mpu.h.
portNVIC_INT_CTRL_REG
#define portNVIC_INT_CTRL_REG (* ((volatile uint32_t *) 0xe000ed04))
Definition at line 138 of file portmacro_mpu.h.
portNVIC_PENDSVSET_BIT
#define portNVIC_PENDSVSET_BIT (1UL << 28UL)
Definition at line 139 of file portmacro_mpu.h.
portPRIVILEGE_BIT
#define portPRIVILEGE_BIT (0x80000000UL)
Definition at line 75 of file portmacro_mpu.h.
portPRIVILEGED_FLASH_REGION
#define portPRIVILEGED_FLASH_REGION (1UL)
Definition at line 85 of file portmacro_mpu.h.
portPRIVILEGED_RAM_REGION
#define portPRIVILEGED_RAM_REGION (2UL)
Definition at line 86 of file portmacro_mpu.h.
portRECORD_READY_PRIORITY
#define portRECORD_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) |= (1UL << (uxPriority))
Definition at line 170 of file portmacro_mpu.h.
portRESET_READY_PRIORITY
#define portRESET_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) &= ~(1UL << (uxPriority))
Definition at line 171 of file portmacro_mpu.h.
portSET_INTERRUPT_MASK_FROM_ISR
#define portSET_INTERRUPT_MASK_FROM_ISR() ulPortRaiseBASEPRI()
Definition at line 152 of file portmacro_mpu.h.
portSHORT
#define portSHORT short
Definition at line 52 of file portmacro_mpu.h.
portSTACK_GROWTH
#define portSTACK_GROWTH (-1)
Definition at line 110 of file portmacro_mpu.h.
portSTACK_REGION
#define portSTACK_REGION (4UL)
Definition at line 88 of file portmacro_mpu.h.
portSTACK_TYPE
#define portSTACK_TYPE uint32_t
Definition at line 53 of file portmacro_mpu.h.
portSVC_RAISE_PRIVILEGE
#define portSVC_RAISE_PRIVILEGE 2
Definition at line 122 of file portmacro_mpu.h.
portSVC_START_SCHEDULER
#define portSVC_START_SCHEDULER 0
Definition at line 120 of file portmacro_mpu.h.
portSVC_YIELD
#define portSVC_YIELD 1
Definition at line 121 of file portmacro_mpu.h.
portSWITCH_TO_USER_MODE
#define portSWITCH_TO_USER_MODE() vPortSwitchToUserMode()
Definition at line 95 of file portmacro_mpu.h.
portSY_FULL_READ_WRITE
#define portSY_FULL_READ_WRITE (15)
Definition at line 115 of file portmacro_mpu.h.
portTASK_FUNCTION
#define portTASK_FUNCTION(vFunction, pvParameters) void vFunction(void *pvParameters)
Definition at line 184 of file portmacro_mpu.h.
portTASK_FUNCTION_PROTO
#define portTASK_FUNCTION_PROTO(vFunction, pvParameters) void vFunction(void *pvParameters)
Definition at line 183 of file portmacro_mpu.h.
portTICK_PERIOD_MS
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
Definition at line 111 of file portmacro_mpu.h.
portTICK_TYPE_IS_ATOMIC
#define portTICK_TYPE_IS_ATOMIC 1
Definition at line 69 of file portmacro_mpu.h.
portTOTAL_NUM_REGIONS
#define portTOTAL_NUM_REGIONS (portNUM_CONFIGURABLE_REGIONS + 1) /* Plus one to make space for the stack region. */
Definition at line 92 of file portmacro_mpu.h.
portUNPRIVILEGED_FLASH_REGION
#define portUNPRIVILEGED_FLASH_REGION (0UL)
Definition at line 84 of file portmacro_mpu.h.
portUSING_MPU_WRAPPERS
#define portUSING_MPU_WRAPPERS 1
Definition at line 74 of file portmacro_mpu.h.
portYIELD
#define portYIELD() __asm{ SVC portSVC_YIELD }
Definition at line 126 of file portmacro_mpu.h.
portYIELD_FROM_ISR
#define portYIELD_FROM_ISR(x) portEND_SWITCHING_ISR(x)
Definition at line 141 of file portmacro_mpu.h.
portYIELD_WITHIN_API
#define portYIELD_WITHIN_API()
Value:
{ \
    /* Set a PendSV to request a context switch. */ \
    portNVIC_INT_CTRL_REG = portNVIC_PENDSVSET_BIT; \
                                                                                \
    /* Barriers are normally not required but do ensure the code is completely \
    within the specified behaviour for the architecture. */ \
    __dsb(portSY_FULL_READ_WRITE); \
    __isb(portSY_FULL_READ_WRITE); \
}
Definition at line 127 of file portmacro_mpu.h.
Typedef Documentation
BaseType_t
typedef long BaseType_t
Definition at line 56 of file portmacro_mpu.h.
StackType_t
typedef portSTACK_TYPE StackType_t
Definition at line 55 of file portmacro_mpu.h.
TickType_t
typedef uint32_t TickType_t
Definition at line 63 of file portmacro_mpu.h.
UBaseType_t
typedef unsigned long UBaseType_t
Definition at line 57 of file portmacro_mpu.h.
xMPU_REGION_REGISTERS
typedef struct MPU_REGION_REGISTERS xMPU_REGION_REGISTERS
xMPU_SETTINGS
typedef struct MPU_SETTINGS xMPU_SETTINGS
Function Documentation
ulPortRaiseBASEPRI()
static portFORCE_INLINE uint32_t ulPortRaiseBASEPRI (void) [static]
Definition at line 240 of file portmacro_mpu.h.
References basepri, and configMAX_SYSCALL_INTERRUPT_PRIORITY.
vPortClearBASEPRIFromISR()
static portFORCE_INLINE void vPortClearBASEPRIFromISR (void) [static]
Definition at line 228 of file portmacro_mpu.h.
References basepri.
vPortEnterCritical()
void vPortEnterCritical (void)
Definition at line 429 of file port_mpu.h.
References configASSERT, portDISABLE_INTERRUPTS, portNVIC_INT_CTRL_REG, portVECTACTIVE_MASK, uxCriticalNesting, vPortResetPrivilege(), and xPortRaisePrivilege().
vPortExitCritical()
void vPortExitCritical (void)
Definition at line 440 of file port_mpu.h.
References configASSERT, portENABLE_INTERRUPTS, uxCriticalNesting, vPortResetPrivilege(), and xPortRaisePrivilege().
vPortRaiseBASEPRI()
static portFORCE_INLINE void vPortRaiseBASEPRI (void) [static]
Definition at line 213 of file portmacro_mpu.h.
References basepri, and configMAX_SYSCALL_INTERRUPT_PRIORITY.
vPortResetPrivilege()
static portFORCE_INLINE void vPortResetPrivilege (BaseType_t xRunningPrivileged) [static]
Definition at line 283 of file portmacro_mpu.h.
References control, and pdTRUE.
vPortSetBASEPRI()
static portFORCE_INLINE void vPortSetBASEPRI (uint32_t ulBASEPRI) [static]
Definition at line 202 of file portmacro_mpu.h.
References basepri.
vPortSwitchToUserMode()
void vPortSwitchToUserMode (void)
Definition at line 541 of file port_mpu.h.
References control, r0, and r14.
xPortIsInsideInterrupt()
static portFORCE_INLINE BaseType_t xPortIsInsideInterrupt (void) [static]
Definition at line 258 of file portmacro_mpu.h.
References pdFALSE, and pdTRUE.