Dave/Model/APPS/FREERTOS/v4_1_2/Templates/portable/Keil/ARM_CM4F/port_mpu.h File Reference
#include `FREERTOS/FreeRTOS.h`
#include `FREERTOS/task.h`
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define portNVIC_SYSTICK_CTRL_REG (* ((volatile uint32_t *) 0xe000e010))
#define portNVIC_SYSTICK_LOAD_REG (* ((volatile uint32_t *) 0xe000e014))
#define portNVIC_SYSTICK_CURRENT_VALUE_REG (* ((volatile uint32_t *) 0xe000e018))
#define portNVIC_SYSPRI2_REG (*	((volatile uint32_t *) 0xe000ed20))
#define portNVIC_SYSPRI1_REG (* ((volatile uint32_t *) 0xe000ed1c))
#define portNVIC_SYS_CTRL_STATE_REG (* ((volatile uint32_t *) 0xe000ed24))
#define portNVIC_MEM_FAULT_ENABLE (1UL << 16UL)
#define portMPU_TYPE_REG (* ((volatile uint32_t *) 0xe000ed90))
#define portMPU_REGION_BASE_ADDRESS_REG (* ((volatile uint32_t *) 0xe000ed9C))
#define portMPU_REGION_ATTRIBUTE_REG (* ((volatile uint32_t *) 0xe000edA0))
#define portMPU_CTRL_REG (* ((volatile uint32_t *) 0xe000ed94))
#define portEXPECTED_MPU_TYPE_VALUE (8UL << 8UL) /* 8 regions, unified. */
#define portMPU_ENABLE (0x01UL)
#define portMPU_BACKGROUND_ENABLE (1UL << 2UL)
#define portPRIVILEGED_EXECUTION_START_ADDRESS (0UL)
#define portMPU_REGION_VALID (0x10UL)
#define portMPU_REGION_ENABLE (0x01UL)
#define portPERIPHERALS_START_ADDRESS 0x40000000UL
#define portPERIPHERALS_END_ADDRESS 0x5FFFFFFFUL
#define portNVIC_SYSTICK_CLK (0x00000004UL)
#define portNVIC_SYSTICK_INT (0x00000002UL)
#define portNVIC_SYSTICK_ENABLE (0x00000001UL)
#define portNVIC_PENDSV_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 16UL)
#define portNVIC_SYSTICK_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
#define portNVIC_SVC_PRI (((uint32_t) configMAX_SYSCALL_INTERRUPT_PRIORITY - 1UL) << 24UL)
#define portFPCCR ((volatile uint32_t *) 0xe000ef34UL) /* Floating point context control register. */
#define portASPEN_AND_LSPEN_BITS (0x3UL << 30UL)
#define portINITIAL_XPSR (0x01000000UL)
#define portINITIAL_EXC_RETURN (0xfffffffdUL)
#define portINITIAL_CONTROL_IF_UNPRIVILEGED (0x03)
#define portINITIAL_CONTROL_IF_PRIVILEGED (0x02)
#define portFIRST_USER_INTERRUPT_NUMBER (16)
#define portNVIC_IP_REGISTERS_OFFSET_16 (0xE000E3F0)
#define portAIRCR_REG (* ((volatile uint32_t *) 0xE000ED0C))
#define portMAX_8_BIT_VALUE ((uint8_t) 0xff)
#define portTOP_BIT_OF_BYTE ((uint8_t) 0x80)
#define portMAX_PRIGROUP_BITS ((uint8_t) 7)
#define portPRIORITY_GROUP_MASK (0x07UL << 8UL)
#define portPRIGROUP_SHIFT (8UL)
#define portOFFSET_TO_PC (6)
#define portSTART_ADDRESS_MASK ((StackType_t) 0xfffffffeUL)
Functions
static void prvSetupTimerInterrupt (void) PRIVILEGED_FUNCTION
static void prvSetupMPU (void) PRIVILEGED_FUNCTION
static void prvStartFirstTask (void) PRIVILEGED_FUNCTION
static uint32_t prvGetMPURegionSizeSetting (uint32_t ulActualSizeInBytes) PRIVILEGED_FUNCTION
BaseType_t xPortRaisePrivilege (void)
void xPortPendSVHandler (void) PRIVILEGED_FUNCTION
void xPortSysTickHandler (void) PRIVILEGED_FUNCTION
void vPortSVCHandler (void) PRIVILEGED_FUNCTION
static void prvRestoreContextOfFirstTask (void) PRIVILEGED_FUNCTION
void prvSVCHandler (uint32_t *pulRegisters) __attribute__((used)) PRIVILEGED_FUNCTION
static void vPortEnableVFP (void)
static uint32_t prvPortGetIPSR (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters, BaseType_t xRunPrivileged)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
__asm void vPortSwitchToUserMode (void)
void vPortStoreTaskMPUSettings (xMPU_SETTINGS *xMPUSettings, const struct xMEMORY_REGION *const xRegions, StackType_t *pxBottomOfStack, uint32_t ulStackDepth)
Variables
static UBaseType_t uxCriticalNesting = 0xaaaaaaaa
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 36 of file port_mpu.h.
portAIRCR_REG
#define portAIRCR_REG (* ((volatile uint32_t *) 0xE000ED0C))
Definition at line 92 of file port_mpu.h.
portASPEN_AND_LSPEN_BITS
#define portASPEN_AND_LSPEN_BITS (0x3UL << 30UL)
Definition at line 81 of file port_mpu.h.
portEXPECTED_MPU_TYPE_VALUE
#define portEXPECTED_MPU_TYPE_VALUE (8UL << 8UL) /* 8 regions, unified. */
Definition at line 62 of file port_mpu.h.
portFIRST_USER_INTERRUPT_NUMBER
#define portFIRST_USER_INTERRUPT_NUMBER (16)
Definition at line 90 of file port_mpu.h.
portFPCCR
#define portFPCCR ((volatile uint32_t *) 0xe000ef34UL) /* Floating point context control register. */
Definition at line 80 of file port_mpu.h.
portINITIAL_CONTROL_IF_PRIVILEGED
#define portINITIAL_CONTROL_IF_PRIVILEGED (0x02)
Definition at line 87 of file port_mpu.h.
portINITIAL_CONTROL_IF_UNPRIVILEGED
#define portINITIAL_CONTROL_IF_UNPRIVILEGED (0x03)
Definition at line 86 of file port_mpu.h.
portINITIAL_EXC_RETURN
#define portINITIAL_EXC_RETURN (0xfffffffdUL)
Definition at line 85 of file port_mpu.h.
portINITIAL_XPSR
#define portINITIAL_XPSR (0x01000000UL)
Definition at line 84 of file port_mpu.h.
portMAX_8_BIT_VALUE
#define portMAX_8_BIT_VALUE ((uint8_t) 0xff)
Definition at line 93 of file port_mpu.h.
portMAX_PRIGROUP_BITS
#define portMAX_PRIGROUP_BITS ((uint8_t) 7)
Definition at line 95 of file port_mpu.h.
portMPU_BACKGROUND_ENABLE
#define portMPU_BACKGROUND_ENABLE (1UL << 2UL)
Definition at line 64 of file port_mpu.h.
portMPU_CTRL_REG
#define portMPU_CTRL_REG (* ((volatile uint32_t *) 0xe000ed94))
Definition at line 61 of file port_mpu.h.
portMPU_ENABLE
#define portMPU_ENABLE (0x01UL)
Definition at line 63 of file port_mpu.h.
portMPU_REGION_ATTRIBUTE_REG
#define portMPU_REGION_ATTRIBUTE_REG (* ((volatile uint32_t *) 0xe000edA0))
Definition at line 60 of file port_mpu.h.
portMPU_REGION_BASE_ADDRESS_REG
#define portMPU_REGION_BASE_ADDRESS_REG (* ((volatile uint32_t *) 0xe000ed9C))
Definition at line 59 of file port_mpu.h.
portMPU_REGION_ENABLE
#define portMPU_REGION_ENABLE (0x01UL)
Definition at line 67 of file port_mpu.h.
portMPU_REGION_VALID
#define portMPU_REGION_VALID (0x10UL)
Definition at line 66 of file port_mpu.h.
portMPU_TYPE_REG
#define portMPU_TYPE_REG (* ((volatile uint32_t *) 0xe000ed90))
Definition at line 58 of file port_mpu.h.
portNVIC_IP_REGISTERS_OFFSET_16
#define portNVIC_IP_REGISTERS_OFFSET_16 (0xE000E3F0)
Definition at line 91 of file port_mpu.h.
portNVIC_MEM_FAULT_ENABLE
#define portNVIC_MEM_FAULT_ENABLE (1UL << 16UL)
Definition at line 55 of file port_mpu.h.
portNVIC_PENDSV_PRI
#define portNVIC_PENDSV_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 16UL)
Definition at line 75 of file port_mpu.h.
portNVIC_SVC_PRI
#define portNVIC_SVC_PRI (((uint32_t) configMAX_SYSCALL_INTERRUPT_PRIORITY - 1UL) << 24UL)
Definition at line 77 of file port_mpu.h.
portNVIC_SYS_CTRL_STATE_REG
#define portNVIC_SYS_CTRL_STATE_REG (* ((volatile uint32_t *) 0xe000ed24))
Definition at line 54 of file port_mpu.h.
portNVIC_SYSPRI1_REG
#define portNVIC_SYSPRI1_REG (* ((volatile uint32_t *) 0xe000ed1c))
Definition at line 53 of file port_mpu.h.
portNVIC_SYSPRI2_REG
#define portNVIC_SYSPRI2_REG (*	((volatile uint32_t *) 0xe000ed20))
Definition at line 52 of file port_mpu.h.
portNVIC_SYSTICK_CLK
#define portNVIC_SYSTICK_CLK (0x00000004UL)
Definition at line 72 of file port_mpu.h.
portNVIC_SYSTICK_CTRL_REG
#define portNVIC_SYSTICK_CTRL_REG (* ((volatile uint32_t *) 0xe000e010))
Definition at line 49 of file port_mpu.h.
portNVIC_SYSTICK_CURRENT_VALUE_REG
#define portNVIC_SYSTICK_CURRENT_VALUE_REG (* ((volatile uint32_t *) 0xe000e018))
Definition at line 51 of file port_mpu.h.
portNVIC_SYSTICK_ENABLE
#define portNVIC_SYSTICK_ENABLE (0x00000001UL)
Definition at line 74 of file port_mpu.h.
portNVIC_SYSTICK_INT
#define portNVIC_SYSTICK_INT (0x00000002UL)
Definition at line 73 of file port_mpu.h.
portNVIC_SYSTICK_LOAD_REG
#define portNVIC_SYSTICK_LOAD_REG (* ((volatile uint32_t *) 0xe000e014))
Definition at line 50 of file port_mpu.h.
portNVIC_SYSTICK_PRI
#define portNVIC_SYSTICK_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
Definition at line 76 of file port_mpu.h.
portOFFSET_TO_PC
#define portOFFSET_TO_PC (6)
Definition at line 100 of file port_mpu.h.
portPERIPHERALS_END_ADDRESS
#define portPERIPHERALS_END_ADDRESS 0x5FFFFFFFUL
Definition at line 69 of file port_mpu.h.
portPERIPHERALS_START_ADDRESS
#define portPERIPHERALS_START_ADDRESS 0x40000000UL
Definition at line 68 of file port_mpu.h.
portPRIGROUP_SHIFT
#define portPRIGROUP_SHIFT (8UL)
Definition at line 97 of file port_mpu.h.
portPRIORITY_GROUP_MASK
#define portPRIORITY_GROUP_MASK (0x07UL << 8UL)
Definition at line 96 of file port_mpu.h.
portPRIVILEGED_EXECUTION_START_ADDRESS
#define portPRIVILEGED_EXECUTION_START_ADDRESS (0UL)
Definition at line 65 of file port_mpu.h.
portSTART_ADDRESS_MASK
#define portSTART_ADDRESS_MASK ((StackType_t) 0xfffffffeUL)
Definition at line 104 of file port_mpu.h.
portTOP_BIT_OF_BYTE
#define portTOP_BIT_OF_BYTE ((uint8_t) 0x80)
Definition at line 94 of file port_mpu.h.
Function Documentation
prvGetMPURegionSizeSetting()
static uint32_t prvGetMPURegionSizeSetting (uint32_t ulActualSizeInBytes) [static]
Definition at line 630 of file port_mpu.h.
Referenced by prvSetupMPU(), and vPortStoreTaskMPUSettings().
prvPortGetIPSR()
__asm uint32_t prvPortGetIPSR (void) [static]
Definition at line 764 of file port_mpu.h.
References r0, and r14.
prvRestoreContextOfFirstTask()
__asm void prvRestoreContextOfFirstTask (void) [static]
Definition at line 273 of file port_mpu.h.
References basepri, control, msp, psp, pxCurrentTCB, r0, r1, r14, r2, and r3.
Referenced by prvSVCHandler().
prvSetupMPU()
static void prvSetupMPU (void) [static]
Definition at line 567 of file port_mpu.h.
References portEXPECTED_MPU_TYPE_VALUE, portGENERAL_PERIPHERALS_REGION, portMPU_BACKGROUND_ENABLE, portMPU_CTRL_REG, portMPU_ENABLE, portMPU_REGION_ATTRIBUTE_REG, portMPU_REGION_BASE_ADDRESS_REG, portMPU_REGION_CACHEABLE_BUFFERABLE, portMPU_REGION_ENABLE, portMPU_REGION_EXECUTE_NEVER, portMPU_REGION_PRIVILEGED_READ_ONLY, portMPU_REGION_PRIVILEGED_READ_WRITE, portMPU_REGION_READ_ONLY, portMPU_REGION_READ_WRITE, portMPU_REGION_VALID, portMPU_TYPE_REG, portNVIC_MEM_FAULT_ENABLE, portNVIC_SYS_CTRL_STATE_REG, portPERIPHERALS_END_ADDRESS, portPERIPHERALS_START_ADDRESS, portPRIVILEGED_FLASH_REGION, portPRIVILEGED_RAM_REGION, portUNPRIVILEGED_FLASH_REGION, and prvGetMPURegionSizeSetting().
Referenced by xPortStartScheduler().
prvSetupTimerInterrupt()
static void prvSetupTimerInterrupt (void) [static]
Definition at line 529 of file port_mpu.h.
References configCPU_CLOCK_HZ, configTICK_RATE_HZ, portNVIC_SYSTICK_CLK, portNVIC_SYSTICK_CTRL_REG, portNVIC_SYSTICK_CURRENT_VALUE_REG, portNVIC_SYSTICK_ENABLE, portNVIC_SYSTICK_INT, and portNVIC_SYSTICK_LOAD_REG.
Referenced by xPortStartScheduler().
prvStartFirstTask()
__asm void prvStartFirstTask (void) [static]
Definition at line 399 of file port_mpu.h.
References control, msp, portSVC_START_SCHEDULER, and r0.
Referenced by xPortStartScheduler().
prvSVCHandler()
void prvSVCHandler (uint32_t * pulRegisters)
Definition at line 216 of file port_mpu.h.
References control, portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET_BIT, portNVIC_SVC_PRI, portNVIC_SYSPRI1_REG, portOFFSET_TO_PC, portSVC_RAISE_PRIVILEGE, portSVC_START_SCHEDULER, portSVC_YIELD, and prvRestoreContextOfFirstTask().
Referenced by vPortSVCHandler().
pxPortInitialiseStack()
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters, BaseType_t xRunPrivileged)
Definition at line 183 of file port_mpu.h.
References pdTRUE, portINITIAL_CONTROL_IF_PRIVILEGED, portINITIAL_CONTROL_IF_UNPRIVILEGED, portINITIAL_EXC_RETURN, portINITIAL_XPSR, and portSTART_ADDRESS_MASK.
vPortEnableVFP()
static void vPortEnableVFP (void) [static]
Definition at line 552 of file port_mpu.h.
References r0, r1, and r14.
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 425 of file port_mpu.h.
References configASSERT, and uxCriticalNesting.
Referenced by vTaskEndScheduler().
vPortEnterCritical()
void vPortEnterCritical (void)
Definition at line 433 of file port_mpu.h.
References portDISABLE_INTERRUPTS, uxCriticalNesting, vPortResetPrivilege(), and xPortRaisePrivilege().
vPortExitCritical()
void vPortExitCritical (void)
Definition at line 444 of file port_mpu.h.
References configASSERT, portENABLE_INTERRUPTS, uxCriticalNesting, vPortResetPrivilege(), and xPortRaisePrivilege().
vPortStoreTaskMPUSettings()
void vPortStoreTaskMPUSettings (xMPU_SETTINGS * xMPUSettings, const struct xMEMORY_REGION *const xRegions, StackType_t * pxBottomOfStack, uint32_t ulStackDepth)
Definition at line 666 of file port_mpu.h.
References portMPU_REGION_CACHEABLE_BUFFERABLE, portMPU_REGION_ENABLE, portMPU_REGION_PRIVILEGED_READ_WRITE, portMPU_REGION_READ_WRITE, portMPU_REGION_VALID, portNUM_CONFIGURABLE_REGIONS, portSTACK_REGION, prvGetMPURegionSizeSetting(), MPU_REGION_REGISTERS::ulRegionAttribute, MPU_REGION_REGISTERS::ulRegionBaseAddress, and MPU_SETTINGS::xRegion.
vPortSVCHandler()
void vPortSVCHandler (void)
Definition at line 254 of file port_mpu.h.
References msp, prvSVCHandler(), psp, and r0.
vPortSwitchToUserMode()
__asm void vPortSwitchToUserMode (void)
Definition at line 541 of file port_mpu.h.
References control, r0, and r14.
xPortPendSVHandler()
void xPortPendSVHandler (void)
Definition at line 458 of file port_mpu.h.
References basepri, configMAX_SYSCALL_INTERRUPT_PRIORITY, control, psp, pxCurrentTCB, r0, r1, r14, r2, r3, sp, uxCriticalNesting, and vTaskSwitchContext().
xPortRaisePrivilege()
BaseType_t xPortRaisePrivilege (void)
Definition at line 654 of file port_mpu.h.
References control, portSVC_RAISE_PRIVILEGE, and r0.
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 301 of file port_mpu.h.
References __NVIC_PRIO_BITS, configASSERT, configMAX_SYSCALL_INTERRUPT_PRIORITY, portASPEN_AND_LSPEN_BITS, portFIRST_USER_INTERRUPT_NUMBER, portFPCCR, portMAX_8_BIT_VALUE, portMAX_PRIGROUP_BITS, portNVIC_IP_REGISTERS_OFFSET_16, portNVIC_PENDSV_PRI, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, portPRIGROUP_SHIFT, portPRIORITY_GROUP_MASK, portSVC_START_SCHEDULER, portTOP_BIT_OF_BYTE, prvSetupMPU(), prvSetupTimerInterrupt(), prvStartFirstTask(), uxCriticalNesting, vPortEnableVFP(), and vPortSetupTimerInterrupt().
Referenced by vTaskStartScheduler().
xPortSysTickHandler()
void xPortSysTickHandler (void)
Definition at line 508 of file port_mpu.h.
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET_BIT, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskIncrementTick().
Variable Documentation
uxCriticalNesting
UBaseType_t uxCriticalNesting = 0xaaaaaaaa [static]
Definition at line 108 of file port_mpu.h.
Referenced by vPortEndScheduler(), vPortEnterCritical(), vPortExitCritical(), xPortPendSVHandler(), and xPortStartScheduler().