ManagerTask.h File Reference
#include <DAVE.h>
Functions
void Manager_Task (void *pvParameters)
Function Documentation
Manager_Task()
void Manager_Task (void * pvParameters)
Definition at line 7 of file ManagerTask.c.
References notification_semaphore, Queue_id, vQueueAddToRegistry(), vTaskResume(), worker1_id, worker2_id, xQueueSend, and xSemaphoreTake.
Referenced by main().