ManagerTask.c File Reference
#include `ManagerTask.h`
Functions
void Manager_Task (void *pvParameters)
Variables
xSemaphoreHandle notification_semaphore
xTaskHandle worker1_id
xTaskHandle worker2_id
xQueueHandle Queue_id
Function Documentation
Manager_Task()
void Manager_Task (void * pvParameters)
Definition at line 7 of file ManagerTask.c.
References notification_semaphore, Queue_id, vQueueAddToRegistry(), vTaskResume(), worker1_id, worker2_id, xQueueSend, and xSemaphoreTake.
Referenced by main().
Variable Documentation
notification_semaphore
xSemaphoreHandle notification_semaphore
Definition at line 15 of file main.c.
Referenced by Manager_Task(), and myTimerCallback().
Queue_id
xQueueHandle Queue_id
Definition at line 14 of file main.c.
Referenced by Manager_Task().
worker1_id
xTaskHandle worker1_id
Definition at line 19 of file main.c.
Referenced by Manager_Task().
worker2_id
xTaskHandle worker2_id
Definition at line 20 of file main.c.
Referenced by Manager_Task().