Dave/Model/APPS/FREERTOS/v4_1_2/Templates/stream_buffer.h File Reference
Macros
#define xStreamBufferCreate(xBufferSizeBytes, xTriggerLevelBytes) xStreamBufferGenericCreate(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE)
#define xStreamBufferCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pucStreamBufferStorageArea, pxStaticStreamBuffer) xStreamBufferGenericCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE, pucStreamBufferStorageArea, pxStaticStreamBuffer)
Typedefs
typedef void * StreamBufferHandle_t
Functions
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
StreamBufferHandle_t xStreamBufferGenericCreate (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer) PRIVILEGED_FUNCTION
StreamBufferHandle_t xStreamBufferGenericCreateStatic (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer, uint8_t *const pucStreamBufferStorageArea, StaticStreamBuffer_t *const pxStaticStreamBuffer) PRIVILEGED_FUNCTION
Macro Definition Documentation
xStreamBufferCreate
#define xStreamBufferCreate(xBufferSizeBytes, xTriggerLevelBytes) xStreamBufferGenericCreate(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE)
Definition at line 133 of file stream_buffer.h.
xStreamBufferCreateStatic
#define xStreamBufferCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pucStreamBufferStorageArea, pxStaticStreamBuffer) xStreamBufferGenericCreateStatic(xBufferSizeBytes, xTriggerLevelBytes, pdFALSE, pucStreamBufferStorageArea, pxStaticStreamBuffer)
Definition at line 214 of file stream_buffer.h.
Typedef Documentation
StreamBufferHandle_t
typedef void* StreamBufferHandle_t
Type by which stream buffers are referenced. For example, a call to xStreamBufferCreate() returns an StreamBufferHandle_t variable that can then be used as a parameter to xStreamBufferSend(), xStreamBufferReceive(), etc.
Definition at line 64 of file stream_buffer.h.
Function Documentation
vStreamBufferDelete()
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer)
Definition at line 335 of file stream_buffer.c.
References configASSERT, pdFALSE, sbFLAGS_IS_STATICALLY_ALLOCATED, traceSTREAM_BUFFER_DELETE, xSTREAM_BUFFER::ucFlags, and vPortFree().
xStreamBufferBytesAvailable()
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 475 of file stream_buffer.c.
References configASSERT, and prvBytesInBuffer().
xStreamBufferGenericCreate()
StreamBufferHandle_t xStreamBufferGenericCreate (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer)
Definition at line 219 of file stream_buffer.c.
References configASSERT, prvInitialiseNewStreamBuffer(), pvPortMalloc(), sbBYTES_TO_STORE_MESSAGE_LENGTH, traceSTREAM_BUFFER_CREATE, and traceSTREAM_BUFFER_CREATE_FAILED.
xStreamBufferGenericCreateStatic()
StreamBufferHandle_t xStreamBufferGenericCreateStatic (size_t xBufferSizeBytes, size_t xTriggerLevelBytes, BaseType_t xIsMessageBuffer, uint8_t *const pucStreamBufferStorageArea, StaticStreamBuffer_t *const pxStaticStreamBuffer)
xStreamBufferIsEmpty()
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer)
Definition at line 902 of file stream_buffer.c.
References configASSERT, pdFALSE, pdTRUE, xSTREAM_BUFFER::xHead, and xSTREAM_BUFFER::xTail.
xStreamBufferIsFull()
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer)
Definition at line 925 of file stream_buffer.c.
References configASSERT, pdFALSE, pdTRUE, sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, xSTREAM_BUFFER::ucFlags, and xStreamBufferSpacesAvailable().
xStreamBufferReceive()
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait)
Definition at line 691 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvReadMessageFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbRECEIVE_COMPLETED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_STREAM_BUFFER_RECEIVE, traceSTREAM_BUFFER_RECEIVE, traceSTREAM_BUFFER_RECEIVE_FAILED, xSTREAM_BUFFER::ucFlags, xTaskGetCurrentTaskHandle(), xTaskNotifyStateClear(), xTaskNotifyWait(), and xSTREAM_BUFFER::xTaskWaitingToReceive.
xStreamBufferReceiveCompletedFromISR()
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 990 of file stream_buffer.c.
References configASSERT, eNoAction, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskNotifyFromISR.
xStreamBufferReceiveFromISR()
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 795 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvReadMessageFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbRECEIVE_COMPLETED_FROM_ISR, traceSTREAM_BUFFER_RECEIVE_FROM_ISR, and xSTREAM_BUFFER::ucFlags.
xStreamBufferReset()
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer)
Definition at line 368 of file stream_buffer.c.
References configASSERT, pdFAIL, pdFALSE, pdPASS, pdTRUE, prvInitialiseNewStreamBuffer(), xSTREAM_BUFFER::pucBuffer, sbFLAGS_IS_MESSAGE_BUFFER, traceSTREAM_BUFFER_RESET, xSTREAM_BUFFER::ucFlags, xSTREAM_BUFFER::uxStreamBufferNumber, xSTREAM_BUFFER::xLength, xSTREAM_BUFFER::xTaskWaitingToReceive, xSTREAM_BUFFER::xTaskWaitingToSend, and xSTREAM_BUFFER::xTriggerLevelBytes.
xStreamBufferSend()
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait)
Definition at line 487 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, prvBytesInBuffer(), prvWriteMessageToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbSEND_COMPLETED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_STREAM_BUFFER_SEND, traceSTREAM_BUFFER_SEND, traceSTREAM_BUFFER_SEND_FAILED, xSTREAM_BUFFER::ucFlags, vTaskSetTimeOutState(), xStreamBufferSpacesAvailable(), xTaskCheckForTimeOut(), xTaskGetCurrentTaskHandle(), xTaskNotifyStateClear(), xTaskNotifyWait(), xSTREAM_BUFFER::xTaskWaitingToSend, and xSTREAM_BUFFER::xTriggerLevelBytes.
xStreamBufferSendCompletedFromISR()
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 960 of file stream_buffer.c.
References configASSERT, eNoAction, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskNotifyFromISR.
xStreamBufferSendFromISR()
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 588 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvWriteMessageToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbSEND_COMPLETE_FROM_ISR, traceSTREAM_BUFFER_SEND_FROM_ISR, xSTREAM_BUFFER::ucFlags, xStreamBufferSpacesAvailable(), and xSTREAM_BUFFER::xTriggerLevelBytes.
xStreamBufferSetTriggerLevel()
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel)
Definition at line 422 of file stream_buffer.c.
References configASSERT, pdFALSE, pdPASS, and xSTREAM_BUFFER::xTriggerLevelBytes.
xStreamBufferSpacesAvailable()
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 451 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, xSTREAM_BUFFER::xHead, xSTREAM_BUFFER::xLength, and xSTREAM_BUFFER::xTail.
Referenced by xStreamBufferIsFull(), xStreamBufferSend(), and xStreamBufferSendFromISR().