Dave/Model/APPS/CLOCK_XMC1/v4_0_20/Templates/clock_xmc1.h File Reference
#include <xmc_scu.h>
#include <DAVE_Common.h>
#include `clock_xmc1_conf.h`
#include `clock_xmc1_extern.h`
Data Structures
struct CLOCK_XMC1
Configuration structure for CLOCK_XMC1 APP.
Typedefs
typedef struct CLOCK_XMC1 CLOCK_XMC1_t
Configuration structure for CLOCK_XMC1 APP.
Functions
DAVE_APP_VERSION_t CLOCK_XMC1_GetAppVersion (void)
Get CLOCK_XMC1 APP version.
CLOCK_XMC1_STATUS_t CLOCK_XMC1_Init (CLOCK_XMC1_t *handle)
Initializes a CLOCK_XMC1 APP instance.
void CLOCK_XMC1_SetMCLKFrequency (uint32_t freq_khz)
API for ramping up/down the system clock frequency.
enum CLOCK_XMC1_STATUS { CLOCK_XMC1_STATUS_SUCCESS = 0U,
CLOCK_XMC1_STATUS_FAILURE = 1U,
CLOCK_XMC1_STATUS_SUCCESS = 0U,
CLOCK_XMC1_STATUS_FAILURE = 1U
 }
typedef enum CLOCK_XMC1_STATUS CLOCK_XMC1_STATUS_t
Detailed Description
Date
2015-07-08
NOTE: This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
Typedef Documentation
CLOCK_XMC1_STATUS_t
typedef enum CLOCK_XMC1_STATUS CLOCK_XMC1_STATUS_t
CLOCK_XMC1_t
typedef struct CLOCK_XMC1 CLOCK_XMC1_t
Configuration structure for CLOCK_XMC1 APP.
Enumeration Type Documentation
CLOCK_XMC1_STATUS
enum CLOCK_XMC1_STATUS
Enumerator
CLOCK_XMC1_STATUS_SUCCESS APP initialization is success
CLOCK_XMC1_STATUS_FAILURE APP initialization is failure
CLOCK_XMC1_STATUS_SUCCESS APP initialization is success
CLOCK_XMC1_STATUS_FAILURE APP initialization is failure
Definition at line 106 of file clock_xmc1.h.
Function Documentation
CLOCK_XMC1_GetAppVersion()
DAVE_APP_VERSION_t CLOCK_XMC1_GetAppVersion (void)
Get CLOCK_XMC1 APP version.
Returns
DAVE_APP_VERSION_t APP version information (major, minor and patch number)
Description:
The function can be used to check application software compatibility with a specific version of the APP.
Example Usage:
#include <DAVE.h>
int main(void)
{
  DAVE_STATUS_t init_status;
  DAVE_APP_VERSION_t version;
  // Initialize CLOCK_XMC1 APP:
  // SystemCoreClockSetup() is called from SystemInit().
  init_status = DAVE_Init();
 if(DAVE_STATUS_SUCCESS == init_status)
 {
   version = CLOCK_XMC1_GetAppVersion();
   if (version.major != 4U) {
     // Probably, not the right version.
   }
   // More code here
   while(1) {
   }
 }
 return (1);
}
Definition at line 80 of file clock_xmc1.c.
References CLOCK_XMC1_MAJOR_VERSION, CLOCK_XMC1_MINOR_VERSION, CLOCK_XMC1_PATCH_VERSION, DAVE_APP_VERSION::major, DAVE_APP_VERSION::minor, and DAVE_APP_VERSION::patch.
CLOCK_XMC1_Init()
CLOCK_XMC1_STATUS_t CLOCK_XMC1_Init (CLOCK_XMC1_t * handle)
Initializes a CLOCK_XMC1 APP instance.
Parameters
handle address of CLOCK_XMC1 APP handler
Returns
CLOCK_XMC1_STATUS_SUCCESS : if initialization is successful
 CLOCK_XMC1_STATUS_FAILURE : if initialization is failed
Description:
CLOCK_XMC1_Init API is called during initialization of DAVE APPS. This API Initializes GLOBAL_SCU_XMC1 APP for setting the interrupts and user callback registration.
Example Usage:
#include <DAVE.h>
int main(void)
{
  DAVE_STATUS_t status;
  status = DAVE_Init(); // CLOCK_XMC1_Init API is called during initialization of DAVE APPS
  if(DAVE_STATUS_SUCCESS == status)
  {
   // user code
    while(1)
    {
    }
  }
  return (1);
}
Definition at line 93 of file clock_xmc1.c.
References CLOCK_XMC1_STATUS_SUCCESS, CLOCK_XMC1::init_status, XMC_ASSERT, and XMC_SCU_INTERRUPT_EnableEvent().
Referenced by DAVE_Init().
CLOCK_XMC1_SetMCLKFrequency()
void CLOCK_XMC1_SetMCLKFrequency (uint32_t freq_khz)
API for ramping up/down the system clock frequency.
Parameters
target_freq required frequency in Hz.
Range: (DCO1/256) to DC01 when Clock Control Unit (CCU) source is DC01,
 (OSC_HP/256) to OSC_HP when CCU source is OSC_HP (External Crystal/Direct input mode) for XMC14 device.
Returns
none
Description:
The function can be used for ramping up/down the system clock frequency.
Example Usage:
#include <DAVE.h>
int main(void)
{
  DAVE_STATUS_t init_status;
  uint32_t freq_khz = 1000U; // 1MHz is the target frequency
  // Initialize CLOCK_XMC1 APP:
  // SystemCoreClockSetup() is called from SystemInit().
  init_status = DAVE_Init();
 if(DAVE_STATUS_SUCCESS == init_status)
 {
   CLOCK_XMC1_SetMCLKFrequency(freq_khz); // system clock frequency is ramping down to 1 MHz
   // More code here
   while(1) {
   }
 }
 return (1);
}
Definition at line 157 of file clock_xmc1.c.
References XMC_SCU_CLOCK_SetMCLKFrequency().