Dave/Model/APPS/FREERTOS/v4_1_2/Templates/heap_3.h File Reference
#include <stdlib.h>
#include `FreeRTOS.h`
#include `task.h`
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Functions
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 46 of file heap_3.h.
Function Documentation
pvPortMalloc()
void* pvPortMalloc (size_t xWantedSize)
Definition at line 58 of file heap_3.h.
References traceMALLOC, vApplicationMallocFailedHook(), vTaskSuspendAll(), and xTaskResumeAll().
vPortFree()
void vPortFree (void * pv)
Definition at line 83 of file heap_3.h.
References traceFREE, vTaskSuspendAll(), and xTaskResumeAll().