Dave/Model/APPS/FREERTOS/v4_1_2/Templates/tasks.c File Reference
#include <stdlib.h>
#include <string.h>
#include `FreeRTOS.h`
#include `task.h`
#include `timers.h`
#include `stack_macros.h`
Data Structures
struct tskTaskControlBlock
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define taskYIELD_IF_USING_PREEMPTION()
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
#define tskSTACK_FILL_BYTE (0xa5U)
#define tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE ((configSUPPORT_STATIC_ALLOCATION == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1))
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
#define tskSET_NEW_STACKS_TO_KNOWN_VALUE 0
#define tskRUNNING_CHAR ('X')
#define tskBLOCKED_CHAR ('B')
#define tskREADY_CHAR ('R')
#define tskDELETED_CHAR ('D')
#define tskSUSPENDED_CHAR ('S')
#define configIDLE_TASK_NAME `IDLE`
#define taskRECORD_READY_PRIORITY(uxPriority)
#define taskSELECT_HIGHEST_PRIORITY_TASK()
#define taskRESET_READY_PRIORITY(uxPriority)
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
#define taskSWITCH_DELAYED_LISTS()
#define prvAddTaskToReadyList(pxTCB)
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? (TCB_t *) pxCurrentTCB : (TCB_t *) (pxHandle))
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Typedefs
typedef struct tskTaskControlBlock tskTCB
typedef tskTCB TCB_t
Functions
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void)
static void prvInitialiseNewTask (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t ulStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, TCB_t *pxNewTCB, const MemoryRegion_t *const xRegions)
static void prvAddNewTaskToReadyList (TCB_t *pxNewTCB)
void vTaskStartScheduler (void)
void vTaskEndScheduler (void)
void vTaskSuspendAll (void)
BaseType_t xTaskResumeAll (void)
TickType_t xTaskGetTickCount (void)
TickType_t xTaskGetTickCountFromISR (void)
UBaseType_t uxTaskGetNumberOfTasks (void)
char * pcTaskGetName (TaskHandle_t xTaskToQuery)
BaseType_t xTaskIncrementTick (void)
void vTaskSwitchContext (void)
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
void vTaskPlaceOnUnorderedEventList (List_t *pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
void vTaskRemoveFromUnorderedEventList (ListItem_t *pxEventListItem, const TickType_t xItemValue)
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
void vTaskMissedYield (void)
static portTASK_FUNCTION (prvIdleTask, pvParameters)
static void prvInitialiseTaskLists (void)
static void prvCheckTasksWaitingTermination (void)
static void prvResetNextTaskUnblockTime (void)
TickType_t uxTaskResetEventItemValue (void)
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t *pulNotificationValue, TickType_t xTicksToWait)
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue)
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue, BaseType_t *pxHigherPriorityTaskWoken)
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t *pxHigherPriorityTaskWoken)
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely)
Variables
PRIVILEGED_DATA TCB_t *volatile pxCurrentTCB = NULL
static PRIVILEGED_DATA List_t pxReadyTasksLists [configMAX_PRIORITIES]
static PRIVILEGED_DATA List_t xDelayedTaskList1
static PRIVILEGED_DATA List_t xDelayedTaskList2
static PRIVILEGED_DATA List_t *volatile pxDelayedTaskList
static PRIVILEGED_DATA List_t *volatile pxOverflowDelayedTaskList
static PRIVILEGED_DATA List_t xPendingReadyList
static PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) configINITIAL_TICK_COUNT
static PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY
static PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE
static PRIVILEGED_DATA volatile UBaseType_t uxPendedTicks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE
static PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0
static PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U
static PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL
static PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE
Macro Definition Documentation
configIDLE_TASK_NAME
#define configIDLE_TASK_NAME `IDLE`
Definition at line 130 of file tasks.c.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 36 of file tasks.c.
portRESET_READY_PRIORITY
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
Definition at line 173 of file tasks.c.
prvAddTaskToReadyList
#define prvAddTaskToReadyList(pxTCB)
Value:
    traceMOVED_TASK_TO_READY_STATE(pxTCB); \
    taskRECORD_READY_PRIORITY((pxTCB)->uxPriority); \
    vListInsertEnd(&(pxReadyTasksLists[ (pxTCB)->uxPriority ]), &((pxTCB)->xStateListItem)); \
    tracePOST_MOVED_TASK_TO_READY_STATE(pxTCB)
Definition at line 235 of file tasks.c.
prvGetTCBFromHandle
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? (TCB_t *) pxCurrentTCB : (TCB_t *) (pxHandle))
Definition at line 248 of file tasks.c.
taskEVENT_LIST_ITEM_VALUE_IN_USE
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Definition at line 261 of file tasks.c.
taskNOT_WAITING_NOTIFICATION
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
Definition at line 69 of file tasks.c.
taskNOTIFICATION_RECEIVED
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
Definition at line 71 of file tasks.c.
taskRECORD_READY_PRIORITY
#define taskRECORD_READY_PRIORITY(uxPriority)
Value:
    { \
        if((uxPriority) > uxTopReadyPriority) \
        { \
            uxTopReadyPriority = (uxPriority); \
        } \
    } /* taskRECORD_READY_PRIORITY */
Definition at line 141 of file tasks.c.
taskRESET_READY_PRIORITY
#define taskRESET_READY_PRIORITY(uxPriority)
Definition at line 172 of file tasks.c.
taskSELECT_HIGHEST_PRIORITY_TASK
#define taskSELECT_HIGHEST_PRIORITY_TASK()
Value:
    { \
    UBaseType_t uxTopPriority = uxTopReadyPriority; \
                                                                                                        \
        /* Find the highest priority queue that contains ready tasks. */ \
        while(listLIST_IS_EMPTY(&(pxReadyTasksLists[ uxTopPriority ]))) \
        { \
            configASSERT(uxTopPriority); \
            --uxTopPriority; \
        } \
                                                                                                        \
        /* listGET_OWNER_OF_NEXT_ENTRY indexes through the list, so the tasks of \
        the same priority get an equal share of the processor time. */ \
        listGET_OWNER_OF_NEXT_ENTRY(pxCurrentTCB, &(pxReadyTasksLists[ uxTopPriority ])); \
        uxTopReadyPriority = uxTopPriority; \
    } /* taskSELECT_HIGHEST_PRIORITY_TASK */
Definition at line 151 of file tasks.c.
taskSWITCH_DELAYED_LISTS
#define taskSWITCH_DELAYED_LISTS()
Value:
{ \
    List_t *pxTemp; \
                                                                                                    \
    /* The delayed tasks list should be empty when the lists are switched. */ \
    configASSERT((listLIST_IS_EMPTY(pxDelayedTaskList))); \
                                                                                                    \
    pxTemp = pxDelayedTaskList; \
    pxDelayedTaskList = pxOverflowDelayedTaskList; \
    pxOverflowDelayedTaskList = pxTemp; \
    xNumOfOverflows++; \
    prvResetNextTaskUnblockTime(); \
}
Definition at line 215 of file tasks.c.
taskWAITING_NOTIFICATION
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
Definition at line 70 of file tasks.c.
taskYIELD_IF_USING_PREEMPTION
#define taskYIELD_IF_USING_PREEMPTION()
Definition at line 63 of file tasks.c.
tskBLOCKED_CHAR
#define tskBLOCKED_CHAR ('B')
Definition at line 114 of file tasks.c.
tskDELETED_CHAR
#define tskDELETED_CHAR ('D')
Definition at line 116 of file tasks.c.
tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
Definition at line 97 of file tasks.c.
tskREADY_CHAR
#define tskREADY_CHAR ('R')
Definition at line 115 of file tasks.c.
tskRUNNING_CHAR
#define tskRUNNING_CHAR ('X')
Definition at line 113 of file tasks.c.
tskSET_NEW_STACKS_TO_KNOWN_VALUE
#define tskSET_NEW_STACKS_TO_KNOWN_VALUE 0
Definition at line 107 of file tasks.c.
tskSTACK_FILL_BYTE
#define tskSTACK_FILL_BYTE (0xa5U)
Definition at line 77 of file tasks.c.
tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE
#define tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE ((configSUPPORT_STATIC_ALLOCATION == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1))
Definition at line 96 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_AND_TCB
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
Definition at line 99 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_ONLY
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
Definition at line 98 of file tasks.c.
tskSUSPENDED_CHAR
#define tskSUSPENDED_CHAR ('S')
Definition at line 117 of file tasks.c.
Typedef Documentation
TCB_t
typedef tskTCB TCB_t
Definition at line 342 of file tasks.c.
tskTCB
typedef struct tskTaskControlBlock tskTCB
Function Documentation
pcTaskGetName()
char* pcTaskGetName (TaskHandle_t xTaskToQuery)
Definition at line 2268 of file tasks.c.
References configASSERT, tskTaskControlBlock::pcTaskName, and prvGetTCBFromHandle.
portTASK_FUNCTION()
static portTASK_FUNCTION (prvIdleTask , pvParameters) [static]
THIS IS THE RTOS IDLE TASK - WHICH IS CREATED AUTOMATICALLY WHEN THE SCHEDULER IS STARTED.
Definition at line 3223 of file tasks.c.
References configASSERT, configEXPECTED_IDLE_TIME_BEFORE_SLEEP, configPRE_SUPPRESS_TICKS_AND_SLEEP_PROCESSING, listCURRENT_LIST_LENGTH, mtCOVERAGE_TEST_MARKER, portSUPPRESS_TICKS_AND_SLEEP, portTASK_CALLS_SECURE_FUNCTIONS, prvCheckTasksWaitingTermination(), pxReadyTasksLists, taskYIELD, traceLOW_POWER_IDLE_BEGIN, traceLOW_POWER_IDLE_END, tskIDLE_PRIORITY, vTaskSuspendAll(), xNextTaskUnblockTime, xTaskResumeAll(), and xTickCount.
prvAddCurrentTaskToDelayedList()
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely) [static]
Definition at line 4911 of file tasks.c.
References listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, portMAX_DELAY, portRESET_READY_PRIORITY, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, tskTaskControlBlock::ucDelayAborted, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, vListInsert(), vListInsertEnd(), xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, and xTickCount.
Referenced by ulTaskNotifyTake(), vTaskPlaceOnEventList(), vTaskPlaceOnUnorderedEventList(), and xTaskNotifyWait().
prvAddNewTaskToReadyList()
static void prvAddNewTaskToReadyList (TCB_t * pxNewTCB) [static]
Definition at line 1026 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, portSETUP_TCB, prvAddTaskToReadyList, prvInitialiseTaskLists(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_CREATE, uxCurrentNumberOfTasks, tskTaskControlBlock::uxPriority, uxTaskNumber, tskTaskControlBlock::uxTCBNumber, and xSchedulerRunning.
prvCheckTasksWaitingTermination()
static void prvCheckTasksWaitingTermination (void) [static]
THIS FUNCTION IS CALLED FROM THE RTOS IDLE TASK
Definition at line 3467 of file tasks.c.
References listGET_OWNER_OF_HEAD_ENTRY, prvDeleteTCB(), taskENTER_CRITICAL, taskEXIT_CRITICAL, uxCurrentNumberOfTasks, uxDeletedTasksWaitingCleanUp, uxListRemove(), tskTaskControlBlock::xStateListItem, and xTasksWaitingTermination.
Referenced by portTASK_FUNCTION().
prvInitialiseNewTask()
static void prvInitialiseNewTask (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t ulStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, TCB_t * pxNewTCB, const MemoryRegion_t *const xRegions) [static]
Definition at line 822 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, configNUM_THREAD_LOCAL_STORAGE_POINTERS, listSET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, tskTaskControlBlock::pcTaskName, pdFALSE, pdTRUE, portPOINTER_SIZE_TYPE, portPRIVILEGE_BIT, tskTaskControlBlock::pvThreadLocalStoragePointers, pxPortInitialiseStack(), tskTaskControlBlock::pxStack, tskTaskControlBlock::pxTopOfStack, taskNOT_WAITING_NOTIFICATION, tskSTACK_FILL_BYTE, tskTaskControlBlock::ucDelayAborted, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, tskTaskControlBlock::uxBasePriority, tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, vListInitialiseItem(), vPortStoreTaskMPUSettings(), tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
prvInitialiseTaskLists() [1/2]
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void) [static]
Utility task that simply returns pdTRUE if the task referenced by xTask is currently in the Suspended state, or pdFALSE if the task referenced by xTask is in any other state.
Definition at line 439 of file tasks.c.
Referenced by prvAddNewTaskToReadyList().
prvInitialiseTaskLists() [2/2]
static void prvInitialiseTaskLists (void) [static]
Definition at line 3435 of file tasks.c.
References configMAX_PRIORITIES, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, vListInitialise(), xDelayedTaskList1, xDelayedTaskList2, xPendingReadyList, xSuspendedTaskList, and xTasksWaitingTermination.
prvResetNextTaskUnblockTime()
static void prvResetNextTaskUnblockTime (void) [static]
Definition at line 3729 of file tasks.c.
References listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, pdFALSE, portMAX_DELAY, pxDelayedTaskList, and xNextTaskUnblockTime.
Referenced by xTaskGenericNotify(), xTaskRemoveFromEventList(), and xTaskResumeAll().
ulTaskNotifyTake()
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
Definition at line 4414 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_TAKE, traceTASK_NOTIFY_TAKE_BLOCK, tskTaskControlBlock::ucNotifyState, and tskTaskControlBlock::ulNotifiedValue.
uxTaskGetNumberOfTasks()
UBaseType_t uxTaskGetNumberOfTasks (void)
Definition at line 2260 of file tasks.c.
References uxCurrentNumberOfTasks.
uxTaskResetEventItemValue()
TickType_t uxTaskResetEventItemValue (void)
Definition at line 4381 of file tasks.c.
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listSET_LIST_ITEM_VALUE, pxCurrentTCB, tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xEventListItem.
Referenced by xEventGroupSync(), and xEventGroupWaitBits().
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 2020 of file tasks.c.
References pdFALSE, portDISABLE_INTERRUPTS, vPortEndScheduler(), and xSchedulerRunning.
vTaskInternalSetTimeOutState()
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3097 of file tasks.c.
References xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 3168 of file tasks.c.
References pdTRUE, and xYieldPending.
Referenced by prvUnlockQueue().
vTaskNotifyGiveFromISR()
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4792 of file tasks.c.
References configASSERT, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, pxCurrentTCB, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_GIVE_FROM_ISR, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
Definition at line 2909 of file tasks.c.
References configASSERT, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, vListInsert(), and tskTaskControlBlock::xEventListItem.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
vTaskPlaceOnUnorderedEventList()
void vTaskPlaceOnUnorderedEventList (List_t * pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
Definition at line 2926 of file tasks.c.
References configASSERT, listSET_LIST_ITEM_VALUE, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxSchedulerSuspended, vListInsertEnd(), and tskTaskControlBlock::xEventListItem.
Referenced by xEventGroupSync(), and xEventGroupWaitBits().
vTaskRemoveFromUnorderedEventList()
void vTaskRemoveFromUnorderedEventList (ListItem_t * pxEventListItem, const TickType_t xItemValue)
Definition at line 3051 of file tasks.c.
References configASSERT, listGET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xStateListItem, and xYieldPending.
Referenced by vEventGroupDelete(), and xEventGroupSetBits().
vTaskSetTimeOutState()
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3085 of file tasks.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xStreamBufferSend().
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1900 of file tasks.c.
References configASSERT, configIDLE_TASK_NAME, configMINIMAL_STACK_SIZE, errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portCONFIGURE_TIMER_FOR_RUN_TIME_STATS, portDISABLE_INTERRUPTS, portMAX_DELAY, portPRIVILEGE_BIT, pxCurrentTCB, tskIDLE_PRIORITY, xIdleTaskHandle, xNextTaskUnblockTime, xPortStartScheduler(), xSchedulerRunning, xTickCount, and xTimerCreateTimerTask().
Referenced by main().
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 2031 of file tasks.c.
References uxSchedulerSuspended.
Referenced by prvProcessTimerOrBlockTask(), pvPortMalloc(), vEventGroupDelete(), vPortFree(), xEventGroupSetBits(), xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 2850 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, pxCurrentTCB, taskCHECK_FOR_STACK_OVERFLOW, taskSELECT_HIGHEST_PRIORITY_TASK, traceTASK_SWITCHED_IN, traceTASK_SWITCHED_OUT, uxSchedulerSuspended, and xYieldPending.
Referenced by xPortPendSVHandler().
xTaskCheckForTimeOut()
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
Definition at line 3105 of file tasks.c.
References configASSERT, pdFALSE, pdTRUE, portMAX_DELAY, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::ucDelayAborted, vTaskInternalSetTimeOutState(), xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), xQueueSemaphoreTake(), and xStreamBufferSend().
xTaskGenericNotify()
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue)
Definition at line 4562 of file tasks.c.
References configASSERT, eIncrement, eNoAction, eSetBits, eSetValueWithoutOverwrite, eSetValueWithOverwrite, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, taskYIELD_IF_USING_PREEMPTION, traceTASK_NOTIFY, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
xTaskGenericNotifyFromISR()
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4668 of file tasks.c.
References configASSERT, eIncrement, eNoAction, eSetBits, eSetValueWithoutOverwrite, eSetValueWithOverwrite, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, pxCurrentTCB, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_FROM_ISR, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
xTaskGetTickCount()
TickType_t xTaskGetTickCount (void)
Definition at line 2214 of file tasks.c.
References portTICK_TYPE_ENTER_CRITICAL, portTICK_TYPE_EXIT_CRITICAL, and xTickCount.
Referenced by prvSampleTimeNow().
xTaskGetTickCountFromISR()
TickType_t xTaskGetTickCountFromISR (void)
Definition at line 2229 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portTICK_TYPE_CLEAR_INTERRUPT_MASK_FROM_ISR, portTICK_TYPE_SET_INTERRUPT_MASK_FROM_ISR, and xTickCount.
xTaskIncrementTick()
BaseType_t xTaskIncrementTick (void)
Definition at line 2588 of file tasks.c.
References listCURRENT_LIST_LENGTH, listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portMAX_DELAY, prvAddTaskToReadyList, pxCurrentTCB, pxDelayedTaskList, pxReadyTasksLists, taskSWITCH_DELAYED_LISTS, traceTASK_INCREMENT_TICK, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xTickCount, and xYieldPending.
Referenced by xPortSysTickHandler().
xTaskNotifyStateClear()
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
Definition at line 4881 of file tasks.c.
References pdFAIL, pdPASS, prvGetTCBFromHandle, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskNOTIFICATION_RECEIVED, and tskTaskControlBlock::ucNotifyState.
Referenced by xStreamBufferReceive(), and xStreamBufferSend().
xTaskNotifyWait()
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t * pulNotificationValue, TickType_t xTicksToWait)
Definition at line 4482 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_WAIT, traceTASK_NOTIFY_WAIT_BLOCK, tskTaskControlBlock::ucNotifyState, and tskTaskControlBlock::ulNotifiedValue.
Referenced by xStreamBufferReceive(), and xStreamBufferSend().
xTaskRemoveFromEventList()
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
Definition at line 2983 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
Referenced by prvNotifyQueueSetContainer(), prvUnlockQueue(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueGiveFromISR(), xQueuePeek(), xQueueReceive(), xQueueReceiveFromISR(), and xQueueSemaphoreTake().
xTaskResumeAll()
BaseType_t xTaskResumeAll (void)
Definition at line 2104 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, uxCurrentNumberOfTasks, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, xTaskIncrementTick(), and xYieldPending.
Referenced by prvProcessTimerOrBlockTask(), pvPortMalloc(), vEventGroupDelete(), vPortFree(), xEventGroupSetBits(), xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
Variable Documentation
pxCurrentTCB
PRIVILEGED_DATA TCB_t* volatile pxCurrentTCB = NULL
Definition at line 347 of file tasks.c.
pxDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxDelayedTaskList [static]
Definition at line 353 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), prvResetNextTaskUnblockTime(), and xTaskIncrementTick().
pxOverflowDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxOverflowDelayedTaskList [static]
Definition at line 354 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), and prvInitialiseTaskLists().
pxReadyTasksLists
PRIVILEGED_DATA List_t pxReadyTasksLists[configMAX_PRIORITIES] [static]
Definition at line 350 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvInitialiseTaskLists(), and xTaskIncrementTick().
uxCurrentNumberOfTasks
PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U [static]
Definition at line 371 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), prvCheckTasksWaitingTermination(), uxTaskGetNumberOfTasks(), and xTaskResumeAll().
uxPendedTicks
PRIVILEGED_DATA volatile UBaseType_t uxPendedTicks = (UBaseType_t) 0U [static]
Definition at line 375 of file tasks.c.
Referenced by xTaskIncrementTick(), and xTaskResumeAll().
uxSchedulerSuspended
PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE [static]
Definition at line 390 of file tasks.c.
Referenced by vTaskNotifyGiveFromISR(), vTaskPlaceOnUnorderedEventList(), vTaskRemoveFromUnorderedEventList(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskGenericNotifyFromISR(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
uxTaskNumber
PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U [static]
Definition at line 378 of file tasks.c.
Referenced by prvAddNewTaskToReadyList().
uxTopReadyPriority
PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY [static]
Definition at line 373 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList().
xDelayedTaskList1
PRIVILEGED_DATA List_t xDelayedTaskList1 [static]
Definition at line 351 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xDelayedTaskList2
PRIVILEGED_DATA List_t xDelayedTaskList2 [static]
Definition at line 352 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xIdleTaskHandle
PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL [static]
Definition at line 380 of file tasks.c.
Referenced by vTaskStartScheduler().
xNextTaskUnblockTime
PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U [static]
Definition at line 379 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), prvResetNextTaskUnblockTime(), vTaskStartScheduler(), and xTaskIncrementTick().
xNumOfOverflows
PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0 [static]
Definition at line 377 of file tasks.c.
Referenced by vTaskInternalSetTimeOutState(), vTaskSetTimeOutState(), and xTaskCheckForTimeOut().
xPendingReadyList
PRIVILEGED_DATA List_t xPendingReadyList [static]
Definition at line 355 of file tasks.c.
Referenced by prvInitialiseTaskLists(), vTaskNotifyGiveFromISR(), xTaskGenericNotifyFromISR(), xTaskRemoveFromEventList(), and xTaskResumeAll().
xSchedulerRunning
PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE [static]
Definition at line 374 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), vTaskEndScheduler(), and vTaskStartScheduler().
xTickCount
PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) configINITIAL_TICK_COUNT [static]
Definition at line 372 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), vTaskInternalSetTimeOutState(), vTaskSetTimeOutState(), vTaskStartScheduler(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskGetTickCountFromISR(), and xTaskIncrementTick().
xYieldPending
PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE [static]
Definition at line 376 of file tasks.c.
Referenced by vTaskMissedYield(), vTaskNotifyGiveFromISR(), vTaskRemoveFromUnorderedEventList(), vTaskSwitchContext(), xTaskGenericNotifyFromISR(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().