Dave/Model/APPS/FREERTOS/v4_1_2/Templates/queue.h File Reference
Macros
#define queueSEND_TO_BACK ((BaseType_t) 0)
#define queueSEND_TO_FRONT ((BaseType_t) 1)
#define queueOVERWRITE ((BaseType_t) 2)
#define queueQUEUE_TYPE_BASE ((uint8_t) 0U)
#define queueQUEUE_TYPE_SET ((uint8_t) 0U)
#define queueQUEUE_TYPE_MUTEX ((uint8_t) 1U)
#define queueQUEUE_TYPE_COUNTING_SEMAPHORE ((uint8_t) 2U)
#define queueQUEUE_TYPE_BINARY_SEMAPHORE ((uint8_t) 3U)
#define queueQUEUE_TYPE_RECURSIVE_MUTEX ((uint8_t) 4U)
#define xQueueSendToFront(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
#define xQueueSendToBack(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueSend(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueOverwrite(xQueue, pvItemToQueue) xQueueGenericSend((xQueue), (pvItemToQueue), 0, queueOVERWRITE)
#define xQueueSendToFrontFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_FRONT)
#define xQueueSendToBackFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
#define xQueueOverwriteFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueOVERWRITE)
#define xQueueSendFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
#define xQueueReset(xQueue) xQueueGenericReset(xQueue, pdFALSE)
Typedefs
typedef void * QueueHandle_t
typedef void * QueueSetHandle_t
typedef void * QueueSetMemberHandle_t
Functions
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition) PRIVILEGED_FUNCTION
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer) PRIVILEGED_FUNCTION
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
void vQueueDelete (QueueHandle_t xQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition) PRIVILEGED_FUNCTION
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueCRSendFromISR (QueueHandle_t xQueue, const void *pvItemToQueue, BaseType_t xCoRoutinePreviouslyWoken)
BaseType_t xQueueCRReceiveFromISR (QueueHandle_t xQueue, void *pvBuffer, BaseType_t *pxTaskWoken)
BaseType_t xQueueCRSend (QueueHandle_t xQueue, const void *pvItemToQueue, TickType_t xTicksToWait)
BaseType_t xQueueCRReceive (QueueHandle_t xQueue, void *pvBuffer, TickType_t xTicksToWait)
QueueHandle_t xQueueCreateMutex (const uint8_t ucQueueType) PRIVILEGED_FUNCTION
QueueHandle_t xQueueCreateMutexStatic (const uint8_t ucQueueType, StaticQueue_t *pxStaticQueue) PRIVILEGED_FUNCTION
QueueHandle_t xQueueCreateCountingSemaphore (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount) PRIVILEGED_FUNCTION
QueueHandle_t xQueueCreateCountingSemaphoreStatic (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount, StaticQueue_t *pxStaticQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
void * xQueueGetMutexHolder (QueueHandle_t xSemaphore) PRIVILEGED_FUNCTION
void * xQueueGetMutexHolderFromISR (QueueHandle_t xSemaphore) PRIVILEGED_FUNCTION
BaseType_t xQueueTakeMutexRecursive (QueueHandle_t xMutex, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
BaseType_t xQueueGiveMutexRecursive (QueueHandle_t pxMutex) PRIVILEGED_FUNCTION
QueueSetHandle_t xQueueCreateSet (const UBaseType_t uxEventQueueLength) PRIVILEGED_FUNCTION
BaseType_t xQueueAddToSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet) PRIVILEGED_FUNCTION
BaseType_t xQueueRemoveFromSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet) PRIVILEGED_FUNCTION
QueueSetMemberHandle_t xQueueSelectFromSet (QueueSetHandle_t xQueueSet, const TickType_t xTicksToWait) PRIVILEGED_FUNCTION
QueueSetMemberHandle_t xQueueSelectFromSetFromISR (QueueSetHandle_t xQueueSet) PRIVILEGED_FUNCTION
void vQueueWaitForMessageRestricted (QueueHandle_t xQueue, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue) PRIVILEGED_FUNCTION
void vQueueSetQueueNumber (QueueHandle_t xQueue, UBaseType_t uxQueueNumber) PRIVILEGED_FUNCTION
UBaseType_t uxQueueGetQueueNumber (QueueHandle_t xQueue) PRIVILEGED_FUNCTION
uint8_t ucQueueGetQueueType (QueueHandle_t xQueue) PRIVILEGED_FUNCTION
Macro Definition Documentation
queueOVERWRITE
#define queueOVERWRITE ((BaseType_t) 2)
Definition at line 66 of file queue.h.
queueQUEUE_TYPE_BASE
#define queueQUEUE_TYPE_BASE ((uint8_t) 0U)
Definition at line 69 of file queue.h.
queueQUEUE_TYPE_BINARY_SEMAPHORE
#define queueQUEUE_TYPE_BINARY_SEMAPHORE ((uint8_t) 3U)
Definition at line 73 of file queue.h.
queueQUEUE_TYPE_COUNTING_SEMAPHORE
#define queueQUEUE_TYPE_COUNTING_SEMAPHORE ((uint8_t) 2U)
Definition at line 72 of file queue.h.
queueQUEUE_TYPE_MUTEX
#define queueQUEUE_TYPE_MUTEX ((uint8_t) 1U)
Definition at line 71 of file queue.h.
queueQUEUE_TYPE_RECURSIVE_MUTEX
#define queueQUEUE_TYPE_RECURSIVE_MUTEX ((uint8_t) 4U)
Definition at line 74 of file queue.h.
queueQUEUE_TYPE_SET
#define queueQUEUE_TYPE_SET ((uint8_t) 0U)
Definition at line 70 of file queue.h.
queueSEND_TO_BACK
#define queueSEND_TO_BACK ((BaseType_t) 0)
Definition at line 64 of file queue.h.
queueSEND_TO_FRONT
#define queueSEND_TO_FRONT ((BaseType_t) 1)
Definition at line 65 of file queue.h.
xQueueOverwrite
#define xQueueOverwrite(xQueue, pvItemToQueue) xQueueGenericSend((xQueue), (pvItemToQueue), 0, queueOVERWRITE)
Definition at line 561 of file queue.h.
xQueueOverwriteFromISR
#define xQueueOverwriteFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueOVERWRITE)
Definition at line 1141 of file queue.h.
xQueueReset
#define xQueueReset(xQueue) xQueueGenericReset(xQueue, pdFALSE)
Definition at line 1432 of file queue.h.
xQueueSend
#define xQueueSend(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 478 of file queue.h.
xQueueSendFromISR
#define xQueueSendFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
Definition at line 1215 of file queue.h.
xQueueSendToBack
#define xQueueSendToBack(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 394 of file queue.h.
xQueueSendToBackFromISR
#define xQueueSendToBackFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
Definition at line 1054 of file queue.h.
xQueueSendToFront
#define xQueueSendToFront(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
Definition at line 312 of file queue.h.
xQueueSendToFrontFromISR
#define xQueueSendToFrontFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_FRONT)
Definition at line 983 of file queue.h.
Typedef Documentation
QueueHandle_t
typedef void* QueueHandle_t
Type by which queues are referenced. For example, a call to xQueueCreate() returns an QueueHandle_t variable that can then be used as a parameter to xQueueSend(), xQueueReceive(), etc.
Definition at line 46 of file queue.h.
QueueSetHandle_t
typedef void* QueueSetHandle_t
Type by which queue sets are referenced. For example, a call to xQueueCreateSet() returns an xQueueSet variable that can then be used as a parameter to xQueueSelectFromSet(), xQueueAddToSet(), etc.
Definition at line 53 of file queue.h.
QueueSetMemberHandle_t
typedef void* QueueSetMemberHandle_t
Queue sets can contain both queues and semaphores, so the QueueSetMemberHandle_t is defined as a type to be used where a parameter or return value can be either an QueueHandle_t or an SemaphoreHandle_t.
Definition at line 60 of file queue.h.
Function Documentation
ucQueueGetQueueType()
uint8_t ucQueueGetQueueType (QueueHandle_t xQueue)
Definition at line 2005 of file queue.c.
References xQueue.
uxQueueGetQueueNumber()
UBaseType_t uxQueueGetQueueNumber (QueueHandle_t xQueue)
Definition at line 1985 of file queue.c.
References xQueue.
uxQueueMessagesWaiting()
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
Definition at line 1895 of file queue.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, and xQueue.
uxQueueMessagesWaitingFromISR()
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
Definition at line 1929 of file queue.c.
References configASSERT, and xQueue.
uxQueueSpacesAvailable()
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
Definition at line 1911 of file queue.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, and xQueue.
vQueueDelete()
void vQueueDelete (QueueHandle_t xQueue)
Definition at line 1941 of file queue.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, traceQUEUE_DELETE, vPortFree(), vQueueUnregisterQueue(), and xQueue.
vQueueSetQueueNumber()
void vQueueSetQueueNumber (QueueHandle_t xQueue, UBaseType_t uxQueueNumber)
Definition at line 1995 of file queue.c.
References xQueue.
vQueueWaitForMessageRestricted()
void vQueueWaitForMessageRestricted (QueueHandle_t xQueue, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
Definition at line 2701 of file queue.c.
References mtCOVERAGE_TEST_MARKER, prvLockQueue, prvUnlockQueue(), QueueDefinition::uxMessagesWaiting, vTaskPlaceOnEventListRestricted(), xQueue, and QueueDefinition::xTasksWaitingToReceive.
Referenced by prvProcessTimerOrBlockTask().
xQueueAddToSet()
BaseType_t xQueueAddToSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
Definition at line 2751 of file queue.c.
References pdFAIL, pdPASS, taskENTER_CRITICAL, and taskEXIT_CRITICAL.
xQueueCreateCountingSemaphore()
QueueHandle_t xQueueCreateCountingSemaphore (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount)
Definition at line 699 of file queue.c.
References configASSERT, queueQUEUE_TYPE_COUNTING_SEMAPHORE, queueSEMAPHORE_QUEUE_ITEM_LENGTH, traceCREATE_COUNTING_SEMAPHORE, traceCREATE_COUNTING_SEMAPHORE_FAILED, and xQueueGenericCreate().
xQueueCreateCountingSemaphoreStatic()
QueueHandle_t xQueueCreateCountingSemaphoreStatic (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount, StaticQueue_t * pxStaticQueue)
xQueueCreateMutex()
QueueHandle_t xQueueCreateMutex (const uint8_t ucQueueType)
Definition at line 482 of file queue.c.
References prvInitialiseMutex(), and xQueueGenericCreate().
xQueueCreateMutexStatic()
QueueHandle_t xQueueCreateMutexStatic (const uint8_t ucQueueType, StaticQueue_t * pxStaticQueue)
xQueueCreateSet()
QueueSetHandle_t xQueueCreateSet (const UBaseType_t uxEventQueueLength)
Definition at line 2737 of file queue.c.
References queueQUEUE_TYPE_SET, and xQueueGenericCreate().
xQueueCRReceive()
BaseType_t xQueueCRReceive (QueueHandle_t xQueue, void * pvBuffer, TickType_t xTicksToWait)
xQueueCRReceiveFromISR()
BaseType_t xQueueCRReceiveFromISR (QueueHandle_t xQueue, void * pvBuffer, BaseType_t * pxTaskWoken)
xQueueCRSend()
BaseType_t xQueueCRSend (QueueHandle_t xQueue, const void * pvItemToQueue, TickType_t xTicksToWait)
xQueueCRSendFromISR()
BaseType_t xQueueCRSendFromISR (QueueHandle_t xQueue, const void * pvItemToQueue, BaseType_t xCoRoutinePreviouslyWoken)
xQueueGenericReset()
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
Definition at line 247 of file queue.c.
References configASSERT, QueueDefinition::cRxLock, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::pcWriteTo, pdFALSE, pdPASS, queueUNLOCKED, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vListInitialise(), xQueue, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by prvInitialiseNewQueue().
xQueueGenericSend()
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
Definition at line 725 of file queue.c.
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataToQueue(), prvIsQueueFull(), prvLockQueue, prvNotifyQueueSetContainer(), prvUnlockQueue(), QueueDefinition::pxQueueSetContainer, queueOVERWRITE, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_SEND, traceQUEUE_SEND, traceQUEUE_SEND_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by prvInitialiseMutex(), and xQueueGiveMutexRecursive().
xQueueGenericSendFromISR()
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
Definition at line 923 of file queue.c.
References configASSERT, QueueDefinition::cTxLock, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataToQueue(), prvNotifyQueueSetContainer(), QueueDefinition::pxQueueSetContainer, queueOVERWRITE, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, xQueue, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
xQueueGetMutexHolder()
void* xQueueGetMutexHolder (QueueHandle_t xSemaphore)
Definition at line 518 of file queue.c.
References pxMutexHolder, queueQUEUE_IS_MUTEX, taskENTER_CRITICAL, taskEXIT_CRITICAL, and uxQueueType.
xQueueGetMutexHolderFromISR()
void* xQueueGetMutexHolderFromISR (QueueHandle_t xSemaphore)
Definition at line 548 of file queue.c.
References configASSERT, pxMutexHolder, queueQUEUE_IS_MUTEX, and uxQueueType.
xQueueGiveFromISR()
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1074 of file queue.c.
References configASSERT, QueueDefinition::cTxLock, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvNotifyQueueSetContainer(), QueueDefinition::pxQueueSetContainer, queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, xQueue, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
xQueueGiveMutexRecursive()
BaseType_t xQueueGiveMutexRecursive (QueueHandle_t pxMutex)
Definition at line 574 of file queue.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, queueMUTEX_GIVE_BLOCK_TIME, queueSEND_TO_BACK, traceGIVE_MUTEX_RECURSIVE, traceGIVE_MUTEX_RECURSIVE_FAILED, QueueDefinition::u, QueueDefinition::uxRecursiveCallCount, xQueueGenericSend(), and xTaskGetCurrentTaskHandle().
xQueueIsQueueEmptyFromISR()
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
Definition at line 2278 of file queue.c.
References configASSERT, pdFALSE, pdTRUE, and xQueue.
xQueueIsQueueFullFromISR()
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Definition at line 2317 of file queue.c.
References configASSERT, pdFALSE, pdTRUE, and xQueue.
xQueuePeek()
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1600 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcReadFrom, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_PEEK, traceQUEUE_PEEK, traceQUEUE_PEEK_FAILED, QueueDefinition::u, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), and QueueDefinition::xTasksWaitingToReceive.
xQueuePeekFromISR()
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
Definition at line 1841 of file queue.c.
References configASSERT, QueueDefinition::pcReadFrom, pdFAIL, pdPASS, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), traceQUEUE_PEEK_FROM_ISR, traceQUEUE_PEEK_FROM_ISR_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, and xQueue.
xQueueReceive()
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1239 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by prvProcessReceivedCommands(), UART_Task(), worker1_task(), worker2_task(), and xQueueSelectFromSet().
xQueueReceiveFromISR()
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1750 of file queue.c.
References configASSERT, QueueDefinition::cRxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), queueUNLOCKED, traceQUEUE_RECEIVE_FROM_ISR, traceQUEUE_RECEIVE_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, xQueue, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueSelectFromSetFromISR().
xQueueRemoveFromSet()
BaseType_t xQueueRemoveFromSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
Definition at line 2784 of file queue.c.
References pdFAIL, pdPASS, QueueDefinition::pxQueueSetContainer, taskENTER_CRITICAL, taskEXIT_CRITICAL, and QueueDefinition::uxMessagesWaiting.
xQueueSelectFromSet()
QueueSetMemberHandle_t xQueueSelectFromSet (QueueSetHandle_t xQueueSet, const TickType_t xTicksToWait)
Definition at line 2820 of file queue.c.
References xQueueReceive().
xQueueSelectFromSetFromISR()
QueueSetMemberHandle_t xQueueSelectFromSetFromISR (QueueSetHandle_t xQueueSet)
Definition at line 2833 of file queue.c.
References xQueueReceiveFromISR().
xQueueSemaphoreTake()
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
Definition at line 1381 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvGetDisinheritPriorityAfterTimeout(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), pvTaskIncrementMutexHeldCount(), queueQUEUE_IS_MUTEX, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskPriorityDisinheritAfterTimeout(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskPriorityInherit(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueTakeMutexRecursive().
xQueueTakeMutexRecursive()
BaseType_t xQueueTakeMutexRecursive (QueueHandle_t xMutex, TickType_t xTicksToWait)
Definition at line 629 of file queue.c.
References configASSERT, pdFAIL, pdPASS, traceTAKE_MUTEX_RECURSIVE, traceTAKE_MUTEX_RECURSIVE_FAILED, QueueDefinition::u, QueueDefinition::uxRecursiveCallCount, xQueueSemaphoreTake(), and xTaskGetCurrentTaskHandle().