Dave/Model/APPS/FREERTOS/v4_1_2/Templates/task.h File Reference
#include `list.h`
Data Structures
struct xTIME_OUT
struct xMEMORY_REGION
struct xTASK_PARAMETERS
struct xTASK_STATUS
Macros
#define tskKERNEL_VERSION_NUMBER `V10.0.1`
#define tskKERNEL_VERSION_MAJOR 10
#define tskKERNEL_VERSION_MINOR 0
#define tskKERNEL_VERSION_BUILD 1
#define tskIDLE_PRIORITY ((UBaseType_t) 0U)
#define taskYIELD() portYIELD()
#define taskENTER_CRITICAL() portENTER_CRITICAL()
#define taskENTER_CRITICAL_FROM_ISR() portSET_INTERRUPT_MASK_FROM_ISR()
#define taskEXIT_CRITICAL() portEXIT_CRITICAL()
#define taskEXIT_CRITICAL_FROM_ISR(x) portCLEAR_INTERRUPT_MASK_FROM_ISR(x)
#define taskDISABLE_INTERRUPTS() portDISABLE_INTERRUPTS()
#define taskENABLE_INTERRUPTS() portENABLE_INTERRUPTS()
#define taskSCHEDULER_SUSPENDED ((BaseType_t) 0)
#define taskSCHEDULER_NOT_STARTED ((BaseType_t) 1)
#define taskSCHEDULER_RUNNING ((BaseType_t) 2)
#define xTaskNotify(xTaskToNotify, ulValue, eAction) xTaskGenericNotify((xTaskToNotify), (ulValue), (eAction), NULL)
#define xTaskNotifyAndQuery(xTaskToNotify, ulValue, eAction, pulPreviousNotifyValue) xTaskGenericNotify((xTaskToNotify), (ulValue), (eAction), (pulPreviousNotifyValue))
#define xTaskNotifyFromISR(xTaskToNotify, ulValue, eAction, pxHigherPriorityTaskWoken) xTaskGenericNotifyFromISR((xTaskToNotify), (ulValue), (eAction), NULL, (pxHigherPriorityTaskWoken))
#define xTaskNotifyAndQueryFromISR(xTaskToNotify, ulValue, eAction, pulPreviousNotificationValue, pxHigherPriorityTaskWoken) xTaskGenericNotifyFromISR((xTaskToNotify), (ulValue), (eAction), (pulPreviousNotificationValue), (pxHigherPriorityTaskWoken))
#define xTaskNotifyGive(xTaskToNotify) xTaskGenericNotify((xTaskToNotify), (0), eIncrement, NULL)
Typedefs
typedef void * TaskHandle_t
typedef BaseType_t(* TaskHookFunction_t) (void *)
typedef struct xTIME_OUT TimeOut_t
typedef struct xMEMORY_REGION MemoryRegion_t
typedef struct xTASK_PARAMETERS TaskParameters_t
typedef struct xTASK_STATUS TaskStatus_t
Enumerations
enum eTaskState {
eRunning = 0,
eReady,
eBlocked,
eSuspended,
eDeleted,
eInvalid,
eRunning = 0,
eReady,
eBlocked,
eSuspended,
eDeleted,
eInvalid
 }
enum eNotifyAction {
eNoAction = 0,
eSetBits,
eIncrement,
eSetValueWithOverwrite,
eSetValueWithoutOverwrite,
eNoAction = 0,
eSetBits,
eIncrement,
eSetValueWithOverwrite,
eSetValueWithoutOverwrite
 }
enum eSleepModeStatus {
eAbortSleep = 0,
eStandardSleep,
eNoTasksWaitingTimeout,
eAbortSleep = 0,
eStandardSleep,
eNoTasksWaitingTimeout
 }
Functions
void vTaskAllocateMPURegions (TaskHandle_t xTask, const MemoryRegion_t *const pxRegions) PRIVILEGED_FUNCTION
void vTaskDelete (TaskHandle_t xTaskToDelete) PRIVILEGED_FUNCTION
void vTaskDelay (const TickType_t xTicksToDelay) PRIVILEGED_FUNCTION
void vTaskDelayUntil (TickType_t *const pxPreviousWakeTime, const TickType_t xTimeIncrement) PRIVILEGED_FUNCTION
BaseType_t xTaskAbortDelay (TaskHandle_t xTask) PRIVILEGED_FUNCTION
UBaseType_t uxTaskPriorityGet (TaskHandle_t xTask) PRIVILEGED_FUNCTION
UBaseType_t uxTaskPriorityGetFromISR (TaskHandle_t xTask) PRIVILEGED_FUNCTION
eTaskState eTaskGetState (TaskHandle_t xTask) PRIVILEGED_FUNCTION
void vTaskGetInfo (TaskHandle_t xTask, TaskStatus_t *pxTaskStatus, BaseType_t xGetFreeStackSpace, eTaskState eState) PRIVILEGED_FUNCTION
void vTaskPrioritySet (TaskHandle_t xTask, UBaseType_t uxNewPriority) PRIVILEGED_FUNCTION
void vTaskSuspend (TaskHandle_t xTaskToSuspend) PRIVILEGED_FUNCTION
void vTaskResume (TaskHandle_t xTaskToResume) PRIVILEGED_FUNCTION
BaseType_t xTaskResumeFromISR (TaskHandle_t xTaskToResume) PRIVILEGED_FUNCTION
void vTaskStartScheduler (void) PRIVILEGED_FUNCTION
void vTaskEndScheduler (void) PRIVILEGED_FUNCTION
void vTaskSuspendAll (void) PRIVILEGED_FUNCTION
BaseType_t xTaskResumeAll (void) PRIVILEGED_FUNCTION
TickType_t xTaskGetTickCount (void) PRIVILEGED_FUNCTION
TickType_t xTaskGetTickCountFromISR (void) PRIVILEGED_FUNCTION
UBaseType_t uxTaskGetNumberOfTasks (void) PRIVILEGED_FUNCTION
char * pcTaskGetName (TaskHandle_t xTaskToQuery) PRIVILEGED_FUNCTION
TaskHandle_t xTaskGetHandle (const char *pcNameToQuery) PRIVILEGED_FUNCTION
UBaseType_t uxTaskGetStackHighWaterMark (TaskHandle_t xTask) PRIVILEGED_FUNCTION
BaseType_t xTaskCallApplicationTaskHook (TaskHandle_t xTask, void *pvParameter) PRIVILEGED_FUNCTION
TaskHandle_t xTaskGetIdleTaskHandle (void) PRIVILEGED_FUNCTION
UBaseType_t uxTaskGetSystemState (TaskStatus_t *const pxTaskStatusArray, const UBaseType_t uxArraySize, uint32_t *const pulTotalRunTime) PRIVILEGED_FUNCTION
void vTaskList (char *pcWriteBuffer) PRIVILEGED_FUNCTION
void vTaskGetRunTimeStats (char *pcWriteBuffer) PRIVILEGED_FUNCTION
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue) PRIVILEGED_FUNCTION
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue, BaseType_t *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t *pulNotificationValue, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
BaseType_t xTaskIncrementTick (void) PRIVILEGED_FUNCTION
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait) PRIVILEGED_FUNCTION
void vTaskPlaceOnUnorderedEventList (List_t *pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait) PRIVILEGED_FUNCTION
void vTaskPlaceOnEventListRestricted (List_t *const pxEventList, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely) PRIVILEGED_FUNCTION
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList) PRIVILEGED_FUNCTION
void vTaskRemoveFromUnorderedEventList (ListItem_t *pxEventListItem, const TickType_t xItemValue) PRIVILEGED_FUNCTION
void vTaskSwitchContext (void) PRIVILEGED_FUNCTION
TickType_t uxTaskResetEventItemValue (void) PRIVILEGED_FUNCTION
TaskHandle_t xTaskGetCurrentTaskHandle (void) PRIVILEGED_FUNCTION
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut) PRIVILEGED_FUNCTION
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait) PRIVILEGED_FUNCTION
void vTaskMissedYield (void) PRIVILEGED_FUNCTION
BaseType_t xTaskGetSchedulerState (void) PRIVILEGED_FUNCTION
BaseType_t xTaskPriorityInherit (TaskHandle_t const pxMutexHolder) PRIVILEGED_FUNCTION
BaseType_t xTaskPriorityDisinherit (TaskHandle_t const pxMutexHolder) PRIVILEGED_FUNCTION
void vTaskPriorityDisinheritAfterTimeout (TaskHandle_t const pxMutexHolder, UBaseType_t uxHighestPriorityWaitingTask) PRIVILEGED_FUNCTION
UBaseType_t uxTaskGetTaskNumber (TaskHandle_t xTask) PRIVILEGED_FUNCTION
void vTaskSetTaskNumber (TaskHandle_t xTask, const UBaseType_t uxHandle) PRIVILEGED_FUNCTION
void vTaskStepTick (const TickType_t xTicksToJump) PRIVILEGED_FUNCTION
eSleepModeStatus eTaskConfirmSleepModeStatus (void) PRIVILEGED_FUNCTION
void * pvTaskIncrementMutexHeldCount (void) PRIVILEGED_FUNCTION
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut) PRIVILEGED_FUNCTION
Macro Definition Documentation
taskDISABLE_INTERRUPTS
#define taskDISABLE_INTERRUPTS() portDISABLE_INTERRUPTS()
Definition at line 204 of file task.h.
taskENABLE_INTERRUPTS
#define taskENABLE_INTERRUPTS() portENABLE_INTERRUPTS()
Definition at line 214 of file task.h.
taskENTER_CRITICAL
#define taskENTER_CRITICAL() portENTER_CRITICAL()
Definition at line 179 of file task.h.
taskENTER_CRITICAL_FROM_ISR
#define taskENTER_CRITICAL_FROM_ISR() portSET_INTERRUPT_MASK_FROM_ISR()
Definition at line 180 of file task.h.
taskEXIT_CRITICAL
#define taskEXIT_CRITICAL() portEXIT_CRITICAL()
Definition at line 194 of file task.h.
taskEXIT_CRITICAL_FROM_ISR
#define taskEXIT_CRITICAL_FROM_ISR(x) portCLEAR_INTERRUPT_MASK_FROM_ISR(x)
Definition at line 195 of file task.h.
taskSCHEDULER_NOT_STARTED
#define taskSCHEDULER_NOT_STARTED ((BaseType_t) 1)
Definition at line 220 of file task.h.
taskSCHEDULER_RUNNING
#define taskSCHEDULER_RUNNING ((BaseType_t) 2)
Definition at line 221 of file task.h.
taskSCHEDULER_SUSPENDED
#define taskSCHEDULER_SUSPENDED ((BaseType_t) 0)
Definition at line 219 of file task.h.
taskYIELD
#define taskYIELD() portYIELD()
Definition at line 165 of file task.h.
tskIDLE_PRIORITY
#define tskIDLE_PRIORITY ((UBaseType_t) 0U)
Defines the priority used by the idle task. This must not be modified.
Definition at line 155 of file task.h.
tskKERNEL_VERSION_BUILD
#define tskKERNEL_VERSION_BUILD 1
Definition at line 50 of file task.h.
tskKERNEL_VERSION_MAJOR
#define tskKERNEL_VERSION_MAJOR 10
Definition at line 48 of file task.h.
tskKERNEL_VERSION_MINOR
#define tskKERNEL_VERSION_MINOR 0
Definition at line 49 of file task.h.
tskKERNEL_VERSION_NUMBER
#define tskKERNEL_VERSION_NUMBER `V10.0.1`
Definition at line 47 of file task.h.
xTaskNotify
#define xTaskNotify(xTaskToNotify, ulValue, eAction) xTaskGenericNotify((xTaskToNotify), (ulValue), (eAction), NULL)
Definition at line 1767 of file task.h.
xTaskNotifyAndQuery
#define xTaskNotifyAndQuery(xTaskToNotify, ulValue, eAction, pulPreviousNotifyValue) xTaskGenericNotify((xTaskToNotify), (ulValue), (eAction), (pulPreviousNotifyValue))
Definition at line 1768 of file task.h.
xTaskNotifyAndQueryFromISR
#define xTaskNotifyAndQueryFromISR(xTaskToNotify, ulValue, eAction, pulPreviousNotificationValue, pxHigherPriorityTaskWoken) xTaskGenericNotifyFromISR((xTaskToNotify), (ulValue), (eAction), (pulPreviousNotificationValue), (pxHigherPriorityTaskWoken))
Definition at line 1859 of file task.h.
xTaskNotifyFromISR
#define xTaskNotifyFromISR(xTaskToNotify, ulValue, eAction, pxHigherPriorityTaskWoken) xTaskGenericNotifyFromISR((xTaskToNotify), (ulValue), (eAction), NULL, (pxHigherPriorityTaskWoken))
Definition at line 1858 of file task.h.
xTaskNotifyGive
#define xTaskNotifyGive(xTaskToNotify) xTaskGenericNotify((xTaskToNotify), (0), eIncrement, NULL)
Definition at line 1980 of file task.h.
Typedef Documentation
MemoryRegion_t
typedef struct xMEMORY_REGION MemoryRegion_t
TaskHandle_t
typedef void* TaskHandle_t
Definition at line 61 of file task.h.
TaskHookFunction_t
typedef BaseType_t(* TaskHookFunction_t) (void *)
Definition at line 67 of file task.h.
TaskParameters_t
typedef struct xTASK_PARAMETERS TaskParameters_t
TaskStatus_t
typedef struct xTASK_STATUS TaskStatus_t
TimeOut_t
typedef struct xTIME_OUT TimeOut_t
Enumeration Type Documentation
eNotifyAction
enum eNotifyAction
Enumerator
eNoAction
eSetBits
eIncrement
eSetValueWithOverwrite
eSetValueWithoutOverwrite
eNoAction
eSetBits
eIncrement
eSetValueWithOverwrite
eSetValueWithoutOverwrite
Definition at line 81 of file task.h.
eSleepModeStatus
enum eSleepModeStatus
Enumerator
eAbortSleep
eStandardSleep
eNoTasksWaitingTimeout
eAbortSleep
eStandardSleep
eNoTasksWaitingTimeout
Definition at line 142 of file task.h.
eTaskState
enum eTaskState
Enumerator
eRunning
eReady
eBlocked
eSuspended
eDeleted
eInvalid
eRunning
eReady
eBlocked
eSuspended
eDeleted
eInvalid
Definition at line 70 of file task.h.
Function Documentation
eTaskConfirmSleepModeStatus()
eSleepModeStatus eTaskConfirmSleepModeStatus (void)
eTaskGetState()
eTaskState eTaskGetState (TaskHandle_t xTask)
task. h
eTaskState eTaskGetState(TaskHandle_t xTask);
INCLUDE_eTaskGetState must be defined as 1 for this function to be available. See the configuration section for more information.
Obtain the state of any task. States are encoded by the eTaskState enumerated type.
Parameters
xTask Handle of the task to be queried.
Returns
The state of xTask at the time the function was called. Note the state of the task might change between the function being called, and the functions return value being tested by the calling task.
Definition at line 1332 of file tasks.c.
References configASSERT, eBlocked, eDeleted, eReady, eRunning, eSuspended, listLIST_ITEM_CONTAINER, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, and xTasksWaitingTermination.
Referenced by vTaskGetInfo(), and xTaskAbortDelay().
pcTaskGetName()
char* pcTaskGetName (TaskHandle_t xTaskToQuery)
Definition at line 2268 of file tasks.c.
References configASSERT, tskTaskControlBlock::pcTaskName, and prvGetTCBFromHandle.
pvTaskIncrementMutexHeldCount()
void* pvTaskIncrementMutexHeldCount (void)
Definition at line 4397 of file tasks.c.
References pxCurrentTCB, and tskTaskControlBlock::uxMutexesHeld.
ulTaskNotifyTake()
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
Definition at line 4414 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_TAKE, traceTASK_NOTIFY_TAKE_BLOCK, tskTaskControlBlock::ucNotifyState, and tskTaskControlBlock::ulNotifiedValue.
uxTaskGetNumberOfTasks()
UBaseType_t uxTaskGetNumberOfTasks (void)
Definition at line 2260 of file tasks.c.
References uxCurrentNumberOfTasks.
uxTaskGetStackHighWaterMark()
UBaseType_t uxTaskGetStackHighWaterMark (TaskHandle_t xTask)
task.h
UBaseType_t uxTaskGetStackHighWaterMark(TaskHandle_t xTask);
INCLUDE_uxTaskGetStackHighWaterMark must be set to 1 in FreeRTOSConfig.h for this function to be available.
Returns the high water mark of the stack associated with xTask. That is, the minimum free stack space there has been (in words, so on a 32 bit machine a value of 1 means 4 bytes) since the task started. The smaller the returned number the closer the task has come to overflowing its stack.
Parameters
xTask Handle of the task associated with the stack to be checked. Set xTask to NULL to check the stack of the calling task.
Returns
The smallest amount of free stack space there has been (in words, so actual spaces on the stack rather than bytes) since the task referenced by xTask was created.
Definition at line 3647 of file tasks.c.
References prvGetTCBFromHandle, prvTaskCheckFreeStackSpace(), and tskTaskControlBlock::pxStack.
uxTaskGetSystemState()
UBaseType_t uxTaskGetSystemState (TaskStatus_t *const pxTaskStatusArray, const UBaseType_t uxArraySize, uint32_t *const pulTotalRunTime)
configUSE_TRACE_FACILITY must be defined as 1 in FreeRTOSConfig.h for uxTaskGetSystemState() to be available.
uxTaskGetSystemState() populates an TaskStatus_t structure for each task in the system. TaskStatus_t structures contain, among other things, members for the task handle, task name, task priority, task state, and total amount of run time consumed by the task. See the TaskStatus_t structure definition in this file for the full member list.
NOTE: This function is intended for debugging use only as its use results in the scheduler remaining suspended for an extended period.
Parameters
pxTaskStatusArray A pointer to an array of TaskStatus_t structures. The array must contain at least one TaskStatus_t structure for each task that is under the control of the RTOS. The number of tasks under the control of the RTOS can be determined using the uxTaskGetNumberOfTasks() API function.
uxArraySize The size of the array pointed to by the pxTaskStatusArray parameter. The size is specified as the number of indexes in the array, or the number of TaskStatus_t structures contained in the array, not by the number of bytes in the array.
pulTotalRunTime If configGENERATE_RUN_TIME_STATS is set to 1 in FreeRTOSConfig.h then *pulTotalRunTime is set by uxTaskGetSystemState() to the total run time (as defined by the run time stats clock, see http://www.freertos.org/rtos-run-time-stats.html) since the target booted. pulTotalRunTime can be set to NULL to omit the total run time information.
Returns
The number of TaskStatus_t structures that were populated by uxTaskGetSystemState(). This should equal the number returned by the uxTaskGetNumberOfTasks() API function, but will be zero if the value passed in the uxArraySize parameter was too small.
Example usage:
 // This example demonstrates how a human readable table of run time stats
 // information is generated from raw data provided by uxTaskGetSystemState().
 // The human readable table is written to pcWriteBuffer
 void vTaskGetRunTimeStats(char *pcWriteBuffer)
 {
 TaskStatus_t *pxTaskStatusArray;
 volatile UBaseType_t uxArraySize, x;
 uint32_t ulTotalRunTime, ulStatsAsPercentage;
    // Make sure the write buffer does not contain a string.
    *pcWriteBuffer = 0x00;
    // Take a snapshot of the number of tasks in case it changes while this
    // function is executing.
    uxArraySize = uxTaskGetNumberOfTasks();
    // Allocate a TaskStatus_t structure for each task. An array could be
    // allocated statically at compile time.
    pxTaskStatusArray = pvPortMalloc(uxArraySize * sizeof(TaskStatus_t));
    if(pxTaskStatusArray != NULL)
    {
        // Generate raw status information about each task.
        uxArraySize = uxTaskGetSystemState(pxTaskStatusArray, uxArraySize, &ulTotalRunTime);
        // For percentage calculations.
        ulTotalRunTime /= 100UL;
        // Avoid divide by zero errors.
        if(ulTotalRunTime > 0)
        {
            // For each populated position in the pxTaskStatusArray array,
            // format the raw data as human readable ASCII data
            for(x = 0; x < uxArraySize; x++)
            {
                // What percentage of the total run time has the task used?
                // This will always be rounded down to the nearest integer.
                // ulTotalRunTimeDiv100 has already been divided by 100.
                ulStatsAsPercentage = pxTaskStatusArray[ x ].ulRunTimeCounter / ulTotalRunTime;
                if(ulStatsAsPercentage > 0UL)
                {
                    sprintf(pcWriteBuffer, "%s\t\t%lu\t\t%lu%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter, ulStatsAsPercentage);
                }
                else
                {
                    // If the percentage is zero here then the task has
                    // consumed less than 1% of the total run time.
                    sprintf(pcWriteBuffer, "%s\t\t%lu\t\t<1%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter);
                }
                pcWriteBuffer += strlen((char *) pcWriteBuffer);
            }
        }
        // The array is no longer needed, free the memory it consumes.
        vPortFree(pxTaskStatusArray);
    }
 }
Definition at line 2408 of file tasks.c.
References configMAX_PRIORITIES, eBlocked, eDeleted, eReady, eSuspended, mtCOVERAGE_TEST_MARKER, prvListTasksWithinSingleList(), pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskIDLE_PRIORITY, uxCurrentNumberOfTasks, vTaskSuspendAll(), xSuspendedTaskList, xTaskResumeAll(), and xTasksWaitingTermination.
Referenced by vTaskList().
uxTaskGetTaskNumber()
UBaseType_t uxTaskGetTaskNumber (TaskHandle_t xTask)
Definition at line 3176 of file tasks.c.
References tskTaskControlBlock::uxTaskNumber.
uxTaskPriorityGet()
UBaseType_t uxTaskPriorityGet (TaskHandle_t xTask)
Definition at line 1403 of file tasks.c.
References prvGetTCBFromHandle, taskENTER_CRITICAL, taskEXIT_CRITICAL, and tskTaskControlBlock::uxPriority.
uxTaskPriorityGetFromISR()
UBaseType_t uxTaskPriorityGetFromISR (TaskHandle_t xTask)
task. h
UBaseType_t uxTaskPriorityGetFromISR(TaskHandle_t xTask);
A version of uxTaskPriorityGet() that can be used from an ISR.
Definition at line 1425 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvGetTCBFromHandle, and tskTaskControlBlock::uxPriority.
uxTaskResetEventItemValue()
TickType_t uxTaskResetEventItemValue (void)
Definition at line 4381 of file tasks.c.
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listSET_LIST_ITEM_VALUE, pxCurrentTCB, tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xEventListItem.
vTaskAllocateMPURegions()
void vTaskAllocateMPURegions (TaskHandle_t xTask, const MemoryRegion_t *const pxRegions)
vTaskDelay()
void vTaskDelay (const TickType_t xTicksToDelay)
Definition at line 1287 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), traceTASK_DELAY, uxSchedulerSuspended, vTaskSuspendAll(), and xTaskResumeAll().
vTaskDelayUntil()
void vTaskDelayUntil (TickType_t *const pxPreviousWakeTime, const TickType_t xTimeIncrement)
Definition at line 1203 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), traceTASK_DELAY_UNTIL, uxSchedulerSuspended, vTaskSuspendAll(), xTaskResumeAll(), and xTickCount.
vTaskDelete()
void vTaskDelete (TaskHandle_t xTaskToDelete)
Definition at line 1111 of file tasks.c.
References configASSERT, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, portPRE_TASK_DELETE_HOOK, portYIELD_WITHIN_API, prvDeleteTCB(), prvGetTCBFromHandle, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskRESET_READY_PRIORITY, traceTASK_DELETE, uxCurrentNumberOfTasks, uxDeletedTasksWaitingCleanUp, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, uxTaskNumber, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, tskTaskControlBlock::xStateListItem, xTasksWaitingTermination, and xYieldPending.
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 2020 of file tasks.c.
References pdFALSE, portDISABLE_INTERRUPTS, vPortEndScheduler(), and xSchedulerRunning.
vTaskGetInfo()
void vTaskGetInfo (TaskHandle_t xTask, TaskStatus_t * pxTaskStatus, BaseType_t xGetFreeStackSpace, eTaskState eState)
Definition at line 3498 of file tasks.c.
References eBlocked, xTASK_STATUS::eCurrentState, eInvalid, eRunning, eSuspended, eTaskGetState(), listLIST_ITEM_CONTAINER, xTASK_STATUS::pcTaskName, tskTaskControlBlock::pcTaskName, pdFALSE, prvGetTCBFromHandle, prvTaskCheckFreeStackSpace(), pxCurrentTCB, tskTaskControlBlock::pxStack, xTASK_STATUS::pxStackBase, xTASK_STATUS::ulRunTimeCounter, xTASK_STATUS::usStackHighWaterMark, xTASK_STATUS::uxBasePriority, tskTaskControlBlock::uxBasePriority, xTASK_STATUS::uxCurrentPriority, tskTaskControlBlock::uxPriority, tskTaskControlBlock::uxTCBNumber, vTaskSuspendAll(), tskTaskControlBlock::xEventListItem, xTASK_STATUS::xHandle, xTASK_STATUS::xTaskNumber, and xTaskResumeAll().
Referenced by prvListTasksWithinSingleList().
vTaskGetRunTimeStats()
void vTaskGetRunTimeStats (char * pcWriteBuffer)
vTaskInternalSetTimeOutState()
void vTaskInternalSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3097 of file tasks.c.
References xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xTaskCheckForTimeOut().
vTaskList()
void vTaskList (char * pcWriteBuffer)
Definition at line 4158 of file tasks.c.
References eBlocked, eDeleted, eReady, eRunning, eSuspended, mtCOVERAGE_TEST_MARKER, prvWriteNameToBuffer(), pvPortMalloc(), tskBLOCKED_CHAR, tskDELETED_CHAR, tskREADY_CHAR, tskRUNNING_CHAR, tskSUSPENDED_CHAR, uxCurrentNumberOfTasks, uxTaskGetSystemState(), and vPortFree().
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 3168 of file tasks.c.
References pdTRUE, and xYieldPending.
vTaskNotifyGiveFromISR()
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4792 of file tasks.c.
References configASSERT, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, pxCurrentTCB, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_GIVE_FROM_ISR, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
Definition at line 2909 of file tasks.c.
References configASSERT, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, vListInsert(), and tskTaskControlBlock::xEventListItem.
vTaskPlaceOnEventListRestricted()
void vTaskPlaceOnEventListRestricted (List_t *const pxEventList, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
Definition at line 2952 of file tasks.c.
References configASSERT, pdFALSE, portMAX_DELAY, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, traceTASK_DELAY_UNTIL, vListInsertEnd(), tskTaskControlBlock::xEventListItem, and xTickCount.
vTaskPlaceOnUnorderedEventList()
void vTaskPlaceOnUnorderedEventList (List_t * pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
Definition at line 2926 of file tasks.c.
References configASSERT, listSET_LIST_ITEM_VALUE, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxSchedulerSuspended, vListInsertEnd(), and tskTaskControlBlock::xEventListItem.
vTaskPriorityDisinheritAfterTimeout()
void vTaskPriorityDisinheritAfterTimeout (TaskHandle_t const pxMutexHolder, UBaseType_t uxHighestPriorityWaitingTask)
Definition at line 3967 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, prvAddTaskToReadyList, pxCurrentTCB, pxMutexHolder, pxReadyTasksLists, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_DISINHERIT, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
vTaskPrioritySet()
void vTaskPrioritySet (TaskHandle_t xTask, UBaseType_t uxNewPriority)
Definition at line 1465 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portRESET_READY_PRIORITY, prvAddTaskToReadyList, prvGetTCBFromHandle, pxCurrentTCB, pxReadyTasksLists, taskENTER_CRITICAL, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_PRIORITY_SET, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
vTaskRemoveFromUnorderedEventList()
void vTaskRemoveFromUnorderedEventList (ListItem_t * pxEventListItem, const TickType_t xItemValue)
Definition at line 3051 of file tasks.c.
References configASSERT, listGET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xStateListItem, and xYieldPending.
vTaskResume()
void vTaskResume (TaskHandle_t xTaskToResume)
Definition at line 1776 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, prvAddTaskToReadyList, prvTaskIsTaskSuspended(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_RESUME, uxListRemove(), tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xStateListItem.
vTaskSetTaskNumber()
void vTaskSetTaskNumber (TaskHandle_t xTask, const UBaseType_t uxHandle)
Definition at line 3199 of file tasks.c.
References tskTaskControlBlock::uxTaskNumber.
vTaskSetTimeOutState()
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3085 of file tasks.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1900 of file tasks.c.
References configASSERT, configIDLE_TASK_NAME, configMINIMAL_STACK_SIZE, errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portCONFIGURE_TIMER_FOR_RUN_TIME_STATS, portDISABLE_INTERRUPTS, portMAX_DELAY, portPRIVILEGE_BIT, pxCurrentTCB, tskIDLE_PRIORITY, xIdleTaskHandle, xNextTaskUnblockTime, xPortStartScheduler(), xSchedulerRunning, xTickCount, and xTimerCreateTimerTask().
vTaskStepTick()
void vTaskStepTick (const TickType_t xTicksToJump)
vTaskSuspend()
void vTaskSuspend (TaskHandle_t xTaskToSuspend)
Definition at line 1629 of file tasks.c.
References configASSERT, listCURRENT_LIST_LENGTH, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvGetTCBFromHandle, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskRESET_READY_PRIORITY, taskWAITING_NOTIFICATION, traceTASK_SUSPEND, tskTaskControlBlock::ucNotifyState, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), vTaskSwitchContext(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, tskTaskControlBlock::xStateListItem, and xSuspendedTaskList.
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 2031 of file tasks.c.
References uxSchedulerSuspended.
Referenced by portTASK_FUNCTION(), uxTaskGetSystemState(), vTaskDelay(), vTaskDelayUntil(), vTaskGetInfo(), xTaskAbortDelay(), and xTaskGetHandle().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 2850 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, pxCurrentTCB, taskCHECK_FOR_STACK_OVERFLOW, taskSELECT_HIGHEST_PRIORITY_TASK, traceTASK_SWITCHED_IN, traceTASK_SWITCHED_OUT, uxSchedulerSuspended, and xYieldPending.
Referenced by vTaskSuspend().
xTaskAbortDelay()
BaseType_t xTaskAbortDelay (TaskHandle_t xTask)
Definition at line 2514 of file tasks.c.
References configASSERT, eBlocked, eTaskGetState(), listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::ucDelayAborted, uxListRemove(), tskTaskControlBlock::uxPriority, vTaskSuspendAll(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xStateListItem, xTaskResumeAll(), and xYieldPending.
xTaskCallApplicationTaskHook()
BaseType_t xTaskCallApplicationTaskHook (TaskHandle_t xTask, void * pvParameter)
task.h
BaseType_t xTaskCallApplicationTaskHook(TaskHandle_t xTask, void *pvParameter);
Calls the hook function associated with xTask. Passing xTask as NULL has the effect of calling the Running tasks (the calling task) hook function.
pvParameter is passed to the hook function for the task to interpret as it wants. The return value is the value returned by the task hook function registered by the user.
xTaskCheckForTimeOut()
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
Definition at line 3105 of file tasks.c.
References configASSERT, pdFALSE, pdTRUE, portMAX_DELAY, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::ucDelayAborted, vTaskInternalSetTimeOutState(), xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
xTaskGenericNotify()
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue)
Definition at line 4562 of file tasks.c.
References configASSERT, eIncrement, eNoAction, eSetBits, eSetValueWithoutOverwrite, eSetValueWithOverwrite, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, taskYIELD_IF_USING_PREEMPTION, traceTASK_NOTIFY, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
xTaskGenericNotifyFromISR()
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4668 of file tasks.c.
References configASSERT, eIncrement, eNoAction, eSetBits, eSetValueWithoutOverwrite, eSetValueWithOverwrite, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, pxCurrentTCB, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_FROM_ISR, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
xTaskGetCurrentTaskHandle()
TaskHandle_t xTaskGetCurrentTaskHandle (void)
Definition at line 3755 of file tasks.c.
References pxCurrentTCB.
xTaskGetHandle()
TaskHandle_t xTaskGetHandle (const char * pcNameToQuery)
Definition at line 2343 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, prvSearchForNameWithinSingleList(), pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskIDLE_PRIORITY, vTaskSuspendAll(), xSuspendedTaskList, xTaskResumeAll(), and xTasksWaitingTermination.
xTaskGetIdleTaskHandle()
TaskHandle_t xTaskGetIdleTaskHandle (void)
xTaskGetIdleTaskHandle() is only available if INCLUDE_xTaskGetIdleTaskHandle is set to 1 in FreeRTOSConfig.h.
Simply returns the handle of the idle task. It is not valid to call xTaskGetIdleTaskHandle() before the scheduler has been started.
Definition at line 2482 of file tasks.c.
References configASSERT, and xIdleTaskHandle.
xTaskGetSchedulerState()
BaseType_t xTaskGetSchedulerState (void)
Definition at line 3772 of file tasks.c.
References pdFALSE, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, uxSchedulerSuspended, and xSchedulerRunning.
xTaskGetTickCount()
TickType_t xTaskGetTickCount (void)
Definition at line 2214 of file tasks.c.
References portTICK_TYPE_ENTER_CRITICAL, portTICK_TYPE_EXIT_CRITICAL, and xTickCount.
xTaskGetTickCountFromISR()
TickType_t xTaskGetTickCountFromISR (void)
Definition at line 2229 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portTICK_TYPE_CLEAR_INTERRUPT_MASK_FROM_ISR, portTICK_TYPE_SET_INTERRUPT_MASK_FROM_ISR, and xTickCount.
xTaskIncrementTick()
BaseType_t xTaskIncrementTick (void)
Definition at line 2588 of file tasks.c.
References listCURRENT_LIST_LENGTH, listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portMAX_DELAY, prvAddTaskToReadyList, pxCurrentTCB, pxDelayedTaskList, pxReadyTasksLists, taskSWITCH_DELAYED_LISTS, traceTASK_INCREMENT_TICK, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xTickCount, and xYieldPending.
Referenced by xTaskResumeAll().
xTaskNotifyStateClear()
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
Definition at line 4881 of file tasks.c.
References pdFAIL, pdPASS, prvGetTCBFromHandle, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskNOTIFICATION_RECEIVED, and tskTaskControlBlock::ucNotifyState.
xTaskNotifyWait()
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t * pulNotificationValue, TickType_t xTicksToWait)
Definition at line 4482 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_WAIT, traceTASK_NOTIFY_WAIT_BLOCK, tskTaskControlBlock::ucNotifyState, and tskTaskControlBlock::ulNotifiedValue.
xTaskPriorityDisinherit()
BaseType_t xTaskPriorityDisinherit (TaskHandle_t const pxMutexHolder)
Definition at line 3887 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, pxMutexHolder, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_DISINHERIT, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
xTaskPriorityInherit()
BaseType_t xTaskPriorityInherit (TaskHandle_t const pxMutexHolder)
Definition at line 3800 of file tasks.c.
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, pxMutexHolder, pxReadyTasksLists, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_INHERIT, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
xTaskRemoveFromEventList()
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
Definition at line 2983 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
xTaskResumeAll()
BaseType_t xTaskResumeAll (void)
Definition at line 2104 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, uxCurrentNumberOfTasks, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, xTaskIncrementTick(), and xYieldPending.
Referenced by portTASK_FUNCTION(), uxTaskGetSystemState(), vTaskDelay(), vTaskDelayUntil(), vTaskGetInfo(), xTaskAbortDelay(), and xTaskGetHandle().
xTaskResumeFromISR()
BaseType_t xTaskResumeFromISR (TaskHandle_t xTaskToResume)
Definition at line 1830 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, prvTaskIsTaskSuspended(), pxCurrentTCB, traceTASK_RESUME_FROM_ISR, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, and tskTaskControlBlock::xStateListItem.