Dave/Model/APPS/FREERTOS/v4_1_2/Templates/queue.c File Reference
#include <stdlib.h>
#include <string.h>
#include `FreeRTOS.h`
#include `task.h`
#include `queue.h`
Data Structures
struct QueueDefinition
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define queueUNLOCKED ((int8_t) -1)
#define queueLOCKED_UNMODIFIED ((int8_t) 0)
#define pxMutexHolder pcTail
#define uxQueueType pcHead
#define queueQUEUE_IS_MUTEX NULL
#define queueSEMAPHORE_QUEUE_ITEM_LENGTH ((UBaseType_t) 0)
#define queueMUTEX_GIVE_BLOCK_TIME ((TickType_t) 0U)
#define queueYIELD_IF_USING_PREEMPTION()
#define prvLockQueue(pxQueue)
Typedefs
typedef struct QueueDefinition xQUEUE
typedef xQUEUE Queue_t
Functions
static void prvUnlockQueue (Queue_t *const pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvIsQueueEmpty (const Queue_t *pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvIsQueueFull (const Queue_t *pxQueue) PRIVILEGED_FUNCTION
static BaseType_t prvCopyDataToQueue (Queue_t *const pxQueue, const void *pvItemToQueue, const BaseType_t xPosition) PRIVILEGED_FUNCTION
static void prvCopyDataFromQueue (Queue_t *const pxQueue, void *const pvBuffer) PRIVILEGED_FUNCTION
static void prvInitialiseNewQueue (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, uint8_t *pucQueueStorage, const uint8_t ucQueueType, Queue_t *pxNewQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
QueueHandle_t xQueueGenericCreate (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, const uint8_t ucQueueType)
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
void vQueueDelete (QueueHandle_t xQueue)
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 35 of file queue.c.
prvLockQueue
#define prvLockQueue(pxQueue)
Value:
    taskENTER_CRITICAL(); \
    { \
        if((pxQueue)->cRxLock == queueUNLOCKED) \
        { \
            (pxQueue)->cRxLock = queueLOCKED_UNMODIFIED; \
        } \
        if((pxQueue)->cTxLock == queueUNLOCKED) \
        { \
            (pxQueue)->cTxLock = queueLOCKED_UNMODIFIED; \
        } \
    } \
    taskEXIT_CRITICAL()
Definition at line 233 of file queue.c.
pxMutexHolder
#define pxMutexHolder pcTail
Definition at line 67 of file queue.c.
queueLOCKED_UNMODIFIED
#define queueLOCKED_UNMODIFIED ((int8_t) 0)
Definition at line 54 of file queue.c.
queueMUTEX_GIVE_BLOCK_TIME
#define queueMUTEX_GIVE_BLOCK_TIME ((TickType_t) 0U)
Definition at line 74 of file queue.c.
queueQUEUE_IS_MUTEX
#define queueQUEUE_IS_MUTEX NULL
Definition at line 69 of file queue.c.
queueSEMAPHORE_QUEUE_ITEM_LENGTH
#define queueSEMAPHORE_QUEUE_ITEM_LENGTH ((UBaseType_t) 0)
Definition at line 73 of file queue.c.
queueUNLOCKED
#define queueUNLOCKED ((int8_t) -1)
Definition at line 53 of file queue.c.
queueYIELD_IF_USING_PREEMPTION
#define queueYIELD_IF_USING_PREEMPTION()
Definition at line 79 of file queue.c.
uxQueueType
#define uxQueueType pcHead
Definition at line 68 of file queue.c.
Typedef Documentation
Queue_t
typedef xQUEUE Queue_t
Definition at line 127 of file queue.c.
xQUEUE
typedef struct QueueDefinition xQUEUE
Function Documentation
prvCopyDataFromQueue()
static void prvCopyDataFromQueue (Queue_t *const pxQueue, void *const pvBuffer) [static]
Definition at line 2119 of file queue.c.
References mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::u, and QueueDefinition::uxItemSize.
Referenced by xQueuePeek(), xQueuePeekFromISR(), xQueueReceive(), and xQueueReceiveFromISR().
prvCopyDataToQueue()
static BaseType_t prvCopyDataToQueue (Queue_t *const pxQueue, const void * pvItemToQueue, const BaseType_t xPosition) [static]
Definition at line 2040 of file queue.c.
References mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::pcWriteTo, pdFALSE, queueOVERWRITE, queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, and xTaskPriorityDisinherit().
Referenced by xQueueGenericSend(), and xQueueGenericSendFromISR().
prvInitialiseNewQueue()
static void prvInitialiseNewQueue (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, uint8_t * pucQueueStorage, const uint8_t ucQueueType, Queue_t * pxNewQueue) [static]
Definition at line 408 of file queue.c.
References QueueDefinition::pcHead, pdTRUE, QueueDefinition::pxQueueSetContainer, traceQUEUE_CREATE, QueueDefinition::ucQueueType, QueueDefinition::uxItemSize, QueueDefinition::uxLength, and xQueueGenericReset().
Referenced by xQueueGenericCreate().
prvIsQueueEmpty()
static BaseType_t prvIsQueueEmpty (const Queue_t * pxQueue) [static]
Definition at line 2257 of file queue.c.
References pdFALSE, pdTRUE, taskENTER_CRITICAL, taskEXIT_CRITICAL, and QueueDefinition::uxMessagesWaiting.
Referenced by xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
prvIsQueueFull()
static BaseType_t prvIsQueueFull (const Queue_t * pxQueue) [static]
Definition at line 2296 of file queue.c.
References pdFALSE, pdTRUE, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
Referenced by xQueueGenericSend().
prvUnlockQueue()
static void prvUnlockQueue (Queue_t *const pxQueue) [static]
Definition at line 2137 of file queue.c.
References QueueDefinition::cRxLock, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, prvNotifyQueueSetContainer(), QueueDefinition::pxQueueSetContainer, queueLOCKED_UNMODIFIED, queueSEND_TO_BACK, queueUNLOCKED, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskMissedYield(), xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueGenericSend(), xQueuePeek(), xQueueReceive(), and xQueueSemaphoreTake().
uxQueueMessagesWaiting()
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
Definition at line 1895 of file queue.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, and xQueue.
uxQueueMessagesWaitingFromISR()
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
Definition at line 1929 of file queue.c.
References configASSERT, and xQueue.
uxQueueSpacesAvailable()
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
Definition at line 1911 of file queue.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, and xQueue.
vQueueDelete()
void vQueueDelete (QueueHandle_t xQueue)
Definition at line 1941 of file queue.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, traceQUEUE_DELETE, vPortFree(), vQueueUnregisterQueue(), and xQueue.
xQueueGenericCreate()
QueueHandle_t xQueueGenericCreate (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, const uint8_t ucQueueType)
Definition at line 358 of file queue.c.
References configASSERT, pdFALSE, prvInitialiseNewQueue(), pvPortMalloc(), and traceQUEUE_CREATE_FAILED.
xQueueGenericReset()
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
Definition at line 247 of file queue.c.
References configASSERT, QueueDefinition::cRxLock, QueueDefinition::cTxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::pcWriteTo, pdFALSE, pdPASS, queueUNLOCKED, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vListInitialise(), xQueue, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
xQueueGenericSend()
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
Definition at line 725 of file queue.c.
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataToQueue(), prvIsQueueFull(), prvLockQueue, prvNotifyQueueSetContainer(), prvUnlockQueue(), QueueDefinition::pxQueueSetContainer, queueOVERWRITE, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_SEND, traceQUEUE_SEND, traceQUEUE_SEND_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
xQueueGenericSendFromISR()
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
Definition at line 923 of file queue.c.
References configASSERT, QueueDefinition::cTxLock, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataToQueue(), prvNotifyQueueSetContainer(), QueueDefinition::pxQueueSetContainer, queueOVERWRITE, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, xQueue, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
xQueueGiveFromISR()
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1074 of file queue.c.
References configASSERT, QueueDefinition::cTxLock, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvNotifyQueueSetContainer(), QueueDefinition::pxQueueSetContainer, queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, xQueue, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToReceive.
xQueueIsQueueEmptyFromISR()
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
Definition at line 2278 of file queue.c.
References configASSERT, pdFALSE, pdTRUE, and xQueue.
xQueueIsQueueFullFromISR()
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Definition at line 2317 of file queue.c.
References configASSERT, pdFALSE, pdTRUE, and xQueue.
xQueuePeek()
BaseType_t xQueuePeek (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1600 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcReadFrom, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_PEEK, traceQUEUE_PEEK, traceQUEUE_PEEK_FAILED, QueueDefinition::u, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), and QueueDefinition::xTasksWaitingToReceive.
xQueuePeekFromISR()
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
Definition at line 1841 of file queue.c.
References configASSERT, QueueDefinition::pcReadFrom, pdFAIL, pdPASS, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), traceQUEUE_PEEK_FROM_ISR, traceQUEUE_PEEK_FROM_ISR_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, and xQueue.
xQueueReceive()
BaseType_t xQueueReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait)
Definition at line 1239 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
xQueueReceiveFromISR()
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1750 of file queue.c.
References configASSERT, QueueDefinition::cRxLock, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), queueUNLOCKED, traceQUEUE_RECEIVE_FROM_ISR, traceQUEUE_RECEIVE_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, xQueue, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToSend.
xQueueSemaphoreTake()
BaseType_t xQueueSemaphoreTake (QueueHandle_t xQueue, TickType_t xTicksToWait)
Definition at line 1381 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvGetDisinheritPriorityAfterTimeout(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), pvTaskIncrementMutexHeldCount(), queueQUEUE_IS_MUTEX, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, vTaskInternalSetTimeOutState(), vTaskPlaceOnEventList(), vTaskPriorityDisinheritAfterTimeout(), vTaskSuspendAll(), xQueue, xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskPriorityInherit(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.