Dave/Model/APPS/FREERTOS/v4_1_2/Templates/portable.h File Reference
#include `deprecated_definitions.h`
#include `mpu_wrappers.h`
Data Structures
struct HeapRegion
Macros
#define portNUM_CONFIGURABLE_REGIONS 1
Typedefs
typedef struct HeapRegion HeapRegion_t
Functions
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters) PRIVILEGED_FUNCTION
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions) PRIVILEGED_FUNCTION
void * pvPortMalloc (size_t xSize) PRIVILEGED_FUNCTION
void vPortFree (void *pv) PRIVILEGED_FUNCTION
void vPortInitialiseBlocks (void) PRIVILEGED_FUNCTION
size_t xPortGetFreeHeapSize (void) PRIVILEGED_FUNCTION
size_t xPortGetMinimumEverFreeHeapSize (void) PRIVILEGED_FUNCTION
BaseType_t xPortStartScheduler (void) PRIVILEGED_FUNCTION
void vPortEndScheduler (void) PRIVILEGED_FUNCTION
Macro Definition Documentation
portNUM_CONFIGURABLE_REGIONS
#define portNUM_CONFIGURABLE_REGIONS 1
Definition at line 93 of file portable.h.
Typedef Documentation
HeapRegion_t
typedef struct HeapRegion HeapRegion_t
Function Documentation
pvPortMalloc()
void* pvPortMalloc (size_t xSize)
Definition at line 70 of file heap_1.h.
References configADJUSTED_HEAP_SIZE, configASSERT, heapMINIMUM_BLOCK_SIZE, heapSTRUCT_SIZE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portBYTE_ALIGNMENT, portPOINTER_SIZE_TYPE, prvHeapInit(), prvInsertBlockIntoFreeList, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, ucHeap, vApplicationMallocFailedHook(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xEnd, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, xNextFreeByte, xStart, and xTaskResumeAll().
Referenced by main(), vTaskList(), xEventGroupCreate(), xQueueGenericCreate(), xStreamBufferGenericCreate(), and xTimerCreate().
pxPortInitialiseStack()
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
References HeapRegion::pucStartAddress, and HeapRegion::xSizeInBytes.
vPortDefineHeapRegions()
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
Definition at line 393 of file heap_5.h.
References configASSERT, heapBITS_PER_BYTE, portBYTE_ALIGNMENT, HeapRegion::pucStartAddress, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, HeapRegion::xSizeInBytes, and xStart.
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 421 of file port_mpu.h.
References configASSERT, and uxCriticalNesting.
vPortFree()
void vPortFree (void * pv)
Definition at line 122 of file heap_1.h.
References configASSERT, heapSTRUCT_SIZE, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList, A_BLOCK_LINK::pxNextFreeBlock, traceFREE, vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, and xTaskResumeAll().
Referenced by prvDeleteTCB(), prvProcessReceivedCommands(), vEventGroupDelete(), vQueueDelete(), vStreamBufferDelete(), and vTaskList().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 134 of file heap_1.h.
References xNextFreeByte.
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 141 of file heap_1.h.
References configADJUSTED_HEAP_SIZE, xFreeBytesRemaining, and xNextFreeByte.
xPortGetMinimumEverFreeHeapSize()
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 317 of file heap_4.h.
References xMinimumEverFreeBytesRemaining.
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 307 of file port_mpu.h.
References __NVIC_PRIO_BITS, configASSERT, configMAX_SYSCALL_INTERRUPT_PRIORITY, portASPEN_AND_LSPEN_BITS, portCORTEX_M7_r0p0_ID, portCORTEX_M7_r0p1_ID, portCPUID, portFIRST_USER_INTERRUPT_NUMBER, portFPCCR, portMAX_8_BIT_VALUE, portMAX_PRIGROUP_BITS, portNVIC_IP_REGISTERS_OFFSET_16, portNVIC_PENDSV_PRI, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, portPRIGROUP_SHIFT, portPRIORITY_GROUP_MASK, portSVC_START_SCHEDULER, portTOP_BIT_OF_BYTE, prvSetupMPU(), prvSetupTimerInterrupt(), prvStartFirstTask(), uxCriticalNesting, vPortEnableVFP(), vPortSetupTimerInterrupt(), and vPortStartFirstTask().