Dave/Model/APPS/SPI_SLAVE/v4_0_8/Templates/spi_slave.c File Reference
#include `spi_slave.h`
#include `string.h`
Macros
#define SPI_SLAVE_PORT_ALTERNATE_FN_MSK (0x0fUL << PORT0_IOCR0_PC0_Pos)
Functions
static SPI_SLAVE_STATUS_t SPI_SLAVE_lValidateModeChange (const SPI_SLAVE_t *const handle, XMC_SPI_CH_MODE_t mode)
DAVE_APP_VERSION_t SPI_SLAVE_GetAppVersion ()
Get the SPI_SLAVE APP version.
SPI_SLAVE_STATUS_t SPI_SLAVE_Init (const SPI_SLAVE_t *const handle)
Initializes the USIC channel as SPI slave.
SPI_SLAVE_STATUS_t SPI_SLAVE_Transmit (const SPI_SLAVE_t *const handle, uint8_t *data_ptr, uint32_t count)
Registers a request for transmitting data over SPI channel as a slave device.
SPI_SLAVE_STATUS_t SPI_SLAVE_Receive (const SPI_SLAVE_t *const handle, uint8_t *data_ptr, uint32_t count)
Registers a request for receiving data over SPI_SLAVE channel.
SPI_SLAVE_STATUS_t SPI_SLAVE_SetMode (const SPI_SLAVE_t *const handle, XMC_SPI_CH_MODE_t mode)
Changes the operation mode of the SPI slave channel.
SPI_SLAVE_STATUS_t SPI_SLAVE_Transfer (const SPI_SLAVE_t *const handle, uint8_t *tx_dataptr, uint8_t *rx_dataptr, uint32_t count)
Registers a request for transmitting and receiving data simultaneously over SPI channel as a slave device.
Detailed Description
Date
2015-12-17
NOTE: This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
Macro Definition Documentation
SPI_SLAVE_PORT_ALTERNATE_FN_MSK
#define SPI_SLAVE_PORT_ALTERNATE_FN_MSK (0x0fUL << PORT0_IOCR0_PC0_Pos)
Definition at line 62 of file spi_slave.c.
Function Documentation
SPI_SLAVE_GetAppVersion()
DAVE_APP_VERSION_t SPI_SLAVE_GetAppVersion (void)
Get the SPI_SLAVE APP version.
Returns
DAVE_APP_VERSION_t APP version information (major, minor and patch number)
Example Usage:
#include <DAVE.h>
//Example below, transmits data to master only if the version of the SPI_SLAVE APP is v4.0.x
//Value of x can be anything.
int main(void)
{
  SPI_SLAVE_STATUS_t init_status;
  DAVE_APP_VERSION_t spi_slave_version;
  uint8_t valid_data[] = {0x55, 0xaa, 0x5a, 0xa5};
  init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
  if(init_status == SPI_SLAVE_STATUS_SUCCESS)
  {
    spi_slave_version = SPI_SLAVE_GetAppVersion();
    //Check the APP version
    if((spi_slave_version.major == 4) &&
      (spi_slave_version.minor == 0))
    {
      //Transmit data
      SPI_SLAVE_Transmit(&SPI_SLAVE_0, valid_data, sizeof(valid_data));
    }
  }
  else
  {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
  }
  return 1U;
}
Definition at line 111 of file spi_slave.c.
References DAVE_APP_VERSION::major, DAVE_APP_VERSION::minor, DAVE_APP_VERSION::patch, SPI_SLAVE_MAJOR_VERSION, SPI_SLAVE_MINOR_VERSION, and SPI_SLAVE_PATCH_VERSION.
SPI_SLAVE_Init()
SPI_SLAVE_STATUS_t SPI_SLAVE_Init (const SPI_SLAVE_t *const handle)
Initializes the USIC channel as SPI slave.
Parameters
handle Pointer to static and dynamic attributes of APP configuration.
Returns
SPI_SLAVE_STATUS_t: Status of SPI_SLAVE driver initialization.
 SPI_SLAVE_STATUS_SUCCESS - on successful initialization.
 SPI_SLAVE_STATUS_FAILURE - if initialization fails.
 SPI_SLAVE_STATUS_BUSY - if SPI_SLAVE channel is busy.
Description:
Initializes IO pins used for the SPI_SLAVE communication, configures USIC registers based on the GUI modifications. It also configures selected interrupts, DMA channels and peripheral register bitfields.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
       while(1U)
       {
       }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 132 of file spi_slave.c.
References SPI_SLAVE::config, SPI_SLAVE_CONFIG::fptr_spi_slave_config, SPI_SLAVE::runtime, SPI_SLAVE_STATUS_SUCCESS, and XMC_ASSERT.
SPI_SLAVE_lValidateModeChange()
static SPI_SLAVE_STATUS_t SPI_SLAVE_lValidateModeChange (const SPI_SLAVE_t *const handle, XMC_SPI_CH_MODE_t mode) [static]
Definition at line 422 of file spi_slave.c.
References SPI_SLAVE_PIN_CONFIG::config, SPI_SLAVE::config, SPI_SLAVE_CONFIG::dx0_source, SPI_SLAVE_CONFIG::mosi0_pin_config, SPI_SLAVE_CONFIG::mosi1_pin_config, SPI_SLAVE_CONFIG::spi_configured_mode, SPI_SLAVE_INPUT_INVALID, SPI_SLAVE_PORT_ALTERNATE_FN_MSK, SPI_SLAVE_STATUS_FAILURE, SPI_SLAVE_STATUS_SUCCESS, XMC_SPI_CH_MODE_STANDARD, and XMC_SPI_CH_MODE_STANDARD_HALFDUPLEX.
Referenced by SPI_SLAVE_SetMode().
SPI_SLAVE_Receive()
SPI_SLAVE_STATUS_t SPI_SLAVE_Receive (const SPI_SLAVE_t *const handle, uint8_t * data_ptr, uint32_t count)
Registers a request for receiving data over SPI_SLAVE channel.
Parameters
handle Pointer to SPI_SLAVE_t handle structure
data_ptr Pointer to data of type uint8_t.
count Total no of bytes to be received.
 Range: minimum= 1, maximum= maximum value supported by type uint32_t.
 In DMA mode, a maximum of 4095 words can be received in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status for receive request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a reception is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
Description:
Data will be received from the SPI master synchronously. After the requested number of data bytes are received, optionally, the user configured callback function will be executed. Data reception is accomplished using the receive mode selected in the UI. Interrupt:
 Based on the UI configuration, either standard receive buffer(RBUF) or receive FIFO(OUT) is used for data reception. An interrupt is configured for reading received data from the bus. This function only registers a request to receive a number of data bytes from a USIC channel. If FIFO is configured for reception, the FIFO limit is dynamically configured to optimally utilize the CPU load. Before starting data reception, the receive buffers are flushed. So only those data, received after calling the API, will be placed in the user buffer. When all the requested number of data bytes are received, the configured callback function will be executed. If a callback function is not configured, the user has to poll for the value of the variable, handle->runtime->rx_busy to be false. The value is updated to false when all the requested number of data bytes are received.
 DMA:
 DMA mode is available only in XMC4x family of microcontrollers. In this mode, a DMA channel is configured for receiving data from standard receive buffer(RBUF) to the user buffer. By calling this API, the DMA channel destination address is configured to the user buffer and the channel is enabled. Receive FIFO will not be used when the receive mode is DMA. Before starting data reception, the receive buffers are flushed. So only those data, received after calling the API, will be placed in the user buffer. When all the requested number of data bytes are received, the configured callback function will be executed. If a callback function is not configured, the user has to poll for the value of the variable, handle->runtime->rx_busy to be false. The value is updated to false when all the requested number of data bytes are received.
 Direct
 In Direct receive mode, neither interrupt nor DMA is used. The API polls the receive flag to read the received data and waits for all the requested number of bytes to be received. Based on FIFO configuration, either RBUF or OUT register is used for reading received data. Before starting data reception, the receive buffers are flushed. So only those data, received after calling the API, will be placed in the user buffer. Note: In Direct mode, the API blocks the CPU until the count of bytes requested is received. If this behaviour is not desired, use other APIs like SPI_SLAVE_GetReceivedWord, SPI_SLAVE_GetProtocolStatus etc.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Receive mode should be configured as "Direct".
 //Description:
 //Receives 10 bytes from master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t ReadData[10];
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     if(SPI_SLAVE_Receive(&SPI_SLAVE_0, ReadData, 10) == SPI_SLAVE_STATUS_SUCCESS)
     {
       SPI_SLAVE_Transmit(&SPI_SLAVE_0, ReadData, 10);
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 207 of file spi_slave.c.
References SPI_SLAVE::config, SPI_SLAVE_CONFIG::receive_mode, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_StartReceiveIRQ(), SPI_SLAVE_STATUS_BUFFER_INVALID, SPI_SLAVE_STATUS_BUSY, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_TRANSFER_MODE_DIRECT, SPI_SLAVE_TRANSFER_MODE_DMA, and SPI_SLAVE_TRANSFER_MODE_INTERRUPT.
SPI_SLAVE_SetMode()
SPI_SLAVE_STATUS_t SPI_SLAVE_SetMode (const SPI_SLAVE_t *const handle, XMC_SPI_CH_MODE_t mode)
Changes the operation mode of the SPI slave channel.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
mode Operation mode to be configured.
Range: XMC_SPI_CH_MODE_STANDARD - Full duplex
 XMC_SPI_CH_MODE_STANDARD_HALFDUPLEX - Half duplex
 XMC_SPI_CH_MODE_DUAL - Dual SPI
 XMC_SPI_CH_MODE_QUAD - Quad SPI
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission or reception is in progress.
 SPI_SLAVE_STATUS_FAILURE if the mode change is not possible.
 Imp Note: Return value should be validated by user to ensure that the operation mode is changed.
Description:
Tries to change the operation mode of the SPI channel. Mode change is possible when the operation mode configured in the GUI uses higher number of pins than the new mode requested. Mode change is not possible when the GUI configured operation mode is 'Full Duplex' or 'Half Duplex'. This is due to the connection between MOSI and MISO pins. In 'Full Duplex' mode, MOSI pin of the SPI slave device will be configured as input. But in 'Half Duplex' mode, the same pin has to be configured as output pin with the alternate function of USIC channel DOUT0. Information about the output alternate function will not be available with the APP at runtime. So change of operation mode from 'Full Duplex' to 'Half Duplex' is not possible. Mode change is possible from 'Quad SPI' to 'Dual SPI' or to 'Half Duplex' or to 'Full Duplex'. Mode change is also possible from 'Dual SPI' to 'Half Duplex' or 'Full Duplex'. But mode change from 'Dual SPI' to 'Quad SPI' is not possible. When the mode change is not possible, the API will return the status SPI_SLAVE_STATUS_FAILURE.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Precondition:
 //Configure the SPI_SLAVE APP operation mode as 'Quad SPI'.
 //Description:
 //The following code expects a command from SPI master device (0x08, 0x01) to change the operation mode to 'Half Duplex'
 //After receiving the code, slave device changes opeation mode and starts waiting for 4 words of data.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[10];
   uint8_t Rec_Data[10];
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     SPI_SLAVE_Receive(&SPI_SLAVE_0, Rec_Data, 2);
     while(SPI_SLAVE_0.runtime->rx_busy)
     {
     }
     if((Rec_Data[0] == 0x08) && (Rec_Data[1] == 0x01))
     {
       if(SPI_SLAVE_SetMode(&SPI_SLAVE_0, XMC_SPI_CH_MODE_STANDARD_HALFDUPLEX) == SPI_SLAVE_STATUS_FAILURE)
       {
         while(1);
       }
       else
       {
         SPI_SLAVE_Receive(&SPI_SLAVE_0, Rec_Data, 4);
         while(SPI_SLAVE_0.runtime->rx_busy)
         {
         }
       }
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 379 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE_PIN_CONFIG::config, SPI_SLAVE::config, SPI_SLAVE_CONFIG::dx0_source, SPI_SLAVE_PIN_CONFIG::hw_control, SPI_SLAVE_CONFIG::mosi0_pin_config, SPI_SLAVE_CONFIG::mosi1_pin_config, SPI_SLAVE_PIN_CONFIG::pin, SPI_SLAVE_PIN_CONFIG::port, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_RUNTIME::spi_current_mode, SPI_SLAVE_lValidateModeChange(), SPI_SLAVE_STATUS_BUSY, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_RUNTIME::tx_busy, XMC_GPIO_HWCTRL_DISABLED, XMC_GPIO_Init(), XMC_GPIO_SetHardwareControl(), XMC_GPIO_SetMode(), XMC_SPI_CH_INPUT_DIN0, XMC_SPI_CH_MODE_DUAL, XMC_SPI_CH_MODE_QUAD, XMC_SPI_CH_MODE_STANDARD, XMC_SPI_CH_MODE_STANDARD_HALFDUPLEX, and XMC_SPI_CH_SetInputSource().
SPI_SLAVE_Transfer()
SPI_SLAVE_STATUS_t SPI_SLAVE_Transfer (const SPI_SLAVE_t *const handle, uint8_t * tx_dataptr, uint8_t * rx_dataptr, uint32_t count)
Registers a request for transmitting and receiving data simultaneously over SPI channel as a slave device.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
tx_dataptr Pointer to data of type uint8_t.
rx_dataptr Pointer to data of type uint8_t.
count Total no of words to be transmitted and received.
Range: minimum= 1, maximum= maximum supported by uint32_t.
 In DMA mode, a maximum of 4095 words can be transferred in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
 Imp Note: Return value should be validated by user to ensure that the request is registered.
Description:
Transmits and receives data simultaneously using the SPI channel as a slave device. API is applicable only in Full duplex</> operation mode. Data transfer happens based on the individual modes configured for transmission and reception.
 Two data pins MOSI and MISO will be used for receiving and transmitting data respectively. A callback function can be configured to execute after completing the transfer when 'Interrupt' or 'DMA' mode is used. The callback function should be configured for End of receive/transfer callback in the 'Interrupt Settings' tab. The callback function will be executed when the last word of data is received.
Example Usage:
  #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
//Precondition: Operation mode should be 'Full Duplex"
//Description: Transmit and receive 9 bytes of data from master in parallel.
  int main(void)
  {
    SPI_SLAVE_STATUS_t init_status;
    uint8_t Send_Data[] = {1,2,3,4,5,6,7,8,9};
    uint8_t Rec_Data[10];
    init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
    if(init_status == SPI_SLAVE_STATUS_SUCCESS)
    {
      SPI_SLAVE_Transfer(&SPI_SLAVE_0, Send_Data, Rec_Data, sizeof(Send_Data));
      while(SPI_SLAVE_0.runtime->rx_busy)
      {
      }
    }
    else
    {
     XMC_DEBUG("main: Application initialization failed");
     while(1U)
     {
     }
    }
     return 1U;
 }
Definition at line 801 of file spi_slave.c.
References SPI_SLAVE::config, SPI_SLAVE_CONFIG::receive_mode, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_RUNTIME::spi_current_mode, SPI_SLAVE_Receive(), SPI_SLAVE_STATUS_BUFFER_INVALID, SPI_SLAVE_STATUS_BUSY, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_TRANSFER_MODE_DIRECT, SPI_SLAVE_Transmit(), SPI_SLAVE_RUNTIME::tx_busy, XMC_ASSERT, and XMC_SPI_CH_MODE_STANDARD.
SPI_SLAVE_Transmit()
SPI_SLAVE_STATUS_t SPI_SLAVE_Transmit (const SPI_SLAVE_t *const handle, uint8_t * data_ptr, uint32_t count)
Registers a request for transmitting data over SPI channel as a slave device.
Parameters
handle SPI_SLAVE APP handle pointer of type SPI_SLAVE_t
data_ptr Pointer to data of type uint8_t.
count Total no of words to be transmitted.
Range: minimum= 1, maximum= maximum supported by uint32_t.
 In DMA mode, a maximum of 4095 words can be transmitted in one attempt.
Returns
SPI_SLAVE_STATUS_t: Status of transmit request.
 SPI_SLAVE_STATUS_SUCCESS if the request is accepted.
 SPI_SLAVE_STATUS_BUSY if a transmission is in progress.
 SPI_SLAVE_STATUS_BUFFER_INVALID if the data_ptr is NULL or count is 0.
 Imp Note: Return value should be validated by user to ensure that the request is registered.
Description:
Transmits data using the SPI channel as a slave device. Transmission is accomplished using the transmit mode as configured in the UI.
 Interrupt:
 The data transmission is accomplished using transmit interrupt. User can configure a callback function in the APP UI. When the data is fully transmitted, the callback function will be executed. If transmit FIFO is enabled, the trigger limit is set to 1. So the transmit interrupt will be generated when all the data in FIFO is moved out of FIFO. The APP handle's runtime structure is used to store the data pointer, count, data index and status of transmission. This function only registers a data transmission request if there is no active transmission in progress. Actual data transmission happens in the transmit interrupt service routine. A trigger is generated for the transmit interrupt to start loading the data to the transmit buffer. If transmit FIFO is configured, the data is filled into the FIFO. Transmit interrupt will be generated subsequently when the transmit FIFO is empty. At this point of time, if there is some more data to be transmitted, it is loaded to the FIFO again. When FIFO is not enabled, data is transmitted one byte at a time. On transmission of each byte an interrupt is generated and the next byte is transmitted in the interrupt service routine. Callback function is executed when all the data bytes are transmitted. If a callback function is not configured, user has to poll for the value of tx_busy flag of the APP handle structure(handle->runtime->tx_busy) to check for the completion of data transmission.
 DMA:
 A DMA channel is configured to provide data to the SPI channel transmit buffer. This removes the load off the CPU. This API will only configure and enable the DMA channel by specifying the data buffer and count of bytes to transmit. Rest is taken care without the CPU's intervention. User can configure a callback function in the APP UI. When the transmission is complete, the callback function will be executed. FIFO will not be used in DMA mode. Receive start interrupt is configured for triggering the DMA channel. So each byte is transmitted in the background through the DMA channel. If the callback function is not configured, handle->runtime->tx_busy flag can be checked to verify if the transmission is complete. Direct:
 Data will be transmitted using polling method. Status flags are used to check if data can be transmitted. Note: In Direct mode, the API blocks the CPU until the count of bytes requested is transmitted. If this behavior is not desired, use other APIs like SPI_SLAVE_TransmitWord, SPI_SLAVE_GetProtocolStatus etc.
Example Usage:
 #include <DAVE.h> //Declarations from DAVE Code Generation (includes SFR declaration)
 //Pre-condition:
 //Transmit mode should be configured as "Direct".
 //Description:
 //Transmits 9 bytes to the master.
 int main(void)
 {
   SPI_SLAVE_STATUS_t init_status;
   uint8_t Send_Data[] = {1,2,3,4,5,6,7,8,9};
   init_status = (SPI_SLAVE_STATUS_t)SPI_SLAVE_Init(&SPI_SLAVE_0);
   if(init_status == SPI_SLAVE_STATUS_SUCCESS)
   {
     SPI_SLAVE_Transmit(&SPI_SLAVE_0, Send_Data, sizeof(Send_Data));
     while(SPI_SLAVE_0.runtime->tx_busy)
     {
     }
   }
   else
   {
    XMC_DEBUG("main: Application initialization failed");
    while(1U)
    {
    }
   }
    return 1U;
}
Definition at line 158 of file spi_slave.c.
References SPI_SLAVE::config, SPI_SLAVE::runtime, SPI_SLAVE_StartTransmitIRQ(), SPI_SLAVE_STATUS_BUFFER_INVALID, SPI_SLAVE_STATUS_BUSY, SPI_SLAVE_STATUS_MODE_MISMATCH, SPI_SLAVE_TRANSFER_MODE_DIRECT, SPI_SLAVE_TRANSFER_MODE_DMA, SPI_SLAVE_TRANSFER_MODE_INTERRUPT, SPI_SLAVE_CONFIG::transmit_mode, and SPI_SLAVE_RUNTIME::tx_busy.