Dave/Model/APPS/FREERTOS/v4_1_2/Templates/heap_4.h File Reference
#include <stdlib.h>
#include `FreeRTOS.h`
#include `task.h`
Data Structures
struct A_BLOCK_LINK
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define heapMINIMUM_BLOCK_SIZE ((size_t) (xHeapStructSize << 1))
#define heapBITS_PER_BYTE ((size_t) 8)
Typedefs
typedef struct A_BLOCK_LINK BlockLink_t
Functions
static void prvInsertBlockIntoFreeList (BlockLink_t *pxBlockToInsert)
static void prvHeapInit (void)
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
size_t xPortGetFreeHeapSize (void)
size_t xPortGetMinimumEverFreeHeapSize (void)
void vPortInitialiseBlocks (void)
Variables
static uint8_t ucHeap [configTOTAL_HEAP_SIZE]
static const size_t xHeapStructSize = (sizeof(BlockLink_t) + ((size_t) (portBYTE_ALIGNMENT - 1))) & ~((size_t) portBYTE_ALIGNMENT_MASK)
static BlockLink_t xStart
static BlockLink_t * pxEnd = NULL
static size_t xFreeBytesRemaining = 0U
static size_t xMinimumEverFreeBytesRemaining = 0U
static size_t xBlockAllocatedBit = 0
Macro Definition Documentation
heapBITS_PER_BYTE
#define heapBITS_PER_BYTE ((size_t) 8)
Definition at line 57 of file heap_4.h.
heapMINIMUM_BLOCK_SIZE
#define heapMINIMUM_BLOCK_SIZE ((size_t) (xHeapStructSize << 1))
Definition at line 54 of file heap_4.h.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 42 of file heap_4.h.
Typedef Documentation
BlockLink_t
typedef struct A_BLOCK_LINK BlockLink_t
Function Documentation
prvHeapInit()
static void prvHeapInit (void) [static]
Definition at line 329 of file heap_4.h.
References configTOTAL_HEAP_SIZE, heapBITS_PER_BYTE, portBYTE_ALIGNMENT, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, ucHeap, xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, and xStart.
Referenced by pvPortMalloc().
prvInsertBlockIntoFreeList()
static void prvInsertBlockIntoFreeList (BlockLink_t * pxBlockToInsert) [static]
Definition at line 377 of file heap_4.h.
References mtCOVERAGE_TEST_MARKER, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, A_BLOCK_LINK::xBlockSize, and xStart.
Referenced by pvPortMalloc(), and vPortFree().
pvPortMalloc()
void* pvPortMalloc (size_t xWantedSize)
Definition at line 113 of file heap_4.h.
References configASSERT, heapMINIMUM_BLOCK_SIZE, mtCOVERAGE_TEST_MARKER, portBYTE_ALIGNMENT, prvHeapInit(), prvInsertBlockIntoFreeList(), pxEnd, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, vApplicationMallocFailedHook(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, xStart, and xTaskResumeAll().
vPortFree()
void vPortFree (void * pv)
Definition at line 263 of file heap_4.h.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList(), A_BLOCK_LINK::pxNextFreeBlock, traceFREE, vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, and xTaskResumeAll().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 323 of file heap_4.h.
References xNextFreeByte.
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 311 of file heap_4.h.
References xFreeBytesRemaining.
xPortGetMinimumEverFreeHeapSize()
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 317 of file heap_4.h.
References xMinimumEverFreeBytesRemaining.
Variable Documentation
pxEnd
BlockLink_t * pxEnd = NULL [static]
Definition at line 98 of file heap_4.h.
Referenced by prvHeapInit(), prvInsertBlockIntoFreeList(), and pvPortMalloc().
ucHeap
uint8_t ucHeap[configTOTAL_HEAP_SIZE] [static]
Definition at line 64 of file heap_4.h.
Referenced by prvHeapInit().
xBlockAllocatedBit
size_t xBlockAllocatedBit = 0 [static]
Definition at line 109 of file heap_4.h.
Referenced by prvHeapInit(), pvPortMalloc(), and vPortFree().
xFreeBytesRemaining
size_t xFreeBytesRemaining = 0U [static]
Definition at line 102 of file heap_4.h.
Referenced by prvHeapInit(), pvPortMalloc(), vPortFree(), and xPortGetFreeHeapSize().
xHeapStructSize
const size_t xHeapStructSize = (sizeof(BlockLink_t) + ((size_t) (portBYTE_ALIGNMENT - 1))) & ~((size_t) portBYTE_ALIGNMENT_MASK) [static]
Definition at line 95 of file heap_4.h.
Referenced by prvHeapInit(), pvPortMalloc(), and vPortFree().
xMinimumEverFreeBytesRemaining
size_t xMinimumEverFreeBytesRemaining = 0U [static]
Definition at line 103 of file heap_4.h.
Referenced by prvHeapInit(), pvPortMalloc(), and xPortGetMinimumEverFreeHeapSize().
xStart
BlockLink_t xStart [static]
Definition at line 98 of file heap_4.h.
Referenced by prvHeapInit(), prvInsertBlockIntoFreeList(), and pvPortMalloc().