SpiTask.c File Reference
#include `SpiTask.h`
Functions
void MySPILEDsToggling (uint8_t tyleRazy)
void MySPIErrorHandler (uint8_t errNumber)
void dec2hex (int num, char *myHex)
void SPI_Slave_Task (void *pvParameters)
Variables
QueueHandle_t xQueue
Function Documentation
dec2hex()
void dec2hex (int num, char * myHex)
Definition at line 25 of file SpiTask.c.
MySPIErrorHandler()
void MySPIErrorHandler (uint8_t errNumber)
Definition at line 19 of file SpiTask.c.
References MySPILEDsToggling(), pdMS_TO_TICKS, and vTaskDelay().
Referenced by SPI_Slave_Task().
MySPILEDsToggling()
void MySPILEDsToggling (uint8_t tyleRazy)
Definition at line 10 of file SpiTask.c.
References DIGITAL_IO_SetOutputHigh(), DIGITAL_IO_SetOutputLow(), LED0, and vTaskDelay().
Referenced by MySPIErrorHandler().
SPI_Slave_Task()
void SPI_Slave_Task (void * pvParameters)
Definition at line 57 of file SpiTask.c.
References SPI_SLAVE::channel, DATA_COUNT, DataToSend, MySPIErrorHandler(), pdMS_TO_TICKS, pdTRUE, SPI_SLAVE_0, SPI_SLAVE_Receive(), SPI_SLAVE_STATUS_SUCCESS, vTaskDelay(), xBlockTime, XMC_SPI_CH_GetStatusFlag(), XMC_SPI_CH_STATUS_FLAG_DX2S, xQueue, and xQueueSend.
Variable Documentation
xQueue
QueueHandle_t xQueue
Definition at line 13 of file main.c.
Referenced by SPI_Slave_Task().