SpiTask.h File Reference
#include <DAVE.h>
Macros
#define DATA_COUNT 8
Functions
void SPI_Slave_Task (void *pvParameters)
Macro Definition Documentation
DATA_COUNT
#define DATA_COUNT 8
Definition at line 7 of file SpiTask.h.
Function Documentation
SPI_Slave_Task()
void SPI_Slave_Task (void * pvParameters)
Definition at line 57 of file SpiTask.c.
References SPI_SLAVE::channel, DATA_COUNT, DataToSend, MySPIErrorHandler(), pdMS_TO_TICKS, pdTRUE, SPI_SLAVE_0, SPI_SLAVE_Receive(), SPI_SLAVE_STATUS_SUCCESS, vTaskDelay(), xBlockTime, XMC_SPI_CH_GetStatusFlag(), XMC_SPI_CH_STATUS_FLAG_DX2S, xQueue, and xQueueSend.