UartTask.h File Reference
#include <DAVE.h>
#include <stdio.h>
Functions
void fEndOfTransmitCallback (void)
void UART_Task (void *pvParameters)
Function Documentation
fEndOfTransmitCallback()
void fEndOfTransmitCallback (void)
Definition at line 60 of file UartTask.c.
References bTransmitBusy.
UART_Task()
void UART_Task (void * pvParameters)
Definition at line 68 of file UartTask.c.
References DataToReceive, DIGITAL_IO_SetOutputHigh(), DIGITAL_IO_SetOutputLow(), fMyPrintf(), iMainMenuLoopCounter, mb, MyUARTErrorHandler(), pdMS_TO_TICKS, pdTRUE, ucUartReceivedDataGlobal, VDIOP0_0, VDIOP0_5, vTaskDelay(), xDelay, xQueue, and xQueueReceive().