Worker1Task.h File Reference
#include <DAVE.h>
Functions
void worker1_task (void *pvParameters)
Variables
xQueueHandle Queue_id
xTaskHandle worker1_id
Function Documentation
worker1_task()
void worker1_task (void * pvParameters)
Definition at line 3 of file Worker1Task.c.
References DIGITAL_IO_ToggleOutput(), LED0, Queue_id, vTaskDelete(), vTaskSuspend(), worker1_id, and xQueueReceive().
Referenced by main().
Variable Documentation
Queue_id
xQueueHandle Queue_id
Definition at line 14 of file main.c.
worker1_id
xTaskHandle worker1_id
Definition at line 19 of file main.c.
Referenced by main(), and worker1_task().