Worker2Task.h File Reference
#include <DAVE.h>
Functions
void worker2_task (void *pvParameters)
Variables
xQueueHandle Queue_id
xTaskHandle worker2_id
Function Documentation
worker2_task()
void worker2_task (void * pvParameters)
Definition at line 4 of file Worker2Task.c.
References DIGITAL_IO_ToggleOutput(), LED1, Queue_id, vTaskDelete(), vTaskSuspend(), worker2_id, and xQueueReceive().
Referenced by main().
Variable Documentation
Queue_id
xQueueHandle Queue_id
Definition at line 14 of file main.c.
Referenced by main(), worker1_task(), and worker2_task().
worker2_id
xTaskHandle worker2_id
Definition at line 20 of file main.c.
Referenced by main(), and worker2_task().