Worker2Task.c File Reference
#include `Worker2Task.h`
Functions
void worker2_task (void *pvParameters)
Function Documentation
worker2_task()
void worker2_task (void * pvParameters)
Definition at line 4 of file Worker2Task.c.
References DIGITAL_IO_ToggleOutput(), LED1, Queue_id, vTaskDelete(), vTaskSuspend(), worker2_id, and xQueueReceive().
Referenced by main().