Worker1Task.c File Reference
#include `Worker1Task.h`
Functions
void worker1_task (void *pvParameters)
Function Documentation
worker1_task()
void worker1_task (void * pvParameters)
Definition at line 3 of file Worker1Task.c.
References DIGITAL_IO_ToggleOutput(), LED0, Queue_id, vTaskDelete(), vTaskSuspend(), worker1_id, and xQueueReceive().
Referenced by main().