NVIC Functions
Functions that manage interrupts and exceptions via the NVIC.
Modules
FPU Functions
Function that provides FPU type.
__STATIC_INLINE void __NVIC_EnableIRQ (IRQn_Type IRQn)
Enable Interrupt.
__STATIC_INLINE uint32_t __NVIC_GetEnableIRQ (IRQn_Type IRQn)
Get Interrupt Enable status.
__STATIC_INLINE void __NVIC_DisableIRQ (IRQn_Type IRQn)
Disable Interrupt.
__STATIC_INLINE uint32_t __NVIC_GetPendingIRQ (IRQn_Type IRQn)
Get Pending Interrupt.
__STATIC_INLINE void __NVIC_SetPendingIRQ (IRQn_Type IRQn)
Set Pending Interrupt.
__STATIC_INLINE void __NVIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear Pending Interrupt.
__STATIC_INLINE void __NVIC_SetPriority (IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
__STATIC_INLINE uint32_t __NVIC_GetPriority (IRQn_Type IRQn)
Get Interrupt Priority.
__STATIC_INLINE void __NVIC_SetVector (IRQn_Type IRQn, uint32_t vector)
Set Interrupt Vector.
__STATIC_INLINE uint32_t __NVIC_GetVector (IRQn_Type IRQn)
Get Interrupt Vector.
__STATIC_INLINE void __NVIC_SystemReset (void)
System Reset.
#define NVIC_EnableIRQ __NVIC_EnableIRQ
#define NVIC_GetEnableIRQ __NVIC_GetEnableIRQ
#define NVIC_DisableIRQ __NVIC_DisableIRQ
#define NVIC_GetPendingIRQ __NVIC_GetPendingIRQ
#define NVIC_SetPendingIRQ __NVIC_SetPendingIRQ
#define NVIC_ClearPendingIRQ __NVIC_ClearPendingIRQ
#define NVIC_SetPriority __NVIC_SetPriority
#define NVIC_GetPriority __NVIC_GetPriority
#define NVIC_SystemReset __NVIC_SystemReset
#define NVIC_SetVector __NVIC_SetVector
#define NVIC_GetVector __NVIC_GetVector
#define NVIC_USER_IRQ_OFFSET 16
#define _BIT_SHIFT(IRQn) (((((uint32_t)(int32_t)(IRQn))) & 0x03UL) * 8UL)
#define _SHP_IDX(IRQn) ((((((uint32_t)(int32_t)(IRQn)) & 0x0FUL)-8UL) >> 2UL))
#define _IP_IDX(IRQn) ((((uint32_t)(int32_t)(IRQn)) >> 2UL))
Detailed Description
Functions that manage interrupts and exceptions via the NVIC.
Macro Definition Documentation
_BIT_SHIFT
#define _BIT_SHIFT(IRQn) (((((uint32_t)(int32_t)(IRQn))) & 0x03UL) * 8UL)
Definition at line 605 of file core_cm0.h.
_IP_IDX
#define _IP_IDX(IRQn) ((((uint32_t)(int32_t)(IRQn)) >> 2UL))
Definition at line 607 of file core_cm0.h.
_SHP_IDX
#define _SHP_IDX(IRQn) ((((((uint32_t)(int32_t)(IRQn)) & 0x0FUL)-8UL) >> 2UL))
Definition at line 606 of file core_cm0.h.
NVIC_ClearPendingIRQ
#define NVIC_ClearPendingIRQ __NVIC_ClearPendingIRQ
Definition at line 583 of file core_cm0.h.
NVIC_DisableIRQ
#define NVIC_DisableIRQ __NVIC_DisableIRQ
Definition at line 580 of file core_cm0.h.
NVIC_EnableIRQ
#define NVIC_EnableIRQ __NVIC_EnableIRQ
Definition at line 578 of file core_cm0.h.
NVIC_GetEnableIRQ
#define NVIC_GetEnableIRQ __NVIC_GetEnableIRQ
Definition at line 579 of file core_cm0.h.
NVIC_GetPendingIRQ
#define NVIC_GetPendingIRQ __NVIC_GetPendingIRQ
Definition at line 581 of file core_cm0.h.
NVIC_GetPriority
#define NVIC_GetPriority __NVIC_GetPriority
Definition at line 586 of file core_cm0.h.
NVIC_GetVector
#define NVIC_GetVector __NVIC_GetVector
Definition at line 597 of file core_cm0.h.
NVIC_SetPendingIRQ
#define NVIC_SetPendingIRQ __NVIC_SetPendingIRQ
Definition at line 582 of file core_cm0.h.
NVIC_SetPriority
#define NVIC_SetPriority __NVIC_SetPriority
Definition at line 585 of file core_cm0.h.
NVIC_SetVector
#define NVIC_SetVector __NVIC_SetVector
Definition at line 596 of file core_cm0.h.
NVIC_SystemReset
#define NVIC_SystemReset __NVIC_SystemReset
Definition at line 587 of file core_cm0.h.
NVIC_USER_IRQ_OFFSET
#define NVIC_USER_IRQ_OFFSET 16
Definition at line 600 of file core_cm0.h.
Function Documentation
__NVIC_ClearPendingIRQ()
__STATIC_INLINE void __NVIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear Pending Interrupt.
Clears the pending bit of a device specific interrupt in the NVIC pending register.
Parameters
 in IRQn Device specific interrupt number.
Note
IRQn must not be negative.
Definition at line 704 of file core_cm0.h.
References NVIC.
__NVIC_DisableIRQ()
__STATIC_INLINE void __NVIC_DisableIRQ (IRQn_Type IRQn)
Disable Interrupt.
Disables a device specific interrupt in the NVIC interrupt controller.
Parameters
 in IRQn Device specific interrupt number.
Note
IRQn must not be negative.
Definition at line 651 of file core_cm0.h.
References __DSB(), __ISB(), and NVIC.
__NVIC_EnableIRQ()
__STATIC_INLINE void __NVIC_EnableIRQ (IRQn_Type IRQn)
Enable Interrupt.
Enables a device specific interrupt in the NVIC interrupt controller.
Parameters
 in IRQn Device specific interrupt number.
Note
IRQn must not be negative.
Definition at line 615 of file core_cm0.h.
References NVIC.
__NVIC_GetEnableIRQ()
__STATIC_INLINE uint32_t __NVIC_GetEnableIRQ (IRQn_Type IRQn)
Get Interrupt Enable status.
Returns a device specific interrupt enable status from the NVIC interrupt controller.
Parameters
 in IRQn Device specific interrupt number.
Returns
0 Interrupt is not enabled.
1 Interrupt is enabled.
Note
IRQn must not be negative.
Definition at line 632 of file core_cm0.h.
References NVIC.
__NVIC_GetPendingIRQ()
__STATIC_INLINE uint32_t __NVIC_GetPendingIRQ (IRQn_Type IRQn)
Get Pending Interrupt.
Reads the NVIC pending register and returns the pending bit for the specified device specific interrupt.
Parameters
 in IRQn Device specific interrupt number.
Returns
0 Interrupt status is not pending.
1 Interrupt status is pending.
Note
IRQn must not be negative.
Definition at line 670 of file core_cm0.h.
References NVIC.
__NVIC_GetPriority()
__STATIC_INLINE uint32_t __NVIC_GetPriority (IRQn_Type IRQn)
Get Interrupt Priority.
Reads the priority of a device specific interrupt or a processor exception. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception.
Parameters
 in IRQn Interrupt number.
Returns
Interrupt Priority. Value is aligned automatically to the implemented priority bits of the microcontroller.
Definition at line 746 of file core_cm0.h.
References __NVIC_PRIO_BITS, _BIT_SHIFT, _IP_IDX, _SHP_IDX, NVIC, and SCB.
__NVIC_GetVector()
__STATIC_INLINE uint32_t __NVIC_GetVector (IRQn_Type IRQn)
Get Interrupt Vector.
Reads an interrupt vector from interrupt vector table. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception.
Parameters
 in IRQn Interrupt number.
Returns
Address of interrupt handler function
Definition at line 784 of file core_cm0.h.
References NVIC_USER_IRQ_OFFSET.
__NVIC_SetPendingIRQ()
__STATIC_INLINE void __NVIC_SetPendingIRQ (IRQn_Type IRQn)
Set Pending Interrupt.
Sets the pending bit of a device specific interrupt in the NVIC pending register.
Parameters
 in IRQn Device specific interrupt number.
Note
IRQn must not be negative.
Definition at line 689 of file core_cm0.h.
References NVIC.
__NVIC_SetPriority()
__STATIC_INLINE void __NVIC_SetPriority (IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
Sets the priority of a device specific interrupt or a processor exception. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception.
Parameters
 in IRQn Interrupt number.
 in priority Priority to set.
Note
The priority cannot be set for every processor exception.
Definition at line 722 of file core_cm0.h.
References __NVIC_PRIO_BITS, _BIT_SHIFT, _IP_IDX, _SHP_IDX, NVIC, and SCB.
__NVIC_SetVector()
__STATIC_INLINE void __NVIC_SetVector (IRQn_Type IRQn, uint32_t vector)
Set Interrupt Vector.
Sets an interrupt vector in SRAM based interrupt vector table. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception. Address 0 must be mapped to SRAM.
Parameters
 in IRQn Interrupt number
 in vector Address of interrupt handler function
Definition at line 769 of file core_cm0.h.
References NVIC_USER_IRQ_OFFSET.
__NVIC_SystemReset()
__STATIC_INLINE void __NVIC_SystemReset (void)
System Reset.
Initiates a system reset request to reset the MCU.
Definition at line 795 of file core_cm0.h.
References __DSB(), __NOP, SCB, SCB_AIRCR_SYSRESETREQ_Msk, and SCB_AIRCR_VECTKEY_Pos.