COMMON
Common APIs to all peripherals for XMC microcontroller family.
Data Structures
struct XMC_DRIVER_VERSION
struct XMC_PRIOARRAY_ITEM
struct XMC_PRIOARRAY
Macros
#define XMC_LIB_MAJOR_VERSION (2U)
#define XMC_LIB_MINOR_VERSION (1U)
#define XMC_LIB_PATCH_VERSION (18U)
#define XMC_LIB_VERSION ((XMC_LIB_MAJOR_VERSION << 16U) + (XMC_LIB_MINOR_VERSION << 8U) + XMC_LIB_PATCH_VERSION)
#define XMC_ASSERT(msg, exp) { ; }
#define XMC_DEBUG(...) { ; }
#define XMC_UNUSED_ARG(x) (void)x
#define XMC_STRUCT_INIT(m) memset(&m, 0, sizeof(m))
#define XMC_PRIOARRAY_DEF(name, size)
#define XMC_PRIOARRAY(name) &prioarray_def_##name
Typedefs
typedef struct XMC_DRIVER_VERSION XMC_DRIVER_VERSION_t
typedef void * XMC_LIST_t
typedef struct XMC_PRIOARRAY_ITEM XMC_PRIOARRAY_ITEM_t
typedef struct XMC_PRIOARRAY XMC_PRIOARRAY_t
Functions
void XMC_AssertHandler (const char *const msg, const char *const file, uint32_t line)
void XMC_LIST_Init (XMC_LIST_t *list)
void XMC_LIST_Add (XMC_LIST_t *list, void *const item)
void XMC_LIST_Remove (XMC_LIST_t *list, void *const item)
uint32_t XMC_LIST_GetLength (XMC_LIST_t *list)
void * XMC_LIST_GetHead (XMC_LIST_t *list)
void * XMC_LIST_GetTail (XMC_LIST_t *list)
void XMC_LIST_Insert (XMC_LIST_t *list, void *prev_item, void *new_item)
void XMC_PRIOARRAY_Init (XMC_PRIOARRAY_t *prioarray)
void XMC_PRIOARRAY_Add (XMC_PRIOARRAY_t *prioarray, int32_t item, int32_t priority)
void XMC_PRIOARRAY_Remove (XMC_PRIOARRAY_t *prioarray, int32_t item)
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetHead (XMC_PRIOARRAY_t *prioarray)
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetTail (XMC_PRIOARRAY_t *prioarray)
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetItemPriority (XMC_PRIOARRAY_t *prioarray, int32_t item)
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetItemNext (XMC_PRIOARRAY_t *prioarray, int32_t item)
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetItemPrevious (XMC_PRIOARRAY_t *prioarray, int32_t item)
Detailed Description
Common APIs to all peripherals for XMC microcontroller family.
Macro Definition Documentation
XMC_ASSERT
#define XMC_ASSERT(msg, exp) { ; }
Definition at line 133 of file xmc_common.h.
XMC_DEBUG
#define XMC_DEBUG(...) { ; }
Definition at line 140 of file xmc_common.h.
XMC_LIB_MAJOR_VERSION
#define XMC_LIB_MAJOR_VERSION (2U)
Definition at line 93 of file xmc_common.h.
XMC_LIB_MINOR_VERSION
#define XMC_LIB_MINOR_VERSION (1U)
Definition at line 94 of file xmc_common.h.
XMC_LIB_PATCH_VERSION
#define XMC_LIB_PATCH_VERSION (18U)
Definition at line 95 of file xmc_common.h.
XMC_LIB_VERSION
#define XMC_LIB_VERSION ((XMC_LIB_MAJOR_VERSION << 16U) + (XMC_LIB_MINOR_VERSION << 8U) + XMC_LIB_PATCH_VERSION)
Definition at line 97 of file xmc_common.h.
XMC_PRIOARRAY
#define XMC_PRIOARRAY(name) &prioarray_def_##name
Definition at line 151 of file xmc_common.h.
XMC_PRIOARRAY_DEF
#define XMC_PRIOARRAY_DEF(name, size)
Value:
XMC_PRIOARRAY_ITEM_t prioarray_m_##name[size + 2]; \
XMC_PRIOARRAY_t prioarray_def_##name = {(size), (prioarray_m_##name)};
Definition at line 147 of file xmc_common.h.
XMC_STRUCT_INIT
#define XMC_STRUCT_INIT(m) memset(&m, 0, sizeof(m))
Definition at line 145 of file xmc_common.h.
XMC_UNUSED_ARG
#define XMC_UNUSED_ARG(x) (void)x
Definition at line 143 of file xmc_common.h.
Typedef Documentation
XMC_DRIVER_VERSION_t
typedef struct XMC_DRIVER_VERSION XMC_DRIVER_VERSION_t
XMC_LIST_t
typedef void* XMC_LIST_t
Definition at line 169 of file xmc_common.h.
XMC_PRIOARRAY_ITEM_t
typedef struct XMC_PRIOARRAY_ITEM XMC_PRIOARRAY_ITEM_t
XMC_PRIOARRAY_t
typedef struct XMC_PRIOARRAY XMC_PRIOARRAY_t
Function Documentation
XMC_AssertHandler()
void XMC_AssertHandler (const char *const msg, const char *const file, uint32_t line)
XMC_LIST_Add()
void XMC_LIST_Add (XMC_LIST_t * list, void *const item)
Definition at line 106 of file xmc_common.c.
References list::next, and XMC_LIST_GetTail().
XMC_LIST_GetHead()
void* XMC_LIST_GetHead (XMC_LIST_t * list)
Definition at line 82 of file xmc_common.c.
XMC_LIST_GetLength()
uint32_t XMC_LIST_GetLength (XMC_LIST_t * list)
XMC_LIST_GetTail()
void* XMC_LIST_GetTail (XMC_LIST_t * list)
Definition at line 87 of file xmc_common.c.
References list::next.
Referenced by XMC_LIST_Add().
XMC_LIST_Init()
void XMC_LIST_Init (XMC_LIST_t * list)
Definition at line 77 of file xmc_common.c.
XMC_LIST_Insert()
void XMC_LIST_Insert (XMC_LIST_t * list, void * prev_item, void * new_item)
Definition at line 152 of file xmc_common.c.
References list::next.
XMC_LIST_Remove()
void XMC_LIST_Remove (XMC_LIST_t * list, void *const item)
Definition at line 123 of file xmc_common.c.
References list::next.
XMC_PRIOARRAY_Add()
void XMC_PRIOARRAY_Add (XMC_PRIOARRAY_t * prioarray, int32_t item, int32_t priority)
Definition at line 182 of file xmc_common.c.
References XMC_PRIOARRAY::items, list::next, XMC_PRIOARRAY_ITEM::next, XMC_PRIOARRAY_ITEM::previous, XMC_PRIOARRAY_ITEM::priority, XMC_ASSERT, XMC_PRIOARRAY_GetHead(), XMC_PRIOARRAY_GetItemNext(), and XMC_PRIOARRAY_GetItemPriority().
XMC_PRIOARRAY_GetHead()
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetHead (XMC_PRIOARRAY_t * prioarray)
Definition at line 256 of file xmc_common.h.
References XMC_PRIOARRAY::items, XMC_PRIOARRAY_ITEM::next, XMC_PRIOARRAY::size, and XMC_ASSERT.
Referenced by XMC_PRIOARRAY_Add().
XMC_PRIOARRAY_GetItemNext()
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetItemNext (XMC_PRIOARRAY_t * prioarray, int32_t item)
Definition at line 283 of file xmc_common.h.
References XMC_PRIOARRAY::items, XMC_PRIOARRAY_ITEM::next, and XMC_ASSERT.
Referenced by XMC_PRIOARRAY_Add().
XMC_PRIOARRAY_GetItemPrevious()
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetItemPrevious (XMC_PRIOARRAY_t * prioarray, int32_t item)
Definition at line 292 of file xmc_common.h.
References XMC_PRIOARRAY::items, XMC_PRIOARRAY_ITEM::previous, and XMC_ASSERT.
XMC_PRIOARRAY_GetItemPriority()
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetItemPriority (XMC_PRIOARRAY_t * prioarray, int32_t item)
Definition at line 274 of file xmc_common.h.
References XMC_PRIOARRAY::items, XMC_PRIOARRAY_ITEM::priority, and XMC_ASSERT.
Referenced by XMC_PRIOARRAY_Add().
XMC_PRIOARRAY_GetTail()
__STATIC_INLINE int32_t XMC_PRIOARRAY_GetTail (XMC_PRIOARRAY_t * prioarray)
Definition at line 265 of file xmc_common.h.
References XMC_PRIOARRAY::items, XMC_PRIOARRAY_ITEM::previous, XMC_PRIOARRAY::size, and XMC_ASSERT.
XMC_PRIOARRAY_Init()
void XMC_PRIOARRAY_Init (XMC_PRIOARRAY_t * prioarray)
Definition at line 166 of file xmc_common.c.
References XMC_PRIOARRAY::items, XMC_PRIOARRAY_ITEM::next, XMC_PRIOARRAY_ITEM::previous, XMC_PRIOARRAY_ITEM::priority, XMC_PRIOARRAY::size, and XMC_ASSERT.
XMC_PRIOARRAY_Remove()
void XMC_PRIOARRAY_Remove (XMC_PRIOARRAY_t * prioarray, int32_t item)
Definition at line 205 of file xmc_common.c.
References XMC_PRIOARRAY::items, list::next, XMC_PRIOARRAY_ITEM::next, XMC_PRIOARRAY_ITEM::previous, and XMC_ASSERT.