I2S
(IIS) driver for the XMC microcontroller family.
Data Structures
struct XMC_I2S_CH_CONFIG
I2S_CH configuration structure.
Typedefs
typedef enum XMC_I2S_CH_STATUS XMC_I2S_CH_STATUS_t
I2S Status.
typedef enum XMC_I2S_CH_STATUS_FLAG XMC_I2S_CH_STATUS_FLAG_t
I2S status flag.
typedef enum XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_t
I2S Baudrate Generator shift clock output.
typedef enum XMC_I2S_CH_INTERRUPT_NODE_POINTER XMC_I2S_CH_INTERRUPT_NODE_POINTER_t
I2S channel interrupt node pointers.
typedef enum XMC_I2S_CH_EVENT XMC_I2S_CH_EVENT_t
I2S events.
typedef enum XMC_I2S_CH_WA_POLARITY XMC_I2S_CH_WA_POLARITY_t
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
typedef enum XMC_I2S_CH_CHANNEL XMC_I2S_CH_CHANNEL_t
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
typedef enum XMC_I2S_CH_INPUT XMC_I2S_CH_INPUT_t
I2S input stage selection.
typedef enum XMC_I2S_CH_BUS_MODE XMC_I2S_CH_BUS_MODE_t
Defines the I2S bus mode.
typedef struct XMC_I2S_CH_CONFIG XMC_I2S_CH_CONFIG_t
I2S_CH configuration structure.
Enumerations
enum XMC_I2S_CH_STATUS { XMC_I2S_CH_STATUS_OK,
XMC_I2S_CH_STATUS_ERROR,
XMC_I2S_CH_STATUS_BUSY
 }
I2S Status.
enum XMC_I2S_CH_STATUS_FLAG {
XMC_I2S_CH_STATUS_FLAG_WORD_ADDRESS = USIC_CH_PSR_IISMode_WA_Msk,
XMC_I2S_CH_STATUS_FLAG_DX2S = USIC_CH_PSR_IISMode_DX2S_Msk,
XMC_I2S_CH_STATUS_FLAG_DX2T_EVENT_DETECTED = USIC_CH_PSR_IISMode_DX2TEV_Msk,
XMC_I2S_CH_STATUS_FLAG_WA_FALLING_EDGE_EVENT = USIC_CH_PSR_IISMode_WAFE_Msk,
XMC_I2S_CH_STATUS_FLAG_WA_RISING_EDGE_EVENT = USIC_CH_PSR_IISMode_WARE_Msk,
XMC_I2S_CH_STATUS_FLAG_WA_GENERATION_END = USIC_CH_PSR_IISMode_END_Msk,
XMC_I2S_CH_STATUS_FLAG_RECEIVER_START_INDICATION = USIC_CH_PSR_IISMode_RSIF_Msk,
XMC_I2S_CH_STATUS_FLAG_DATA_LOST_INDICATION = USIC_CH_PSR_IISMode_DLIF_Msk,
XMC_I2S_CH_STATUS_FLAG_TRANSMIT_SHIFT_INDICATION = USIC_CH_PSR_IISMode_TSIF_Msk,
XMC_I2S_CH_STATUS_FLAG_TRANSMIT_BUFFER_INDICATION = USIC_CH_PSR_IISMode_TBIF_Msk,
XMC_I2S_CH_STATUS_FLAG_RECEIVE_INDICATION = USIC_CH_PSR_IISMode_RIF_Msk,
XMC_I2S_CH_STATUS_FLAG_ALTERNATIVE_RECEIVE_INDICATION = USIC_CH_PSR_IISMode_AIF_Msk,
XMC_I2S_CH_STATUS_FLAG_BAUD_RATE_GENERATOR_INDICATION = USIC_CH_PSR_IISMode_BRGIF_Msk
 }
I2S status flag.
enum XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT { XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_SCLK = XMC_USIC_CH_BRG_SHIFT_CLOCK_OUTPUT_SCLK,
XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_DX1 = XMC_USIC_CH_BRG_SHIFT_CLOCK_OUTPUT_DX1
 }
I2S Baudrate Generator shift clock output.
enum XMC_I2S_CH_INTERRUPT_NODE_POINTER {
XMC_I2S_CH_INTERRUPT_NODE_POINTER_TRANSMIT_SHIFT = XMC_USIC_CH_INTERRUPT_NODE_POINTER_TRANSMIT_SHIFT,
XMC_I2S_CH_INTERRUPT_NODE_POINTER_TRANSMIT_BUFFER = XMC_USIC_CH_INTERRUPT_NODE_POINTER_TRANSMIT_BUFFER,
XMC_I2S_CH_INTERRUPT_NODE_POINTER_RECEIVE = XMC_USIC_CH_INTERRUPT_NODE_POINTER_RECEIVE,
XMC_I2S_CH_INTERRUPT_NODE_POINTER_ALTERNATE_RECEIVE = XMC_USIC_CH_INTERRUPT_NODE_POINTER_ALTERNATE_RECEIVE,
XMC_I2S_CH_INTERRUPT_NODE_POINTER_PROTOCOL = XMC_USIC_CH_INTERRUPT_NODE_POINTER_PROTOCOL
 }
I2S channel interrupt node pointers.
enum XMC_I2S_CH_EVENT {
XMC_I2S_CH_EVENT_RECEIVE_START = USIC_CH_CCR_RSIEN_Msk,
XMC_I2S_CH_EVENT_DATA_LOST = USIC_CH_CCR_DLIEN_Msk,
XMC_I2S_CH_EVENT_TRANSMIT_SHIFT = USIC_CH_CCR_TSIEN_Msk,
XMC_I2S_CH_EVENT_TRANSMIT_BUFFER = USIC_CH_CCR_TBIEN_Msk,
XMC_I2S_CH_EVENT_STANDARD_RECEIVE = USIC_CH_CCR_RIEN_Msk,
XMC_I2S_CH_EVENT_ALTERNATIVE_RECEIVE = USIC_CH_CCR_AIEN_Msk,
XMC_I2S_CH_EVENT_BAUD_RATE_GENERATOR = USIC_CH_CCR_BRGIEN_Msk,
XMC_I2S_CH_EVENT_WA_FALLING_EDGE = USIC_CH_PCR_IISMode_WAFEIEN_Msk << 2U,
XMC_I2S_CH_EVENT_WA_RISING_EDGE = USIC_CH_PCR_IISMode_WAREIEN_Msk << 2U,
XMC_I2S_CH_EVENT_WA_GENERATION_END = USIC_CH_PCR_IISMode_ENDIEN_Msk << 2U,
XMC_I2S_CH_EVENT_DX2TIEN_ACTIVATED = USIC_CH_PCR_IISMode_DX2TIEN_Msk << 2U
 }
I2S events.
enum XMC_I2S_CH_WA_POLARITY { XMC_I2S_CH_WA_POLARITY_DIRECT = 0x0UL,
XMC_I2S_CH_WA_POLARITY_INVERTED = 0x1UL << USIC_CH_PCR_IISMode_SELINV_Pos
 }
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
enum XMC_I2S_CH_CHANNEL { XMC_I2S_CH_CHANNEL_1_LEFT = 0U,
XMC_I2S_CH_CHANNEL_2_RIGHT = 1U
 }
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
enum XMC_I2S_CH_INPUT { XMC_I2S_CH_INPUT_DIN0 = 0UL,
XMC_I2S_CH_INPUT_SLAVE_SCLKIN = 1UL,
XMC_I2S_CH_INPUT_SLAVE_WA = 2UL
 }
I2S input stage selection.
enum XMC_I2S_CH_BUS_MODE { XMC_I2S_CH_BUS_MODE_MASTER,
XMC_I2S_CH_BUS_MODE_SLAVE
 }
Defines the I2S bus mode.
Functions
void XMC_I2S_CH_Init (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_CONFIG_t *const config)
__STATIC_INLINE void XMC_I2S_CH_Start (XMC_USIC_CH_t *const channel)
XMC_I2S_CH_STATUS_t XMC_I2S_CH_Stop (XMC_USIC_CH_t *const channel)
XMC_I2S_CH_STATUS_t XMC_I2S_CH_SetBaudrate (XMC_USIC_CH_t *const channel, const uint32_t rate)
void XMC_I2S_CH_SetSystemWordLength (XMC_USIC_CH_t *const channel, uint32_t sclk_cycles_system_word_length)
void XMC_I2S_CH_Transmit (XMC_USIC_CH_t *const channel, const uint16_t data, const XMC_I2S_CH_CHANNEL_t channel_number)
__STATIC_INLINE void XMC_I2S_CH_Receive (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_CHANNEL_t channel_number)
uint16_t XMC_I2S_CH_GetReceivedData (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_SetBitOrderLsbFirst (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_SetBitOrderMsbFirst (XMC_USIC_CH_t *const channel)
void XMC_I2S_CH_EnableEvent (XMC_USIC_CH_t *const channel, const uint32_t event)
void XMC_I2S_CH_DisableEvent (XMC_USIC_CH_t *const channel, const uint32_t event)
__STATIC_INLINE uint32_t XMC_I2S_CH_GetStatusFlag (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_ClearStatusFlag (XMC_USIC_CH_t *const channel, const uint32_t flag)
__STATIC_INLINE void XMC_I2S_CH_EnableMasterClock (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_DisableMasterClock (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_ConfigureShiftClockOutput (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_t clock_output)
__STATIC_INLINE void XMC_I2S_CH_SetWordLength (XMC_USIC_CH_t *const channel, const uint8_t word_length)
__STATIC_INLINE void XMC_I2S_CH_SetFrameLength (XMC_USIC_CH_t *const channel, const uint8_t frame_length)
__STATIC_INLINE void XMC_I2S_CH_SetInputSource (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INPUT_t input, const uint8_t source)
__STATIC_INLINE void XMC_I2S_CH_WordAddressSignalPolarity (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_WA_POLARITY_t wa_inversion)
__STATIC_INLINE void XMC_I2S_CH_EnableInputInversion (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INPUT_t input)
__STATIC_INLINE void XMC_I2S_CH_DisableInputInversion (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INPUT_t input)
__STATIC_INLINE void XMC_I2S_CH_SetInterruptNodePointer (XMC_USIC_CH_t *const channel, const uint8_t service_request)
__STATIC_INLINE void XMC_I2S_CH_SelectInterruptNodePointer (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INTERRUPT_NODE_POINTER_t interrupt_node, const uint32_t service_request)
__STATIC_INLINE void XMC_I2S_CH_TriggerServiceRequest (XMC_USIC_CH_t *const channel, const uint32_t service_request_line)
__STATIC_INLINE void XMC_I2S_CH_EnableDelayCompensation (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_DisableDelayCompensation (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_EnableDataTransmission (XMC_USIC_CH_t *const channel)
__STATIC_INLINE void XMC_I2S_CH_DisableDataTransmission (XMC_USIC_CH_t *const channel)
Detailed Description
(IIS) driver for the XMC microcontroller family.
USIC IIS Features:
Typedef Documentation
XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_t
typedef enum XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_t
I2S Baudrate Generator shift clock output.
XMC_I2S_CH_BUS_MODE_t
typedef enum XMC_I2S_CH_BUS_MODE XMC_I2S_CH_BUS_MODE_t
Defines the I2S bus mode.
XMC_I2S_CH_CHANNEL_t
typedef enum XMC_I2S_CH_CHANNEL XMC_I2S_CH_CHANNEL_t
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
XMC_I2S_CH_CONFIG_t
typedef struct XMC_I2S_CH_CONFIG XMC_I2S_CH_CONFIG_t
I2S_CH configuration structure.
XMC_I2S_CH_EVENT_t
typedef enum XMC_I2S_CH_EVENT XMC_I2S_CH_EVENT_t
I2S events.
XMC_I2S_CH_INPUT_t
typedef enum XMC_I2S_CH_INPUT XMC_I2S_CH_INPUT_t
I2S input stage selection.
XMC_I2S_CH_INTERRUPT_NODE_POINTER_t
typedef enum XMC_I2S_CH_INTERRUPT_NODE_POINTER XMC_I2S_CH_INTERRUPT_NODE_POINTER_t
I2S channel interrupt node pointers.
XMC_I2S_CH_STATUS_FLAG_t
typedef enum XMC_I2S_CH_STATUS_FLAG XMC_I2S_CH_STATUS_FLAG_t
I2S status flag.
XMC_I2S_CH_STATUS_t
typedef enum XMC_I2S_CH_STATUS XMC_I2S_CH_STATUS_t
I2S Status.
XMC_I2S_CH_WA_POLARITY_t
typedef enum XMC_I2S_CH_WA_POLARITY XMC_I2S_CH_WA_POLARITY_t
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
Enumeration Type Documentation
XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT
enum XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT
I2S Baudrate Generator shift clock output.
Enumerator
XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_SCLK Baudrate Generator shift clock output: SCLK
XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_DX1 Clock obtained as input from master: DX1
Definition at line 142 of file xmc_i2s.h.
XMC_I2S_CH_BUS_MODE
enum XMC_I2S_CH_BUS_MODE
Defines the I2S bus mode.
Enumerator
XMC_I2S_CH_BUS_MODE_MASTER I2S Master
XMC_I2S_CH_BUS_MODE_SLAVE I2S Slave
Definition at line 217 of file xmc_i2s.h.
XMC_I2S_CH_CHANNEL
enum XMC_I2S_CH_CHANNEL
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
Enumerator
XMC_I2S_CH_CHANNEL_1_LEFT Channel 1 (left)
XMC_I2S_CH_CHANNEL_2_RIGHT Channel 2 (right)
Definition at line 193 of file xmc_i2s.h.
XMC_I2S_CH_EVENT
enum XMC_I2S_CH_EVENT
I2S events.
Enumerator
XMC_I2S_CH_EVENT_RECEIVE_START Receive start event
XMC_I2S_CH_EVENT_DATA_LOST Data lost event
XMC_I2S_CH_EVENT_TRANSMIT_SHIFT Transmit shift event
XMC_I2S_CH_EVENT_TRANSMIT_BUFFER Transmit buffer event
XMC_I2S_CH_EVENT_STANDARD_RECEIVE Receive event
XMC_I2S_CH_EVENT_ALTERNATIVE_RECEIVE Alternate receive event
XMC_I2S_CH_EVENT_BAUD_RATE_GENERATOR Baudrate generator event
XMC_I2S_CH_EVENT_WA_FALLING_EDGE WA falling edge event
XMC_I2S_CH_EVENT_WA_RISING_EDGE WA rising edge event
XMC_I2S_CH_EVENT_WA_GENERATION_END END event
XMC_I2S_CH_EVENT_DX2TIEN_ACTIVATED WA input signal transition event
Definition at line 163 of file xmc_i2s.h.
XMC_I2S_CH_INPUT
enum XMC_I2S_CH_INPUT
I2S input stage selection.
Enumerator
XMC_I2S_CH_INPUT_DIN0 Data input stage 0
XMC_I2S_CH_INPUT_SLAVE_SCLKIN Clock input stage
XMC_I2S_CH_INPUT_SLAVE_WA WA input stage
Definition at line 202 of file xmc_i2s.h.
XMC_I2S_CH_INTERRUPT_NODE_POINTER
enum XMC_I2S_CH_INTERRUPT_NODE_POINTER
I2S channel interrupt node pointers.
Enumerator
XMC_I2S_CH_INTERRUPT_NODE_POINTER_TRANSMIT_SHIFT Node pointer for transmit shift interrupt
XMC_I2S_CH_INTERRUPT_NODE_POINTER_TRANSMIT_BUFFER Node pointer for transmit buffer interrupt
XMC_I2S_CH_INTERRUPT_NODE_POINTER_RECEIVE Node pointer for receive interrupt
XMC_I2S_CH_INTERRUPT_NODE_POINTER_ALTERNATE_RECEIVE Node pointer for alternate receive interrupt
XMC_I2S_CH_INTERRUPT_NODE_POINTER_PROTOCOL Node pointer for protocol related interrupts
Definition at line 151 of file xmc_i2s.h.
XMC_I2S_CH_STATUS
enum XMC_I2S_CH_STATUS
I2S Status.
Enumerator
XMC_I2S_CH_STATUS_OK Status OK
XMC_I2S_CH_STATUS_ERROR Status ERROR
XMC_I2S_CH_STATUS_BUSY Status BUSY
Definition at line 110 of file xmc_i2s.h.
XMC_I2S_CH_STATUS_FLAG
enum XMC_I2S_CH_STATUS_FLAG
I2S status flag.
Enumerator
XMC_I2S_CH_STATUS_FLAG_WORD_ADDRESS Word Address status
XMC_I2S_CH_STATUS_FLAG_DX2S Status of WA input(DX2) signal
XMC_I2S_CH_STATUS_FLAG_DX2T_EVENT_DETECTED Status for WA input signal transition
XMC_I2S_CH_STATUS_FLAG_WA_FALLING_EDGE_EVENT Falling edge of the WA output signal has been generated
XMC_I2S_CH_STATUS_FLAG_WA_RISING_EDGE_EVENT Rising edge of the WA output signal has been generated
XMC_I2S_CH_STATUS_FLAG_WA_GENERATION_END The WA generation has ended
XMC_I2S_CH_STATUS_FLAG_RECEIVER_START_INDICATION Receive start indication status
XMC_I2S_CH_STATUS_FLAG_DATA_LOST_INDICATION Data lost indication status
XMC_I2S_CH_STATUS_FLAG_TRANSMIT_SHIFT_INDICATION Transmit shift indication status
XMC_I2S_CH_STATUS_FLAG_TRANSMIT_BUFFER_INDICATION Transmit buffer indication status
XMC_I2S_CH_STATUS_FLAG_RECEIVE_INDICATION Receive indication status
XMC_I2S_CH_STATUS_FLAG_ALTERNATIVE_RECEIVE_INDICATION Alternate receive indication status
XMC_I2S_CH_STATUS_FLAG_BAUD_RATE_GENERATOR_INDICATION Baud rate generator indication status
Definition at line 120 of file xmc_i2s.h.
XMC_I2S_CH_WA_POLARITY
enum XMC_I2S_CH_WA_POLARITY
Defines the Polarity of the WA in the SELO output lines in relation to the internal WA signal.
Enumerator
XMC_I2S_CH_WA_POLARITY_DIRECT The SELO outputs have the same polarity as the WA signal (active high)
XMC_I2S_CH_WA_POLARITY_INVERTED The SELO outputs have the inverted polarity to the WA signal (active low)
Definition at line 182 of file xmc_i2s.h.
Function Documentation
XMC_I2S_CH_ClearStatusFlag()
__STATIC_INLINE void XMC_I2S_CH_ClearStatusFlag (XMC_USIC_CH_t *const channel, const uint32_t flag)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
flag Protocol event status to be cleared for detection of next occurence. Refer @ XMC_I2S_CH_STATUS_FLAG_t for valid values. OR combinations of these enum item can be used as input.
Returns
None
Description:
Clears the events specified, by setting PSCR register.
During communication the events occurred have to be cleared to detect their next occurence.
e.g: During transmission Transmit buffer event occurs to indicating data word transfer has started. This event has to be cleared after transmission of each data word. Otherwise next event cannot be recognized.
Related APIs:
XMC_I2S_CH_GetStatusFlag()
Definition at line 499 of file xmc_i2s.h.
References XMC_USIC_CH::PSCR.
Referenced by XMC_I2S_CH_Transmit().
XMC_I2S_CH_ConfigureShiftClockOutput()
__STATIC_INLINE void XMC_I2S_CH_ConfigureShiftClockOutput (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_t clock_output)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
clock_output shift clock source.
 Refer XMC_I2S_CH_BRG_SHIFT_CLOCK_OUTPUT_t for valid inputs.
Returns
None
Description:
Configures the shift clock source by setting BRG.SCLKOSEL.
In Master mode operation, shift clock is generated by the internal baud rate generator. This SCLK is made available for external slave devices by SCLKOUT signal.
In Slave mode, the signal is received from the external master. So the DX1(input) stage has to be connected to input.
Definition at line 553 of file xmc_i2s.h.
References XMC_USIC_CH_ConfigureShiftClockOutput().
XMC_I2S_CH_DisableDataTransmission()
__STATIC_INLINE void XMC_I2S_CH_DisableDataTransmission (XMC_USIC_CH_t *const channel)
Parameters
channel Constant pointer to USIC channel handle of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0,XMC_I2S1_CH1,XMC_I2S2_CH0,XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Returns
None
Description
Disable data transmission.
Use this function in combination with XMC_I2S_CH_EnableDataTransmission() to fill the FIFO and send the FIFO content without gaps in the transmission. FIFO is filled using XMC_USIC_CH_TXFIFO_PutData().
Related APIs:
XMC_I2S_CH_EnableDataTransmission()
Definition at line 821 of file xmc_i2s.h.
References XMC_USIC_CH_SetStartTransmisionMode(), and XMC_USIC_CH_START_TRANSMISION_DISABLED.
XMC_I2S_CH_DisableDelayCompensation()
__STATIC_INLINE void XMC_I2S_CH_DisableDelayCompensation (XMC_USIC_CH_t *const channel)
Parameters
channel Pointer to USIC channel handler of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0,XMC_I2S1_CH1,XMC_I2S2_CH0,XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Returns
None
Description
Disables delay compensation..
Related APIs:
XMC_I2S_CH_EnableDelayCompensation()
Definition at line 784 of file xmc_i2s.h.
References XMC_USIC_CH_DisableDelayCompensation().
XMC_I2S_CH_DisableEvent()
void XMC_I2S_CH_DisableEvent (XMC_USIC_CH_t *const channel, const uint32_t event)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
event Protocol events which have to be disabled. Refer @ XMC_I2S_CH_EVENT_t for valid values. OR combinations of these enum item can be used as input.
Returns
None
Description:
Disables the I2S protocol specific events, by configuring PCR register.
After disabling the events, XMC_I2S_CH_EnableEvent() has to be invoked to re-enable the events.
Related APIs:
XMC_I2S_CH_EnableEvent()
Definition at line 264 of file xmc_i2s.c.
References XMC_USIC_CH::CCR, and XMC_USIC_CH::PCR_IISMode.
XMC_I2S_CH_DisableInputInversion()
__STATIC_INLINE void XMC_I2S_CH_DisableInputInversion (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INPUT_t input)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
input I2S channel input stage.
 Refer XMC_I2S_CH_INPUT_t for valid inputs.
Returns
None
Description
Disables the polarity inversion of input data signal, by clearing DXyCR.DPOL(where y = input).
Resets the input data polarity. Invoke XMC_I2S_CH_EnableInputInversion() to apply inversion.
Related APIs:
XMC_I2S_CH_EnableInputInversion()
Definition at line 677 of file xmc_i2s.h.
References XMC_USIC_CH_DisableInputInversion().
XMC_I2S_CH_DisableMasterClock()
__STATIC_INLINE void XMC_I2S_CH_DisableMasterClock (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
None
Description:
Disables the generation of Master clock by clearing PCR.MCLK bit.
This clock can be enabled by invoking XMC_I2S_CH_EnableMasterClock() as needed in the program.
Related APIs:
XMC_I2S_CH_EnableMasterClock()
Definition at line 535 of file xmc_i2s.h.
References XMC_USIC_CH::PCR_IISMode, and USIC_CH_PCR_IISMode_MCLK_Msk.
XMC_I2S_CH_EnableDataTransmission()
__STATIC_INLINE void XMC_I2S_CH_EnableDataTransmission (XMC_USIC_CH_t *const channel)
Parameters
channel Constant pointer to USIC channel handle of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0,XMC_I2S1_CH1,XMC_I2S2_CH0,XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Returns
None
Description
Enable data transmission.
Use this function in combination with XMC_I2S_CH_DisableDataTransmission() to fill the FIFO and send the FIFO content without gaps in the transmission. FIFO is filled using XMC_USIC_CH_TXFIFO_PutData().
Note
If you need more control over the start of transmission use XMC_USIC_CH_SetStartTransmisionMode()
Related APIs:
XMC_I2S_CH_DisableDataTransmission()
Definition at line 803 of file xmc_i2s.h.
References XMC_USIC_CH_SetStartTransmisionMode(), and XMC_USIC_CH_START_TRANSMISION_ON_TDV.
XMC_I2S_CH_EnableDelayCompensation()
__STATIC_INLINE void XMC_I2S_CH_EnableDelayCompensation (XMC_USIC_CH_t *const channel)
Parameters
channel Pointer to USIC channel handler of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0,XMC_I2S1_CH1,XMC_I2S2_CH0,XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Returns
None
Description
Enables delay compensation.
 Delay compensation can be applied to the receive path.
Related APIs:
XMC_I2S_CH_DisableDelayCompensation()
Definition at line 768 of file xmc_i2s.h.
References XMC_USIC_CH_EnableDelayCompensation().
XMC_I2S_CH_EnableEvent()
void XMC_I2S_CH_EnableEvent (XMC_USIC_CH_t *const channel, const uint32_t event)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
event Protocol events which have to be enabled. Refer @ XMC_I2S_CH_EVENT_t for valid values. OR combinations of these enum items can be used as input.
Returns
None
Description:
Enables the I2S protocol specific events, by configuring PCR register.
Events can be enabled as needed using XMC_I2S_CH_EnableEvent(). XMC_I2S_CH_DisableEvent() can be used to disable the events.
Related APIs:
XMC_I2S_CH_DisableEvent()
Definition at line 258 of file xmc_i2s.c.
References XMC_USIC_CH::CCR, and XMC_USIC_CH::PCR_IISMode.
XMC_I2S_CH_EnableInputInversion()
__STATIC_INLINE void XMC_I2S_CH_EnableInputInversion (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INPUT_t input)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
input I2S channel input stage.
 Refer XMC_I2S_CH_INPUT_t for valid inputs.
Returns
None
Description
Enables the polarity inversion of input data signal, by setting DXyCR.DPOL(where y = input).
This is not set in XMC_I2S_CH_Init(). Invoke XMC_I2S_CH_EnableInputInversion() as needed later in the program. To disable the inversion XMC_I2S_CH_DisableInputInversion() can be invoked.
Related APIs:
XMC_I2S_CH_DisableInputInversion()
Definition at line 657 of file xmc_i2s.h.
References XMC_USIC_CH_EnableInputInversion().
XMC_I2S_CH_EnableMasterClock()
__STATIC_INLINE void XMC_I2S_CH_EnableMasterClock (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
None
Description:
Enables the generation of Master clock by setting PCR.MCLK bit.
This clock can be used as a clock reference for external devices. This is not enabled during initialization in XMC_I2S_CH_Init(). Invoke XMC_I2S_CH_EnableMasterClock() to enable as needed in the program, or if it is disabled by XMC_I2S_CH_DisableMasterClock().
Related APIs:
XMC_I2S_CH_DisableMasterClock()
Definition at line 518 of file xmc_i2s.h.
References XMC_USIC_CH::PCR_IISMode, and USIC_CH_PCR_IISMode_MCLK_Msk.
XMC_I2S_CH_GetReceivedData()
uint16_t XMC_I2S_CH_GetReceivedData (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
uint16_t Data read from the receive buffer.
Description:
Reads data from the receive buffer based on the FIFO selection.
Invocation of XMC_I2S_CH_Receive() receives the data and place it into receive buffer. After receiving the data XMC_I2S_CH_GetReceivedData() can be used to read the data from the buffer.
Related APIs:
XMC_I2S_CH_Receive()
Definition at line 224 of file xmc_i2s.c.
References XMC_USIC_CH::OUTR, XMC_USIC_CH::RBCTR, XMC_USIC_CH::RBUF, and USIC_CH_RBCTR_SIZE_Msk.
XMC_I2S_CH_GetStatusFlag()
__STATIC_INLINE uint32_t XMC_I2S_CH_GetStatusFlag (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
uint32_t Status of I2S protocol events.
Description:
Returns the status of the events, by reading PSR register.
This indicates the status of the all the events, for I2S communication.
Related APIs:
XMC_I2S_CH_ClearStatusFlag()
Definition at line 478 of file xmc_i2s.h.
References XMC_USIC_CH::PSR_IISMode.
XMC_I2S_CH_Init()
void XMC_I2S_CH_Init (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_CONFIG_t *const config)
Parameters
channel Constant pointer to USIC channel handle of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0, XMC_I2S1_CH1,XMC_I2S2_CH0, XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Parameters
config Constant pointer to I2S configuration structure of type XMC_I2S_CH_CONFIG_t.
Returns
XMC_I2S_CH_STATUS_t Status of initializing the USIC channel for I2S protocol.
 Range: XMC_I2S_CH_STATUS_OK if initialization is successful.
 XMC_I2S_CH_STATUS_ERROR if configuration of baudrate failed.
Description
Initializes the USIC channel for I2S protocol.
During the initialization, USIC channel is enabled and baudrate is configured. After each change of the WA signal, a complete data frame is intended to be transferred (frame length <= system word length). The number of data bits transferred after a change of signal WA is defined by config->frame_length. A data frame can consist of several data words with a data word length defined by config->data_bits. The changes of signal WA define the system word length as the number of SCLK cycles between two changes of WA. The system word length is set by default to the frame length defined by config->frame_length.
XMC_I2S_CH_Start() should be invoked after the initialization to enable the channel.
Related APIs:
XMC_I2S_CH_Start(), XMC_I2S_CH_Stop(), XMC_I2S_CH_Transmit(), XMC_I2S_CH_SetSystemWordLength()
Definition at line 88 of file xmc_i2s.c.
References XMC_I2S_CH_CONFIG::baudrate, XMC_I2S_CH_CONFIG::bus_mode, XMC_I2S_CH_CONFIG::data_bits, XMC_I2S_CH_CONFIG::data_delayed_sclk_periods, XMC_I2S_CH_CONFIG::frame_length, XMC_USIC_CH::PCR_IISMode, XMC_USIC_CH::PSCR, XMC_USIC_CH::SCTR, XMC_USIC_CH::TCSR, USIC_CH_PCR_IISMode_DTEN_Msk, USIC_CH_PCR_IISMode_TDEL_Pos, USIC_CH_PCR_IISMode_WAGEN_Msk, USIC_CH_SCTR_FLE_Pos, USIC_CH_SCTR_SDIR_Msk, USIC_CH_SCTR_TRM_Pos, USIC_CH_SCTR_WLE_Pos, USIC_CH_TCSR_FLEMD_Msk, USIC_CH_TCSR_HPCMD_Msk, USIC_CH_TCSR_SELMD_Msk, USIC_CH_TCSR_TDEN_Pos, USIC_CH_TCSR_TDSSM_Msk, USIC_CH_TCSR_WAMD_Msk, USIC_CH_TCSR_WLEMD_Msk, XMC_I2S_CH_CONFIG::wa_inversion, XMC_ASSERT, XMC_I2S_CH_BUS_MODE_MASTER, XMC_I2S_CH_SetBaudrate(), XMC_I2S_CH_SetSystemWordLength(), and XMC_USIC_CH_Enable().
XMC_I2S_CH_Receive()
__STATIC_INLINE void XMC_I2S_CH_Receive (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_CHANNEL_t channel_number)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
channel_number Communication output channel of the I2S, based on this mode TCI(Transmit control information)is updated.
 Refer XMC_I2S_CH_CHANNEL_t for valid values.
Returns
None
Description:
Transmits a dummy data(FFFFH) to provide clock for slave and receives the data from the slave.
XMC_I2S_CH_Receive() receives the data and places it into buffer based on the FIFO selection. After reception of data XMC_I2S_CH_GetReceivedData() can be invoked to read the data from the buffers.
Related APIs:
XMC_I2S_CH_GetReceivedData()
Definition at line 374 of file xmc_i2s.h.
References XMC_I2S_CH_Transmit().
XMC_I2S_CH_SelectInterruptNodePointer()
__STATIC_INLINE void XMC_I2S_CH_SelectInterruptNodePointer (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INTERRUPT_NODE_POINTER_t interrupt_node, const uint32_t service_request)
Parameters
channel Pointer to USIC channel handler of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0,XMC_I2S1_CH1,XMC_I2S2_CH0,XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Parameters
interrupt_node Interrupt node pointer to be configured.
 Range: XMC_I2S_CH_INTERRUPT_NODE_POINTER_TRANSMIT_SHIFT, XMC_I2S_CH_INTERRUPT_NODE_POINTER_TRANSMIT_BUFFER etc.
service_request Service request number.
 Range: 0 to 5.
Returns
None
Description
Sets the interrupt node for USIC channel events.
For an event to generate interrupt, node pointer should be configured with service request(SR0, SR1..SR5). The NVIC node gets linked to the interrupt event by doing so.
 Note: NVIC node should be separately enabled to generate the interrupt.
Related APIs:
XMC_I2S_CH_EnableEvent()
Definition at line 728 of file xmc_i2s.h.
References XMC_USIC_CH_SetInterruptNodePointer().
XMC_I2S_CH_SetBaudrate()
XMC_I2S_CH_STATUS_t XMC_I2S_CH_SetBaudrate (XMC_USIC_CH_t *const channel, const uint32_t rate)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
rate Bus speed in bits per second
Returns
XMC_I2S_CH_STATUS_t Status of the I2S driver after the request for setting baudrate is processed.
 XMC_I2S_CH_STATUS_OK- If the baudrate is successfully changed.
 XMC_I2S_CH_STATUS_ERROR- If the new baudrate value is out of range.
Description:
Sets the bus speed in bits per second
Related APIs:
XMC_I2S_CH_Init(), XMC_I2S_CH_Stop()
Definition at line 136 of file xmc_i2s.c.
References XMC_USIC_CH::BRG, USIC_CH_BRG_CTQSEL_Msk, USIC_CH_BRG_CTQSEL_Pos, USIC_CH_BRG_PPPEN_Msk, XMC_I2S_CH_OVERSAMPLING, XMC_I2S_CH_STATUS_ERROR, XMC_I2S_CH_STATUS_OK, XMC_SCU_CLOCK_GetPeripheralClockFrequency(), XMC_USIC_CH_SetBaudrate(), and XMC_USIC_CH_STATUS_OK.
Referenced by XMC_I2S_CH_Init().
XMC_I2S_CH_SetBitOrderLsbFirst()
__STATIC_INLINE void XMC_I2S_CH_SetBitOrderLsbFirst (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
None
Description:
Set the order of data transfer from LSB to MSB, by clearing SCTR.SDIR bit.
This is typically based on the slave settings. Invoke XMC_I2S_CH_SetBitOrderLsbFirst() to set direction as needed in the program.
Related APIs:
XMC_I2S_CH_SetBitOrderMsbFirst()
Definition at line 408 of file xmc_i2s.h.
References XMC_USIC_CH::SCTR, and USIC_CH_SCTR_SDIR_Msk.
XMC_I2S_CH_SetBitOrderMsbFirst()
__STATIC_INLINE void XMC_I2S_CH_SetBitOrderMsbFirst (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
None
Description:
Set the order of data transfer from MSB to LSB, by setting SCTR.SDIR bit.
This is typically based on the slave settings. This is not set during XMC_I2S_CH_Init(). Invoke XMC_I2S_CH_SetBitOrderMsbFirst() to set direction as needed in the program.
Related APIs:
XMC_I2S_CH_SetBitOrderLsbFirst()
Definition at line 426 of file xmc_i2s.h.
References XMC_USIC_CH::SCTR, and USIC_CH_SCTR_SDIR_Msk.
XMC_I2S_CH_SetFrameLength()
__STATIC_INLINE void XMC_I2S_CH_SetFrameLength (XMC_USIC_CH_t *const channel, const uint8_t frame_length)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
frame_length Number of bits in a frame.
 Range: 1 to 64.
Returns
None
Description
Define the data frame length.
Set the number of bits to be serially transmitted in a frame. The frame length should be multiples of word length.
Related APIs:
XMC_USIC_CH_SetWordLength()
Definition at line 594 of file xmc_i2s.h.
References XMC_USIC_CH_SetFrameLength().
XMC_I2S_CH_SetInputSource()
__STATIC_INLINE void XMC_I2S_CH_SetInputSource (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_INPUT_t input, const uint8_t source)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
input I2S channel input stage.
 Refer XMC_I2S_CH_INPUT_t for valid values
source Input source select for the input stage. Range : [0 to 7]
Returns
None
Description
Selects the data source for I2S input stage, by configuring DXCR.DSEL bits.
Selects the input data signal source among DXnA, DXnB.. DXnG for the input stage. The API can be used for all the input stages like DX0CR, DX1CR etc. This is not done during initialization. This has to be configured before starting the I2S communication.
Definition at line 614 of file xmc_i2s.h.
References XMC_USIC_CH::DXCR, USIC_CH_DX0CR_DSEN_Msk, USIC_CH_DX0CR_INSW_Msk, and XMC_USIC_CH_SetInputSource().
XMC_I2S_CH_SetInterruptNodePointer()
__STATIC_INLINE void XMC_I2S_CH_SetInterruptNodePointer (XMC_USIC_CH_t *const channel, const uint8_t service_request)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
service_request Service request number. Range: [0 to 5]
Returns
None
Description
Sets the interrupt node for I2S channel events.
For an event to generate interrupt, node pointer should be configured with service request(SR0, SR1..SR5). The NVIC node gets linked to the interrupt event by doing so. This is not configured in XMC_I2S_CH_Init() during initialization.
Note::
NVIC node should be separately enabled to generate the interrupt.
Related APIs:
XMC_USIC_CH_EnableEvent()
Definition at line 702 of file xmc_i2s.h.
References XMC_USIC_CH_INTERRUPT_NODE_POINTER_PROTOCOL, and XMC_USIC_CH_SetInterruptNodePointer().
XMC_I2S_CH_SetSystemWordLength()
void XMC_I2S_CH_SetSystemWordLength (XMC_USIC_CH_t *const channel, uint32_t sclk_cycles_system_word_length)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
sclk_cycles_system_word_length system word length in terms of sclk clock cycles.
Returns
None
Description:
Configures the system word length by setting BRG.DCTQ bit field.
This value has to be always higher than 1U and lower than the data with (SCTR.FLE)
Definition at line 157 of file xmc_i2s.c.
References XMC_USIC_CH::BRG, USIC_CH_BRG_DCTQ_Msk, USIC_CH_BRG_DCTQ_Pos, USIC_CH_BRG_PCTQ_Msk, USIC_CH_BRG_PCTQ_Pos, and XMC_ASSERT.
Referenced by XMC_I2S_CH_Init().
XMC_I2S_CH_SetWordLength()
__STATIC_INLINE void XMC_I2S_CH_SetWordLength (XMC_USIC_CH_t *const channel, const uint8_t word_length)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
word_length Number of bits to be configured for a data word.
 Range: 1 to 16.
Returns
None
Description
Defines the data word length.
Sets the number of bits to represent a data word. Frame length should be a multiple of word length.
Related APIs:
XMC_I2S_CH_SetFrameLength()
Definition at line 574 of file xmc_i2s.h.
References XMC_USIC_CH_SetWordLength().
XMC_I2S_CH_Start()
__STATIC_INLINE void XMC_I2S_CH_Start (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
None
Description:
Set the selected USIC channel to operate in I2S mode, by setting CCR.MODE bits.
It should be executed after XMC_I2S_CH_Init() during initialization. By invoking XMC_I2S_CH_Stop(), the MODE is set to IDLE state. Call XMC_I2S_CH_Start() to set the I2S mode again, as needed later in the program.
Related APIs:
XMC_I2S_CH_Init(), XMC_I2S_CH_Stop()
Definition at line 288 of file xmc_i2s.h.
References XMC_USIC_CH_OPERATING_MODE_I2S, and XMC_USIC_CH_SetMode().
XMC_I2S_CH_Stop()
XMC_I2S_CH_STATUS_t XMC_I2S_CH_Stop (XMC_USIC_CH_t *const channel)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
Returns
XMC_I2S_CH_STATUS_t Status of the I2S driver after the request for stopping is processed.
 XMC_I2S_CH_STATUS_OK- If the USIC channel is successfully put to IDLE mode.
 XMC_I2S_CH_STATUS_BUSY- If the USIC channel is busy transmitting data.
Description:
Set the selected I2S channel to IDLE mode, by clearing CCR.MODE bits.
After calling XMC_I2S_CH_Stop, channel is IDLE mode. So no communication is supported. XMC_I2S_CH_Start() has to be invoked to start the communication again.
Related APIs:
XMC_I2S_CH_Start()
Definition at line 241 of file xmc_i2s.c.
References XMC_I2S_CH_STATUS_BUSY, XMC_I2S_CH_STATUS_OK, XMC_USIC_CH_GetTransmitBufferStatus(), XMC_USIC_CH_OPERATING_MODE_IDLE, XMC_USIC_CH_SetMode(), and XMC_USIC_CH_TBUF_STATUS_BUSY.
XMC_I2S_CH_Transmit()
void XMC_I2S_CH_Transmit (XMC_USIC_CH_t *const channel, const uint16_t data, const XMC_I2S_CH_CHANNEL_t channel_number)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
data Data to be transmitted
channel_number Communication output channel of the I2S, based on this channel selection TCI(Transmit control information)is updated.
 Refer XMC_I2S_CH_CHANNEL_t for valid values.
Returns
None
Description:
Puts the data into FIFO, if FIFO mode is enabled or else into standard buffer, by setting the proper mode.
TCI(Transmit Control Information) allows dynamic control of output channel during data transfers. To support this auto update, TCSR.WAMD(Automatic WA mode) will be enabled during the initialization using XMC_I2S_CH_Init() for all modes.
Related APIs:
XMC_I2S_CH_Receive()
Definition at line 204 of file xmc_i2s.c.
References XMC_USIC_CH::IN, XMC_USIC_CH::TBCTR, XMC_USIC_CH::TBUF, USIC_CH_TBCTR_SIZE_Msk, XMC_I2S_CH_ClearStatusFlag(), XMC_I2S_CH_STATUS_FLAG_TRANSMIT_BUFFER_INDICATION, XMC_USIC_CH_GetTransmitBufferStatus(), and XMC_USIC_CH_TBUF_STATUS_BUSY.
Referenced by XMC_I2S_CH_Receive().
XMC_I2S_CH_TriggerServiceRequest()
__STATIC_INLINE void XMC_I2S_CH_TriggerServiceRequest (XMC_USIC_CH_t *const channel, const uint32_t service_request_line)
Parameters
channel Pointer to USIC channel handler of type XMC_USIC_CH_t
 Range: XMC_I2S0_CH0, XMC_I2S0_CH1,XMC_I2S1_CH0,XMC_I2S1_CH1,XMC_I2S2_CH0,XMC_I2S2_CH1
Note
Availability of I2S1 and I2S2 depends on device selection
Parameters
service_request_line service request number of the event to be triggered.
 Range: 0 to 5.
Returns
None
Description
Trigger a I2S interrupt service request.
When the I2S service request is triggered, the NVIC interrupt associated with it will be generated if enabled.
Related APIs:
XMC_I2S_CH_SelectInterruptNodePointer()
Definition at line 751 of file xmc_i2s.h.
References XMC_USIC_CH_TriggerServiceRequest().
XMC_I2S_CH_WordAddressSignalPolarity()
__STATIC_INLINE void XMC_I2S_CH_WordAddressSignalPolarity (XMC_USIC_CH_t *const channel, const XMC_I2S_CH_WA_POLARITY_t wa_inversion)
Parameters
channel A constant pointer to XMC_USIC_CH_t, pointing to the USIC channel base address.
wa_inversion Polarity of the word address signal.
 Refer XMC_I2S_CH_WA_POLARITY_t for valid values
Returns
None
Description
Set the polarity of the word address signal, by configuring PCR.SELINV bit.
Normally WA signal is active low level signal. This is configured in XMC_I2S_CH_Init() during initialization. Invoke XMC_I2S_CH_WordAddressSignalPolarity() with desired settings as needed later in the program.
Definition at line 635 of file xmc_i2s.h.
References XMC_USIC_CH::PCR_IISMode, and USIC_CH_PCR_IISMode_SELINV_Msk.