FLASH
Flash driver for XMC microcontroller family.
Functions
void XMC_FLASH_ClearStatus (void)
uint32_t XMC_FLASH_GetStatus (void)
void XMC_FLASH_EnableEvent (const uint32_t event_msk)
void XMC_FLASH_DisableEvent (const uint32_t event_msk)
void XMC_FLASH_ProgramPage (uint32_t *address, const uint32_t *data)
void XMC_FLASH_EraseSector (uint32_t *address)
__STATIC_INLINE bool XMC_FLASH_IsBusy (void)
Detailed Description
Flash driver for XMC microcontroller family.
Flash is a non volatile memory module used to store instruction code or constant data. The flash low level driver provides support to the following functionalities of flash memory.
Function Documentation
XMC_FLASH_ClearStatus()
void XMC_FLASH_ClearStatus (void)
Parameters
None
Returns
None
Description:
Related APIs:
None
Definition at line 85 of file xmc1_flash.c.
References NVM, NVM_NVMPROG_RSTECC_Msk, and NVM_NVMPROG_RSTVERR_Msk.
XMC_FLASH_DisableEvent()
void XMC_FLASH_DisableEvent (const uint32_t event_msk)
Parameters
event_msk ORed values of XMC_FLASH_EVENT_t enumeration
Returns
None
Description:
Disables the particular flash events as specified in the input parameter.
Related APIs:
XMC_FLASH_EnableEvent()
Definition at line 109 of file xmc1_flash.c.
References NVM.
XMC_FLASH_EnableEvent()
void XMC_FLASH_EnableEvent (const uint32_t event_msk)
Parameters
event_msk ORed values of XMC_FLASH_EVENT_t enumeration
Returns
None
Description:
Enables the particular flash events as specified in the input parameter.
Related APIs:
XMC_FLASH_DisableEvent()
Definition at line 101 of file xmc1_flash.c.
References NVM.
XMC_FLASH_EraseSector()
void XMC_FLASH_EraseSector (uint32_t * address)
Parameters
address Pointer to the starting address of the page to be erased.
Returns
None
Description:
Definition at line 241 of file xmc1_flash.c.
References XMC_ASSERT, and XMC_FLASH_ErasePages().
XMC_FLASH_GetStatus()
uint32_t XMC_FLASH_GetStatus (void)
Parameters
None
Returns
uint32_t Status of the previous flash operation.
Description:
Related APIs:
None
Definition at line 93 of file xmc1_flash.c.
References NVM.
Referenced by XMC_FLASH_IsBusy().
XMC_FLASH_IsBusy()
__STATIC_INLINE bool XMC_FLASH_IsBusy (void)
Parameters
None
Returns
true if flash is in busy state else returns false.
Description:
Checks whether flash is in busy state or not.
 It is checked by calling the XMC_FLASH_GetStatus() API internally. Refer XMC_FLASH_GetStatus() for more details.
Related APIs:
XMC_FLASH_GetStatus()
Definition at line 258 of file xmc_flash.h.
References XMC_FLASH_GetStatus().
Referenced by XMC_FLASH_ErasePages(), XMC_FLASH_VerifyBlocks(), and XMC_FLASH_WriteBlocks().
XMC_FLASH_ProgramPage()
void XMC_FLASH_ProgramPage (uint32_t * address, const uint32_t * data)
Parameters
address Pointer to the starting address of flash page from where the programming starts.
data Pointer to the source address where targeted data is located.
Returns
None
Description:
Note:
Flash will be busy state during write is ongoing, hence no operations allowed until it completes.
Related APIs:
None
Definition at line 249 of file xmc1_flash.c.
References XMC_FLASH_ProgramVerifyPage().