main.c File Reference
#include <DAVE.h>
#include `ManagerTask.h`
#include `UartTask.h`
#include `SpiTask.h`
#include `Worker1Task.h`
#include `Worker2Task.h`
Data Structures
struct parameter_struct
struct SEMAPHORE_PARAMETERS
Typedefs
typedef struct parameter_struct parameter_struct_t
typedef struct SEMAPHORE_PARAMETERS xSemaphoreParameters_t
Functions
void MyLEDsToggling (uint8_t tyleRazy)
void MyErrorHandler (TaskHandle_t xUARTHandle)
void vApplicationStackOverflowHook (xTaskHandle *pxTask, signed char *pcTaskName)
void vApplicationMallocFailedHook ()
void myTimerCallback (xTimerHandle pxTimer)
int main (void)
Variables
QueueHandle_t xQueue = NULL
xQueueHandle Queue_id
xSemaphoreHandle notification_semaphore
xTimerHandle Timer_handle
xTaskHandle UARTHandle = NULL
xTaskHandle SPIHandle = NULL
xTaskHandle worker1_id
xTaskHandle worker2_id
Typedef Documentation
parameter_struct_t
typedef struct parameter_struct parameter_struct_t
xSemaphoreParameters_t
typedef struct SEMAPHORE_PARAMETERS xSemaphoreParameters_t
Function Documentation
main()
int main (void)
Definition at line 77 of file main.c.
References configMINIMAL_STACK_SIZE, DAVE_Init(), DAVE_STATUS_SUCCESS, Manager_Task(), myTimerCallback(), pdTRUE, pvPortMalloc(), Queue_id, Timer_handle, tskIDLE_PRIORITY, vTaskStartScheduler(), worker1_id, worker1_task(), worker2_id, worker2_task(), XMC_DEBUG, xQueue, xTimerCreate(), and xTimerStart.
MyErrorHandler()
void MyErrorHandler (TaskHandle_t xUARTHandle)
Definition at line 42 of file main.c.
References MyLEDsToggling(), pdMS_TO_TICKS, vTaskDelay(), and vTaskDelete().
MyLEDsToggling()
void MyLEDsToggling (uint8_t tyleRazy)
Definition at line 34 of file main.c.
References DIGITAL_IO_ToggleOutput(), LED0, LED1, and vTaskDelay().
Referenced by MyErrorHandler(), vApplicationMallocFailedHook(), and vApplicationStackOverflowHook().
myTimerCallback()
void myTimerCallback (xTimerHandle pxTimer)
Definition at line 70 of file main.c.
References notification_semaphore, and xSemaphoreGive.
Referenced by main().
vApplicationMallocFailedHook()
void vApplicationMallocFailedHook ()
Definition at line 63 of file main.c.
References MyLEDsToggling(), pdMS_TO_TICKS, and vTaskDelay().
Referenced by pvPortMalloc().
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (xTaskHandle * pxTask, signed char * pcTaskName)
Definition at line 53 of file main.c.
References MyLEDsToggling(), pdMS_TO_TICKS, and vTaskDelay().
Variable Documentation
notification_semaphore
xSemaphoreHandle notification_semaphore
Definition at line 15 of file main.c.
Referenced by Manager_Task(), and myTimerCallback().
Queue_id
xQueueHandle Queue_id
Definition at line 14 of file main.c.
Referenced by main(), Manager_Task(), worker1_task(), and worker2_task().
SPIHandle
xTaskHandle SPIHandle = NULL
Definition at line 18 of file main.c.
Timer_handle
xTimerHandle Timer_handle
Definition at line 16 of file main.c.
Referenced by main().
UARTHandle
xTaskHandle UARTHandle = NULL
Definition at line 17 of file main.c.
worker1_id
xTaskHandle worker1_id
Definition at line 19 of file main.c.
Referenced by main(), Manager_Task(), and worker1_task().
worker2_id
xTaskHandle worker2_id
Definition at line 20 of file main.c.
Referenced by main(), Manager_Task(), and worker2_task().
xQueue
QueueHandle_t xQueue = NULL
Definition at line 13 of file main.c.
Referenced by main(), pcQueueGetName(), SPI_Slave_Task(), UART_Task(), ucQueueGetQueueType(), uxQueueGetQueueNumber(), uxQueueMessagesWaiting(), uxQueueMessagesWaitingFromISR(), uxQueueSpacesAvailable(), vQueueAddToRegistry(), vQueueDelete(), vQueueSetQueueNumber(), vQueueUnregisterQueue(), vQueueWaitForMessageRestricted(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueGiveFromISR(), xQueueIsQueueEmptyFromISR(), xQueueIsQueueFullFromISR(), xQueuePeek(), xQueuePeekFromISR(), xQueueReceive(), xQueueReceiveFromISR(), and xQueueSemaphoreTake().