Dave/Generated/SPI_SLAVE/spi_slave_conf.c File Reference
#include `spi_slave.h`
Functions
void SPI_SLAVE_lTransmitHandler (const SPI_SLAVE_t *const handle)
void SPI_SLAVE_lReceiveHandler (const SPI_SLAVE_t *const handle)
void SPI_SLAVE_lProtocolHandler (const SPI_SLAVE_t *const handle)
SPI_SLAVE_STATUS_t SPI_SLAVE_0_init (void)
void SPI_SLAVE_0_TX_HANDLER ()
void SPI_SLAVE_0_RX_HANDLER ()
Variables
const XMC_SPI_CH_CONFIG_t SPI_SLAVE_0_channel_config
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_mosi1_pin_config
const SPI_SLAVE_PIN_CONFIG_t SPI_SLAVE_0_miso_pin
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_mosi_pin_config
const SPI_SLAVE_PIN_CONFIG_t SPI_SLAVE_0_mosi_pin
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_sclk_pin_config
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_slavesel_pin_config
const SPI_SLAVE_CONFIG_t SPI_SLAVE_0_conf
SPI_SLAVE_RUNTIME_t SPI_SLAVE_0_runtime
SPI_SLAVE_t SPI_SLAVE_0
Function Documentation
SPI_SLAVE_0_init()
SPI_SLAVE_STATUS_t SPI_SLAVE_0_init (void)
Definition at line 163 of file spi_slave_conf.c.
References NVIC_EnableIRQ, NVIC_SetPriority, PORT0_BASE, PORT2_BASE, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_0, SPI_SLAVE_0_channel_config, SPI_SLAVE_0_mosi1_pin_config, SPI_SLAVE_0_mosi_pin_config, SPI_SLAVE_0_sclk_pin_config, SPI_SLAVE_0_slavesel_pin_config, SPI_SLAVE_STATUS_SUCCESS, SPI_SLAVE_RUNTIME::tx_busy, XMC_GPIO_HWCTRL_DISABLED, XMC_GPIO_Init(), XMC_GPIO_SetHardwareControl(), XMC_SPI_CH_EnableInputInversion(), XMC_SPI_CH_Init(), XMC_SPI_CH_INPUT_SLAVE_SELIN, XMC_SPI_CH_SetBitOrderMsbFirst(), XMC_SPI_CH_SetFrameLength(), XMC_SPI_CH_SetInputSource(), XMC_SPI_CH_SetWordLength(), XMC_SPI_CH_Start(), XMC_USIC_CH_FIFO_SIZE_16WORDS, XMC_USIC_CH_INPUT_DX0, XMC_USIC_CH_INPUT_DX1, XMC_USIC_CH_INPUT_DX2, XMC_USIC_CH_INPUT_DX3, XMC_USIC_CH_INPUT_DX4, XMC_USIC_CH_INPUT_DX5, XMC_USIC_CH_INTERRUPT_NODE_POINTER_PROTOCOL, XMC_USIC_CH_RXFIFO_Configure(), XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_ALTERNATE, XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_STANDARD, XMC_USIC_CH_RXFIFO_SetInterruptNodePointer(), XMC_USIC_CH_SetInterruptNodePointer(), XMC_USIC_CH_TXFIFO_Configure(), XMC_USIC_CH_TXFIFO_INTERRUPT_NODE_POINTER_STANDARD, and XMC_USIC_CH_TXFIFO_SetInterruptNodePointer().
SPI_SLAVE_0_RX_HANDLER()
void SPI_SLAVE_0_RX_HANDLER ()
Definition at line 235 of file spi_slave_conf.c.
References SPI_SLAVE_0, and SPI_SLAVE_lReceiveHandler().
SPI_SLAVE_0_TX_HANDLER()
void SPI_SLAVE_0_TX_HANDLER ()
Definition at line 229 of file spi_slave_conf.c.
References SPI_SLAVE_0, and SPI_SLAVE_lTransmitHandler().
SPI_SLAVE_lProtocolHandler()
void SPI_SLAVE_lProtocolHandler (const SPI_SLAVE_t *const handle)
SPI_SLAVE_lReceiveHandler()
void SPI_SLAVE_lReceiveHandler (const SPI_SLAVE_t *const handle)
Definition at line 698 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE_RUNTIME::data_size, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::rx_busy, SPI_SLAVE_CONFIG::rx_cbhandler, SPI_SLAVE_RUNTIME::rx_data, SPI_SLAVE_RUNTIME::rx_data_count, SPI_SLAVE_RUNTIME::rx_data_index, SPI_SLAVE_CONFIG::rx_fifo_size, SPI_SLAVE_lReconfigureRxFIFO(), XMC_SPI_CH_DisableEvent(), XMC_SPI_CH_EVENT_ALTERNATIVE_RECEIVE, XMC_SPI_CH_EVENT_STANDARD_RECEIVE, XMC_SPI_CH_GetReceivedData(), XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_RXFIFO_DisableEvent(), XMC_USIC_CH_RXFIFO_EVENT_CONF_ALTERNATE, XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD, and XMC_USIC_CH_RXFIFO_IsEmpty().
Referenced by SPI_SLAVE_0_RX_HANDLER().
SPI_SLAVE_lTransmitHandler()
void SPI_SLAVE_lTransmitHandler (const SPI_SLAVE_t *const handle)
Definition at line 539 of file spi_slave.c.
References SPI_SLAVE::channel, SPI_SLAVE::config, SPI_SLAVE_RUNTIME::data_size, SPI_SLAVE::runtime, SPI_SLAVE_RUNTIME::spi_current_mode, SPI_SLAVE_RUNTIME::tx_busy, SPI_SLAVE_CONFIG::tx_cbhandler, SPI_SLAVE_RUNTIME::tx_data, SPI_SLAVE_RUNTIME::tx_data_count, SPI_SLAVE_RUNTIME::tx_data_index, SPI_SLAVE_CONFIG::tx_fifo_size, XMC_SPI_CH_DisableEvent(), XMC_SPI_CH_EVENT_TRANSMIT_BUFFER, XMC_SPI_CH_Transmit(), XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_GetTransmitBufferStatus(), XMC_USIC_CH_TBUF_STATUS_BUSY, XMC_USIC_CH_TXFIFO_DisableEvent(), XMC_USIC_CH_TXFIFO_EVENT_CONF_STANDARD, XMC_USIC_CH_TXFIFO_IsEmpty(), and XMC_USIC_CH_TXFIFO_IsFull().
Referenced by SPI_SLAVE_0_TX_HANDLER().
Variable Documentation
SPI_SLAVE_0
SPI_SLAVE_t SPI_SLAVE_0
Initial value:
=
{
  .channel = XMC_SPI0_CH0,
  .config = &SPI_SLAVE_0_conf,
  .runtime = &SPI_SLAVE_0_runtime
}
Definition at line 152 of file spi_slave_conf.c.
Referenced by DAVE_Init(), SPI_SLAVE_0_init(), SPI_SLAVE_0_RX_HANDLER(), SPI_SLAVE_0_TX_HANDLER(), and SPI_Slave_Task().
SPI_SLAVE_0_channel_config
const XMC_SPI_CH_CONFIG_t SPI_SLAVE_0_channel_config
Initial value:
=
{
  .bus_mode = XMC_SPI_CH_BUS_MODE_SLAVE,
  .parity_mode = XMC_USIC_CH_PARITY_MODE_NONE
}
Definition at line 62 of file spi_slave_conf.c.
Referenced by SPI_SLAVE_0_init().
SPI_SLAVE_0_conf
const SPI_SLAVE_CONFIG_t SPI_SLAVE_0_conf
Initial value:
=
{
  .channel_config = &SPI_SLAVE_0_channel_config,
  .mosi1_pin_config = &SPI_SLAVE_0_miso_pin,
  .mosi0_pin_config = &SPI_SLAVE_0_mosi_pin,
  .fptr_spi_slave_config = SPI_SLAVE_0_init,
  .tx_cbhandler = NULL,
  .rx_cbhandler = NULL,
  .parity_error_cbhandler = NULL,
  .slave_select_cbhandler = NULL,
  .transmit_mode = SPI_SLAVE_TRANSFER_MODE_INTERRUPT,
  .receive_mode = SPI_SLAVE_TRANSFER_MODE_INTERRUPT,
  .tx_fifo_size = XMC_USIC_CH_FIFO_SIZE_16WORDS,
  .rx_fifo_size = XMC_USIC_CH_FIFO_SIZE_16WORDS,
  .spi_configured_mode = XMC_SPI_CH_MODE_STANDARD,
  .tx_sr = 4U,
  .dx0_source = SPI_SLAVE_INPUT_INVALID,
}
Definition at line 120 of file spi_slave_conf.c.
SPI_SLAVE_0_miso_pin
const SPI_SLAVE_PIN_CONFIG_t SPI_SLAVE_0_miso_pin
Initial value:
=
{
  .port = (XMC_GPIO_PORT_t *)PORT2_BASE,
  .config = &SPI_SLAVE_0_mosi1_pin_config,
  .hw_control = XMC_GPIO_HWCTRL_DISABLED,
  .pin = 0U
}
Definition at line 79 of file spi_slave_conf.c.
SPI_SLAVE_0_mosi1_pin_config
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_mosi1_pin_config
Initial value:
=
{
  .mode = XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT6,
  .output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH
}
Definition at line 68 of file spi_slave_conf.c.
Referenced by SPI_SLAVE_0_init().
SPI_SLAVE_0_mosi_pin
const SPI_SLAVE_PIN_CONFIG_t SPI_SLAVE_0_mosi_pin
Initial value:
=
{
  .port = (XMC_GPIO_PORT_t *)PORT2_BASE,
  .config = &SPI_SLAVE_0_mosi_pin_config,
  .hw_control = XMC_GPIO_HWCTRL_DISABLED,
  .pin = 10U
}
Definition at line 96 of file spi_slave_conf.c.
SPI_SLAVE_0_mosi_pin_config
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_mosi_pin_config
Initial value:
=
{
  .mode = XMC_GPIO_MODE_INPUT_TRISTATE,
  .output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH,
  .input_hysteresis = XMC_GPIO_INPUT_HYSTERESIS_STANDARD
}
Definition at line 88 of file spi_slave_conf.c.
Referenced by SPI_SLAVE_0_init().
SPI_SLAVE_0_runtime
SPI_SLAVE_RUNTIME_t SPI_SLAVE_0_runtime
Initial value:
=
{
  .spi_current_mode = XMC_SPI_CH_MODE_STANDARD,
  .data_size = SPI_SLAVE_DATA_SIZE_8BITS,
  .tx_busy = false,
  .rx_busy = false
}
Definition at line 144 of file spi_slave_conf.c.
SPI_SLAVE_0_sclk_pin_config
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_sclk_pin_config
Initial value:
=
{
  .mode = XMC_GPIO_MODE_INPUT_TRISTATE,
  .output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH,
  .input_hysteresis = XMC_GPIO_INPUT_HYSTERESIS_STANDARD
}
Definition at line 105 of file spi_slave_conf.c.
Referenced by SPI_SLAVE_0_init().
SPI_SLAVE_0_slavesel_pin_config
const XMC_GPIO_CONFIG_t SPI_SLAVE_0_slavesel_pin_config
Initial value:
=
{
  .mode = XMC_GPIO_MODE_INPUT_TRISTATE,
  .output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH,
  .input_hysteresis = XMC_GPIO_INPUT_HYSTERESIS_STANDARD
}
Definition at line 113 of file spi_slave_conf.c.
Referenced by SPI_SLAVE_0_init().