Libraries/CMSIS/Infineon/XMC1100_series/Include/system_XMC1100.h File Reference
#include <stdint.h>
Functions
void SystemInit (void)
Initialize the system.
void SystemCoreSetup (void)
Initialize CPU settings.
void SystemCoreClockSetup (void)
Initialize clock.
void SystemCoreClockUpdate (void)
Update SystemCoreClock variable.
Variables
uint32_t SystemCoreClock
Function Documentation
SystemCoreClockSetup()
void SystemCoreClockSetup (void)
Initialize clock.
< 8/10 Bit Fractional divider
< 8 Bit integer divider
Definition at line 69 of file clock_xmc1_conf.c.
References SCU_CLK, SCU_CLK_CLKCR_VDDC2LOW_Msk, SCU_GENERAL, SystemCoreClockUpdate(), and XMC_SCU_CLOCK_Init().
Referenced by SystemInit().
SystemCoreClockUpdate()
void SystemCoreClockUpdate (void)
Update SystemCoreClock variable.
Definition at line 115 of file system_XMC1100.c.
References DCO1_FREQUENCY, SCU_CLK, SCU_CLK_CLKCR_FDIV_Msk, SCU_CLK_CLKCR_FDIV_Pos, SCU_CLK_CLKCR_IDIV_Msk, SCU_CLK_CLKCR_IDIV_Pos, and SystemCoreClock.
Referenced by SystemCoreClockSetup().
SystemCoreSetup()
void SystemCoreSetup (void)
Initialize CPU settings.
Definition at line 63 of file cpu_ctrl_xmc1_conf.c.
References NVM, NVM_CONFIG1_FIXWS_Msk, and NVM_NVMCONF_WS_Msk.
Referenced by SystemInit().
SystemInit()
void SystemInit (void)
Initialize the system.
Definition at line 87 of file system_XMC1100.c.
References SystemCoreClockSetup(), and SystemCoreSetup().
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock
Referenced by SystemCoreClockUpdate(), XMC_SCU_CLOCK_GetCpuClockFrequency(), and XMC_SCU_CLOCK_GetPeripheralClockFrequency().