Startup/system_XMC1100.c File Reference
#include <XMC1100.h>
#include `system_XMC1100.h`
Macros
#define DCO1_FREQUENCY (64000000U)
Functions
__WEAK void SystemInit (void)
Initialize the system.
__WEAK void SystemCoreSetup (void)
Initialize CPU settings.
__WEAK void SystemCoreClockSetup (void)
Initialize clock.
__WEAK void SystemCoreClockUpdate (void)
Update SystemCoreClock variable.
Macro Definition Documentation
DCO1_FREQUENCY
#define DCO1_FREQUENCY (64000000U)
Definition at line 66 of file system_XMC1100.c.
Function Documentation
SystemCoreClockSetup()
__WEAK void SystemCoreClockSetup (void)
Initialize clock.
< 8/10 Bit Fractional divider
< 8 Bit integer divider
Definition at line 102 of file system_XMC1100.c.
References SCU_CLK, SCU_CLK_CLKCR_VDDC2LOW_Msk, SCU_GENERAL, SystemCoreClockUpdate(), and XMC_SCU_CLOCK_Init().
Referenced by SystemInit().
SystemCoreClockUpdate()
__WEAK void SystemCoreClockUpdate (void)
Update SystemCoreClock variable.
Definition at line 115 of file system_XMC1100.c.
References DCO1_FREQUENCY, SCU_CLK, SCU_CLK_CLKCR_FDIV_Msk, SCU_CLK_CLKCR_FDIV_Pos, SCU_CLK_CLKCR_IDIV_Msk, SCU_CLK_CLKCR_IDIV_Pos, and SystemCoreClock.
Referenced by SystemCoreClockSetup().
SystemCoreSetup()
__WEAK void SystemCoreSetup (void)
Initialize CPU settings.
Definition at line 93 of file system_XMC1100.c.
References NVM, NVM_CONFIG1_FIXWS_Msk, and NVM_NVMCONF_WS_Msk.
Referenced by SystemInit().
SystemInit()
__WEAK void SystemInit (void)
Initialize the system.
Definition at line 87 of file system_XMC1100.c.
References SystemCoreClockSetup(), and SystemCoreSetup().