Dave/Generated/UART/uart_conf.c File Reference
#include `uart.h`
Functions
void UART_lTransmitHandler (const UART_t *const handle)
void UART_lReceiveHandler (const UART_t *const handle)
void UART_lProtocolHandler (const UART_t *const handle)
UART_STATUS_t UART_0_init (void)
void UART_0_TX_HANDLER ()
void UART_0_RX_HANDLER ()
Variables
const XMC_UART_CH_CONFIG_t UART_0_channel_config
const XMC_GPIO_CONFIG_t UART_0_tx_pin_config
const UART_TX_CONFIG_t UART_0_tx_pin
const UART_CONFIG_t UART_0_config
UART_RUNTIME_t UART_0_runtime
UART_t UART_0
const XMC_GPIO_CONFIG_t UART_0_rx_pin_config
Function Documentation
UART_0_init()
UART_STATUS_t UART_0_init (void)
Definition at line 166 of file uart_conf.c.
References NVIC_EnableIRQ, NVIC_SetPriority, PORT1_BASE, UART_0_channel_config, UART_0_rx_pin_config, UART_0_tx_pin_config, UART_STATUS_SUCCESS, XMC_GPIO_Init(), XMC_UART_CH_Init(), XMC_UART_CH_Start(), XMC_USIC_CH_FIFO_SIZE_16WORDS, XMC_USIC_CH_INPUT_DX0, XMC_USIC_CH_INPUT_DX3, XMC_USIC_CH_INPUT_DX5, XMC_USIC_CH_INTERRUPT_NODE_POINTER_PROTOCOL, XMC_USIC_CH_RXFIFO_Configure(), XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_ALTERNATE, XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_STANDARD, XMC_USIC_CH_RXFIFO_SetInterruptNodePointer(), XMC_USIC_CH_SetInputSource(), XMC_USIC_CH_SetInterruptNodePointer(), XMC_USIC_CH_TXFIFO_Configure(), XMC_USIC_CH_TXFIFO_INTERRUPT_NODE_POINTER_STANDARD, and XMC_USIC_CH_TXFIFO_SetInterruptNodePointer().
UART_0_RX_HANDLER()
void UART_0_RX_HANDLER ()
Definition at line 220 of file uart_conf.c.
References UART_0, and UART_lReceiveHandler().
UART_0_TX_HANDLER()
void UART_0_TX_HANDLER ()
Definition at line 214 of file uart_conf.c.
References UART_0, and UART_lTransmitHandler().
UART_lProtocolHandler()
void UART_lProtocolHandler (const UART_t *const handle)
UART_lReceiveHandler()
void UART_lReceiveHandler (const UART_t *const handle)
Definition at line 924 of file uart.c.
References UART::channel, UART::config, UART::runtime, UART_RUNTIME::rx_busy, UART_CONFIG::rx_cbhandler, UART_RUNTIME::rx_data, UART_RUNTIME::rx_data_count, UART_RUNTIME::rx_data_index, UART_CONFIG::rx_fifo_size, UART_lReconfigureRxFIFO(), XMC_UART_CH_GetReceivedData(), XMC_USIC_CH_DisableEvent(), XMC_USIC_CH_EVENT_ALTERNATIVE_RECEIVE, XMC_USIC_CH_EVENT_STANDARD_RECEIVE, XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_RXFIFO_DisableEvent(), XMC_USIC_CH_RXFIFO_EVENT_CONF_ALTERNATE, XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD, and XMC_USIC_CH_RXFIFO_IsEmpty().
Referenced by UART_0_RX_HANDLER().
UART_lTransmitHandler()
void UART_lTransmitHandler (const UART_t *const handle)
Definition at line 850 of file uart.c.
References UART::channel, UART::config, UART::runtime, UART_RUNTIME::tx_busy, UART_CONFIG::tx_cbhandler, UART_RUNTIME::tx_data, UART_RUNTIME::tx_data_count, UART_RUNTIME::tx_data_index, UART_CONFIG::tx_fifo_size, XMC_UART_CH_Transmit(), XMC_USIC_CH_DisableEvent(), XMC_USIC_CH_EVENT_TRANSMIT_BUFFER, XMC_USIC_CH_FIFO_DISABLED, XMC_USIC_CH_GetTransmitBufferStatus(), XMC_USIC_CH_TBUF_STATUS_BUSY, XMC_USIC_CH_TXFIFO_DisableEvent(), XMC_USIC_CH_TXFIFO_EVENT_CONF_STANDARD, XMC_USIC_CH_TXFIFO_IsEmpty(), and XMC_USIC_CH_TXFIFO_IsFull().
Referenced by UART_0_TX_HANDLER().
Variable Documentation
UART_0
UART_t UART_0
Initial value:
=
{
  .channel = XMC_UART0_CH1,
  .config = &UART_0_config,
  .runtime = &UART_0_runtime
}
Definition at line 149 of file uart_conf.c.
Referenced by DAVE_Init(), fMyPrintf(), INT_UART_Receive_ISR(), UART_0_RX_HANDLER(), and UART_0_TX_HANDLER().
UART_0_channel_config
const XMC_UART_CH_CONFIG_t UART_0_channel_config
Initial value:
=
{
  .baudrate = 19200U,
  .data_bits = 8U,
  .frame_length = 8U,
  .stop_bits = 1U,
  .oversampling = 16U,
  .parity_mode = XMC_USIC_CH_PARITY_MODE_NONE
}
Definition at line 94 of file uart_conf.c.
Referenced by UART_0_init().
UART_0_config
const UART_CONFIG_t UART_0_config
Initial value:
=
{
  .channel_config = &UART_0_channel_config,
  .fptr_uart_config = UART_0_init,
  .tx_cbhandler = NULL,
  .rx_cbhandler = NULL,
  .sync_error_cbhandler = NULL,
  .rx_noise_error_cbhandler = NULL,
  .format_error_bit0_cbhandler = NULL,
  .format_error_bit1_cbhandler = NULL,
  .collision_error_cbhandler = NULL,
  .tx_pin_config = &UART_0_tx_pin,
  .mode = UART_MODE_FULLDUPLEX,
  .transmit_mode = UART_TRANSFER_MODE_INTERRUPT,
  .receive_mode = UART_TRANSFER_MODE_INTERRUPT,
  .tx_fifo_size = XMC_USIC_CH_FIFO_SIZE_16WORDS,
  .rx_fifo_size = XMC_USIC_CH_FIFO_SIZE_16WORDS,
  .tx_sr = 0x3U,
}
Definition at line 119 of file uart_conf.c.
UART_0_runtime
UART_RUNTIME_t UART_0_runtime
Initial value:
=
{
  .tx_busy = false,
  .rx_busy = false,
}
Definition at line 142 of file uart_conf.c.
UART_0_rx_pin_config
const XMC_GPIO_CONFIG_t UART_0_rx_pin_config
Initial value:
= {
  .mode = XMC_GPIO_MODE_INPUT_TRISTATE,
  .output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH,
  .input_hysteresis = XMC_GPIO_INPUT_HYSTERESIS_STANDARD
}
Definition at line 157 of file uart_conf.c.
Referenced by UART_0_init().
UART_0_tx_pin
const UART_TX_CONFIG_t UART_0_tx_pin
Initial value:
=
{
  .port = (XMC_GPIO_PORT_t *)PORT1_BASE,
  .config = &UART_0_tx_pin_config,
  .pin = 2U
}
Definition at line 111 of file uart_conf.c.
UART_0_tx_pin_config
const XMC_GPIO_CONFIG_t UART_0_tx_pin_config
Initial value:
=
{
  .mode = XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT7,
  .output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH
}
Definition at line 104 of file uart_conf.c.
Referenced by UART_0_init().