Libraries/XMCLib/src/xmc1_flash.c File Reference
#include `xmc_flash.h`
Typedefs
typedef enum FLASH_ACTION FLASH_ACTION_t
Enumerations
enum FLASH_ACTION {
FLASH_ACTION_IDLE = (uint32_t)0x00,
FLASH_ACTION_ONESHOT_WRITE_VERIFY = ((uint32_t)0x51 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_ONESHOT_WRITE = ((uint32_t)0x91 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_CONTINUOUS_WRITE_VERIFY = ((uint32_t)0x61 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_CONTINUOUS_WRITE = ((uint32_t)0xa1 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_ONESHOT_PAGE_ERASE = ((uint32_t)0x92 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_CONTINUOUS_PAGE_ERASE = ((uint32_t)0xa2 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_ONESHOT_VERIFY_ONLY = ((uint32_t)0xd0 << NVM_NVMPROG_ACTION_Pos),
FLASH_ACTION_CONTINUOUS_VERIFY_ONLY = ((uint32_t)0xe0 << NVM_NVMPROG_ACTION_Pos)
 }
Functions
void XMC_FLASH_ClearStatus (void)
uint32_t XMC_FLASH_GetStatus (void)
void XMC_FLASH_EnableEvent (const uint32_t event_msk)
void XMC_FLASH_DisableEvent (const uint32_t event_msk)
void XMC_FLASH_ErasePage (uint32_t *address)
void XMC_FLASH_ProgramVerifyPage (uint32_t *address, const uint32_t *data)
void XMC_FLASH_WriteBlocks (uint32_t *address, const uint32_t *data, uint32_t num_blocks, bool verify)
void XMC_FLASH_ErasePages (uint32_t *address, uint32_t num_pages)
void XMC_FLASH_VerifyBlocks (uint32_t *address, const uint32_t *data, uint32_t num_blocks)
void XMC_FLASH_ReadBlocks (uint32_t *address, uint32_t *data, uint32_t num_blocks)
void XMC_FLASH_EraseSector (uint32_t *address)
void XMC_FLASH_ProgramPage (uint32_t *address, const uint32_t *data)
Detailed Description
Date
2015-10-14
Typedef Documentation
FLASH_ACTION_t
typedef enum FLASH_ACTION FLASH_ACTION_t
Enumeration Type Documentation
FLASH_ACTION
enum FLASH_ACTION
Enumerator
FLASH_ACTION_IDLE
FLASH_ACTION_ONESHOT_WRITE_VERIFY
FLASH_ACTION_ONESHOT_WRITE
FLASH_ACTION_CONTINUOUS_WRITE_VERIFY
FLASH_ACTION_CONTINUOUS_WRITE
FLASH_ACTION_ONESHOT_PAGE_ERASE
FLASH_ACTION_CONTINUOUS_PAGE_ERASE
FLASH_ACTION_ONESHOT_VERIFY_ONLY
FLASH_ACTION_CONTINUOUS_VERIFY_ONLY
Definition at line 64 of file xmc1_flash.c.
Function Documentation
XMC_FLASH_ErasePage()
void XMC_FLASH_ErasePage (uint32_t * address)
Definition at line 114 of file xmc1_flash.c.
References XMC1000_NvmErasePage.
XMC_FLASH_ErasePages()
void XMC_FLASH_ErasePages (uint32_t * address, uint32_t num_pages)
Definition at line 165 of file xmc1_flash.c.
References XMC1000_NvmErasePage, XMC_ASSERT, and XMC_FLASH_IsBusy().
Referenced by XMC_FLASH_EraseSector().
XMC_FLASH_ProgramVerifyPage()
void XMC_FLASH_ProgramVerifyPage (uint32_t * address, const uint32_t * data)
Definition at line 119 of file xmc1_flash.c.
References XMC1000_NvmProgVerify.
Referenced by XMC_FLASH_ProgramPage().
XMC_FLASH_ReadBlocks()
void XMC_FLASH_ReadBlocks (uint32_t * address, uint32_t * data, uint32_t num_blocks)
Definition at line 221 of file xmc1_flash.c.
References XMC_ASSERT.
XMC_FLASH_VerifyBlocks()
void XMC_FLASH_VerifyBlocks (uint32_t * address, const uint32_t * data, uint32_t num_blocks)
Definition at line 188 of file xmc1_flash.c.
References FLASH_ACTION_CONTINUOUS_VERIFY_ONLY, NVM, NVM_NVMPROG_ACTION_Msk, NVM_NVMPROG_RSTECC_Msk, NVM_NVMPROG_RSTVERR_Msk, XMC_ASSERT, and XMC_FLASH_IsBusy().
XMC_FLASH_WriteBlocks()
void XMC_FLASH_WriteBlocks (uint32_t * address, const uint32_t * data, uint32_t num_blocks, bool verify)
Definition at line 125 of file xmc1_flash.c.
References FLASH_ACTION_CONTINUOUS_WRITE, FLASH_ACTION_CONTINUOUS_WRITE_VERIFY, NVM, NVM_NVMPROG_ACTION_Msk, NVM_NVMPROG_RSTECC_Msk, NVM_NVMPROG_RSTVERR_Msk, XMC_ASSERT, and XMC_FLASH_IsBusy().